import EnterpriseMath.Relation.BRCFiniteTransition
import Mathlib.GroupTheory.Subgroup.Basic
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Fintype.Prod
import Mathlib.Tactic

namespace EnterpriseMath.BranchRecoalescence

namespace FiniteTransitionSystem

variable {BranchId S W G C : Type*}
variable [Monoid W] [Group G] [AddMonoid C]
variable {ρ : CoordinateAction G C}

/-- Smallest frame subgroup containing every declared branch frame.

This is the correct algebraic candidate for identity-start reachable-frame
compression.  It is *not* by itself permission to replace a full-atlas global
determinant by a subgroup determinant; that requires the observer/start-frame
contract to restrict attention to the reachable component. -/
def generatedFrameSubgroup
    (T : FiniteTransitionSystem BranchId S W G C ρ) : Subgroup G :=
  Subgroup.closure (Set.range fun b => (T.arrow b).path.frame)

/-- Every declared branch frame belongs to the generated reachable subgroup. -/
theorem branch_frame_mem_generatedFrameSubgroup
    (T : FiniteTransitionSystem BranchId S W G C ρ) (b : BranchId) :
    (T.arrow b).path.frame ∈ T.generatedFrameSubgroup := by
  apply Subgroup.subset_closure
  exact ⟨b, rfl⟩

/-- Accumulated frame of a finite branch word, in BRC serial-composition order. -/
def wordFrame (T : FiniteTransitionSystem BranchId S W G C ρ) :
    List BranchId → G
  | [] => 1
  | b :: bs => (T.arrow b).path.frame * T.wordFrame bs

@[simp] theorem wordFrame_nil
    (T : FiniteTransitionSystem BranchId S W G C ρ) :
    T.wordFrame [] = 1 := rfl

@[simp] theorem wordFrame_cons
    (T : FiniteTransitionSystem BranchId S W G C ρ)
    (b : BranchId) (bs : List BranchId) :
    T.wordFrame (b :: bs) = (T.arrow b).path.frame * T.wordFrame bs := rfl

/-- Starting from identity, every finite branch word remains inside the subgroup
generated by declared branch frames. -/
theorem wordFrame_mem_generatedFrameSubgroup
    (T : FiniteTransitionSystem BranchId S W G C ρ)
    (bs : List BranchId) :
    T.wordFrame bs ∈ T.generatedFrameSubgroup := by
  induction bs with
  | nil => simp [generatedFrameSubgroup]
  | cons b bs ih =>
      exact T.generatedFrameSubgroup.mul_mem
        (T.branch_frame_mem_generatedFrameSubgroup b) ih

/-- For a finite ambient frame group, the generated reachable subgroup cannot be
larger than the full frame atlas. -/
theorem generatedFrameSubgroup_card_le
    [Fintype G]
    (T : FiniteTransitionSystem BranchId S W G C ρ) :
    Fintype.card T.generatedFrameSubgroup ≤ Fintype.card G := by
  exact Fintype.card_subtype_le _

/-- Consequently the identity-start state × reachable-frame index set is never
larger than the full state × frame index set.  Strict reduction depends on the
actual generated subgroup and on the declared observer contract. -/
theorem reachable_stateFrame_card_le
    [Fintype S] [Fintype G]
    (T : FiniteTransitionSystem BranchId S W G C ρ) :
    Fintype.card (S × T.generatedFrameSubgroup) ≤ Fintype.card (S × G) := by
  rw [Fintype.card_prod, Fintype.card_prod]
  exact Nat.mul_le_mul_left _ T.generatedFrameSubgroup_card_le

end FiniteTransitionSystem

end EnterpriseMath.BranchRecoalescence
