import EnterpriseMath.Relation.BRCK4OptimalExtraction
import Mathlib.Tactic

namespace EnterpriseMath.BranchRecoalescence

/-- Exact star-semigroup generation means that the six edge counts are entirely
explained by four nonnegative vertex-star multiplicities, with zero residual. -/
def k4ExactlyStarGenerated (n : K4Capacity) : Prop :=
  ∃ a b c d : ℕ,
    n.ab = a + b ∧
    n.ac = a + c ∧
    n.ad = a + d ∧
    n.bc = b + c ∧
    n.bd = b + d ∧
    n.cd = c + d

/-- Exact star-generated capacities satisfy the three opposite-edge balance
relations. -/
theorem k4ExactlyStarGenerated_opposite_balanced
    (n : K4Capacity) (h : k4ExactlyStarGenerated n) :
    n.ab + n.cd = n.ac + n.bd ∧
    n.ac + n.bd = n.ad + n.bc := by
  rcases h with ⟨a, b, c, d, hab, hac, had, hbc, hbd, hcd⟩
  constructor <;> omega

/-- Exact star generation forces every triangle-edge sum to be even; here the
ABC triangle is used as a representative parity readout. -/
theorem k4ExactlyStarGenerated_triangle_even
    (n : K4Capacity) (h : k4ExactlyStarGenerated n) :
    ∃ t : ℕ, n.ab + n.ac + n.bc = 2 * t := by
  rcases h with ⟨a, b, c, d, hab, hac, had, hbc, hbd, hcd⟩
  refine ⟨a + b + c, ?_⟩
  omega

/-- An explicit exceptional witness makes the representative triangle sum odd. -/
theorem k4ExceptionalWitness_triangle_odd
    (n : K4Capacity) {a b c d : ℕ}
    (hab : n.ab = a + b + 1)
    (hac : n.ac = a + c + 1)
    (had : n.ad = a + d + 1)
    (hbc : n.bc = b + c + 1)
    (hbd : n.bd = b + d + 1)
    (hcd : n.cd = c + d + 1) :
    ∃ t : ℕ, n.ab + n.ac + n.bc = 2 * t + 1 := by
  refine ⟨a + b + c + 1, ?_⟩
  omega

/-- The exceptional half-integral K4 pattern is never exactly generated by
integer star multiplicities.  This is the algebraic parity obstruction behind
the one-unit optimum deficit. -/
theorem k4Exceptional_not_exactlyStarGenerated
    (n : K4Capacity) (h : k4Exceptional n) :
    ¬ k4ExactlyStarGenerated n := by
  rcases h with ⟨p, q, r, s, hab, hac, had, hbc, hbd, hcd⟩
  rintro ⟨a, b, c, d, hab', hac', had', hbc', hbd', hcd'⟩
  omega

/-- Double every edge capacity. -/
def k4DoubleCapacity (n : K4Capacity) : K4Capacity :=
  ⟨2 * n.ab, 2 * n.ac, 2 * n.ad,
    2 * n.bc, 2 * n.bd, 2 * n.cd⟩

/-- Every exceptional capacity becomes exactly star-generated after doubling.
For witness base `(p,q,r,s)`, the doubled star multiplicities are
`(2p+1, 2q+1, 2r+1, 2s+1)`.

Thus exceptional capacities are explicit degree-two saturation holes of the
nonnegative star-exponent semigroup: absent at scale one, present at scale two. -/
theorem k4Exceptional_double_exactlyStarGenerated
    (n : K4Capacity) (h : k4Exceptional n) :
    k4ExactlyStarGenerated (k4DoubleCapacity n) := by
  rcases h with ⟨p, q, r, s, hab, hac, had, hbc, hbd, hcd⟩
  refine ⟨2 * p + 1, 2 * q + 1, 2 * r + 1, 2 * s + 1, ?_, ?_, ?_, ?_, ?_, ?_⟩
  all_goals simp [k4DoubleCapacity]
  all_goals omega

/-- Fundamental hole: the all-one six-edge capacity is not exactly star
generated. -/
theorem k4AllOne_not_exactlyStarGenerated :
    ¬ k4ExactlyStarGenerated ⟨1, 1, 1, 1, 1, 1⟩ := by
  intro h
  rcases k4ExactlyStarGenerated_triangle_even ⟨1, 1, 1, 1, 1, 1⟩ h with ⟨t, ht⟩
  omega

/-- But its double, the all-two capacity, is exactly generated by taking one of
each of the four K4 star factors. -/
theorem k4AllTwo_exactlyStarGenerated :
    k4ExactlyStarGenerated ⟨2, 2, 2, 2, 2, 2⟩ := by
  exact ⟨1, 1, 1, 1, by omega, by omega, by omega, by omega, by omega, by omega⟩

end EnterpriseMath.BranchRecoalescence
