import Mathlib.Data.Nat.Basic
import Mathlib.Tactic

namespace EnterpriseMath.PrimePowerQuotientTriangle

/-- Quotient-scale return generated by the prime power `2`. -/
def q2 (n : ℕ) : ℕ := n / 2

/-- Quotient-scale return generated by the prime power `4`. -/
def q4 (n : ℕ) : ℕ := n / 4

/-- Two successive quotient-by-two returns equal one quotient-by-four return. -/
theorem q2_q2_eq_q4 (n : ℕ) : q2 (q2 n) = q4 n := by
  simp [q2, q4, Nat.div_div_eq_div_mul]

/-- Signless edge defect on the quotient-by-two edge. -/
def defect2 (f : ℕ → ℝ) (n : ℕ) : ℝ :=
  f n + f (q2 n)

/-- Signless edge defect on the quotient-by-four edge. -/
def defect4 (f : ℕ → ℝ) (n : ℕ) : ℝ :=
  f n + f (q4 n)

/--
The exact `2-2-4` odd-triangle identity.  The direct edge and the two-edge
route have opposite parity, so their signless defects recover the vertex.
-/
theorem oddTriangle_identity (f : ℕ → ℝ) (n : ℕ) :
    2 * f n = defect2 f n + defect4 f n - defect2 f (q2 n) := by
  rw [show q2 (q2 n) = q4 n from q2_q2_eq_q4 n]
  simp only [defect2, defect4]
  ring

/-- An exact sign reversal on both prime-power return families is necessarily zero. -/
theorem no_exact_minus_one_mode
    (f : ℕ → ℝ)
    (h2 : ∀ n, defect2 f n = 0)
    (h4 : ∀ n, defect4 f n = 0) :
    ∀ n, f n = 0 := by
  intro n
  have h := oddTriangle_identity f n
  rw [h2 n, h4 n, h2 (q2 n)] at h
  linarith

/-- Local signless Poincare/coercivity inequality supplied by one odd triangle. -/
theorem oddTriangle_sq_coercive (f : ℕ → ℝ) (n : ℕ) :
    4 * (f n) ^ 2 ≤
      3 * ((defect2 f n) ^ 2 + (defect4 f n) ^ 2 +
        (defect2 f (q2 n)) ^ 2) := by
  let a := defect2 f n
  let b := defect4 f n
  let c := defect2 f (q2 n)
  have h : 2 * f n = a + b - c := by
    simpa [a, b, c] using oddTriangle_identity f n
  nlinarith [sq_nonneg (a - b), sq_nonneg (a + c), sq_nonneg (b + c)]

end EnterpriseMath.PrimePowerQuotientTriangle
