"""Exact research checks. Run: python verify_extension.py (Python >=3.10)."""
from __future__ import annotations
from fractions import Fraction as F
from hashlib import sha1
from itertools import product
from pathlib import Path
from random import Random
import json

from brc_transport import (
    Affine, EffectHistogram, matrix, eye, mm, mv, ma, sm, transpose,
    inv, mpow, factor_defect, point_moment, explicit_moment,
    euclidean_digits, recompose, MomentState,
)
import importlib
import importlib.util
REFERENCE_PACKAGE = "enterprise_math" if importlib.util.find_spec("enterprise_math") else "reference_brc"
hist_module = importlib.import_module(REFERENCE_PACKAGE+".brc_histogram")
pred_module = importlib.import_module(REFERENCE_PACKAGE+".predictive_quotient")
WeightHistogram = hist_module.WeightHistogram
histogram_recoalesce = hist_module.histogram_recoalesce
histogram_serial = hist_module.histogram_serial
predictive_block_profile = pred_module.predictive_block_profile
stable_predictive_partition = pred_module.stable_predictive_partition
finite_horizon_partition = pred_module.finite_horizon_partition
distinguishing_horizon = pred_module.distinguishing_horizon
quotient_transition_table = pred_module.quotient_transition_table

HERE = Path(__file__).resolve().parent
RESULTS = {}
RNG = Random(20260919)


def record(name, data):
    RESULTS[name] = data


def source_checks():
    values = {}
    for name,expected in [('predictive_quotient.py','f27d9ddf908f5b07051acfaf0c69f359d499b98b'),
                          ('brc_histogram.py','9a3962ec095095f14e63a91cfe6b7ebf07d9a1d1')]:
        b=Path((pred_module if name=='predictive_quotient.py' else hist_module).__file__).read_bytes()
        actual=sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()
        assert actual==expected, (name,actual)
        values[name]=actual
    record('01_existing_source_byte_identity', values)


def rand_action():
    return Affine(matrix([[RNG.randint(-2,2) for _ in range(2)] for _ in range(2)]),
                  tuple(F(RNG.randint(-2,2)) for _ in range(2)))


def algebra_checks():
    unit=EffectHistogram.unit(2)
    zero=EffectHistogram.zero(2)
    for _ in range(48):
        packets=[EffectHistogram.from_terms(2,[(F(RNG.randint(1,4),RNG.randint(1,5)),rand_action(),RNG.randint(1,3))
                  for _ in range(2)]) for _ in range(3)]
        a,b,c=packets
        assert a.then(b).then(c)==a.then(b.then(c))
        assert a.then(b.alternatives(c))==a.then(b).alternatives(a.then(c))
        assert a.alternatives(b).then(c)==a.then(c).alternatives(b.then(c))
        assert a.then(unit)==unit.then(a)==a
        assert a.then(zero)==zero.then(a)==zero
        assert a.alternatives(zero)==a
        assert a.alternatives(b).forget_effects()==histogram_recoalesce(a.forget_effects(),b.forget_effects())
        assert a.then(b).forget_effects()==histogram_serial(a.forget_effects(),b.forget_effects())
        x=(F(2),F(-3))
        z=point_moment(x)
        assert a.then(b).moment_action(z)==b.moment_action(a.moment_action(z))
        assert a.moment_action(z)==explicit_moment(a.evaluate(x))
    h=WeightHistogram.from_weights([F(2,3),F(2,3),F(9,5)])
    assert h.prime_valuation_terms()==((((2,1),(3,-1)),2),(((3,2),(5,-1)),1))
    record('02_joint_algebra_backward_compatibility', {'random_packet_triples':48,'source_histogram_executed':True,
            'associativity_distributivity_unit_zero_moment_composition':'PASS','prime_valuation_excerpt_executed':True})


A5=matrix(((1,-1),(2,3)))
A7=matrix(((1,-2),(2,3)))


def canonical(n):
    a=b=0
    while n%5==0:
        a+=1;n//=5
    while n%7==0:
        b+=1;n//=7
    if n!=1:
        raise ValueError('probe uses only the multiplicative semigroup generated by 5,7')
    return mm(mpow(A5,a),mpow(A7,b))


def det2(a):
    return a[0][0]*a[1][1]-a[0][1]*a[1][0]


def holonomy_checks():
    first5=mm(A7,A5)
    first7=mm(A5,A7)
    assert first5==matrix(((-3,-7),(8,7)))
    assert first7==matrix(((-1,-5),(8,5)))
    h=mm(first5,inv(first7))
    assert h==matrix(((F(41,35),F(-8,35)),(F(-16,35),F(33,35))))
    assert det2(h)==1 and h!=eye(2)
    labels=[1,5,7,25,35,49]
    count=0
    for l,m,n in product(labels,repeat=3):
        dlm=factor_defect(canonical(l),canonical(m),canonical(l*m))
        dlmn=factor_defect(canonical(l*m),canonical(n),canonical(l*m*n))
        dmn=factor_defect(canonical(m),canonical(n),canonical(m*n))
        dl_mn=factor_defect(canonical(l),canonical(m*n),canonical(l*m*n))
        lhs=mm(dlm,dlmn)
        rhs=mm(mm(mm(canonical(l),dmn),inv(canonical(l))),dl_mn)
        assert lhs==rhs
        count+=1
    g=matrix(((1,1),(0,1)))
    ap=mm(mm(g,A5),inv(g));bp=mm(mm(g,A7),inv(g))
    hp=mm(mm(bp,ap),inv(mm(ap,bp)))
    assert hp==mm(mm(g,h),inv(g))
    assert sum(hp[i][i] for i in range(2))==F(74,35)
    record('03_noncommutative_defect_and_coherence',{'5_then_7':first5,'7_then_5':first7,
           'relative_defect':h,'defect_determinant':det2(h),'defect_trace':F(74,35),
           'twisted_cocycle_triples':count,'common_basis_conjugacy':'PASS',
           'scope':'chosen rational comparison maps, not global native rotations or lattice inverses'})


def phase_checks():
    a=matrix(((2,0),(0,F(1,2))))
    b=matrix(((F(1,2),0),(0,2)))
    # Same present scalar squared-size readout, unequal transported futures.
    size=lambda t:sum(x*x for row in t for x in row)
    assert size(a)==size(b)==F(17,4)
    follow=inv(a)
    assert mm(follow,a)==eye(2)
    assert mm(follow,b)==matrix(((F(1,4),0),(0,4)))
    record('04_scalar_defect_erases_orientation',{'same_initial_size':size(a),
           'next_sizes':[size(mm(follow,a)),size(mm(follow,b))]})


def joint_checks():
    plus=Affine(eye(1),(F(1),));minus=Affine(eye(1),(F(-1),))
    a=EffectHistogram.from_terms(1,[(1,plus,1),(2,minus,1)])
    b=EffectHistogram.from_terms(1,[(2,plus,1),(1,minus,1)])
    assert a.forget_effects()==b.forget_effects()
    assert {action for _,action,_ in a.entries}=={action for _,action,_ in b.entries}
    am=a.moment_action(point_moment((0,)));bm=b.moment_action(point_moment((0,)))
    assert am[0][1]==-1 and bm[0][1]==1 and am[1][1]==bm[1][1]==3
    record('05_weight_effect_correlation_is_necessary',{'same_weight_histogram':a.forget_effects().entries,
           'normalized_means':[am[0][1]/am[1][1],bm[0][1]/bm[1][1]]})


def future_checks():
    states=tuple((x,tag) for x in range(35) for tag in range(2))
    obs=lambda st:st[0]//5
    a5={'add5':lambda st:((st[0]+5)%35,st[1])}
    a1={'add1':lambda st:((st[0]+1)%35,st[1])}
    profile5=predictive_block_profile(states,a5,obs,6)
    profile1=predictive_block_profile(states,a1,obs,6)
    assert profile5==(7,)*7
    assert profile1==(7,14,21,28,35,35,35)
    stable=stable_predictive_partition(states,a1,obs)
    assert stable.block_count==35 and stable.stabilization_depth==4
    assert distinguishing_horizon(states,a1,obs,(18,0),(19,0))==1
    assert distinguishing_horizon(states,a1,obs,(18,0),(18,1)) is None
    # Independent exhaustive finite-word output signatures, not a second refiner.
    for k in range(7):
        partition=finite_horizon_partition(states,a1,obs,k)
        signatures=[tuple(((x+j)%35)//5 for j in range(k+1)) for x,_ in states]
        for i in range(len(states)):
            for j in range(len(states)):
                assert (partition[i]==partition[j])==(signatures[i]==signatures[j])
    try:
        quotient_transition_table(states,a1,finite_horizon_partition(states,a1,obs,0))
    except ValueError:
        pass
    else:
        raise AssertionError('unsafe quotient was not rejected')
    assert len(quotient_transition_table(states,a1,stable.partition))==35
    record('06_existing_T6_future_safe_compression',{'raw_states':70,'add5_profile':profile5,
           'add1_profile':profile1,'stable_states':35,'stabilization_depth':4,
           'independent_pair_signature_comparisons':7*70*70,
           'scope':'finite Z/35 with an explicitly unobserved inert duplicate label'})


def carry_checks():
    tested=0
    for x in range(-250,251):
        for bases in [(5,7),(7,5),(5,5),(5,7,5)]:
            q,r=euclidean_digits(x,bases)
            assert recompose(q,r,bases)==x
            modulus=1
            for b in bases:modulus*=b
            assert q==x//modulus
            assert recompose(0,r,bases)==x%modulus
            tested+=1
        assert euclidean_digits(x,(5,7))[0]==euclidean_digits(x,(7,5))[0]
    record('07_remainder_lift_and_exact_recomposition',{'round_trips':tested,
           '17_base5_then7':euclidean_digits(17,(5,7)),
           '17_base7_then5':euclidean_digits(17,(7,5)),
           'scope':'digit ordering differs, final scalar remainder is canonically convertible'})


def native_depth_checks():
    u=tuple(F(x,8) for x in (3,-1,-1,-1,-1,-1))
    v=tuple(F(x,12) for x in (7,1,1,1,1,1))
    obs=lambda q:tuple(x-min(q) for x in q)
    assert obs(u)==obs(v) and u!=v
    assert tuple(x+min(u) for x in obs(u))==u
    assert tuple(x+min(v) for x in obs(v))==v
    assert not any(abs(k+2)+5*abs(k)==4 for k in range(-20,21))
    record('08_native_common_depth_regression',{'depths':[min(u),min(v)],'relative_readout':obs(u)})


def moment_checks():
    dim=6
    p=matrix([[int(i==(j+1)%dim) for j in range(dim)] for i in range(dim)])
    plus=Affine(p,(F(1),)+(F(0),)*5)
    minus=Affine(p,(F(-1),)+(F(0),)*5)
    step=EffectHistogram.from_terms(dim,[(1,plus,1),(1,minus,1)])
    moment=point_moment((0,)*dim)
    # Independent explicit path enumeration through 8 steps.
    raw=[((0,)*dim,F(1))]
    for depth in range(1,9):
        new=[]
        for x,w in raw:
            rotated=(x[-1],)+x[:-1]
            for sign in [-1,1]:
                new.append(((rotated[0]+sign,)+rotated[1:],w))
        raw=new
        moment=step.moment_action(moment)
        direct=sm(0,eye(dim+1))
        for x,w in raw:direct=ma(direct,sm(w,point_moment(x)))
        assert direct==moment
    # 32-step exact moment computation, NOT explicit enumeration of 2^32 paths.
    packed=MomentState.from_point((0,)*dim)
    hist=WeightHistogram.from_weights([1])
    for _ in range(32):
        packed=packed.then(step)
        assert len(packed.upper)==28
        hist=histogram_serial(hist,step.forget_effects())
    moment=packed.to_matrix()
    count=2**32
    assert hist.count==hist.total_mass==moment[-1][-1]==count
    covariance=tuple(tuple(moment[i][j]/count for j in range(dim)) for i in range(dim))
    assert covariance==matrix([[([6,6,5,5,5,5][i] if i==j else 0) for j in range(dim)] for i in range(dim)])
    assert all(moment[i][-1]==0 for i in range(dim))
    record('09_affine_moment_closure',{'explicit_path_depth':8,'paths_at_depth8':len(raw),
           'compressed_depth':32,'represented_path_count':count,'symmetric_rational_entries':28,
           'total_mass':hist.total_mass,'normalized_covariance':covariance,
           'path_enumeration_at_depth32':False,
           'scope':'degree<=2 affine future observations only; no constant bit-memory claim'})


def nonlinear_boundary_checks():
    shift=lambda v:Affine(eye(1),(F(v),))
    a=EffectHistogram.from_terms(1,[(F(1,2),shift(-1),1),(F(1,2),shift(1),1)])
    b=EffectHistogram.from_terms(1,[(F(1,8),shift(-2),1),(F(3,4),shift(0),1),(F(1,8),shift(2),1)])
    assert a.moment_action(point_moment((0,)))==b.moment_action(point_moment((0,)))
    fourth=lambda hist:sum((w*c*act.b[0]**4 for w,act,c in hist.entries),F())
    assert fourth(a)==1 and fourth(b)==4
    record('10_nonlinear_observer_rejects_moment_only_state',{'same_moment':a.moment_action(point_moment((0,))),
           'fourth_moments':[fourth(a),fourth(b)],'zero_location_masses':[0,F(3,4)]})


def covariance_and_mass_boundaries():
    # Epsilon=X on X=+/-1: covariance cross terms are essential.
    ex2=F(1);eps2=F(1);cross=F(1)
    actual=F(4);naive=ex2+eps2
    assert actual==naive+2*cross and actual!=naive
    packet=EffectHistogram.from_terms(1,[(1,Affine(eye(1),(F(1),)),1),
                                       (1,Affine(eye(1),(F(-1),)),1)])
    m=packet.moment_action(point_moment((0,)))
    assert m[0][1]==0 and m[1][1]==2 and m[0][0]==2
    record('11_signed_displacement_is_not_positive_mass_cancellation',
           {'total_mass':2,'first_moment':0,'normalized_variance':1,
            'correlated_noise_true_variance':actual,'incorrect_independence_variance':naive})


def input_checks():
    invalid=[lambda:Affine(((1.0,),),(F(0),)),lambda:EffectHistogram.from_terms(1,[(0,Affine.identity(1),1)]),
             lambda:Affine(((0,),),(0,)).inverse(),lambda:recompose(0,(5,),(5,)),
             lambda:EffectHistogram.unit(1).then(EffectHistogram.unit(2))]
    for thunk in invalid:
        try:thunk()
        except (ValueError,TypeError):pass
        else:raise AssertionError('invalid input accepted')
    record('12_input_and_inverse_boundaries',{'rejected_cases':len(invalid)})


def main():
    for f in [source_checks,algebra_checks,holonomy_checks,phase_checks,joint_checks,
              future_checks,carry_checks,native_depth_checks,moment_checks,
              nonlinear_boundary_checks,covariance_and_mass_boundaries,input_checks]:
        f()
    report={'status':'PASS','check_groups':len(RESULTS),'results':RESULTS,
            'limits':['reference prototype, not production integration','no independent reviewer or Lean proof',
                      'no native arbitrary-rotation theorem','no universal finite-memory or nonlinear compression theorem',
                      'no Nollm runtime or semantic-recall benchmark']}
    text=json.dumps(report,ensure_ascii=False,indent=2,default=str)+'\n'
    (HERE/'verification_results.json').write_text(text,encoding='utf-8')
    print(text)

if __name__=='__main__':main()
