import EnterpriseMath.PrimeFusion.Channels
import EnterpriseMath.PrimeFusion.FusionAlgebra
import EnterpriseMath.PrimeFusion.ArithmeticSplit
import EnterpriseMath.PrimeFusion.MixedLocus
import EnterpriseMath.PrimeFusion.PhaseReadout
import EnterpriseMath.PrimeFusion.PointedQuotient
import EnterpriseMath.PrimeFusion.PointedRecovery
import EnterpriseMath.PrimeFusion.Reconstruction
import EnterpriseMath.PrimeFusion.DualPrime

#print axioms EnterpriseMath.PrimeFusion.channel_gcd_exact
#print axioms EnterpriseMath.PrimeFusion.fusionCRT
#print axioms EnterpriseMath.PrimeFusion.pointedCRT
#print axioms EnterpriseMath.PrimeFusion.pointedResidue_fusion_root
#print axioms EnterpriseMath.PrimeFusion.pointed_channel_recovery
#print axioms EnterpriseMath.PrimeFusion.pointed_idempotent_channel_recovery
#print axioms EnterpriseMath.PrimeFusion.mixed_locus_order_twelve
#print axioms EnterpriseMath.PrimeFusion.mixed_locus_four_orbit
#print axioms EnterpriseMath.PrimeFusion.mixed_orbit_inverse_only_eleven
#print axioms EnterpriseMath.PrimeFusion.dualPrime_sixth_gcd_readout
#print axioms EnterpriseMath.PrimeFusion.mixed_sixth_eq_two_rootIdempotent_sub_one
#print axioms EnterpriseMath.PrimeFusion.idempotent_channel_split
#print axioms EnterpriseMath.PrimeFusion.reconstruct_positive_primitive_channels
#print axioms EnterpriseMath.PrimeFusion.strict_interior_gate_iff
#print axioms EnterpriseMath.PrimeFusion.dualPrime_iff_channelled_squarefree_semiprime
#print axioms EnterpriseMath.PrimeFusion.dualPrime_fixed_zmod_fields
#print axioms EnterpriseMath.PrimeFusion.dualPrime_pointedCRT_prime_field_orders
