import itertools
import math
import unittest
from math import gcd

from enterprise_math.legendre import anchor_product, primes_up_to, square_basin
from enterprise_math.support_incidence import (
    anchor_surviving_exact_support_hit,
    support_product,
    support_unique_basin_hit,
    transverse_prime_support,
)


class SupportIncidenceTests(unittest.TestCase):
    def test_residue_criterion_matches_direct_basin_enumeration(self) -> None:
        for k in range(3, 70):
            center = k * (k + 1)
            transverse = [p for p in primes_up_to(k) if center % p != 0]
            for size in range(2, min(5, len(transverse) + 1)):
                for support in itertools.combinations(transverse, size):
                    G = math.prod(support)
                    if G <= 2 * k:
                        continue
                    direct = [n for n in square_basin(k) if n % G == 0]
                    self.assertLessEqual(len(direct), 1)
                    hit = support_unique_basin_hit(k, support)
                    if direct:
                        self.assertIsNotNone(hit)
                        assert hit is not None
                        self.assertEqual(hit["state"], direct[0])
                        self.assertEqual(hit["cofactor"], direct[0] // G)
                        self.assertLessEqual(hit["cofactor"], (k + 1) // 2)
                    else:
                        self.assertIsNone(hit)

    def test_exact_anchor_surviving_support_matches_direct_definition(self) -> None:
        for k in range(3, 60):
            center = k * (k + 1)
            anchor = anchor_product(k)
            transverse = [p for p in primes_up_to(k) if center % p != 0]
            for size in range(2, min(5, len(transverse) + 1)):
                for support in itertools.combinations(transverse, size):
                    G = support_product(k, support)
                    if G <= 2 * k:
                        continue
                    raw = support_unique_basin_hit(k, support)
                    exact = anchor_surviving_exact_support_hit(k, support)
                    if raw is None:
                        self.assertIsNone(exact)
                        continue
                    state = int(raw["state"])
                    expected = (
                        gcd(state, anchor) == 1
                        and transverse_prime_support(k, state) == list(support)
                    )
                    self.assertEqual(exact is not None, expected)

    def test_anchor_contamination_is_not_exact_surviving_support(self) -> None:
        # M=110, support product 3*7=21>20, and the unique basin hit is
        # 105=21*5.  The raw transverse support is {3,7}, but 5 is an anchor
        # prime, so the state must not be classified as an anchor-surviving
        # exact-support hit.
        raw = support_unique_basin_hit(10, (3, 7))
        self.assertIsNotNone(raw)
        assert raw is not None
        self.assertEqual(raw["state"], 105)
        self.assertEqual(raw["cofactor"], 5)
        self.assertEqual(transverse_prime_support(10, 105), [3, 7])
        self.assertGreater(gcd(105, anchor_product(10)), 1)
        self.assertIsNone(anchor_surviving_exact_support_hit(10, (3, 7)))

    def test_positive_smooth_closure_example(self) -> None:
        # M=272, G=5*11=55>32.  The unique basin hit is 275=55*5;
        # the cofactor is generated by the support itself.
        exact = anchor_surviving_exact_support_hit(16, (5, 11))
        self.assertIsNotNone(exact)
        assert exact is not None
        self.assertEqual(exact["state"], 275)
        self.assertEqual(exact["cofactor"], 5)
        self.assertEqual(exact["exact_transverse_support"], [5, 11])
        self.assertTrue(exact["anchor_surviving"])

    def test_invalid_supports_are_rejected(self) -> None:
        with self.assertRaises(ValueError):
            support_product(10, (2, 3))  # 2 is an anchor prime.
        with self.assertRaises(ValueError):
            support_product(10, (3, 3))
        with self.assertRaises(ValueError):
            support_unique_basin_hit(10, (3,))  # G<=2k.


if __name__ == "__main__":
    unittest.main()
