import pytest

from enterprise_math.smith_certificate import verify_smith_certificate


def test_nontrivial_valid_transform():
    a = ((2, 4), (0, 6))
    u = ((1, 0), (0, 1))
    v = ((1, -2), (0, 1))
    s = ((2, 0), (0, 6))
    out = verify_smith_certificate(a, s, u, v)
    assert out.rank == 2
    assert out.free_rank == 0
    assert out.invariant_factors == (2, 6)
    assert out.torsion_order == 12


def test_rejects_forged_zero_transform_pattern():
    with pytest.raises(ValueError, match="unimodular"):
        verify_smith_certificate(((7,),), ((0,),), ((0,),), ((1,),))


def test_rejects_noncanonical_diagonal_chain():
    with pytest.raises(ValueError, match="d_i"):
        verify_smith_certificate(
            ((4, 0), (0, 6)),
            ((4, 0), (0, 6)),
            ((1, 0), (0, 1)),
            ((1, 0), (0, 1)),
        )


def test_rectangular_cokernel_summary():
    a = ((2, 0, 0), (0, 6, 0))
    out = verify_smith_certificate(
        a,
        a,
        ((1, 0), (0, 1)),
        ((1, 0, 0), (0, 1, 0), (0, 0, 1)),
    )
    assert out.rank == 2
    assert out.free_rank == 0
    assert out.invariant_factors == (2, 6)


def test_power_generated_nontrivial_certificate():
    # Generated by POWER smith_normal_form.py at frozen audit commit 6d784d3.
    a = ((2, 4, 4), (-6, 6, 12), (10, -4, -16))
    s = ((2, 0, 0), (0, 6, 0), (0, 0, 12))
    u = ((1, 0, 0), (2, -1, -1), (3, -4, -3))
    v = ((1, -2, 2), (0, 1, -2), (0, 0, 1))
    out = verify_smith_certificate(a, s, u, v)
    assert out.rank == 3
    assert out.invariant_factors == (2, 6, 12)
    assert out.torsion_order == 144
