from enterprise_math.p022_barlow_half_defect_prime_halving_dag import (
    basis_support_lies_in_endpoint_envelope,
    companion_offset_collision_signature,
    endpoint_dag_certifies_support_avoidance,
    half_defect_support_lies_in_endpoint_envelope,
    left_zero_endpoint_collision_candidates,
    prime_halving_ancestor_primes,
    prime_halving_endpoint_envelope,
)


def test_prime_halving_dag_examples() -> None:
    # 57=3*19; 19 -> 10 -> 5 -> 3 -> 2 under factor-and-half recursion.
    assert prime_halving_ancestor_primes(57) == (3, 5, 19)
    assert set(prime_halving_endpoint_envelope(57)) == {2, 3, 9, 10}

    # 86=2*43; 43 -> 22 -> 11 -> 6 -> 3 -> 2.
    assert prime_halving_ancestor_primes(86) == (3, 11, 43)
    assert set(prime_halving_endpoint_envelope(86)) == {2, 5, 6, 21, 22}


def test_exact_a_basis_support_lies_in_dag_envelope() -> None:
    for value in (3, 5, 7, 10, 14, 26, 50, 57, 74, 86, 119, 146, 194):
        assert basis_support_lies_in_endpoint_envelope(value)


def test_half_defect_support_lies_in_combined_dag() -> None:
    for prime in (23, 29, 47, 53, 71, 101, 149, 167, 173, 191, 197, 239, 269, 293):
        assert half_defect_support_lies_in_endpoint_envelope(prime)


def test_dag_certificate_handles_rank_ceiling_failure_examples() -> None:
    # p=173 has an early zero at j=4.  It is edge-eligible in the abstract
    # because 2*4-1=7 is prime, but 7 does not occur in the actual ancestor
    # prime set generated by m=86 or p-2=171.
    assert left_zero_endpoint_collision_candidates(173) == ()
    assert companion_offset_collision_signature(173) == ()
    assert endpoint_dag_certifies_support_avoidance(173)

    # These examples were also below the coarse rank ceiling, but the exact
    # prime-halving DAG still excludes every zero digit.
    for prime in (359, 389, 701, 863, 941, 1013, 1373, 1973, 2063, 2693):
        assert left_zero_endpoint_collision_candidates(prime) == ()
        assert endpoint_dag_certifies_support_avoidance(prime)


def test_dag_certificate_is_sufficient_not_claimed_necessary() -> None:
    # The function returns a candidate set, not the exact support intersection.
    # Current target examples have no candidate; future candidates would still
    # require coefficient/cancellation analysis before declaring a collision.
    assert left_zero_endpoint_collision_candidates(149) == ()
    assert endpoint_dag_certifies_support_avoidance(149)
