import pytest

from enterprise_math.p022_barlow_twin_transport_window import (
    strict_transport_Q_high_support,
    strict_transport_Q_plus_one_high_support,
    strict_transport_front,
    strict_transport_lower_window_is_captured,
    strict_transport_n0_high_support,
    strict_transport_survival_requires_scaled_twin,
    strict_transport_surviving_residue,
    strict_transport_zero_free_gap,
)


def test_strict_transport_front_forces_q_mod3_and_surviving_mod24_classes() -> None:
    assert strict_transport_front(30, 113) == (54, 17)
    assert strict_transport_front(69, 227) == (90, 11)
    assert strict_transport_surviving_residue(30, 113) == 17
    assert strict_transport_surviving_residue(69, 227) == 11


def test_midpoint_forced_classes_cannot_cross_the_zero_free_gap() -> None:
    # r=21,s=30,q=71 has the right reflected-endpoint twin geometry, but
    # q=23 mod24 and hence q=7 mod8 forces a midpoint zero inside the gap.
    assert strict_transport_front(21, 71) == (30, 23)
    with pytest.raises(ValueError):
        strict_transport_surviving_residue(21, 71)


def test_transport_gap_contains_no_additional_hidden_zero_pair() -> None:
    # For r=69,q=227 the reflected endpoint is s=90 and T-1=136.
    assert strict_transport_zero_free_gap(69, 227, (69, 90, 136, 157)) == (90, 136)


def test_Q_and_Q_plus_one_capture_gate_supports() -> None:
    # r=30 has 4r+1=121 composite, so D_61 exists.
    assert strict_transport_Q_high_support(30) == (
        (30, 1),
        (31, -1),
        (60, 1),
    )
    assert strict_transport_Q_plus_one_high_support(30) == ((61, 1),)

    # r=69 has 4r+1=277 prime, so D_139 is absent; D_140 still exists.
    with pytest.raises(ValueError):
        strict_transport_Q_high_support(69)
    assert strict_transport_Q_plus_one_high_support(69) == ((139, 1),)


def test_fixed_n0_gate_has_two_exact_structural_forms() -> None:
    # n0=206 is composite.
    assert strict_transport_n0_high_support(69) == ((69, 1), (205, 1))

    # n0=269 is prime, adding the sole adjacent middle pair m-1,m=134,135.
    assert strict_transport_n0_high_support(90) == (
        (90, 1),
        (134, 1),
        (135, -1),
        (268, 1),
    )


def test_lower_strict_window_is_closed_at_n0() -> None:
    # q=227 lies below (7r-2)/2=240.5 for r=69.
    assert strict_transport_lower_window_is_captured(69, 227)


def test_upper_n0_survival_forces_scaled_twin_center() -> None:
    # r=90, q=353, s=174: n0=269 is prime and m=135 is the twin center
    # generated by the only possible n0 cancellation channel.
    assert strict_transport_survival_requires_scaled_twin(90, 353) == (135, 271)
