import unittest

from enterprise_math.causal_operation_language import (
    class_count,
    common_refinement,
    induced_generator_maps,
    minimum_future_partition,
    observation_partition,
    operation_coupling_defect,
    operation_language_is_safe,
    partition_collision_spectrum,
    partition_refines,
    refinement_rounds,
    same_partition,
)


class CausalOperationLanguageTests(unittest.TestCase):
    def test_future_refinement_makes_every_generator_descend(self):
        states = (0, 1, 2, 3)
        observation = {0: 0, 1: 0, 2: 0, 3: 1}
        generators = {
            "g": {0: 0, 1: 0, 2: 1, 3: 0},
            "h": {0: 0, 1: 3, 2: 0, 3: 0},
        }
        raw = observation_partition(states, observation)
        future = minimum_future_partition(states, observation, generators)
        self.assertTrue(partition_refines(future, raw))
        self.assertTrue(operation_language_is_safe(states, future, generators))
        self.assertEqual(class_count(future), 4)
        induced = induced_generator_maps(states, future, generators)
        self.assertEqual(set(induced), {"g", "h"})

    def test_mixed_operation_words_create_distinctions_absent_separately(self):
        states = (0, 1, 2, 3)
        observation = {0: 0, 1: 0, 2: 0, 3: 1}
        left = {"g": {0: 0, 1: 0, 2: 1, 3: 0}}
        right = {"h": {0: 0, 1: 3, 2: 0, 3: 0}}

        p_left = minimum_future_partition(states, observation, left)
        p_right = minimum_future_partition(states, observation, right)
        static = common_refinement(states, p_left, p_right)
        joint = minimum_future_partition(states, observation, {**left, **right})

        self.assertEqual(class_count(p_left), 2)
        self.assertEqual(class_count(p_right), 3)
        self.assertEqual(class_count(static), 3)
        self.assertEqual(class_count(joint), 4)
        self.assertEqual(static[0], static[2])
        self.assertNotEqual(joint[0], joint[2])

        # The distinction is genuinely generated by a mixed word: h(g(2))=3 is
        # visible while h(g(0))=0 remains invisible.
        g = left["g"]
        h = right["h"]
        self.assertEqual(observation[h[g[2]]], 1)
        self.assertEqual(observation[h[g[0]]], 0)

    def test_operation_coupling_defect_has_nonnegative_p011_coordinates(self):
        states = (0, 1, 2, 3)
        observation = {0: 0, 1: 0, 2: 0, 3: 1}
        left = {"g": {0: 0, 1: 0, 2: 1, 3: 0}}
        right = {"h": {0: 0, 1: 3, 2: 0, 3: 0}}
        extra_classes, lost = operation_coupling_defect(
            states, observation, left, right, maximum_order=4
        )
        self.assertEqual(extra_classes, 1)
        # Static common refinement has fiber sizes (2,1,1); joint has (1,1,1,1).
        # Hence J1 remains four, J2 loses exactly one collision, higher Jk stay zero.
        self.assertEqual(lost, (0, 1, 0, 0))

    def test_adding_future_generators_can_only_refine_minimum_state(self):
        states = (0, 1, 2, 3, 4)
        observation = {0: 0, 1: 0, 2: 0, 3: 0, 4: 1}
        g = {0: 0, 1: 0, 2: 1, 3: 2, 4: 0}
        h = {0: 0, 1: 4, 2: 0, 3: 0, 4: 0}
        small = minimum_future_partition(states, observation, {"g": g})
        large = minimum_future_partition(states, observation, {"g": g, "h": h})
        self.assertTrue(partition_refines(large, small))
        self.assertGreaterEqual(class_count(large), class_count(small))

    def test_empty_future_language_is_exactly_current_observation(self):
        states = ("a", "b", "c")
        observation = {"a": 0, "b": 0, "c": 1}
        self.assertTrue(
            same_partition(
                minimum_future_partition(states, observation, {}),
                observation_partition(states, observation),
            )
        )
        self.assertEqual(refinement_rounds(states, observation, {}), 0)

    def test_partition_collision_spectrum_decreases_under_refinement(self):
        states = (0, 1, 2, 3)
        coarse = {0: 0, 1: 0, 2: 0, 3: 1}
        fine = {0: 0, 1: 1, 2: 2, 3: 3}
        self.assertTrue(partition_refines(fine, coarse))
        before = partition_collision_spectrum(states, coarse, 4)
        after = partition_collision_spectrum(states, fine, 4)
        self.assertEqual(before[0], after[0])  # J1=|X|
        self.assertTrue(all(a <= b for a, b in zip(after[1:], before[1:])))


if __name__ == "__main__":
    unittest.main()
