from pathlib import Path
import r055_core as r
ART=Path('/mnt/data/r055_work/artifacts')
ledger={
 'schema':'R055_THEOREM_COUNTEREXAMPLE_LEDGER_V1','researcher_id':'EM-R055-4C2A71',
 'freeze_stage':'AFTER_SMALL_N_EXHAUSTIVE_AND_CONSTRUCTION_BEFORE_STRICT_HOLDOUT_AND_EXTERNAL_SHAPE_COMPARISON',
 'frozen_protocol_hashes':{
  'R055_RELAXATION_PROTOCOL_SHA256':'aa69f2bc31cb9b5ec574a85de2879b9f8f765cfdfdb6dd0cbfc625cf8feed683',
  'R055_MOVE_ENERGY_REGISTRY_SHA256':'83d546105a3fa721ba5cadea9a1bbf217a1661fdf0d1560fcdccc6d4c9d29ceb',
  'R055_INITIAL_STATE_REGISTRY_SHA256':'5de0e7ae6ff89cf81342f6c18125eb1eebd78c4725c0324acee2893552acd7f2'
 },
 'entries':[
  {'id':'R055-T01-PAIRWISE-CENTROID-IDENTITY','claim':'For every finite equal-mass cluster C of N points in the declared affine Euclidean lattice realization, I2(C)=sum_x ||x-g||^2=(1/N) sum_{x<y} ||x-y||^2; hence G=N I2=sum_{x<y} Q(x-y) is an exact nonnegative integer.','status':'PROVED','evidence':'algebraic expansion; executable fast-form versus pairwise checks in checker','scope':'all finite N'},
  {'id':'R055-T02-EXACT-REPLACEMENT-DELTA','claim':'For S=sum_C x, d=v-u and L the polar form L((a,b),(c,d))=2ac+ad+bc+2bd, one replacement u->v satisfies DeltaG=N(Q(v)-Q(u))-[L(S,d)+Q(d)].','status':'PROVED','evidence':'direct expansion of G=N sum Q(x)-Q(S); checked per accepted move','scope':'all replacements'},
  {'id':'R055-T03-STRICT-DESCENT-TERMINATION','claim':'Every D1 or D2 trajectory under the frozen strict rule terminates after finitely many accepted moves because G is a nonnegative integer and strictly decreases by at least 1 at every accepted move. The fixed-N translation+D6 state quotient is also finite.','status':'PROVED','scope':'all fixed finite N'},
  {'id':'R055-T04-LOCAL-HOLE-UPDATE-CRITERION','claim':'Starting from hole-free C, for Cprime=(C\\{u}) union {v}, let R=C\\{u}, assume Cprime is connected, let k be the number of occupied components of R, and c the number of cyclic occupied-neighbor runs of v in R. Under the frozen six-neighbor exterior test, Cprime is hole-free iff c=k.','status':'PROVED','evidence':'planar triangular-lattice articulation/run argument; exhaustive candidate cross-check against padded flood fill through all N<=8 classes with zero mismatches','scope':'single-site replacement from hole-free C'},
  {'id':'R055-X01-D1-MIN-NOT-D2-MIN','claim':'Not every D1 local minimum is D2-minimal. Smallest exact counterexample occurs at N=6; two of the three D1 minima admit strict D2 improvement.','status':'COUNTEREXAMPLE','evidence':'R055_SMALL_N_EXHAUSTIVE_ATLAS.json; explicit G=33 ->29 and G=30 ->29 D2 escapes','smallest_N':6},
  {'id':'R055-X02-INITIAL-CONDITION-INDEPENDENCE','claim':'D1 terminal class is not independent of initial state. At N=6 there are three exact D1 local minima; taking them as initial states yields three inequivalent terminal classes. All 13 construction N also show multiple primary terminal classes across frozen starts.','status':'COUNTEREXAMPLE','smallest_N':6},
  {'id':'R055-X03-TIE-BREAK-INDEPENDENCE','claim':'D1 terminal class is not tie-break independent. At N=6 an exact starting class reaches different D1 terminal classes under T0 versus T1/T2; each of the 13 construction N has a frozen-family tie-dependence witness.','status':'COUNTEREXAMPLE','smallest_N':6},
  {'id':'R055-X04-UNIQUE-D1-TERMINAL-SHAPE','claim':'A unique D1 attractor/terminal shape does not exist in general. Exact counterexample at N=6; moreover an infinite centered-shell subsequence has a provable nonglobal D1 trap for every shell radius r>=6.','status':'COUNTEREXAMPLE','smallest_N':6},
  {'id':'R055-X05-UNIQUE-D1-CENTROID-CLASS','claim':'D1 terminal centroid class is not unique in general. The N=6 D1 minima already have distinct centroid residue/D6 stabilizer classes; all construction N have multiple primary terminal centroid classes.','status':'COUNTEREXAMPLE','smallest_N':6},
  {'id':'R055-X06-G-PEDGE-MINIMIZER-SET-EQUALITY','claim':'The exact global G-minimizer set need not equal the exact global P_edge-minimizer set. At N=6 the G minimizer is unique while P_edge has three minimizer classes (including the G minimizer); set inequality recurs at N=9 and N=11 within N<=12.','status':'COUNTEREXAMPLE','smallest_N':6,'boundary':'This does not disprove the stronger inclusion hypothesis global-G-minimizer subset global-P_edge-minimizers, which remains true in N<=12 data and is not proved all-N.'},
  {'id':'R055-X07-G-DECREASE-DOES-NOT-MONOTONIZE-DIAGNOSTICS','claim':'Strict accepted decrease of G does not monotonically improve P_edge, A2, boundary squared-radius dispersion, or six-direction imbalance. Each diagnostic has an explicit worsening step already on N=19 ELONGATED_STRIP primary D1.','status':'COUNTEREXAMPLE','evidence':'R055_OBJECTIVE_COMPARISON.json'},
  {'id':'R055-T05-CENTERED-SHELL-D1-TRAP','claim':'Let H_r={ (a,b): max(|a|,|b|,|a+b|)<=r } with N_r=1+3r(r+1). For every r>=1, H_r is a D1 local minimum of G. D6 symmetry gives S=0. Any nearest-neighbor move to an empty site crosses the shell boundary and has Q(v)-Q(u)>=r+1, while Q(v-u)=1, so DeltaG>=N_r(r+1)-1>0.','status':'PROVED','scope':'all r>=1'},
  {'id':'R055-T06-CENTERED-SHELL-D2-ESCAPE','claim':'For every r>=6, H_r is not D2-minimal. Remove u=(-r,0) and add v=(ceil((r+1)/2),floor((r+1)/2)); the relocation is connected and hole-free. For r=2k>=6, DeltaG=-2k(6k^3-15k^2-8k-1)<0. For r=2k+1>=7, DeltaG=-(2k+1)(6k^3-6k^2-17k-7)<0.','status':'PROVED','scope':'all integer r>=6'},
  {'id':'R055-T07-INFINITE-D1-METASTABILITY','claim':'For every centered-shell count N_r with r>=6, D1 has at least two inequivalent terminal states: H_r itself and the D1 terminal reached after first taking the strict D2-improving state from R055-T06. Their G values differ, so they cannot be translation+D6 equivalent. Hence exact D1 metastability persists along an infinite N subsequence.','status':'PROVED','scope':'N_r=1+3r(r+1), r>=6'},
  {'id':'R055-X08-D2-UNIQUE-ATTRACTOR','claim':'Even D2 strict relocation need not select one terminal class from the tested construction starts. Multiple D2 terminal G/classes are observed at N=31,53,91,113,127,151,169,217 depending on whether D2 starts from frozen initial states or D1 terminals.','status':'BOUNDED_MULTI_START_OBSERVATION','scope':'construction N; not an exact all-state counterexample unless separately exhausted'},
  {'id':'R055-O01-ASYMPTOTIC-ISOTROPY-ROUNDNESS','claim':'Whether global/D2 G minimizers have an isotropic or disk-like continuum limit.','status':'OPEN','reason':'No continuum disk/regular-hex comparison opened before ledger freeze; finite diagnostics are insufficient for theorem.'},
  {'id':'R055-O02-GLOBAL-G-LIMIT-SHAPE','claim':'Existence and uniqueness of a rescaled limit shape for exact global G minimizers.','status':'OPEN'},
  {'id':'R055-O03-D1-TERMINAL-LIMIT-SHAPE','claim':'Existence of one rescaled D1 terminal limit shape independent of initial state.','status':'OPEN','known_obstruction':'Exact terminal nonuniqueness persists on infinite centered-shell subsequence, but distinct continuum subsequential shapes have not yet been proved.'},
  {'id':'R055-O04-GLOBAL-G-SUBSET-PEDGE','claim':'Whether every exact global G minimizer is also a P_edge minimizer for all N.','status':'OPEN','evidence':'true for exhaustive N<=12 only; minimizer-set equality already false.'},
  {'id':'R055-O05-CENTROID-SPECIAL-CLASS-LIMIT','claim':'Whether global/D2 minimizer centroids are restricted asymptotically to a finite family of symmetry residue classes.','status':'OPEN','evidence':'D1 terminals include generic stabilizer-1 centroid classes, so no such restriction holds for arbitrary D1 terminal states.'}
 ],
 'freeze_conclusions':{
  'strict_descent_termination':'PROVED','exact_centroid_pairwise_identity':'PROVED','D1_local_minimum_vs_D2_minimum_equivalence':'COUNTEREXAMPLE','initial_condition_independence':'COUNTEREXAMPLE','tie_break_independence':'COUNTEREXAMPLE','uniqueness_of_terminal_shape':'COUNTEREXAMPLE','uniqueness_of_D1_centroid_class':'COUNTEREXAMPLE','asymptotic_isotropy_roundness':'OPEN','gravity_minimum_vs_perimeter_minimum_set_equivalence':'COUNTEREXAMPLE','disk_or_hexagonal_continuum_limit':'OPEN'
 },
 'holdout_unopened_at_freeze':True,'external_euclidean_disk_or_regular_hexagon_comparison_unopened_at_freeze':True,'classical_pi_used_pre_freeze':False
}
r.json_dump(ART/'R055_THEOREM_COUNTEREXAMPLE_LEDGER.json',ledger)
print(r.sha256_file(ART/'R055_THEOREM_COUNTEREXAMPLE_LEDGER.json'))
