#include <algorithm>
#include <array>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <queue>
#include <set>
#include <string>
#include <tuple>
#include <unordered_set>
#include <unordered_map>
#include <vector>
using namespace std;
struct P{int a,b; bool operator==(P const&o)const{return a==o.a&&b==o.b;} bool operator!=(P const&o)const{return !(*this==o);} bool operator<(P const&o)const{return a<o.a||(a==o.a&&b<o.b);} };
static const array<P,6>D={P{1,0},P{0,1},P{-1,1},P{-1,0},P{0,-1},P{1,-1}};
static const uint64_t MASK64=~uint64_t(0);
P addp(P x,P y){return{x.a+y.a,x.b+y.b};}P subp(P x,P y){return{x.a-y.a,x.b-y.b};}
long long Q(P p){return 1LL*p.a*p.a+1LL*p.a*p.b+1LL*p.b*p.b;}long long L(P p,P q){return 2LL*p.a*q.a+1LL*p.a*q.b+1LL*p.b*q.a+2LL*p.b*q.b;}
P rot(P p){return{-p.b,p.a+p.b};}P refl(P p){return{p.a+p.b,-p.b};}P trans(P p,int idx){if(idx>=6)p=refl(p);for(int k=0;k<idx%6;k++)p=rot(p);return p;}
uint64_t pack(P p){return (uint64_t)(uint32_t)(p.a+100000)<<32 | (uint32_t)(p.b+100000);}
unordered_set<uint64_t> pset(const vector<P>&v){unordered_set<uint64_t>s;s.reserve(v.size()*3+8);for(auto p:v)s.insert(pack(p));return s;}
void sortv(vector<P>&v){sort(v.begin(),v.end());}
vector<P> norm_trans(vector<P>v){int ma=1000000000,mb=1000000000;for(auto p:v){ma=min(ma,p.a);mb=min(mb,p.b);}for(auto &p:v){p.a-=ma;p.b-=mb;}sortv(v);return v;}
string enc_norm(const vector<P>&vin){auto v=norm_trans(vin);string s;s.reserve(v.size()*12);for(auto p:v){s+=to_string(p.a);s.push_back(',');s+=to_string(p.b);s.push_back(';');}return s;}
vector<P> canon_vec(const vector<P>&v){vector<P>best;bool first=true;for(int t=0;t<12;t++){vector<P>w;w.reserve(v.size());for(auto p:v)w.push_back(trans(p,t));w=norm_trans(w);if(first||w<best){best=move(w);first=false;}}return best;}
string canon_key(const vector<P>&v){auto c=canon_vec(v);string s;s.reserve(c.size()*12);for(auto p:c){s+=to_string(p.a);s.push_back(',');s+=to_string(p.b);s.push_back(';');}return s;}
array<int,4> canonical_move_key(const vector<P>&cp,P u,P vv){vector<P>best=canon_vec(cp);array<int,4>bk{1000000,1000000,1000000,1000000};bool have=false;for(int t=0;t<12;t++){vector<P>w;w.reserve(cp.size());for(auto p:cp)w.push_back(trans(p,t));int ma=1000000000,mb=1000000000;for(auto p:w){ma=min(ma,p.a);mb=min(mb,p.b);}for(auto &p:w){p.a-=ma;p.b-=mb;}sortv(w);if(w!=best)continue;P tu=trans(u,t),tv=trans(vv,t);array<int,4>k{tu.a-ma,tu.b-mb,tv.a-ma,tv.b-mb};if(!have||k<bk){bk=k;have=true;}}if(!have)throw runtime_error("no canonical transform");return bk;}
bool connected(const vector<P>&v){if(v.empty())return false;auto occ=pset(v);unordered_set<uint64_t>seen;vector<P>st{v[0]};seen.insert(pack(v[0]));while(!st.empty()){P p=st.back();st.pop_back();for(auto d:D){P q=addp(p,d);auto k=pack(q);if(occ.count(k)&&seen.insert(k).second)st.push_back(q);}}return seen.size()==v.size();}
bool holefree(const vector<P>&v){if(v.empty())return true;auto occ=pset(v);int amin=1e9,amax=-1e9,bmin=1e9,bmax=-1e9;for(auto p:v){amin=min(amin,p.a);amax=max(amax,p.a);bmin=min(bmin,p.b);bmax=max(bmax,p.b);}int A0=amin-1,A1=amax+1,B0=bmin-1,B1=bmax+1;unordered_set<uint64_t>ext;queue<P>q;auto seed=[&](P p){auto k=pack(p);if(!occ.count(k)&&ext.insert(k).second)q.push(p);};for(int a=A0;a<=A1;a++){seed({a,B0});seed({a,B1});}for(int b=B0;b<=B1;b++){seed({A0,b});seed({A1,b});}while(!q.empty()){P p=q.front();q.pop();for(auto d:D){P z=addp(p,d);if(z.a<A0||z.a>A1||z.b<B0||z.b>B1)continue;auto k=pack(z);if(!occ.count(k)&&ext.insert(k).second)q.push(z);}}for(int a=amin;a<=amax;a++)for(int b=bmin;b<=bmax;b++){auto k=pack({a,b});if(!occ.count(k)&&!ext.count(k))return false;}return true;}
vector<P> boundary(const vector<P>&v){auto occ=pset(v);vector<P>b;for(auto p:v){for(auto d:D)if(!occ.count(pack(addp(p,d)))){b.push_back(p);break;}}sortv(b);return b;}
vector<P> frontier(const vector<P>&v){auto occ=pset(v);set<P>f;for(auto p:v)for(auto d:D){P q=addp(p,d);if(!occ.count(pack(q)))f.insert(q);}return vector<P>(f.begin(),f.end());}
long long energy(const vector<P>&v){long long sq=0;P S{0,0};for(auto p:v){sq+=Q(p);S.a+=p.a;S.b+=p.b;}return (long long)v.size()*sq-Q(S);}P sump(const vector<P>&v){P S{0,0};for(auto p:v){S.a+=p.a;S.b+=p.b;}return S;}
bool pure_translation(const vector<P>&a,const vector<P>&b){return norm_trans(a)==norm_trans(b);}
struct RM{P u,v;long long delta;int order;};struct Move{P u,v;long long delta;vector<P>cp;string ck;array<int,4>mk;int order;};
vector<RM> raw_candidates(const vector<P>&C,const string&dyn){auto occ=pset(C);auto bd=boundary(C);P S=sump(C);int n=C.size();vector<RM>out;int ord=0;vector<P>F;vector<int>fc;if(dyn=="D2"){F=frontier(C);fc.resize(F.size());for(size_t i=0;i<F.size();i++){int c=0;for(auto d:D)if(occ.count(pack(addp(F[i],d))))c++;fc[i]=c;}}
 for(auto u:bd){if(dyn=="D1"){for(auto d:D){P v=addp(u,d);if(occ.count(pack(v)))continue;int touch=0;for(auto d2:D){P q=addp(v,d2);if(q==u)continue;if(occ.count(pack(q)))touch++;}if(touch<1)continue;P dd=subp(v,u);long long dg=1LL*n*(Q(v)-Q(u))-(L(S,dd)+Q(dd));if(dg<0)out.push_back({u,v,dg,ord});ord++;}}
 else if(dyn=="D2"){for(size_t i=0;i<F.size();i++){P v=F[i];if(v==u)continue;int cnt=fc[i];bool adj=false;for(auto d:D)if(addp(v,d)==u){adj=true;break;}if(cnt-(adj?1:0)<1)continue;P dd=subp(v,u);long long dg=1LL*n*(Q(v)-Q(u))-(L(S,dd)+Q(dd));if(dg<0)out.push_back({u,v,dg,ord});ord++;}}
 else throw runtime_error("bad dyn");}return out;}
int compcount_without(const vector<P>&C,P u){vector<P>R;R.reserve(C.size()-1);for(auto p:C)if(p!=u)R.push_back(p);if(R.empty())return 0;auto occ=pset(R);unordered_set<uint64_t>seen;int k=0;for(auto p:R){auto pk=pack(p);if(seen.count(pk))continue;k++;vector<P>st{p};seen.insert(pk);while(!st.empty()){P x=st.back();st.pop_back();for(auto d:D){P q=addp(x,d);auto qk=pack(q);if(occ.count(qk)&&seen.insert(qk).second)st.push_back(q);}}}return k;}
int occupied_runs_after_removal(const vector<P>&C,P u,P v){auto occ=pset(C);array<int,6>b{};for(int i=0;i<6;i++){P q=addp(v,D[i]);b[i]=(q!=u && occ.count(pack(q)))?1:0;}bool all=true;for(int x:b)if(!x)all=false;if(all)return 1;int c=0;for(int i=0;i<6;i++)if(b[i]&&!b[(i+5)%6])c++;return c;}
bool legal_after_move_topo(const vector<P>&C,P u,P v,vector<P>&cp,unordered_map<uint64_t,int>&kcache){cp=C;auto it=find(cp.begin(),cp.end(),u);if(it==cp.end())return false;*it=v;sortv(cp);if(pure_translation(C,cp)||!connected(cp))return false;auto ku=pack(u);int k;auto kt=kcache.find(ku);if(kt==kcache.end()){k=compcount_without(C,u);kcache.emplace(ku,k);}else k=kt->second;int c=occupied_runs_after_removal(C,u,v);return c==k;}
Move* select_move(const vector<P>&C,const string&dyn,const string&tie,Move&chosen){auto raws=raw_candidates(C,dyn);if(raws.empty())return nullptr;vector<long long>ds;for(auto&m:raws)ds.push_back(m.delta);sort(ds.begin(),ds.end());ds.erase(unique(ds.begin(),ds.end()),ds.end());long long G=energy(C);unordered_map<uint64_t,int>kcache;for(long long d:ds){vector<Move>leg;for(auto rm:raws){if(rm.delta!=d)continue;vector<P>cp;if(!legal_after_move_topo(C,rm.u,rm.v,cp,kcache))continue;long long Gp=energy(cp);if(Gp-G!=d||!(Gp<G))throw runtime_error("delta/check mismatch");Move m{rm.u,rm.v,d,move(cp),"",{},rm.order};leg.push_back(move(m));}if(leg.empty())continue;int bi=0;if(tie=="T2_ORIENTATION_MOVE_LEX"){for(int i=1;i<(int)leg.size();i++){auto ka=array<int,4>{leg[i].u.a,leg[i].u.b,leg[i].v.a,leg[i].v.b};auto kb=array<int,4>{leg[bi].u.a,leg[bi].u.b,leg[bi].v.a,leg[bi].v.b};if(ka<kb)bi=i;}chosen=move(leg[bi]);return &chosen;}if(leg.size()==1){chosen=move(leg[0]);return &chosen;}for(auto &m:leg){m.ck=canon_key(m.cp);m.mk=canonical_move_key(m.cp,m.u,m.v);}auto lessT0=[&](const Move&a,const Move&b){if(a.ck!=b.ck)return a.ck<b.ck;if(a.mk!=b.mk)return a.mk<b.mk;return a.order<b.order;};auto lessT1=[&](const Move&a,const Move&b){if(a.ck!=b.ck)return a.ck<b.ck;if(a.mk!=b.mk)return a.mk<b.mk;return a.order>b.order;};if(tie=="T0_CANONICAL_MIN"){for(int i=1;i<(int)leg.size();i++)if(lessT0(leg[i],leg[bi]))bi=i;}else if(tie=="T1_CANONICAL_MAX"){for(int i=1;i<(int)leg.size();i++)if(lessT1(leg[bi],leg[i]))bi=i;}else throw runtime_error("bad tie");chosen=move(leg[bi]);return &chosen;}return nullptr;}
uint64_t splitnext(uint64_t &state){state+=0x9E3779B97F4A7C15ULL;uint64_t z=state;z=(z^(z>>30))*0xBF58476D1CE4E5B9ULL;z=(z^(z>>27))*0x94D049BB133111EBULL;return z^(z>>31);} 
vector<P> hexgrow(int N){vector<P>pts{{0,0}};int r=1;array<P,6>wd={P{-1,1},P{-1,0},P{0,-1},P{1,-1},P{1,0},P{0,1}};while((int)pts.size()<N){P p{r,0};vector<P>ring;for(auto d:wd)for(int k=0;k<r;k++){if(find(ring.begin(),ring.end(),p)==ring.end())ring.push_back(p);p=addp(p,d);}if((int)ring.size()!=6*r)throw runtime_error("ring");for(auto z:ring){if((int)pts.size()>=N)break;pts.push_back(z);}r++;}sortv(pts);return pts;}
vector<P> strip(int N){vector<P>v;for(int a=0;a<N;a++)v.push_back({a,0});return v;}
vector<P> star(int N){vector<P>v{{0,0}};array<int,6>len{};int k=0;while((int)v.size()<N){int i=k%6;len[i]++;v.push_back({D[i].a*len[i],D[i].b*len[i]});k++;}sortv(v);return v;}
vector<P> lshape(int N){int h=(N+2)/2;vector<P>v;for(int a=0;a<h;a++)v.push_back({a,0});for(int b=1;b<=N-h;b++)v.push_back({0,b});sortv(v);return v;}
vector<P> eden(int N,uint64_t seed){vector<P>C{{0,0}};uint64_t state=seed ^ (uint64_t(N)*0x9E3779B97F4A7C15ULL);while((int)C.size()<N){auto F=frontier(C);uint64_t z=splitnext(state);size_t st=z%F.size();bool ok=false;for(size_t j=0;j<F.size();j++){P v=F[(st+j)%F.size()];auto cp=C;cp.push_back(v);sortv(cp);if(connected(cp)&&holefree(cp)){C=move(cp);ok=true;break;}}if(!ok)throw runtime_error("eden");}return C;}
int gd(P p){return max({abs(p.a),abs(p.b),abs(p.a+p.b)});}vector<P> compact(int N){vector<P>C{{0,0}};while((int)C.size()<N){auto F=frontier(C);auto occ=pset(C);auto best=F[0];auto key=[&](P p){int nb=0;for(auto d:D)if(occ.count(pack(addp(p,d))))nb++;return tuple<int,int,int,int>{-nb,gd(p),p.b,p.a};};for(auto p:F)if(key(p)<key(best))best=p;C.push_back(best);sortv(C);if(!holefree(C))throw runtime_error("compact hole");}return C;}
vector<pair<string,vector<P>>> initials(int N){return{{"HEX_SHELL_GROWTH",hexgrow(N)},{"ELONGATED_STRIP",strip(N)},{"SIX_ARM_STAR",star(N)},{"L_SHAPE_OR_WEDGE",lshape(N)},{"EDEN_SEEDED_seed_550001",eden(N,550001)},{"EDEN_SEEDED_seed_550021",eden(N,550021)},{"EDEN_SEEDED_seed_550057",eden(N,550057)},{"COMPACT_BFS_ALT_TIE",compact(N)}};}
struct Rec{string dyn,tie,fam,source;vector<P>init,fin;vector<long long>Gs;vector<P>Ss;struct Step{P u,v;long long d,G;P S;};vector<Step>steps;};
Rec relax(vector<P>C,string dyn,string tie,string fam,string source){if(!connected(C)||!holefree(C))throw runtime_error("bad init");Rec r{dyn,tie,fam,source,C,{},{energy(C)},{sump(C)}, {}};for(int k=0;k<200000;k++){Move m;auto pm=select_move(C,dyn,tie,m);if(!pm){r.fin=C;return r;}C=m.cp;long long G=energy(C);P S=sump(C);if(!(G<r.Gs.back()))throw runtime_error("non-desc");r.steps.push_back({m.u,m.v,m.delta,G,S});r.Gs.push_back(G);r.Ss.push_back(S);}throw runtime_error("maxsteps");}
void printP(ostream&o,P p){o<<'['<<p.a<<','<<p.b<<']';}void printState(ostream&o,const vector<P>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';printP(o,v[i]);}o<<']';}
void writeRec(ostream&o,const Rec&r){o<<'{';o<<"\"N\":"<<r.init.size()<<",\"dynamics\":\""<<r.dyn<<"\",\"tie_break\":\""<<r.tie<<"\",\"initial_family\":\""<<r.fam<<"\",\"source\":\""<<r.source<<"\",\"initial_G\":"<<r.Gs.front()<<",\"terminal_G\":"<<r.Gs.back()<<",\"move_count\":"<<r.steps.size()<<",\"initial_state\":";printState(o,r.init);o<<",\"final_state\":";printState(o,r.fin);o<<",\"G_sequence\":[";for(size_t i=0;i<r.Gs.size();i++){if(i)o<<',';o<<r.Gs[i];}o<<"],\"centroid_sum_sequence\":[";for(size_t i=0;i<r.Ss.size();i++){if(i)o<<',';printP(o,r.Ss[i]);}o<<"],\"moves\":[";for(size_t i=0;i<r.steps.size();i++){if(i)o<<',';auto&s=r.steps[i];o<<'['<<s.u.a<<','<<s.u.b<<','<<s.v.a<<','<<s.v.b<<','<<s.d<<','<<s.G<<','<<s.S.a<<','<<s.S.b<<']';}o<<"]}"<<'\n';}
int main(int argc,char**argv){if(argc<3){cerr<<"usage N out.jsonl [mode]\n";return 2;}int N=stoi(argv[1]);ofstream out(argv[2]);string mode=argc>3?argv[3]:"construction";auto ins=initials(N);array<string,3>ties={"T0_CANONICAL_MIN","T1_CANONICAL_MAX","T2_ORIENTATION_MOVE_LEX"};vector<Rec>d1prim;if(mode=="primary"){for(auto &[fam,C]:ins){auto r=relax(C,"D1",ties[0],fam,"INITIAL");d1prim.push_back(r);writeRec(out,r);cerr<<N<<" D1 primary "<<fam<<" "<<r.steps.size()<<" "<<r.Gs.back()<<"\n"<<flush;}return 0;}if(mode=="strip_primary"){auto C=strip(N);auto r=relax(C,"D1",ties[0],"ELONGATED_STRIP","INITIAL");writeRec(out,r);cerr<<N<<" strip primary "<<r.steps.size()<<" "<<r.Gs.back()<<"\n";return 0;}for(auto &[fam,C]:ins){for(auto tie:ties){auto r=relax(C,"D1",tie,fam,"INITIAL");if(tie==ties[0])d1prim.push_back(r);writeRec(out,r);cerr<<N<<" D1 "<<tie<<" "<<fam<<" "<<r.steps.size()<<" "<<r.Gs.back()<<"\n"<<flush;}}
 // D2 primary reference from each initial and each primary D1 terminal.
 for(auto &[fam,C]:ins){auto r=relax(C,"D2",ties[0],fam,"INITIAL");writeRec(out,r);cerr<<N<<" D2 init "<<fam<<" "<<r.steps.size()<<" "<<r.Gs.back()<<"\n"<<flush;}
 for(auto &d1:d1prim){auto r=relax(d1.fin,"D2",ties[0],d1.fam,"D1_PRIMARY_TERMINAL");writeRec(out,r);cerr<<N<<" D2 d1term "<<d1.fam<<" "<<r.steps.size()<<" "<<r.Gs.back()<<"\n"<<flush;}
}
