"""Input/precision boundary audit of frozen Stage80; no new scientific kernel.

All phase intervals are generated by the unchanged Stage79 actual positive BRC
probe. Integer precision scheduling is metadata; no trig or numeric root route.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import os
import sys
from fractions import Fraction as F
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = Path(os.environ.get('BRC_STAGE87_SOURCE',str(ROOT.parent/'stage87-source'))).resolve()
sys.path.insert(0, str(SOURCE))
from stage45.brc_loop_recheck import CALLS, verify_vendor
from stage79.phase_compiler import root_bracket, dyadic_parameters, encode


def first_original_grid_failure(bits, horizon):
    lo = hi = F(1)
    rows = []
    for m in range(3,horizon+1):
        l,_ = root_bracket(lo,bits)
        _,u = root_bracket(hi,bits)
        rows.append({'m':m,'input_lower':lo,'input_upper':hi,
                     'lower':l,'upper':u})
        if m % 8 == 0:
            print('frozen-grid phase',m,'completed',flush=True)
        if not (0 < l <= u < 1 and u-l <= F(4,1<<bits)):
            return {'first_failure_m':m,'bits':bits,'rows':rows,
                    'condition':'Stage79 dyadic_parameters strict positive lower'}
        lo,hi=l,u
    return {'first_failure_m':None,'bits':bits,'rows':rows}


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--output',required=True)
    ap.add_argument('--activity',required=True)
    args=ap.parse_args()
    core=verify_vendor()
    initial=len(CALLS)
    failure=first_original_grid_failure(32,36)
    assert failure['first_failure_m'] is not None
    # Confirm the failure is the unchanged production interface, not merely
    # the diagnostic extraction of its same loop.
    old_failed=False
    try:
        dyadic_parameters(failure['first_failure_m'],32)
    except AssertionError:
        old_failed=True
    assert old_failed
    relevant=['stage79/phase_compiler.py','stage80/fixed_phase.py',
              'stage78/shor_benchmark.py']
    report={'schema':'SHOR_FIXED_PRECISION_BOUNDARY_AUDIT_V1',
            'status':'AUTHOR_EXACT_BRC_CHECK_NOT_INDEPENDENT_ADMISSION',
            'activity':args.activity,
            'source_head':'0852cad130c1d877174d235687cf60c19f318c58',
            'source_sha256':{p:hashlib.sha256((SOURCE/p).read_bytes()).hexdigest()
                             for p in relevant},
            'kernel':core,'arithmetic':'ACTUAL_TYPED_BRC_ONLY',
            'original_failure':failure,'original_function_asserts':old_failed,
            'selected_repair':'zero_endpoint_extension.py; same 32-bit grid',
            'higher_precision_run_performed':False,
            'actual_BRC_core_calls':len(CALLS)-initial,
            'scope':'phase-interval compiler and precision/error schedule only; '
                    'not an executed 34-bit Shor endpoint simulation',
            'no_order_or_factor_input':True,
            'no_float_trig_or_numeric_roots':True}
    Path(args.output).write_text(json.dumps(encode(report),ensure_ascii=False,
                                           indent=2)+'\n',encoding='utf-8')
    print(json.dumps(encode({k:report[k] for k in ['original_function_asserts',
          'selected_repair','actual_BRC_core_calls']}),
          ensure_ascii=False))
    print('first_failure_m',failure['first_failure_m'])

if __name__=='__main__':
    main()
