import Mathlib.Data.Set.Lattice

namespace EnterpriseMath.BranchDeferral

universe u v w x

variable {α : Type u} {β : Type v} {γ : Type w}

/-- Result-support lifting of a relation. It forgets path multiplicity and keeps
only the set of reachable results. -/
def RelSupport (R : α → β → Prop) (A : Set α) : Set β :=
  {y | ∃ x ∈ A, R x y}

/-- Relational composition, oriented so that `R` is followed by `S`. -/
def RelComp (R : α → β → Prop) (S : β → γ → Prop) : α → γ → Prop :=
  fun x z => ∃ y, R x y ∧ S y z

/-- R016-L01: the empty support has no reachable results. -/
theorem relSupport_empty (R : α → β → Prop) :
    RelSupport R ∅ = ∅ := by
  ext y
  constructor
  · rintro ⟨x, hx, _⟩
    exact hx.elim
  · intro hy
    exact hy.elim

/-- R016-L02: relational result-support preserves binary unions exactly. -/
theorem relSupport_union (R : α → β → Prop) (A B : Set α) :
    RelSupport R (A ∪ B) = RelSupport R A ∪ RelSupport R B := by
  ext y
  constructor
  · rintro ⟨x, hx, hxy⟩
    rcases hx with hx | hx
    · exact Or.inl ⟨x, hx, hxy⟩
    · exact Or.inr ⟨x, hx, hxy⟩
  · intro hy
    rcases hy with hy | hy
    · rcases hy with ⟨x, hx, hxy⟩
      exact ⟨x, Or.inl hx, hxy⟩
    · rcases hy with ⟨x, hx, hxy⟩
      exact ⟨x, Or.inr hx, hxy⟩

/-- R016-L03: relational result-support preserves an arbitrary indexed union. -/
theorem relSupport_iUnion {ι : Type x} (R : α → β → Prop) (A : ι → Set α) :
    RelSupport R (⋃ i, A i) = ⋃ i, RelSupport R (A i) := by
  ext y
  constructor
  · rintro ⟨a, ha, hay⟩
    rcases Set.mem_iUnion.mp ha with ⟨i, hai⟩
    exact Set.mem_iUnion.mpr ⟨i, ⟨a, hai, hay⟩⟩
  · intro hy
    rcases Set.mem_iUnion.mp hy with ⟨i, hi⟩
    rcases hi with ⟨a, hai, hay⟩
    exact ⟨a, Set.mem_iUnion.mpr ⟨i, hai⟩, hay⟩

/-- R016-L04: support propagation through a composed relation is exactly
successive support propagation, fixing the composition orientation. -/
theorem relSupport_comp (R : α → β → Prop) (S : β → γ → Prop) (A : Set α) :
    RelSupport (RelComp R S) A = RelSupport S (RelSupport R A) := by
  ext z
  constructor
  · rintro ⟨a, ha, ⟨b, hab, hbz⟩⟩
    exact ⟨b, ⟨a, ha, hab⟩, hbz⟩
  · rintro ⟨b, ⟨a, ha, hab⟩, hbz⟩
    exact ⟨a, ha, ⟨b, hab, hbz⟩⟩

/-- R016-L05: semantic two-branch deferral. Branch now or keep the unresolved
union; the reachable result-support after one relational future is identical. -/
theorem two_branch_deferral (R : α → β → Prop) (A B : Set α) :
    RelSupport R (A ∪ B) = RelSupport R A ∪ RelSupport R B :=
  relSupport_union R A B

/-- R016-L06 (two steps): eager branching and lazy unresolved support have the
same reachable results after two relational futures. -/
theorem two_step_branch_deferral (R : α → β → Prop) (S : β → γ → Prop)
    (A B : Set α) :
    RelSupport S (RelSupport R (A ∪ B)) =
      RelSupport S (RelSupport R A) ∪ RelSupport S (RelSupport R B) := by
  calc
    RelSupport S (RelSupport R (A ∪ B)) =
        RelSupport S (RelSupport R A ∪ RelSupport R B) := by
          rw [relSupport_union R A B]
    _ = RelSupport S (RelSupport R A) ∪ RelSupport S (RelSupport R B) :=
      relSupport_union S (RelSupport R A) (RelSupport R B)

/-- Same-type finite-horizon support propagation. The head relation acts first. -/
def PropagateList {σ : Type u} : List (σ → σ → Prop) → Set σ → Set σ
  | [], A => A
  | R :: Rs, A => PropagateList Rs (RelSupport R A)

/-- R016-L06 (arbitrary finite same-type horizon): every finite relational
future preserves branch deferral. This theorem is induction-ready and avoids a
bespoke heterogeneous list. -/
theorem propagateList_union {σ : Type u} (Rs : List (σ → σ → Prop)) (A B : Set σ) :
    PropagateList Rs (A ∪ B) = PropagateList Rs A ∪ PropagateList Rs B := by
  induction Rs generalizing A B with
  | nil => rfl
  | cons R Rs ih =>
      simp only [PropagateList]
      rw [relSupport_union R A B]
      exact ih (RelSupport R A) (RelSupport R B)

/-- Preservation of arbitrary unions, stated through `sUnion`. This convention
includes the empty family, so it forces preservation of the empty set. -/
def PreservesArbitraryUnions (T : Set α → Set β) : Prop :=
  ∀ 𝒜 : Set (Set α), T (⋃₀ 𝒜) = ⋃₀ (T '' 𝒜)

/-- R016-L07: arbitrary-union preservation includes the empty family and hence
forces `T ∅ = ∅`; no separate hidden hypothesis is required. -/
theorem preservesArbitraryUnions_empty {T : Set α → Set β}
    (hT : PreservesArbitraryUnions T) : T ∅ = ∅ := by
  have h := hT (∅ : Set (Set α))
  calc
    T ∅ = T (⋃₀ (∅ : Set (Set α))) := by simp
    _ = ⋃₀ (T '' (∅ : Set (Set α))) := h
    _ = ∅ := by simp

/-- The family of singleton subsets generated by `A` has union exactly `A`. -/
private theorem sUnion_singletons_subtype (A : Set α) :
    ⋃₀ (Set.range (fun x : A => ({x.1} : Set α))) = A := by
  ext y
  constructor
  · intro hy
    rcases Set.mem_sUnion.mp hy with ⟨U, hU, hyU⟩
    rcases hU with ⟨x, rfl⟩
    have hyx : y = x.1 := by
      change y = x.1 at hyU
      exact hyU
    rw [hyx]
    exact x.2
  · intro hy
    apply Set.mem_sUnion.mpr
    refine ⟨{y}, ?_, ?_⟩
    · exact ⟨⟨y, hy⟩, rfl⟩
    · rfl

/-- Image under `T` of the singleton family is the indexed union of singleton
images. -/
private theorem sUnion_image_singletons (T : Set α → Set β) (A : Set α) :
    ⋃₀ (T '' Set.range (fun x : A => ({x.1} : Set α))) =
      ⋃ x : A, T ({x.1} : Set α) := by
  ext y
  constructor
  · intro hy
    rcases Set.mem_sUnion.mp hy with ⟨U, hU, hyU⟩
    rcases hU with ⟨V, hV, rfl⟩
    rcases hV with ⟨x, rfl⟩
    exact Set.mem_iUnion.mpr ⟨x, hyU⟩
  · intro hy
    rcases Set.mem_iUnion.mp hy with ⟨x, hx⟩
    apply Set.mem_sUnion.mpr
    refine ⟨T ({x.1} : Set α), ?_, hx⟩
    exact ⟨({x.1} : Set α), ⟨x, rfl⟩, rfl⟩

/-- R016-L07: an arbitrary-union-preserving powerset transformer is completely
determined by its singleton images. -/
theorem transformer_eq_iUnion_singletons {T : Set α → Set β}
    (hT : PreservesArbitraryUnions T) (A : Set α) :
    T A = ⋃ x : A, T ({x.1} : Set α) := by
  calc
    T A = T (⋃₀ Set.range (fun x : A => ({x.1} : Set α))) := by
      rw [sUnion_singletons_subtype A]
    _ = ⋃₀ (T '' Set.range (fun x : A => ({x.1} : Set α))) :=
      hT (Set.range (fun x : A => ({x.1} : Set α)))
    _ = ⋃ x : A, T ({x.1} : Set α) := sUnion_image_singletons T A

/-- Relation generated by the singleton images of a powerset transformer. -/
def RelOfTransformer (T : Set α → Set β) : α → β → Prop :=
  fun x y => y ∈ T {x}

/-- R016-L07: every arbitrary-union-preserving powerset transformer is exactly
relational direct image under its singleton-generated relation. -/
theorem transformer_eq_relSupport {T : Set α → Set β}
    (hT : PreservesArbitraryUnions T) (A : Set α) :
    T A = RelSupport (RelOfTransformer T) A := by
  rw [transformer_eq_iUnion_singletons hT A]
  ext y
  constructor
  · intro hy
    rcases Set.mem_iUnion.mp hy with ⟨x, hx⟩
    exact ⟨x.1, x.2, hx⟩
  · rintro ⟨x, hx, hxy⟩
    exact Set.mem_iUnion.mpr ⟨⟨x, hx⟩, hxy⟩

/-- R016-L07 converse: every relational support transformer preserves arbitrary
unions, including the empty family. -/
theorem relSupport_preservesArbitraryUnions (R : α → β → Prop) :
    PreservesArbitraryUnions (RelSupport R) := by
  intro 𝒜
  ext y
  constructor
  · rintro ⟨x, hx, hxy⟩
    rcases Set.mem_sUnion.mp hx with ⟨A, hA, hxA⟩
    apply Set.mem_sUnion.mpr
    refine ⟨RelSupport R A, ?_, ⟨x, hxA, hxy⟩⟩
    exact ⟨A, hA, rfl⟩
  · intro hy
    rcases Set.mem_sUnion.mp hy with ⟨U, hU, hyU⟩
    rcases hU with ⟨A, hA, rfl⟩
    rcases hyU with ⟨x, hxA, hxy⟩
    exact ⟨x, Set.mem_sUnion.mpr ⟨A, hA, hxA⟩, hxy⟩

/-- R016-L07 exact characterization: preserving all unions is equivalent to
being a singleton-generated relational direct-image transformer. -/
theorem preservesArbitraryUnions_iff_exists_relSupport (T : Set α → Set β) :
    PreservesArbitraryUnions T ↔
      ∃ R : α → β → Prop, T = RelSupport R := by
  constructor
  · intro hT
    refine ⟨RelOfTransformer T, ?_⟩
    funext A
    exact transformer_eq_relSupport hT A
  · rintro ⟨R, rfl⟩
    exact relSupport_preservesArbitraryUnions R

/-- R016-L08: coalescing duplicate support is idempotent for every relational
future because result-support carries no multiplicity. -/
theorem coalescence_idempotence (R : α → β → Prop) (A : Set α) :
    RelSupport R (A ∪ A) = RelSupport R A := by
  calc
    RelSupport R (A ∪ A) = RelSupport R A ∪ RelSupport R A := relSupport_union R A A
    _ = RelSupport R A := by simp

/-- A finite Boolean future matrix is represented directly by a proposition at
each row/column entry. -/
abbrev BoolMatrix (n m : Nat) := Fin n → Fin m → Prop

/-- Boolean support-vector propagation: existential/AND semantics. -/
def MatrixPropagate {n m : Nat} (M : BoolMatrix n m) (A : Set (Fin n)) :
    Set (Fin m) :=
  {j | ∃ i ∈ A, M i j}

/-- Boolean matrix composition: existential/AND semantics, not path counting. -/
def MatrixComp {n m k : Nat} (M : BoolMatrix n m) (N : BoolMatrix m k) :
    BoolMatrix n k :=
  fun i k' => ∃ j, M i j ∧ N j k'

/-- R016-L09.1: Boolean matrix support propagation is extensionally the same
operation as relational result-support lifting. -/
theorem matrixPropagate_eq_relSupport {n m : Nat} (M : BoolMatrix n m)
    (A : Set (Fin n)) :
    MatrixPropagate M A = RelSupport M A := by
  rfl

/-- R016-L09.2: Boolean matrix composition is extensionally the same operation
as relation composition. -/
theorem matrixComp_eq_relComp {n m k : Nat} (M : BoolMatrix n m)
    (N : BoolMatrix m k) :
    MatrixComp M N = RelComp M N := by
  rfl

/-- R016-L09.3: Boolean support propagation distributes over support OR/union. -/
theorem matrixPropagate_union {n m : Nat} (M : BoolMatrix n m)
    (A B : Set (Fin n)) :
    MatrixPropagate M (A ∪ B) = MatrixPropagate M A ∪ MatrixPropagate M B :=
  relSupport_union M A B

/-- R016-L09.4: propagating through two Boolean future matrices is exactly
propagation through their Boolean composition. -/
theorem matrixPropagate_comp {n m k : Nat} (M : BoolMatrix n m)
    (N : BoolMatrix m k) (A : Set (Fin n)) :
    MatrixPropagate (MatrixComp M N) A =
      MatrixPropagate N (MatrixPropagate M A) :=
  relSupport_comp M N A

/-- Boolean relation/matrix composition is associative extensionally. -/
theorem matrixComp_assoc {n m k l : Nat} (M : BoolMatrix n m)
    (N : BoolMatrix m k) (P : BoolMatrix k l) :
    MatrixComp (MatrixComp M N) P = MatrixComp M (MatrixComp N P) := by
  funext i q
  apply propext
  constructor
  · rintro ⟨r, ⟨j, hij, hjr⟩, hrq⟩
    exact ⟨j, hij, ⟨r, hjr, hrq⟩⟩
  · rintro ⟨j, hij, ⟨r, hjr, hrq⟩⟩
    exact ⟨r, ⟨j, hij, hjr⟩, hrq⟩

/-- Positive finite sanity relation: two distinct states coalesce to the sole
state of `Fin 1`. -/
def sanityCoalesce : Fin 2 → Fin 1 → Prop := fun _ _ => True

/-- Positive finite sanity relation: the coalesced state later rebranches to
both states of `Fin 2`. -/
def sanityRebranch : Fin 1 → Fin 2 → Prop := fun _ _ => True

/-- R016-L10 positive sanity: the two current branches genuinely coalesce to a
single result-support state. -/
theorem sanity_coalesces :
    RelSupport sanityCoalesce (({0} : Set (Fin 2)) ∪ {1}) = ({0} : Set (Fin 1)) := by
  ext y
  constructor
  · intro _
    change y = 0
    exact Subsingleton.elim _ _
  · intro _
    exact ⟨0, Or.inl rfl, trivial⟩

/-- R016-L10 positive sanity: after coalescence, the next relation rebranches to
all final states. -/
theorem sanity_rebranches :
    RelSupport sanityRebranch ({0} : Set (Fin 1)) = Set.univ := by
  ext z
  constructor
  · intro _
    trivial
  · intro _
    exact ⟨0, rfl, trivial⟩

/-- R016-L10 positive sanity: eager branches and the unresolved/coalesced route
have exactly the same final reachable support. -/
theorem sanity_branch_deferral :
    RelSupport sanityRebranch
        (RelSupport sanityCoalesce (({0} : Set (Fin 2)) ∪ {1})) =
      RelSupport sanityRebranch (RelSupport sanityCoalesce ({0} : Set (Fin 2))) ∪
        RelSupport sanityRebranch (RelSupport sanityCoalesce ({1} : Set (Fin 2))) :=
  two_step_branch_deferral sanityCoalesce sanityRebranch {0} {1}

/-- A support-global rule that emits a result only when both source states are
present simultaneously. It is intentionally not union-preserving. -/
def BothPresentRule (A : Set (Fin 2)) : Set (Fin 1) :=
  fun _ => (0 : Fin 2) ∈ A ∧ (1 : Fin 2) ∈ A

/-- R016-L10 negative sanity: `BothPresentRule` fails even binary union preservation. -/
theorem bothPresentRule_not_union_preserving :
    BothPresentRule (({0} : Set (Fin 2)) ∪ {1}) ≠
      BothPresentRule ({0} : Set (Fin 2)) ∪
        BothPresentRule ({1} : Set (Fin 2)) := by
  intro hUnion
  have hLeft :
      (0 : Fin 1) ∈
        BothPresentRule (({0} : Set (Fin 2)) ∪ {1}) := by
    change
      ((0 : Fin 2) ∈ (({0} : Set (Fin 2)) ∪ {1})) ∧
      ((1 : Fin 2) ∈ (({0} : Set (Fin 2)) ∪ {1}))
    exact ⟨Or.inl rfl, Or.inr rfl⟩
  have hRight :
      (0 : Fin 1) ∈
        BothPresentRule ({0} : Set (Fin 2)) ∪
          BothPresentRule ({1} : Set (Fin 2)) := by
    rw [← hUnion]
    exact hLeft
  rcases hRight with h0 | h1
  · have h10 := h0.2
    change (1 : Fin 2) = 0 at h10
    exact (by decide : ¬ ((1 : Fin 2) = 0)) h10
  · have h01 := h1.1
    change (0 : Fin 2) = 1 at h01
    exact (by decide : ¬ ((0 : Fin 2) = 1)) h01

/-- R016-L10 negative sanity: the support-global rule cannot be represented by
any relational direct-image lifting. -/
theorem bothPresentRule_not_relSupport :
    ¬ ∃ R : Fin 2 → Fin 1 → Prop, BothPresentRule = RelSupport R := by
  rintro ⟨R, hR⟩
  apply bothPresentRule_not_union_preserving
  rw [hR]
  exact relSupport_union R
    ({0} : Set (Fin 2))
    ({1} : Set (Fin 2))

#print axioms relSupport_empty
#print axioms relSupport_union
#print axioms relSupport_iUnion
#print axioms relSupport_comp
#print axioms two_branch_deferral
#print axioms two_step_branch_deferral
#print axioms propagateList_union
#print axioms preservesArbitraryUnions_empty
#print axioms transformer_eq_iUnion_singletons
#print axioms transformer_eq_relSupport
#print axioms relSupport_preservesArbitraryUnions
#print axioms preservesArbitraryUnions_iff_exists_relSupport
#print axioms coalescence_idempotence
#print axioms matrixPropagate_eq_relSupport
#print axioms matrixComp_eq_relComp
#print axioms matrixPropagate_union
#print axioms matrixPropagate_comp
#print axioms matrixComp_assoc
#print axioms sanity_coalesces
#print axioms sanity_rebranches
#print axioms sanity_branch_deferral
#print axioms bothPresentRule_not_union_preserving
#print axioms bothPresentRule_not_relSupport

end EnterpriseMath.BranchDeferral