import EnterpriseMath.Precision.DirichletCoefficientDefect
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Series
import Mathlib.Topology.Algebra.InfiniteSum.NatInt

namespace EnterpriseMath.Precision

open scoped BigOperators Nat

/-- Positive weighted series kernel generated by the finite coefficient-defect bound. -/
noncomputable def dirichletDefectWeight (R : ℝ) (j : ℕ) : ℝ :=
  (j : ℝ) * ((j : ℝ) + 1) * (2 * (j : ℝ) + 1) * R ^ (2 * j) /
    (((2 * j + 1) ! : ℕ) : ℝ)

/-- Closed value of the weighted coefficient-defect series. -/
noncomputable def dirichletDefectSeriesValue (R : ℝ) : ℝ :=
  (R ^ 2 / 4) * Real.cosh R + (3 * R / 4) * Real.sinh R

/-- The zero-th weighted defect term vanishes. -/
theorem dirichletDefectWeight_zero (R : ℝ) :
    dirichletDefectWeight R 0 = 0 := by
  simp [dirichletDefectWeight]

/-- Every weighted defect term is nonnegative. -/
theorem dirichletDefectWeight_nonneg (R : ℝ) (j : ℕ) :
    0 ≤ dirichletDefectWeight R j := by
  unfold dirichletDefectWeight
  positivity

/--
After deleting the zero-th term, the weighted kernel splits into one shifted `cosh`
coefficient and one shifted `sinh` coefficient.
-/
theorem dirichletDefectWeight_succ_decompose (R : ℝ) (n : ℕ) :
    dirichletDefectWeight R (n + 1) =
      (R ^ 2 / 4) *
          (R ^ (2 * n) / (((2 * n) ! : ℕ) : ℝ)) +
        (3 * R / 4) *
          (R ^ (2 * n + 1) / (((2 * n + 1) ! : ℕ) : ℝ)) := by
  have hfac1 :
      (2 * n + 1)! = (2 * n + 1) * (2 * n)! := by
    grind [Nat.factorial_succ]
  have hfac3 :
      (2 * (n + 1) + 1)! =
        (2 * n + 3) * (2 * n + 2) * (2 * n + 1)! := by
    grind [Nat.factorial_succ]
  unfold dirichletDefectWeight
  rw [hfac3, hfac1]
  rw [show 2 * (n + 1) = 2 * n + 2 by omega, pow_add]
  push_cast
  have hf : ((((2 * n)! : ℕ) : ℝ)) ≠ 0 := by positivity
  have h1 : (2 * (n : ℝ) + 1) ≠ 0 := by positivity
  have h2 : (2 * (n : ℝ) + 2) ≠ 0 := by positivity
  have h3 : (2 * (n : ℝ) + 3) ≠ 0 := by positivity
  field_simp [hf, h1, h2, h3]
  ring

/-- Exact `HasSum` identity behind the analytic main term in WSR-T02. -/
theorem hasSum_dirichletDefectWeight (R : ℝ) :
    HasSum (fun j : ℕ => dirichletDefectWeight R j)
      (dirichletDefectSeriesValue R) := by
  have hc := (Real.hasSum_cosh R).mul_left (R ^ 2 / 4)
  have hs := (Real.hasSum_sinh R).mul_left (3 * R / 4)
  have hshift :
      HasSum (fun n : ℕ => dirichletDefectWeight R (n + 1))
        (dirichletDefectSeriesValue R) := by
    unfold dirichletDefectSeriesValue
    refine HasSum.congr_fun (hc.add hs) (fun n => ?_)
    exact (dirichletDefectWeight_succ_decompose R n).symm
  have hfull := HasSum.zero_add hshift
  simpa [dirichletDefectWeight_zero] using hfull

/-- The closed series value in the exact form used by the theorem packet. -/
theorem dirichletDefectSeriesValue_eq (R : ℝ) :
    dirichletDefectSeriesValue R =
      (R ^ 2 * Real.cosh R + 3 * R * Real.sinh R) / 4 := by
  unfold dirichletDefectSeriesValue
  ring

/-- Every finite partial weighted sum lies below the exact `cosh/sinh` total. -/
theorem sum_dirichletDefectWeight_le_value (R : ℝ) (M : ℕ) :
    (∑ j ∈ Finset.range M, dirichletDefectWeight R j) ≤
      dirichletDefectSeriesValue R := by
  have hsum := hasSum_dirichletDefectWeight R
  have hle := hsum.summable.sum_le_tsum (Finset.range M)
    (fun j _hj => dirichletDefectWeight_nonneg R j)
  calc
    (∑ j ∈ Finset.range M, dirichletDefectWeight R j) ≤
        ∑' j : ℕ, dirichletDefectWeight R j := hle
    _ = dirichletDefectSeriesValue R := hsum.tsum_eq

/-- Partial weighted sums are bounded by the theorem-packet closed form. -/
theorem sum_dirichletDefectWeight_le_closed (R : ℝ) (M : ℕ) :
    (∑ j ∈ Finset.range M, dirichletDefectWeight R j) ≤
      (R ^ 2 * Real.cosh R + 3 * R * Real.sinh R) / 4 := by
  rw [← dirichletDefectSeriesValue_eq]
  exact sum_dirichletDefectWeight_le_value R M

end EnterpriseMath.Precision
