import EnterpriseMath.Precision.EulerTwistedEndpointCohomology

namespace EnterpriseMath.Precision.EulerTetrahedralTransportDichotomy

open EnterpriseMath.Precision.EulerC12RootTorsorFlatness
open EnterpriseMath.Precision.EulerHolonomyResidualDuality
open EnterpriseMath.Precision.EulerTwistedEndpointCohomology

abbrev Vertex4 := Fin 4
abbrev Perm4 := Equiv.Perm Vertex4

def swap01 : Perm4 := Equiv.swap 0 1
def swap02 : Perm4 := Equiv.swap 0 2
def swap03 : Perm4 := Equiv.swap 0 3
def swap12 : Perm4 := Equiv.swap 1 2
def swap13 : Perm4 := Equiv.swap 1 3
def swap23 : Perm4 := Equiv.swap 2 3

/-- Reflection-type transport on the base edge `{0,1}`. -/
def reflective01 : Perm4 := swap01

/-- Proper tetrahedral half-turn on the base edge `{0,1}`. -/
def proper01 : Perm4 := swap01 * swap23

def proper12 : Perm4 := swap12 * swap03
def proper20 : Perm4 := swap02 * swap13

/-- Conditions forced on an equivariant base-edge transport: exchange the two
    endpoints, be an involution, and commute with the setwise stabilizer
    generated by the endpoint and complementary transpositions. -/
def IsBaseTransport (σ : Perm4) : Prop :=
  σ 0 = 1 ∧
  σ 1 = 0 ∧
  σ * σ = 1 ∧
  σ * swap01 = swap01 * σ ∧
  σ * swap23 = swap23 * σ

instance instDecidablePredIsBaseTransport : DecidablePred IsBaseTransport := fun σ => by
  unfold IsBaseTransport
  infer_instance

/-- There are exactly two fully tetrahedrally symmetric involutive transports
    on one overlap edge: the endpoint reflection and the complementary double
    transposition. -/
theorem base_transport_classification : ∀ σ : Perm4,
    IsBaseTransport σ ↔ σ = reflective01 ∨ σ = proper01 := by
  native_decide

theorem reflective_is_involution : reflective01 * reflective01 = 1 := by
  native_decide

theorem proper_is_involution : proper01 * proper01 = 1 := by
  native_decide

/-- The proper transports around one face are the three nontrivial Klein-four
    elements and close exactly. -/
theorem proper_face_transport_is_identity :
    proper20 * proper12 * proper01 = 1 := by
  native_decide

/-- The three endpoint reflections around one face do not close to the
    identity; their composite is orientation reversing. -/
theorem reflective_face_transport_is_nontrivial :
    swap02 * swap12 * swap01 ≠ 1 := by
  native_decide

theorem reflective_transport_is_odd :
    Equiv.Perm.sign reflective01 = -1 := by
  native_decide

theorem proper_transport_is_even :
    Equiv.Perm.sign proper01 = 1 := by
  native_decide

theorem reflective_face_transport_is_odd :
    Equiv.Perm.sign (swap02 * swap12 * swap01) = -1 := by
  native_decide

/-- The two transport families select exactly the two `S4`-fixed residual
    phases: flat zero and uniform torsion. -/
def properTransitionBits : EdgeBits :=
  ⟨false, false, false, false, false, false⟩

def reflectiveTransitionBits : EdgeBits :=
  ⟨true, true, true, true, true, true⟩

theorem proper_phase_is_flat : Flat properTransitionBits := by
  native_decide

theorem reflective_phase_is_uniformly_twisted :
    faceABC reflectiveTransitionBits = true ∧
    faceABD reflectiveTransitionBits = true ∧
    faceACD reflectiveTransitionBits = true ∧
    faceBCD reflectiveTransitionBits = true := by
  native_decide

theorem proper_phase_maps_to_zero_residual :
    edgeToResidual properTransitionBits = zeroResidual := by
  native_decide

theorem reflective_phase_maps_to_torsion_residual :
    edgeToResidual reflectiveTransitionBits = torsionResidual := by
  native_decide

end EnterpriseMath.Precision.EulerTetrahedralTransportDichotomy
