"""Local browser acceptance and Python/JS cross-check. No external URLs."""
import json, sys, math, hashlib
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from nollm_visual_toolkit import phase32_lab as m
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'verification'/'phase32_browser';OUT.mkdir(parents=True,exist_ok=True)
m.render(ROOT/'phase32_outputs'/'field.html',dict(mode='hash'))
checks=[];errors=[];requests=[]
def ck(name,cond):
    assert cond,name
    checks.append(name);print('PASS',name,flush=True)
with sync_playwright() as pw:
    b=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
    page=b.new_page(viewport={'width':1600,'height':1050},accept_downloads=True)
    page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:requests.append(r.url))
    page.set_content((ROOT/'phase32_outputs/field.html').read_text());page.wait_for_function('window.NollmPhase32 && NollmPhase32.status().drawn===65536')
    ck('full_65536_render',page.evaluate('NollmPhase32.status().drawn')==65536)
    for mode in ['golden','hash','spiral']:
        c=dict(m.DEFAULT,mode=mode)
        py=m.build(c)
        page.evaluate('c=>NollmPhase32.set(c)',c)
        js=page.evaluate('NollmPhase32.phase()')
        ck('exact_all_phases_'+mode,js==py['phase'])
        met=page.evaluate('NollmPhase32.status().metrics');ref=m.metrics(py)
        ck('exact_all_bins_'+mode,met['equal_area_counts']==ref['equal_area_counts'])
        ck('quantization_occupancy_'+mode,met['occupied_cells']==ref['occupied_cells'])
        ck('angular_cv_'+mode,abs(met['angular_cv']-ref['angular_cv'])<1e-13)
        ck('multiplication_'+mode,page.evaluate('c=>NollmPhase32.multiply(NollmPhase32.build(c),5,7)',c)['phase_defect_uint32']==m.multiplication(py,5,7)['phase_defect_uint32'])
    page.select_option('#mode','hash');page.wait_for_function('NollmPhase32.status().config.mode==="hash"')
    original=page.evaluate('NollmPhase32.phase()')
    page.fill('#phasePrime','5');page.fill('#phaseAngle','90');page.click('#phaseApply')
    changed=page.evaluate('NollmPhase32.phase()');c=page.evaluate('NollmPhase32.status().config');py=m.build(c)
    ck('custom_phase_python_js',changed==py['phase'])
    ck('nonmultiples_unchanged',all(changed[n]==original[n] for n in range(1,65536) if n%5))
    page.click('#phaseReset')
    page.fill('#a','65535');page.fill('#b','2');page.click('#multiply');ck('out_of_range_visible','不在当前范围' in page.inner_text('#productInfo'))
    page.fill('#a','5');page.fill('#b','7');page.click('#trace')
    ck('multiplication_trajectory',page.evaluate('NollmPhase32.status().path')==[5,35,245,1715,12005])
    page.fill('#lookup','0');page.click('#find');ck('zero_no_fabricated_phase',json.loads(page.inner_text('#detail'))['phase_numerator'] is None)
    page.fill('#lookup','35');page.click('#find');ck('lookup_35',page.evaluate('NollmPhase32.status().selected')==35)
    oldmetrics=page.evaluate('NollmPhase32.status().metrics');oldphase=page.evaluate('NollmPhase32.phase()');page.click('#turn')
    ck('camera_not_data',oldphase==page.evaluate('NollmPhase32.phase()') and oldmetrics==page.evaluate('NollmPhase32.status().metrics'))
    page.select_option('#view','layers');page.wait_for_function('NollmPhase32.status().config.view==="layers"');page.screenshot(path=str(OUT/'layers_preview.png'))
    ck('layers_explicit_boundary','不是 Nollm 物理层' in page.inner_text('#notice'))
    xy=page.evaluate('NollmPhase32.project(35)');box=page.locator('#scene').bounding_box();page.mouse.click(box['x']+xy[0],box['y']+xy[1]);ck('canvas_pointer_selection',page.evaluate('NollmPhase32.status().selected') is not None)
    page.select_option('#view','hex');page.click('#fiber');detail=json.loads(page.inner_text('#detail'));ck('fiber_retains_selection',detail['n'] in detail['same_hex_cell_ids'])
    page.select_option('#view','plane');page.screenshot(path=str(OUT/'plane_preview.png'))
    saved=page.evaluate('NollmPhase32.packet()');bad=json.loads(json.dumps(saved));bad['config']['count']=1000000
    ck('invalid_restore_rejected',page.evaluate('x=>{try{NollmPhase32.restore(x);return false}catch(e){return true}}',bad))
    ck('invalid_restore_keeps_current',page.evaluate('NollmPhase32.packet()')==saved)
    page.select_option('#mode','golden');page.evaluate('x=>NollmPhase32.restore(x)',saved);ck('restore_exact_config',page.evaluate('NollmPhase32.packet()')==saved)
    page.locator('summary').click()
    with page.expect_download() as d:page.click('#saveConfig')
    d.value.save_as(OUT/'downloaded_config.json');ck('downloaded_config_matches',json.loads((OUT/'downloaded_config.json').read_text())==saved)
    with page.expect_download() as d:page.click('#saveData')
    d.value.save_as(OUT/'downloaded_data.json');got=json.loads((OUT/'downloaded_data.json').read_text());ck('export_all_ids',len(got['records'])==65536 and len({r['id'] for r in got['records']})==65536)
    ck('export_retains_integer_carrier',all(r['phase_numerator']==oldphase[r['n']] for r in got['records'][1:]))
    with page.expect_download() as d:page.click('#savePage')
    d.value.save_as(OUT/'downloaded_page.html');snapshot=(OUT/'downloaded_page.html').read_text()
    ck('export_selfcontained_no_placeholder','__CONFIG__' not in snapshot)
    with page.expect_download() as d:page.click('#savePng')
    d.value.save_as(OUT/'canvas.png');ck('png_valid',(OUT/'canvas.png').read_bytes().startswith(b'\x89PNG'))
    page.set_content(snapshot);page.wait_for_function('NollmPhase32.status().drawn===65536');ck('saved_page_reopens_with_config',page.evaluate('NollmPhase32.packet()')==saved)
    page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(150)
    ck('mobile_no_horizontal_overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
    ck('mobile_canvas_height',page.locator('#scene').bounding_box()['height']>=420)
    page.screenshot(path=str(OUT/'mobile_preview.png'),full_page=True)
    ck('no_browser_errors',not errors);ck('no_external_requests',not requests)
    b.close()
result=dict(schema='NOLLM_MULTIPLICATIVE_BROWSER_ACCEPTANCE_V1',checks_passed=len(checks),checks=checks,page_errors=errors,network_requests=requests,browser='Chromium, Playwright set_content; desktop and 390px viewport',limits=['Not native iOS/Safari or real-touch certification','No production kernel integration','Floating screen placement may differ slightly across engines'])
(OUT/'browser_acceptance.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(result,ensure_ascii=False,indent=2))
