"""Real Chromium acceptance for the new lab. No external requests allowed."""
from __future__ import annotations
import json
import math
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from nollm_visual_toolkit import core
from nollm_visual_toolkit import multiplication_lab as lab
from playwright.sync_api import sync_playwright

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'verification'; OUT.mkdir(exist_ok=True)
SITE=ROOT/'site'; lab.build_lab_site(SITE)
checks=[]; errors=[]; requests=[]
def check(name, condition):
    assert condition,name
    checks.append(name); print('PASS',name,flush=True)

with sync_playwright() as pw:
    browser=pw.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox'])
    def load(markup):
        p=browser.new_page(viewport={'width':1560,'height':1100},accept_downloads=True)
        p.set_default_timeout(10000)
        p.on('pageerror',lambda e:errors.append(str(e)))
        p.on('request',lambda r:requests.append(r.url))
        p.set_content(markup,wait_until='load')
        return p
    page=load((SITE/'multiplication.html').read_text())
    page.wait_for_function('NumberFieldLab.status().drawn===65536')
    status=lambda: page.evaluate('NumberFieldLab.status()')
    golden=status()
    check('all_65536_drawn_no_sampling',golden['drawn']==65536)
    check('source_baseline_sha',golden['data_sha256']=='94df92927ff6952c86344ee2f38b428d273c7e749cb41343e25d5c2c5ae51160')
    spf=lab.smallest_factors(65536);phi=lab.phases(spf,lab.prime_phases(spf))
    front=page.evaluate('Array.from({length:65536},(_,n)=>NumberFieldLab.phase(n))')
    check('all_65536_integer_phases_equal_python',front==phi)
    d=lab.diagnostics(phi)
    check('all_64_sector_counts_equal_python',d['angular_counts']==golden['angular_counts'])
    check('cell_occupancy_equals_python',d['occupied_cells']==golden['occupied_cells'])
    check('cv_equals_python',abs(d['angular_cv']-golden['angular_cv'])<1e-14)
    check('zero_phase_undefined',page.evaluate('NumberFieldLab.inspect(0).phase') is None)
    check('zero_factorization_undefined',page.evaluate('NumberFieldLab.inspect(0).factors') is None)
    for k in (2,3,4,5,7,11,13,31):
        page.evaluate('(k)=>NumberFieldLab.configure({k})',k)
        check('finite_phase_multiplication_'+str(k),status()['exact_failures']==0 and status()['multiplication_pairs']==65535//k)
    page.evaluate('NumberFieldLab.configure({k:4})')
    before=page.evaluate('NumberFieldLab.rawData()')
    check('full_V2_source_equal_baseline',before==core.demo_hex())
    page.locator('#turn').click();page.locator('#zin').click();page.locator('#oblique').click()
    check('camera_does_not_change_statistics',status()['angular_counts']==golden['angular_counts'] and status()['occupied_cells']==golden['occupied_cells'])
    page.locator('#prime').fill('5');page.locator('#tick').fill('8192');page.locator('#applyPhase').click()
    altered=lab.phases(spf,lab.prime_phases(spf,overrides={5:8192}))
    check('all_65536_override_phases_equal_python',page.evaluate('Array.from({length:65536},(_,n)=>NumberFieldLab.phase(n))')==altered)
    check('override_changes_geometry',status()['angular_counts']!=golden['angular_counts'])
    check('override_preserves_multiplication',status()['exact_failures']==0)
    page.locator('#resetPhase').click();page.locator('#fit').click()
    check('reset_restores_full_histogram',status()['angular_counts']==golden['angular_counts'])
    page.locator('#layout').select_option('legacy')
    check('original_cells_unique',status()['occupied_cells']==65536)
    check('original_times_four_exact',status()['exact_failures']==0)
    page.evaluate('NumberFieldLab.configure({k:2})')
    check('original_times_two_reports_counterexample',status()['exact_failures']>0 and status()['first_witness']['n']==2)
    page.evaluate('NumberFieldLab.preset("zero")')
    check('zero_phase_negative_control',abs(status()['angular_cv']-math.sqrt(63))<1e-14)
    page.evaluate('NumberFieldLab.preset("golden")')
    page.screenshot(path=str(SITE/'preview.png'))
    page.evaluate('NumberFieldLab.preset("layers")')
    page.wait_for_timeout(60)
    check('stack_is_explicit_observer',status()['state']['stack'])
    page.screenshot(path=str(SITE/'layers.png'))
    page.evaluate('NumberFieldLab.configure({limit:1023,quantized:true,selected:3,k:5,overrides:{5:12345}})')
    saved=page.evaluate('NumberFieldLab.snapshot()')
    exported=page.evaluate('NumberFieldLab.exportHTML()')
    (SITE/'saved-session-demo.html').write_text(exported,encoding='utf-8')
    page.close();page=load((SITE/'saved-session-demo.html').read_text())
    page.wait_for_function('NumberFieldLab.status().drawn===1024')
    check('saved_webpage_restores_exact_configuration',page.evaluate('NumberFieldLab.snapshot()')==saved)
    check('saved_webpage_preserves_source',page.evaluate('NumberFieldLab.rawData()')==before)
    bad=json.loads(json.dumps(saved));bad['data_sha256']='wrong'
    check('wrong_source_configuration_rejected',page.evaluate('(s)=>{try{NumberFieldLab.restore(s);return false}catch(e){return true}}',bad))
    check('rejection_does_not_mutate_state',page.evaluate('NumberFieldLab.snapshot()')==saved)
    check('composite_phase_rejected',page.evaluate('()=>{try{NumberFieldLab.configure({overrides:{4:12}});return false}catch(e){return true}}'))
    check('nonfinite_scale_rejected',page.evaluate('()=>{try{NumberFieldLab.configure({scale:NaN});return false}catch(e){return true}}'))
    check('zero_multiplier_rejected',page.evaluate('()=>{try{NumberFieldLab.configure({k:0});return false}catch(e){return true}}'))
    check('empty_prefix_rejected',page.evaluate('()=>{try{NumberFieldLab.configure({limit:0});return false}catch(e){return true}}'))
    page.evaluate('NumberFieldLab.configure({stack:false,quantized:false,pitch:0})');page.wait_for_timeout(50)
    p=page.evaluate('NumberFieldLab.point(3)');box=page.locator('#fieldCanvas').bounding_box()
    page.mouse.click(box['x']+p[0],box['y']+p[1]);check('actual_canvas_point_selects_valid_id',0<=status()['state']['selected']<=1023)
    page.locator('summary').click()
    with page.expect_download(timeout=10000) as dl: page.locator('#png').click()
    dl.value.save_as(OUT/'download.png');check('png_download_real_signature',(OUT/'download.png').read_bytes().startswith(b'\x89PNG'))
    with page.expect_download(timeout=10000) as dl: page.locator('#source').click()
    dl.value.save_as(OUT/'source-v2.json');check('source_export_accepted_by_toolkit',core.read_data(OUT/'source-v2.json')==before)
    with page.expect_download(timeout=10000) as dl: page.locator('#report').click()
    dl.value.save_as(OUT/'observation.json');obs=json.loads((OUT/'observation.json').read_text())
    check('report_retains_complete_prime_phase_table',len(obs['prime_phase_table'])==6542)
    check('report_marks_float_quantization',obs['quantization_is_floating'])
    page.close();page=load((SITE/'index.html').read_text())
    frame=page.frame(name='lab');frame.wait_for_function('NumberFieldLab.status().drawn===65536')
    check('real_gallery_iframe_loads',frame.evaluate('NumberFieldLab.status().drawn')==65536)
    page.get_by_role('link',name='原六角编码',exact=True).click();frame.wait_for_function('NumberFieldLab.status().state.layout==="legacy"')
    check('gallery_switches_to_legacy',frame.evaluate('NumberFieldLab.status().occupied_cells')==65536)
    page.get_by_role('link',name='全零相位反例',exact=True).click();frame.wait_for_function('NumberFieldLab.status().state.mode==="zero"')
    check('gallery_switches_negative_control',abs(frame.evaluate('NumberFieldLab.status().angular_cv')-math.sqrt(63))<1e-14)
    page.get_by_role('link',name='立体分层',exact=True).click();frame.wait_for_function('NumberFieldLab.status().state.stack')
    check('gallery_switches_stack',frame.evaluate('NumberFieldLab.status().drawn')==65536)
    page.screenshot(path=str(SITE/'gallery.png'))
    page.close();page=load((SITE/'multiplication.html').read_text());page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(100)
    check('mobile_no_horizontal_overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
    check('mobile_canvas_height',page.locator('#fieldCanvas').bounding_box()['height']>=420)
    page.screenshot(path=str(SITE/'mobile.png'),full_page=True)
    check('no_page_errors',not errors)
    check('no_external_requests',not any(x.startswith(('http:','https:')) for x in requests))
    browser.close()
result={'schema':'NOLLM_MULTIPLICATION_UI_ACCEPTANCE_V1','checks_passed':len(checks),'checks':checks,'errors':errors,'external_requests':[r for r in requests if r.startswith(('http:','https:'))], 'navigation':'host-supplied HTML via set_content; actual srcdoc iframe rendering and preset switching','limitations':['Native file navigation blocked by test host; not tested, not bypassed','Not a native iOS Safari test','No production Nollm integration or full repository CI','Float display quantization is not a formal geometric certificate'],'golden_baseline':golden}
(OUT/'browser.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('TOTAL',len(checks))
