import EnterpriseMath.PrecisionPi.N58RotationGeometry

namespace EnterpriseMath.PrecisionPi.N58Constants

/-- `9801` and `396` are the square and fourfold longitudinal coordinates. -/
theorem scale_constants :
    (9801 : ℤ) = 99 ^ 2 ∧ (396 : ℤ) = 4 * 99 := by
  norm_num

/-- The derivative coefficient factors through the two near-axis projections and scale. -/
theorem derivative_coefficient :
    (26390 : ℤ) = 29 * 70 * 13 := by
  norm_num

/-- Equivalent Pell-shell factorization of the derivative coefficient. -/
theorem derivative_coefficient_alt :
    (26390 : ℤ) = 58 * 455 ∧ (2 : ℤ) * 455 = 70 * 13 := by
  norm_num

/-- Division-free geometric identity generating Ramanujan's `1103`. -/
theorem ramanujan_1103_geometric_identity :
    (4 : ℤ) * 1103 =
      29 * 70 * 13 - 2 * 99 * (99 + 13 - 1) := by
  norm_num

/-- The same identity expressed using the derivative coefficient. -/
theorem ramanujan_1103_from_derivative :
    (4 : ℤ) * 1103 = 26390 - 2 * 99 * 111 := by
  norm_num

/-- The correction coordinate is the projected scale-plus-longitudinal quantity. -/
theorem correction_coordinate :
    (111 : ℤ) = 99 + 13 - 1 := by
  norm_num

/-- All four classical large constants are generated by the same integer carrier data. -/
theorem all_constants_certificate :
    (9801 : ℤ) = 99 ^ 2 ∧
    (396 : ℤ) = 4 * 99 ∧
    (26390 : ℤ) = 29 * 70 * 13 ∧
    (4 : ℤ) * 1103 =
      29 * 70 * 13 - 2 * 99 * (99 + 13 - 1) := by
  norm_num

end EnterpriseMath.PrecisionPi.N58Constants
