import EnterpriseMath.PrecisionPi.PairedPell

namespace EnterpriseMath.PrecisionPi.N58RotationGeometry

/-- Integral two-coordinate carrier vector. -/
structure Vec2 where
  x : ℤ
  y : ℤ
  deriving DecidableEq, Repr

/-- Coordinatewise vector addition. -/
def add (v w : Vec2) : Vec2 := ⟨v.x + w.x, v.y + w.y⟩

/-- Squared Euclidean carrier length. -/
def normSq (v : Vec2) : ℤ := v.x ^ 2 + v.y ^ 2

/-- Oriented unit-area determinant. -/
def det (v w : Vec2) : ℤ := v.x * w.y - v.y * w.x

/-- The integral similitude with multiplier `12+5i` and squared scale `13²`. -/
def sim13 (v : Vec2) : Vec2 :=
  ⟨12 * v.x + 5 * v.y, -5 * v.x + 12 * v.y⟩

/-- The similitude scales squared lengths by `169=13²`. -/
theorem normSq_sim13 (v : Vec2) :
    normSq (sim13 v) = 169 * normSq v := by
  simp [normSq, sim13]
  ring

/-- The two primitive carrier directions used in the N=58 configuration. -/
def a : Vec2 := ⟨5, 2⟩

def b : Vec2 := ⟨7, 3⟩

def u : Vec2 := add a b

@[simp] theorem a_normSq : normSq a = 29 := by
  norm_num [normSq, a]

@[simp] theorem b_normSq : normSq b = 58 := by
  norm_num [normSq, b]

@[simp] theorem u_coordinates : u = ⟨12, 5⟩ := by
  rfl

@[simp] theorem u_normSq : normSq u = 169 := by
  norm_num [normSq, u, add, a, b]

/-- The two primitive directions span one oriented lattice-area quantum. -/
theorem det_a_b : det a b = 1 := by
  norm_num [det, a, b]

/-- The length-13 similitude sends the `sqrt(29)` direction almost to the axis. -/
theorem sim13_a : sim13 a = ⟨70, -1⟩ := by
  norm_num [sim13, a]

/-- The same similitude sends the `sqrt(58)` direction to the Pell residual vector `(99,1)`. -/
theorem sim13_b : sim13 b = ⟨99, 1⟩ := by
  norm_num [sim13, b]

/-- The first near-axis identity. -/
theorem near_axis_29 : (70 : ℤ) ^ 2 + 1 = 29 * 13 ^ 2 := by
  norm_num

/-- The N=58 negative-Pell identity generated by the same similitude. -/
theorem near_axis_58 : (99 : ℤ) ^ 2 + 1 = 58 * 13 ^ 2 := by
  norm_num

/-- Equivalent standard negative-Pell form. -/
theorem negative_pell_58 : (99 : ℤ) ^ 2 - 58 * 13 ^ 2 = -1 := by
  norm_num

/-- The companion positive-Pell shell at the same longitudinal coordinate. -/
theorem positive_pell_2 : (99 : ℤ) ^ 2 - 2 * 70 ^ 2 = 1 := by
  norm_num

/-- The paired shells yield the class-invariant norm-one unit
`9801 + 1820 sqrt(29)`. -/
theorem class_unit_58 :
    (9801 : ℤ) ^ 2 - 29 * 1820 ^ 2 = 1 := by
  norm_num

/-- The class-unit identity is exactly the product of the two Pell shells. -/
theorem class_unit_58_from_paired :
    ((99 : ℤ) ^ 2) ^ 2 - 29 * (2 * (70 * 13)) ^ 2 = 1 := by
  calc
    ((99 : ℤ) ^ 2) ^ 2 - 29 * (2 * (70 * 13)) ^ 2 =
        ((99 : ℤ) ^ 2) ^ 2 - (2 * 58) * (70 * 13) ^ 2 := by ring
    _ = 1 := PairedPell.n58_square_trace_norm

/-- Rational coordinates appearing in the classical 1103 formula. -/
theorem n58_constant_coordinates :
    (9801 : ℤ) = 99 ^ 2 ∧
    (396 : ℤ) = 4 * 99 ∧
    (26390 : ℤ) = 29 * 70 * 13 := by
  norm_num

end EnterpriseMath.PrecisionPi.N58RotationGeometry
