import Mathlib

namespace EnterpriseMath.PrecisionPi.SquareTraceDoublePell

/-- Positive Pell shell at longitudinal coordinate `P`. -/
def PellPlus (P d a : ℤ) : Prop := P ^ 2 - d * a ^ 2 = 1

/-- Negative Pell shell at longitudinal coordinate `P`. -/
def PellMinus (P d b : ℤ) : Prop := P ^ 2 - d * b ^ 2 = -1

/-- A norm-one quadratic unit whose rational half-trace is the square `P²`. -/
def SquareTraceUnit (P D Y : ℤ) : Prop :=
  (P ^ 2) ^ 2 - D * Y ^ 2 = 1

/-- Paired positive and negative Pell shells at the same longitudinal
coordinate fuse to a square-half-trace norm-one unit whenever the product of
the two shell discriminants is `D r²`. -/
theorem pairedPell_to_squareTraceUnit
    {P dPlus dMinus a b D r : ℤ}
    (hPlus : PellPlus P dPlus a)
    (hMinus : PellMinus P dMinus b)
    (hDisc : dPlus * dMinus = D * r ^ 2) :
    SquareTraceUnit P D (r * a * b) := by
  have hp : P ^ 2 - 1 = dPlus * a ^ 2 := by
    linarith [hPlus]
  have hm : P ^ 2 + 1 = dMinus * b ^ 2 := by
    linarith [hMinus]
  unfold SquareTraceUnit
  calc
    (P ^ 2) ^ 2 - D * (r * a * b) ^ 2 =
        (P ^ 2 - 1) * (P ^ 2 + 1) + 1 -
          (D * r ^ 2) * (a * b) ^ 2 := by ring
    _ = (dPlus * a ^ 2) * (dMinus * b ^ 2) + 1 -
          (dPlus * dMinus) * (a * b) ^ 2 := by rw [hp, hm, hDisc]
    _ = 1 := by ring

/-- The fused shell factor is the norm of the two signed shell components. -/
theorem fusedShell_norm (u : ℚ) :
    (1 - u) * (1 + u) = 1 - u ^ 2 := by
  ring

/-- At a nonzero longitudinal coordinate, the fused shell variable is
exactly `1-P⁻⁴`. -/
theorem fusedShell_at_inverseSquare (P : ℤ) (hP : P ≠ 0) :
    (1 - (1 : ℚ) / (P : ℚ) ^ 2) *
        (1 + (1 : ℚ) / (P : ℚ) ^ 2) =
      1 - (1 : ℚ) / (P : ℚ) ^ 4 := by
  have hPq : (P : ℚ) ≠ 0 := by exact_mod_cast hP
  field_simp
  ring

/-- The `P=3` positive shell. -/
theorem pellPlus_three : PellPlus 3 2 2 := by
  norm_num [PellPlus]

/-- The `P=3` negative shell. -/
theorem pellMinus_three : PellMinus 3 10 1 := by
  norm_num [PellMinus]

/-- The `P=3` paired shell yields the unit `9+4√5`. -/
theorem squareTraceUnit_three : SquareTraceUnit 3 5 4 := by
  exact pairedPell_to_squareTraceUnit pellPlus_three pellMinus_three (by norm_num)

/-- The `P=7` positive shell. -/
theorem pellPlus_seven : PellPlus 7 3 4 := by
  norm_num [PellPlus]

/-- The `P=7` negative shell. -/
theorem pellMinus_seven : PellMinus 7 2 5 := by
  norm_num [PellMinus]

/-- The `P=7` paired shell yields the unit `49+20√6`. -/
theorem squareTraceUnit_seven : SquareTraceUnit 7 6 20 := by
  exact pairedPell_to_squareTraceUnit pellPlus_seven pellMinus_seven (by norm_num)

/-- The `P=99` positive Pell shell. -/
theorem pellPlus_ninetyNine : PellPlus 99 2 70 := by
  norm_num [PellPlus]

/-- The `P=99` negative Pell shell generated by `√58`. -/
theorem pellMinus_ninetyNine : PellMinus 99 58 13 := by
  norm_num [PellMinus]

/-- The discriminant product behind the `N=58` square-trace unit. -/
theorem discriminantFusion_ninetyNine : (2 : ℤ) * 58 = 29 * 2 ^ 2 := by
  norm_num

/-- The paired `P=99` shells yield the norm-one unit
`9801 + 1820√29`. -/
theorem squareTraceUnit_ninetyNine : SquareTraceUnit 99 29 1820 := by
  exact pairedPell_to_squareTraceUnit pellPlus_ninetyNine
    pellMinus_ninetyNine discriminantFusion_ninetyNine

/-- The rational half-trace in the `N=58` unit is `99²=9801`. -/
theorem halfTrace_ninetyNine : (99 : ℤ) ^ 2 = 9801 := by
  norm_num

/-- The quartic acceleration denominator is `99⁴`. -/
theorem compressionDenominator_ninetyNine : (99 : ℕ) ^ 4 = 96059601 := by
  norm_num

end EnterpriseMath.PrecisionPi.SquareTraceDoublePell
