#!/usr/bin/env python3
"""Exact finite checker for RS-GEO6-HADWIGER-CELL-COVER-ILLUMINATION.

The checker proves only the declared signed-axis shell probe statements in the
research return. It does not identify this probe with the whole P000 Cell space.
"""

from itertools import combinations, product


def negative_pattern(n, neg):
    neg = set(neg)
    return tuple(-1 if i in neg else 1 for i in range(n))


def elementary_half_turn_patterns(n):
    """Identity plus one-step two-axis half-turns."""
    out = [negative_pattern(n, ())]
    out.extend(negative_pattern(n, pair) for pair in combinations(range(n), 2))
    return out


def even_closure_patterns(n):
    """Closure generated by all two-axis half-turns: even sign parity."""
    return [
        s
        for s in product((-1, 1), repeat=n)
        if sum(x < 0 for x in s) % 2 == 0
    ]


def full_sign_patterns(n):
    return list(product((-1, 1), repeat=n))


def sign_preserving_patterns(n):
    # Any sign-preserving axis permutation fixes the positive half-shell template
    # as a set, so its orbit has this single sign pattern.
    return [(1,) * n]


def separation_number(patterns, n):
    """Min pattern count whose coordinate projections each contain both signs."""
    for r in range(1, len(patterns) + 1):
        for idxs in combinations(range(len(patterns)), r):
            if all({patterns[j][i] for j in idxs} == {-1, 1} for i in range(n)):
                return r
    return None


def boundary_cells(n, m):
    return {(i, eps, j) for i in range(n) for eps in (-1, 1) for j in range(m)}


def transformed_template(pattern, n, m):
    # Center is omitted because every template contains it; boundary coverage is decisive.
    return {(i, pattern[i], j) for i in range(n) for j in range(m)}


def illuminated_boundary(pattern, n, m):
    # Direction pattern sigma illuminates the boundary polarity opposite sigma_i.
    return {(i, -pattern[i], j) for i in range(n) for j in range(m)}


def min_set_cover(universe, sets):
    for r in range(1, len(sets) + 1):
        for idxs in combinations(range(len(sets)), r):
            union = set()
            for j in idxs:
                union.update(sets[j])
            if universe <= union:
                return r
    return None


def cover_number(patterns, n, m):
    u = boundary_cells(n, m)
    return min_set_cover(u, [transformed_template(s, n, m) for s in patterns])


def illumination_number(patterns, n, m):
    u = boundary_cells(n, m)
    return min_set_cover(u, [illuminated_boundary(s, n, m) for s in patterns])


EXPECTED = {
    1: {"elementary": None, "even_closure": None, "full": 2, "sign_preserving": None},
    2: {"elementary": 2, "even_closure": 2, "full": 2, "sign_preserving": None},
    3: {"elementary": 3, "even_closure": 3, "full": 2, "sign_preserving": None},
    4: {"elementary": 2, "even_closure": 2, "full": 2, "sign_preserving": None},
    5: {"elementary": 3, "even_closure": 3, "full": 2, "sign_preserving": None},
    6: {"elementary": 3, "even_closure": 2, "full": 2, "sign_preserving": None},
}


def run():
    families = {
        "elementary": elementary_half_turn_patterns,
        "even_closure": even_closure_patterns,
        "full": full_sign_patterns,
        "sign_preserving": sign_preserving_patterns,
    }

    for n in range(1, 7):
        for name, fn in families.items():
            patterns = fn(n)
            sep = separation_number(patterns, n)
            assert sep == EXPECTED[n][name], (n, name, sep)

            # Exact refinement census. m changes multiplicity only, never sign incidence.
            for m in (1, 2, 3):
                cov = cover_number(patterns, n, m)
                illum = illumination_number(patterns, n, m)
                assert cov == sep, (n, m, name, "cover", cov, sep)
                assert illum == sep, (n, m, name, "illum", illum, sep)

    # Six-dimensional sharp witnesses.
    n = 6
    elem = elementary_half_turn_patterns(n)
    even = even_closure_patterns(n)

    # Three disjoint two-axis half-turns: (12), (34), (56).
    witness3 = [
        negative_pattern(n, (0, 1)),
        negative_pattern(n, (2, 3)),
        negative_pattern(n, (4, 5)),
    ]
    assert separation_number(witness3, n) == 3

    # In the composition closure, global inversion is available:
    # R_12 R_34 R_56 = -I on this sign probe.
    plus = negative_pattern(n, ())
    minus = negative_pattern(n, range(n))
    assert plus in even and minus in even
    assert separation_number([plus, minus], n) == 2

    # No two one-step elementary patterns are antipodal in n=6:
    # their negative weights are 0 or 2, while complements have weights 6 or 4.
    for a, b in combinations(elem, 2):
        assert any(a[i] == b[i] for i in range(n))

    print("PASS: exact cover/illumination census and refinement invariance verified")


if __name__ == "__main__":
    run()
