from __future__ import annotations
import itertools, json, math, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1] if "__file__" in globals() else pathlib.Path(".")
V = ("A","B","C","D")
EDGES = (("A","B"),("A","C"),("A","D"),("B","C"),("B","D"),("C","D"))
EDGE_IDX = {tuple(sorted(e)): i for i,e in enumerate(EDGES)}
ID6 = tuple(range(6))

def vperm(images):
    return dict(zip(V, images))

def compose_v(p,q):
    return {x:p[q[x]] for x in V}

def eperm(p):
    return tuple(EDGE_IDX[tuple(sorted((p[u],p[v])))] for u,v in EDGES)

def comp(p,q):
    return tuple(p[q[i]] for i in range(len(p)))

def inv(p):
    out=[0]*len(p)
    for i,j in enumerate(p):
        out[j]=i
    return tuple(out)

def conj(p,h):
    return comp(comp(p,h),inv(p))

def push_vec(act,v):
    out=[None]*len(v)
    for i in range(len(v)):
        out[act[i]]=v[i]
    return tuple(out)

def swap6(i,j):
    p=list(ID6)
    p[i],p[j]=p[j],p[i]
    return tuple(p)

S4=[vperm(t) for t in itertools.permutations(V)]
EA=[eperm(p) for p in S4]

def pindex(target):
    for i,p in enumerate(S4):
        if all(p[k]==v for k,v in target.items()):
            return i
    raise AssertionError(target)

a_idx=pindex({"A":"A","B":"C","C":"D","D":"B"})  # (BCD)
b_idx=pindex({"A":"B","B":"A","C":"C","D":"D"})  # (AB)
aV,bV=S4[a_idx],S4[b_idx]
aE,bE=EA[a_idx],EA[b_idx]

# Carrier regression and generation.
assert len({tuple(e) for e in EA}) == 24
generated={ID6}
front=[ID6]
while front:
    x=front.pop()
    for g in (aE,bE):
        y=comp(g,x)
        if y not in generated:
            generated.add(y); front.append(y)
assert len(generated)==24

# ---------- PF10 family ladder ----------
def star(x):
    return tuple(1 if x in EDGES[i] else 0 for i in range(6))

ZERO=(0,)*6
E1=(1,0,0,0,0,0)

def pf_eq(P,pidx):
    pv,pe=S4[pidx],EA[pidx]
    return all(
        P[V.index(pv[x])] == push_vec(pe,P[V.index(x)])
        for x in V
    )

H_A=[i for i,p in enumerate(S4) if p["A"]=="A"]
def pf_one_cell_stabilizer_regular(P):
    return all(push_vec(EA[i],P[0])==P[0] for i in H_A)

def vec_orbit(v):
    return {push_vec(e,v) for e in EA}

def pf_same_local_orbit_type(P):
    o=vec_orbit(P[0])
    return all(v in o for v in P)

def pf_full(P):
    return all(pf_eq(P,i) for i in range(24))

PF_GLOBAL=tuple(star(x) for x in V)
PF_CONST_STAR_A=(star("A"),)*4
PF_CONST_E1=(E1,)*4
PF_A_IRREGULAR=(star("A"),ZERO,ZERO,ZERO)

assert pf_one_cell_stabilizer_regular(PF_GLOBAL)
assert pf_same_local_orbit_type(PF_GLOBAL)
assert pf_eq(PF_GLOBAL,a_idx) and pf_eq(PF_GLOBAL,b_idx) and pf_full(PF_GLOBAL)

# Same local orbit type + one-cell regularity + a-equivariance do not force b/full.
assert pf_one_cell_stabilizer_regular(PF_CONST_STAR_A)
assert pf_same_local_orbit_type(PF_CONST_STAR_A)
assert pf_eq(PF_CONST_STAR_A,a_idx)
assert not pf_eq(PF_CONST_STAR_A,b_idx)
assert not pf_full(PF_CONST_STAR_A)

# Same local orbit type does not imply one-cell stabilizer regularity; b alone is insufficient.
assert pf_same_local_orbit_type(PF_CONST_E1)
assert not pf_one_cell_stabilizer_regular(PF_CONST_E1)
assert pf_eq(PF_CONST_E1,b_idx)
assert not pf_eq(PF_CONST_E1,a_idx)
assert not pf_full(PF_CONST_E1)

# a-equivariance and one-cell regularity do not imply same orbit type.
assert pf_eq(PF_A_IRREGULAR,a_idx)
assert pf_one_cell_stabilizer_regular(PF_A_IRREGULAR)
assert not pf_same_local_orbit_type(PF_A_IRREGULAR)
assert not pf_full(PF_A_IRREGULAR)

# For the faithful S4 action generated by a,b, both generator equations imply full equivariance.
def subgroup_closure(gens):
    out={ID6}; front=[ID6]
    while front:
        x=front.pop()
        for g in gens:
            for y in (comp(g,x),comp(x,g)):
                if y not in out:
                    out.add(y); front.append(y)
    return out
assert subgroup_closure((aE,bE)) == set(EA)

# ---------- Hidden-kernel exact theorem ----------
# G0 = C2 x S4, q(k,g)=g. Chosen lifts (0,a),(0,b) generate only H={0}xS4.
Q = tuple(range(24))
G0={(k,g) for k in (0,1) for g in Q}
K={(k, pindex({"A":"A","B":"B","C":"C","D":"D"})) for k in (0,1)}
H={(0,g) for g in Q}
chosen_a=(0,a_idx); chosen_b=(0,b_idx)
assert chosen_a in H and chosen_b in H and len(H)==24 and len(G0)==48

# A background stabilizer H preserves chosen a,b lifts but not the hidden kernel.
GB_CHOSEN_ONLY=set(H)
assert chosen_a in GB_CHOSEN_ONLY and chosen_b in GB_CHOSEN_ONLY
assert GB_CHOSEN_ONLY != G0
assert len(K & GB_CHOSEN_ONLY)==1

# Full lift-fibers of a,b include both kernel translates and generate all G0.
fiber_a={(k,a_idx) for k in (0,1)}
fiber_b={(k,b_idx) for k in (0,1)}
assert not fiber_a.issubset(GB_CHOSEN_ONLY)
assert not fiber_b.issubset(GB_CHOSEN_ONLY)

# Direct finite closure in C2 x S4.
def mulG(x,y):
    k1,g1=x; k2,g2=y
    pv=compose_v(S4[g1],S4[g2])
    gi=next(i for i,p in enumerate(S4) if p==pv)
    return ((k1+k2)%2,gi)
def invG(x):
    k,g=x
    pinv={S4[g][v]:v for v in V}
    gi=next(i for i,p in enumerate(S4) if p==pinv)
    return (k,gi)
def closureG(gens):
    e=(0,pindex({"A":"A","B":"B","C":"C","D":"D"}))
    out={e}; front=[e]
    gens=list(gens)
    while front:
        x=front.pop()
        for g in gens:
            for y in (mulG(g,x),mulG(x,g),mulG(invG(g),x)):
                if y not in out:
                    out.add(y); front.append(y)
    return out
assert closureG(fiber_a|fiber_b)==G0
assert closureG({chosen_a,chosen_b})==H

# Thus: full-fiber a,b preservation <=> full G0 transparency.
# Chosen-lift a,b preservation becomes sufficient only after kernel transparency.
GB_WITH_KERNEL=closureG({chosen_a,chosen_b}|K)
assert GB_WITH_KERNEL==G0

# ---------- Independent connection ladder ----------
ORIENTED=[(x,y) for x in V for y in V if x!=y]

def conn_nat(T,pidx):
    pv,pe=S4[pidx],EA[pidx]
    return all(
        T[(pv[x],pv[y])] == conj(pe,T[(x,y)])
        for x,y in ORIENTED
    )

def conn_full(T):
    return all(conn_nat(T,i) for i in range(24))

def inverse_consistent(T):
    return all(T[(y,x)]==inv(T[(x,y)]) for x,y in ORIENTED)

def path_transport(T,path):
    r=ID6
    for x,y in zip(path,path[1:]):
        r=comp(T[(x,y)],r)
    return r

T_ID={xy:ID6 for xy in ORIENTED}
assert inverse_consistent(T_ID) and conn_full(T_ID)

# b-only naturality: Gen17 marked AB edge.
h=swap6(0,5)
T_MARK={}
for x,y in ORIENTED:
    T_MARK[(x,y)] = h if set((x,y))=={"A","B"} else ID6
assert inverse_consistent(T_MARK)
assert conn_nat(T_MARK,b_idx)
assert not conn_nat(T_MARK,a_idx)
assert not conn_full(T_MARK)

# a-only naturality by propagating a seed around the a-orbit AB->AC->AD.
T_A={xy:None for xy in ORIENTED}
pk={x:x for x in V}; ek=ID6
for _ in range(3):
    x,y=pk["A"],pk["B"]
    hk=conj(ek,h)
    T_A[(x,y)]=hk
    T_A[(y,x)]=inv(hk)
    pk=compose_v(aV,pk); ek=comp(aE,ek)
for xy in ORIENTED:
    if T_A[xy] is None:
        T_A[xy]=ID6
assert inverse_consistent(T_A)
assert conn_nat(T_A,a_idx)
assert not conn_nat(T_A,b_idx)
assert not conn_full(T_A)

# Local edge type regularity alone does not force inverse-edge consistency.
s=list(ID6); s[0],s[1],s[2]=1,2,0; s=tuple(s)
T_LOCAL_TYPE={xy:s for xy in ORIENTED}
assert not inverse_consistent(T_LOCAL_TYPE)

# Standard path transport by ordered edge composition is associative by definition.
# Inverse consistency plus this path-groupoid semantics still does not imply symmetry:
# a flat pure-gauge but asymmetric independent connection has trivial holonomy.
gauges={"A":s,"B":ID6,"C":ID6,"D":ID6}
T_FLAT_GAUGE={
    (x,y): comp(gauges[y],inv(gauges[x]))
    for x,y in ORIENTED
}
assert inverse_consistent(T_FLAT_GAUGE)
cycle_basis=[
    ("A","B","C","A"),
    ("A","B","D","A"),
    ("A","C","D","A"),
]
assert all(path_transport(T_FLAT_GAUGE,c)==ID6 for c in cycle_basis)
assert not conn_nat(T_FLAT_GAUGE,b_idx)
assert not conn_full(T_FLAT_GAUGE)

# Full equivariance does not require flatness.
opp={}
for i,(u,v) in enumerate(EDGES):
    rem=[x for x in V if x not in (u,v)]
    opp[i]=EDGE_IDX[tuple(sorted(rem))]
T_NONFLAT={}
for x,y in ORIENTED:
    i=EDGE_IDX[tuple(sorted((x,y)))]
    T_NONFLAT[(x,y)]=swap6(i,opp[i])
assert inverse_consistent(T_NONFLAT)
assert conn_nat(T_NONFLAT,a_idx) and conn_nat(T_NONFLAT,b_idx)
assert conn_full(T_NONFLAT)
hols=[path_transport(T_NONFLAT,c) for c in cycle_basis]
assert all(hh!=ID6 for hh in hols)

# Both chosen generator naturalities imply full only for a structural group generated by them;
# with hidden kernel, the same full-fiber/kernel criterion as above is required.

# ---------- Independence and information ----------
# Visible S4 symmetry-breaking witnesses each have stabilizer order 4 and orbit index 6.
stab_e1=[i for i,e in enumerate(EA) if e[0]==0]
assert len(stab_e1)==4
conn_compat=[i for i in range(24) if conn_nat(T_MARK,i)]
assert len(conn_compat)==4
assert 24//len(stab_e1)==6
assert 24//len(conn_compat)==6

pf_orbit_bits=math.log2(6)
conn_orbit_bits=math.log2(6)
joint_raw_choice_bits=math.log2(36)
hidden_kernel_bits=math.log2(2)
assert abs(joint_raw_choice_bits-(pf_orbit_bits+conn_orbit_bits))<1e-12

# Four logical combinations are realizable: transparent/leaky independently.
PF_FULL_OK=pf_full(PF_GLOBAL)
PF_LEAK_OK=pf_full(PF_CONST_E1)
CONN_FULL_OK=conn_full(T_ID)
CONN_LEAK_OK=conn_full(T_MARK)
assert (PF_FULL_OK,CONN_FULL_OK)==(True,True)
assert (PF_FULL_OK,CONN_LEAK_OK)==(True,False)
assert (PF_LEAK_OK,CONN_FULL_OK)==(False,True)
assert (PF_LEAK_OK,CONN_LEAK_OK)==(False,False)

# ---------- Frozen repository regressions ----------
gen17 = ROOT / "research_artifacts/P000_BACKGROUND_S4_EQUIVARIANCE_GATE_V17/BACKGROUND_EQUIVARIANCE_CERTIFICATE.json"
if gen17.exists():
    cert=json.loads(gen17.read_text())
    assert cert["terminal_class"]=="MULTIPLE_INDEPENDENT_BACKGROUND_LEAK_SOURCES_AND_PARETO_GATES_CLASSIFIED"
    assert cert["pf10_classification"]["generator_conditions"]["a_and_b"].startswith("sufficient and equivalent")
    assert cert["connection_classification"]["independent_leak_witness"]["compatibility_order"]==4
    assert cert["guards"]["NO_KERNEL_QUOTIENT"] is True

print("PASS P000_LOCAL_TO_GLOBAL_BACKGROUND_EQUIVARIANCE_V18_CHECK")
print("carrier_s4_order=24")
print("visible_generators_ab_generate_s4=true")
print("pf_full_family_ab_and_global=true")
print("pf_a_only_countermodel=true")
print("pf_b_only_countermodel=true")
print("pf_same_orbit_not_stabilizer_countermodel=true")
print("chosen_ab_hidden_kernel_countermodel=G0_48_H_24_K_2")
print("full_lift_fibers_ab_generate_G0=true")
print("connection_a_only_countermodel=true")
print("connection_b_only_countermodel=true")
print("flat_holonomy_but_nonequivariant_countermodel=true")
print("equivariant_nonflat_connection=true")
print("pf_visible_orbit_index=6")
print("connection_visible_orbit_index=6")
print("joint_raw_mark_choice_count=36")
print("hidden_kernel_orbit_index=2")
print("terminal_class=LOCAL_GENERATOR_EQUIVARIANCE_EXACTLY_EQUIVALENT_TO_GLOBAL_BACKGROUND_TRANSPARENCY")
