#!/usr/bin/env python3
"""Exact checker for P000 philosophy-first Q6 representability boundary.

Declared scope:
- Q2 toy model class U_2REG: finite simple 2-regular native-Cell graphs,
  with uniform six-axis carrier/PF10 decoration.
- Radius-1 typed profile P_1 is compressed to (t, p), where
  t = number of roots whose N_1 ball is a rooted triangle,
  p = number of roots whose N_1 ball is a rooted 3-vertex path.
- A formal profile is restriction-compatible when every local output is one
  of these Q2-legal rooted types and all uniform SLICE/ROT/PF10 restrictions
  agree. For support-aware comparison we require n=t+p>=3.
"""

CHECKS = 0


def check(cond, msg):
    global CHECKS
    CHECKS += 1
    if not cond:
        raise AssertionError(msg)


def compose(p, q):
    """Return p o q on 0..5."""
    return tuple(p[q[i]] for i in range(6))


def power(p, n):
    r = tuple(range(6))
    for _ in range(n):
        r = compose(p, r)
    return r


def cycle_partitions(n):
    """Unordered partitions of n into cycle lengths >=3."""
    out = []

    def rec(rem, lo, cur):
        if rem == 0:
            out.append(tuple(cur))
            return
        for k in range(lo, rem + 1):
            rec(rem - k, k, cur + [k])

    rec(n, 3, [])
    return out


def obs_profile(partition):
    """Q2 radius-1 profile for a disjoint union of cycles."""
    triangle_roots = sum(k for k in partition if k == 3)
    path_roots = sum(k for k in partition if k >= 4)
    return (triangle_roots, path_roots)


def predicted_representable(n):
    """Closed-form image of Obs_1 on n-Cell U_2REG states."""
    return {
        (t, n - t)
        for t in range(n + 1)
        if t % 3 == 0 and ((n - t) == 0 or (n - t) >= 4)
    }


def obstruction_certificate(t, p):
    """Zero exactly on representable profiles in the declared scope."""
    triangle_residue = t % 3
    path_shortage = p if 1 <= p <= 3 else 0
    return (triangle_residue, path_shortage)


# Accepted carrier S4 readout regression on six axis types.
# a=(E1 E2 E3)(E4 E6 E5), b=(E2 E4)(E3 E5)
a = (1, 2, 0, 5, 3, 4)
b = (0, 3, 4, 1, 2, 5)
identity = tuple(range(6))
check(power(a, 3) == identity, "a^3 regression failed")
check(power(b, 2) == identity, "b^2 regression failed")
check(power(compose(a, b), 4) == identity, "(ab)^4 regression failed")

# Exhaustively compare the graph-image enumeration with the exact theorem.
for n in range(3, 65):
    actual = {obs_profile(part) for part in cycle_partitions(n)}
    predicted = predicted_representable(n)
    check(actual == predicted, f"image mismatch at n={n}: {actual} != {predicted}")
    check(len(actual) == n // 3, f"image-cardinality mismatch at n={n}")

    # Every formal count profile gets a complete obstruction certificate.
    for t in range(n + 1):
        p = n - t
        is_rep = (t, p) in actual
        cert = obstruction_certificate(t, p)
        check(
            is_rep == (cert == (0, 0)),
            f"certificate mismatch n={n}, t={t}, p={p}, cert={cert}",
        )

# Minimal support-aware pure virtual profile.
check(
    (0, 3) not in predicted_representable(3),
    "three all-path roots must be virtual",
)
check(
    (3, 0) in predicted_representable(3),
    "three triangle roots must be represented by C3",
)

# Pure all-path profiles become representable exactly from C4 onward.
for n in range(3, 8):
    check(
        ((0, n) in predicted_representable(n)) == (n >= 4),
        f"pure-path threshold mismatch at n={n}",
    )

# Q2 noninjectivity survives inside the representable image.
fiber_08 = [
    part
    for part in cycle_partitions(8)
    if obs_profile(part) == (0, 8)
]
check(
    (8,) in fiber_08 and (4, 4) in fiber_08 and len(fiber_08) == 2,
    f"Q2 fiber regression failed: {fiber_08}",
)

# The nontriangle-root mass monoid is generated by 4,5,6,7.
generators = (4, 5, 6, 7)
reachable = {0}
for _ in range(40):
    reachable |= {
        x + g
        for x in tuple(reachable)
        for g in generators
        if x + g <= 128
    }
for p in range(129):
    check(
        (p in reachable) == (p == 0 or p >= 4),
        f"path-mass monoid mismatch at p={p}",
    )

print(
    "PASS P000_REPRESENTABILITY_BOUNDARY; "
    f"checks={CHECKS}; "
    "scope=U_2REG_P1; "
    "minimal_pure_virtual=(t=0,p=3); "
    "representable_iff=t_mod_3_zero_and_p_zero_or_ge_4; "
    "image_size=floor(n/3)_for_n_ge_3; "
    "Q2_noninjective_fiber=(0,8):C8_vs_C4_plus_C4; "
    "carrier_S4_regression=PASS"
)
