#!/usr/bin/env python3
"""Deterministic checker for P000 Q20 three-loop FUSION_BACKWARD stress test.

The checker is task-local.  It:
1. freezes the concrete U/L/P/T refinement category generated by restrictions,
   zero insertions, permutations and XOR fusions;
2. proves by finite equality that its morphisms are exactly partial
   coordinate-assignment/XOR maps;
3. exhausts all 2^15 effectivity assignments and all 2^12 subsets of the
   declared law atoms;
4. verifies the matched lower-law systems and the exact backward-law boundary.
"""
from __future__ import annotations

from collections import Counter, defaultdict
from itertools import product, permutations

TASK_ID = "RS-P000-PHILOSOPHY-FIRST-FUSION-BACKWARD-THREE-LOOP-STRESS"

DIMS = (0, 1, 2, 3)
STATES = {d: tuple(product((0, 1), repeat=d)) for d in DIMS}

# A concrete morphism is (source dimension, target dimension, output table).
Morph = tuple[int, int, tuple[tuple[int, ...], ...]]


def morph(src: int, dst: int, fn) -> Morph:
    return (src, dst, tuple(fn(x) for x in STATES[src]))


def identity(d: int) -> Morph:
    return morph(d, d, lambda x: x)


def compose(g: Morph, f: Morph) -> Morph:
    """Return g after f."""
    s, mid, ft = f
    mid2, d, gt = g
    assert mid == mid2
    index = {x: i for i, x in enumerate(STATES[mid])}
    return (s, d, tuple(gt[index[y]] for y in ft))


def generators() -> set[Morph]:
    out: set[Morph] = {identity(d) for d in DIMS}

    # Unique maps to U.
    for d in (1, 2, 3):
        out.add(morph(d, 0, lambda _x: ()))

    # Unit insertion U -> L.
    out.add(morph(0, 1, lambda _x: (0,)))

    # L -> P neutral insertions.
    out.add(morph(1, 2, lambda x: (x[0], 0)))
    out.add(morph(1, 2, lambda x: (0, x[0])))

    # P -> L restrictions and XOR fusion; P permutation.
    out.add(morph(2, 1, lambda x: (x[0],)))
    out.add(morph(2, 1, lambda x: (x[1],)))
    out.add(morph(2, 1, lambda x: (x[0] ^ x[1],)))
    out.add(morph(2, 2, lambda x: (x[1], x[0])))

    # P -> T neutral insertions.
    out.add(morph(2, 3, lambda x: (x[0], x[1], 0)))
    out.add(morph(2, 3, lambda x: (x[0], 0, x[1])))
    out.add(morph(2, 3, lambda x: (0, x[0], x[1])))

    # T -> P coordinate restrictions.
    out.add(morph(3, 2, lambda x: (x[0], x[1])))
    out.add(morph(3, 2, lambda x: (x[0], x[2])))
    out.add(morph(3, 2, lambda x: (x[1], x[2])))

    # T coordinate permutation generators.
    out.add(morph(3, 3, lambda x: (x[1], x[0], x[2])))
    out.add(morph(3, 3, lambda x: (x[0], x[2], x[1])))

    # Two parenthesization-relevant pair fusions and explicit total XOR.
    out.add(morph(3, 2, lambda x: (x[0] ^ x[1], x[2])))
    out.add(morph(3, 2, lambda x: (x[0], x[1] ^ x[2])))
    out.add(morph(3, 1, lambda x: (x[0] ^ x[1] ^ x[2],)))
    return out


def generated_category() -> set[Morph]:
    seen = set(generators())
    while True:
        current = tuple(seen)
        by_src: dict[int, list[Morph]] = defaultdict(list)
        by_dst: dict[int, list[Morph]] = defaultdict(list)
        for f in current:
            by_src[f[0]].append(f)
            by_dst[f[1]].append(f)
        new: set[Morph] = set()
        for mid in DIMS:
            for f in by_dst[mid]:
                for g in by_src[mid]:
                    h = compose(g, f)
                    if h not in seen:
                        new.add(h)
        if not new:
            return seen
        seen.update(new)


def normal_form_morphism(src: int, dst: int, labels: tuple[int, ...]) -> Morph:
    """Each input coordinate is discarded (0) or sent to one output (1..dst)."""
    assert len(labels) == src
    assert all(0 <= label <= dst for label in labels)

    def fn(x: tuple[int, ...]) -> tuple[int, ...]:
        y = [0] * dst
        for i, label in enumerate(labels):
            if label:
                y[label - 1] ^= x[i]
        return tuple(y)

    return morph(src, dst, fn)


def normal_form_category() -> set[Morph]:
    return {
        normal_form_morphism(src, dst, labels)
        for src in DIMS
        for dst in DIMS
        for labels in product(range(dst + 1), repeat=src)
    }


LAW_NAMES = (
    "ROT_PERM",
    "RESTRICTION",
    "GLUE",
    "NEUTRAL_REFINEMENT",
    "FUSION_FORWARD_2",
    "FUSION_FORWARD_3_PAIR",
    "FUSION_FORWARD_3_TOTAL",
    "UNIT_NATURALITY",
    "UNIT_TRUE",
    "FUSION_BACKWARD_2",
    "FUSION_BACKWARD_3_PAIR",
    "FUSION_BACKWARD_3_TOTAL",
)
K = len(LAW_NAMES)
STATE2 = tuple(product((0, 1), repeat=2))
STATE3 = tuple(product((0, 1), repeat=3))
IDX2 = {x: i for i, x in enumerate(STATE2)}
IDX3 = {x: i for i, x in enumerate(STATE3)}
PERM3 = tuple(permutations(range(3)))


def unpack_assignment(number: int):
    bits = tuple((number >> i) & 1 for i in range(15))
    eu = bool(bits[0])
    e1 = tuple(bool(v) for v in bits[1:3])
    e2 = tuple(bool(v) for v in bits[3:7])
    e3 = tuple(bool(v) for v in bits[7:15])
    return eu, e1, e2, e3


def law_values(number: int) -> tuple[bool, ...]:
    eu, e1, E2, E3 = unpack_assignment(number)

    def e2(a: int, b: int) -> bool:
        return E2[IDX2[(a, b)]]

    def e3(a: int, b: int, c: int) -> bool:
        return E3[IDX3[(a, b, c)]]

    rot_perm = (
        all(e2(a, b) == e2(b, a) for a, b in STATE2)
        and all(
            e3(*x) == e3(*(tuple(x[i] for i in p)))
            for x in STATE3
            for p in PERM3
        )
    )

    restriction = (
        all((not e2(a, b)) or (e1[a] and e1[b]) for a, b in STATE2)
        and all(
            (not e3(a, b, c))
            or (e2(a, b) and e2(a, c) and e2(b, c))
            for a, b, c in STATE3
        )
    )

    glue = (
        all((not (e1[a] and e1[b])) or e2(a, b) for a, b in STATE2)
        and all(
            ((not (e2(a, b) and e1[c])) or e3(a, b, c))
            and ((not (e2(a, c) and e1[b])) or e3(a, b, c))
            and ((not (e2(b, c) and e1[a])) or e3(a, b, c))
            for a, b, c in STATE3
        )
    )

    neutral = (
        all(e2(h, 0) == e1[h] and e2(0, h) == e1[h] for h in (0, 1))
        and all(
            e3(a, b, 0) == e2(a, b)
            and e3(a, 0, c) == e2(a, c)
            and e3(0, b, c) == e2(b, c)
            for a, b, c in STATE3
        )
    )

    forward2 = all((not e2(a, b)) or e1[a ^ b] for a, b in STATE2)

    forward3_pair = all(
        (not e3(a, b, c))
        or (e2(a ^ b, c) and e2(a, b ^ c) and e2(a ^ c, b))
        for a, b, c in STATE3
    )

    forward3_total = all(
        (not e3(a, b, c)) or e1[a ^ b ^ c]
        for a, b, c in STATE3
    )

    unit_naturality = eu == e1[0]
    unit_true = eu

    backward2 = all(
        (not e1[a ^ b]) or e2(a, b)
        for a, b in STATE2
    )

    backward3_pair = all(
        ((not e2(a ^ b, c)) or e3(a, b, c))
        and ((not e2(a, b ^ c)) or e3(a, b, c))
        and ((not e2(a ^ c, b)) or e3(a, b, c))
        for a, b, c in STATE3
    )

    backward3_total = all(
        (not e1[a ^ b ^ c]) or e3(a, b, c)
        for a, b, c in STATE3
    )

    return (
        rot_perm,
        restriction,
        glue,
        neutral,
        forward2,
        forward3_pair,
        forward3_total,
        unit_naturality,
        unit_true,
        backward2,
        backward3_pair,
        backward3_total,
    )


def law_mask(number: int) -> int:
    return sum(1 << i for i, ok in enumerate(law_values(number)) if ok)


def selector_code(number: int) -> int:
    _eu, e1, _e2, _e3 = unpack_assignment(number)
    return int(e1[0]) | (int(e1[1]) << 1)


def selector_name(code: int) -> str:
    return f"{code & 1}{(code >> 1) & 1}"


def assignment_signature(number: int) -> str:
    eu, e1, e2, e3 = unpack_assignment(number)
    b = lambda seq: "".join("1" if x else "0" for x in seq)
    return f"EU={int(eu)};E1={b(e1)};E2={b(e2)};E3={b(e3)}"


def satisfies(number: int, required_mask: int) -> bool:
    return (law_mask(number) & required_mask) == required_mask


def effectivity_at_dim(number: int, dim: int, state: tuple[int, ...]) -> bool:
    eu, e1, e2, e3 = unpack_assignment(number)
    if dim == 0:
        return eu
    if dim == 1:
        return e1[state[0]]
    if dim == 2:
        return e2[IDX2[state]]
    if dim == 3:
        return e3[IDX3[state]]
    raise AssertionError(dim)


def all_morphism_forward_natural(number: int, cat: set[Morph]) -> bool:
    for src, dst, table in cat:
        for i, x in enumerate(STATES[src]):
            if effectivity_at_dim(number, src, x):
                if not effectivity_at_dim(number, dst, table[i]):
                    return False
    return True


def main() -> None:
    checks = 0

    cat = generated_category()
    normal = normal_form_category()
    assert cat == normal
    checks += 1

    hom = Counter((f[0], f[1]) for f in cat)
    hom_matrix = tuple(
        tuple(hom[(src, dst)] for dst in DIMS)
        for src in DIMS
    )
    assert len(cat) == 144
    assert hom_matrix == (
        (1, 1, 1, 1),
        (1, 2, 3, 4),
        (1, 4, 9, 16),
        (1, 8, 27, 64),
    )
    for src in DIMS:
        for dst in DIMS:
            assert hom[(src, dst)] == (dst + 1) ** src
    checks += 2

    # Structural associativity is literal equality of the two total XOR paths.
    for a, b, c in STATE3:
        assert ((a ^ b) ^ c) == (a ^ (b ^ c)) == (a ^ b ^ c)
    checks += 1

    exact_counts = [0] * (1 << K)
    exact_selectors = [0] * (1 << K)
    masks = [0] * (1 << 15)
    for number in range(1 << 15):
        mask = law_mask(number)
        masks[number] = mask
        exact_counts[mask] += 1
        exact_selectors[mask] |= 1 << selector_code(number)
    assert sum(exact_counts) == 32768
    checks += 1

    # Superset zeta transforms: req -> all assignments satisfying every law in req.
    sat_counts = exact_counts[:]
    sat_selectors = exact_selectors[:]
    for i in range(K):
        bit = 1 << i
        for mask in range(1 << K):
            if not (mask & bit):
                sat_counts[mask] += sat_counts[mask | bit]
                sat_selectors[mask] |= sat_selectors[mask | bit]

    def req(*names: str) -> int:
        return sum(1 << LAW_NAMES.index(name) for name in names)

    lower_names = LAW_NAMES[:9]
    lower = req(*lower_names)
    assert sat_counts[lower] == 2
    lower_models = [
        n for n in range(1 << 15)
        if (masks[n] & lower) == lower
    ]
    assert lower_models == [139, 32767]
    assert assignment_signature(139) == "EU=1;E1=10;E2=1000;E3=10000000"
    assert assignment_signature(32767) == "EU=1;E1=11;E2=1111;E3=11111111"
    checks += 3

    # Both matched systems satisfy forward naturality for every one of 144 maps.
    assert all_morphism_forward_natural(139, cat)
    assert all_morphism_forward_natural(32767, cat)
    checks += 2

    b2 = 1 << LAW_NAMES.index("FUSION_BACKWARD_2")
    b3p = 1 << LAW_NAMES.index("FUSION_BACKWARD_3_PAIR")
    b3t = 1 << LAW_NAMES.index("FUSION_BACKWARD_3_TOTAL")
    assert not (masks[139] & b2)
    assert not (masks[139] & b3p)
    assert not (masks[139] & b3t)
    assert masks[32767] & b2
    assert masks[32767] & b3p
    assert masks[32767] & b3t
    assert sat_counts[lower | b2] == 1
    assert sat_counts[lower | b3p] == 1
    assert sat_counts[lower | b3t] == 1
    assert sat_counts[lower | b2 | b3p | b3t] == 1
    checks += 10

    # No subset of the nine backward-free atoms can force selector 11,
    # since the zero-support model satisfies the whole nine-atom bundle.
    backward_free_masks = range(1 << 9)
    for mask in backward_free_masks:
        assert (sat_selectors[mask] & (1 << 1))  # selector 10 survives
        assert (sat_selectors[mask] & (1 << 3))  # selector 11 survives
    checks += 2

    family_counts = Counter()
    for mask in range(1 << K):
        family = tuple(
            selector_name(code)
            for code in range(4)
            if sat_selectors[mask] & (1 << code)
        )
        family_counts[family] += 1
    expected_family_counts = {
        ("00", "10", "01", "11"): 1032,
        ("00", "10", "11"): 744,
        ("10", "11"): 592,
        ("00", "11"): 1296,
        ("11",): 432,
    }
    assert dict(family_counts) == expected_family_counts
    checks += 1

    forcing = {
        mask for mask in range(1 << K)
        if sat_selectors[mask] == (1 << 3)
    }
    minimal = []
    for mask in sorted(forcing):
        if all((mask & ~(1 << i)) not in forcing for i in range(K) if mask & (1 << i)):
            minimal.append(mask)

    minimal_names = {
        tuple(LAW_NAMES[i] for i in range(K) if mask & (1 << i))
        for mask in minimal
    }
    expected_minimal = {
        ("RESTRICTION", "UNIT_NATURALITY", "UNIT_TRUE", "FUSION_BACKWARD_2"),
        ("RESTRICTION", "GLUE", "UNIT_NATURALITY", "UNIT_TRUE", "FUSION_BACKWARD_3_PAIR"),
        ("RESTRICTION", "NEUTRAL_REFINEMENT", "UNIT_NATURALITY", "UNIT_TRUE", "FUSION_BACKWARD_3_PAIR"),
        ("RESTRICTION", "UNIT_NATURALITY", "UNIT_TRUE", "FUSION_BACKWARD_3_TOTAL"),
    }
    assert minimal_names == expected_minimal
    checks += 1

    # Exact deletion witnesses exist for every atom of every minimal forcing core.
    deletion_witnesses = {}
    for mask in minimal:
        key = tuple(LAW_NAMES[i] for i in range(K) if mask & (1 << i))
        deletion_witnesses[key] = {}
        for i in range(K):
            if not (mask & (1 << i)):
                continue
            reduced = mask & ~(1 << i)
            witness = next(
                n for n in range(1 << 15)
                if (masks[n] & reduced) == reduced and selector_code(n) != 3
            )
            deletion_witnesses[key][LAW_NAMES[i]] = assignment_signature(witness)
    assert all(deletion_witnesses.values())
    checks += 1

    # Full law bundle is consistent: exactly the all-effective model.
    full = (1 << K) - 1
    assert sat_counts[full] == 1
    assert (masks[32767] & full) == full
    checks += 2

    print(
        "PASS P000_Q20_FUSION_BACKWARD_THREE_LOOP; "
        f"checks={checks}; category_morphisms={len(cat)}; "
        "hom_matrix=1,1,1,1/1,2,3,4/1,4,9,16/1,8,27,64; "
        "normal_form=(target_dimension+1)^source_dimension; "
        "assignments=32768; law_subsets=4096; exact_law_masks=314; "
        "lower_models=2(trivial_zero_only,all_effective); "
        "backward_free_subsets=512_none_force_11; "
        "lower_plus_each_backward=1; full_bundle=1; "
        "minimal_11_forcing_cores=4; "
        "selector_family_counts="
        "all4:1032,00-10-11:744,10-11:592,00-11:1296,11:432; "
        "terminal=THREE_LOOP_COHERENCE_LEAVES_BACKWARD_REFLECTION_INDEPENDENT"
    )


if __name__ == "__main__":
    main()
