#!/usr/bin/env python3
"""Independent structural re-audit for P000 Philosophy-First Q31.

This checker preserves the frozen Q29 comparison scaffold and audits only the
declared divisor-exponent positive-conjunctive extension language.  Nothing in
this file promotes S3 x S3, the Boolean carrier, the token monoid, or EXP_d to
native P000 structure.
"""

from collections import Counter
from itertools import permutations
from math import gcd

ID = tuple(range(6))
BLOCK = tuple(permutations(range(3)))
LAWS = tuple(tuple(a) + tuple(3 + i for i in b) for a in BLOCK for b in BLOCK)
DIVISORS = (1, 2, 3, 6)

E2 = (1, 0, 2, 4, 3, 5)
E3 = (1, 2, 0, 4, 5, 3)
E6 = (1, 0, 2, 4, 5, 3)


def compose(p, q):
    """Coordinate action p after q."""
    return tuple(q[p[i]] for i in range(6))


def power(p, n):
    out = ID
    for _ in range(n):
        out = compose(p, out)
    return out


def inverse(p):
    out = [0] * 6
    for i, j in enumerate(p):
        out[j] = i
    return tuple(out)


def law_order(p):
    for n in DIVISORS:
        if power(p, n) == ID:
            return n
    raise AssertionError("comparison law order does not divide 6")


def exp_clause(p, d):
    """EXP_d for the cyclic image generated by p."""
    return power(p, d) == ID


def conjugate(c, p):
    return compose(c, compose(p, inverse(c)))


def formula_truth(atoms):
    return frozenset(
        p for p in LAWS if all(exp_clause(p, d) for d in atoms)
    )


def semantic_effective_exponent(atoms):
    """Positive conjunction of EXP_d is equivalent to EXP_gcd(atoms).

    Empty conjunction is TRUE; on this order-divides-6 universe it equals EXP_6.
    """
    if not atoms:
        return 6
    g = atoms[0]
    for d in atoms[1:]:
        g = gcd(g, d)
    return g


def main():
    assert len(LAWS) == 36
    assert len(set(LAWS)) == 36
    assert E2 in LAWS and E3 in LAWS and E6 in LAWS

    # Exact order census. Analytically, S3 has element-order counts 1,3,2
    # for orders 1,2,3; pair order is lcm of block orders.
    orders = Counter(law_order(p) for p in LAWS)
    assert orders == Counter({1: 1, 2: 15, 3: 8, 6: 12})
    assert law_order(E2) == 2
    assert law_order(E3) == 3
    assert law_order(E6) == 6

    truth = {d: formula_truth((d,)) for d in DIVISORS}
    assert {d: len(v) for d, v in truth.items()} == {1: 1, 2: 16, 3: 9, 6: 36}

    # Structural lemma: for every comparison law of order m|6,
    # EXP_d holds iff m divides d.
    for p in LAWS:
        m = law_order(p)
        for d in DIVISORS:
            assert exp_clause(p, d) == (d % m == 0)

    # Enumerate the complete declared positive-conjunctive grammar and verify
    # the analytic gcd normal form for every formula.
    formulas = []
    semantic_classes = {}
    for mask in range(1 << len(DIVISORS)):
        atoms = tuple(d for i, d in enumerate(DIVISORS) if (mask >> i) & 1)
        actual = formula_truth(atoms)
        effective = semantic_effective_exponent(atoms)
        expected = frozenset(p for p in LAWS if effective % law_order(p) == 0)
        assert actual == expected
        formulas.append((atoms, actual, effective))
        semantic_classes.setdefault(actual, []).append(atoms)

    assert len(formulas) == 16
    assert len(semantic_classes) == 4
    assert sorted(len(s) for s in semantic_classes) == [1, 9, 16, 36]

    # The two decisive Q29 witnesses are separated in opposite directions.
    assert E2 in truth[2] and E3 not in truth[2]
    assert E3 in truth[3] and E2 not in truth[3]

    discriminator_classes = {
        ts for ts in semantic_classes if ((E2 in ts) != (E3 in ts))
    }
    assert discriminator_classes == {truth[2], truth[3]}

    # Each discriminator class has a one-atom minimal representative.
    assert semantic_classes[truth[2]] == [(2,), (2, 6)]
    assert semantic_classes[truth[3]] == [(3,), (3, 6)]
    empty_truth = formula_truth(())
    assert E2 in empty_truth and E3 in empty_truth

    # No least discriminator exists in the implication poset: the two minimal
    # truth sets are incomparable. They overlap only at identity and 12
    # order-6 witnesses satisfy neither, so this is not a complementary split.
    assert not truth[2].issubset(truth[3])
    assert not truth[3].issubset(truth[2])
    assert len(truth[2] & truth[3]) == 1
    assert len(set(LAWS) - truth[2] - truth[3]) == 12
    assert E6 not in truth[2] and E6 not in truth[3]

    # Typed-conjugacy invariance, checked exhaustively in the witness universe.
    conjugacy_checks = 0
    for c in LAWS:
        for p in LAWS:
            q = conjugate(c, p)
            assert q in LAWS
            assert law_order(q) == law_order(p)
            for d in DIVISORS:
                assert exp_clause(q, d) == exp_clause(p, d)
                conjugacy_checks += 1
    assert conjugacy_checks == 5184

    print(
        "PASS P000_Q31_EXTENSION_REAUDIT "
        "laws=36 order1=1 order2=15 order3=8 order6=12 "
        "exp1=1 exp2=16 exp3=9 exp6=36 "
        "formulas=16 semantic_classes=4 gcd_normal_form=PASS "
        "separator_antichain=EXP2|EXP3 intersection=1 neither=12 "
        "conjugacy_checks=5184 "
        "terminal=NO_CANONICAL_MINIMAL_ROTATION_EXTENSION_CLAUSE_ON_DECLARED_LANGUAGE"
    )


if __name__ == "__main__":
    main()
