"""Adaptive acquisition calculus for finite A2 precision tasks.

The target partition describes the final answer. A finite query language
describes the primitive observations allowed while acquiring it. On a current
compatible block C, a query with r realized answers costs the least integer
base-B symbol depth L_B(r).

The module separates final answer precision, the eager language-safe quotient
preserving every allowed query, one chosen decision tree's terminal transcript
partition, and adaptive/ordered/stage-synchronous acquisition costs.
"""

from __future__ import annotations

from collections.abc import Hashable, Iterable, Mapping, Sequence
from functools import lru_cache
from itertools import permutations
from math import comb
from typing import TypeAlias

State = Hashable
Partition: TypeAlias = Mapping[State, Hashable]
QueryFamily: TypeAlias = Mapping[str, Partition]


def _domain(states: Iterable[State]) -> tuple[State, ...]:
    domain = tuple(states)
    if not domain:
        raise ValueError("state domain must be nonempty")
    if len(domain) != len(set(domain)):
        raise ValueError("state domain must contain distinct states")
    return domain


def _validate(domain: tuple[State, ...], partition: Partition) -> None:
    if set(partition) != set(domain):
        raise ValueError("partition must label every state exactly once")


def _queries(domain: tuple[State, ...], queries: QueryFamily) -> dict[str, Partition]:
    family = dict(queries)
    for name, query in family.items():
        if not isinstance(name, str) or not name:
            raise ValueError("query names must be nonempty strings")
        _validate(domain, query)
    return family


def integer_symbol_depth(value: int, base: int = 2) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < 1:
        raise ValueError("value must be a positive integer")
    if isinstance(base, bool) or not isinstance(base, int) or base < 2:
        raise ValueError("base must be an integer >=2")
    depth = 0
    capacity = 1
    while capacity < value:
        capacity *= base
        depth += 1
    return depth


def class_count(states: Iterable[State], partition: Partition) -> int:
    domain = _domain(states)
    _validate(domain, partition)
    return len({partition[state] for state in domain})


def query_signature_partition(
    states: Iterable[State], queries: QueryFamily
) -> dict[State, tuple[Hashable, ...]]:
    """Common refinement generated by all primitive queries."""
    domain = _domain(states)
    family = _queries(domain, queries)
    names = tuple(sorted(family))
    return {state: tuple(family[name][state] for name in names) for state in domain}


def language_safe_partition(
    states: Iterable[State], target: Partition, queries: QueryFamily
) -> dict[State, tuple[Hashable, ...]]:
    """Coarsest static quotient preserving target and every allowed query."""
    domain = _domain(states)
    _validate(domain, target)
    query_signature = query_signature_partition(domain, queries)
    return {state: (target[state], *query_signature[state]) for state in domain}


def queries_descend_to_target(
    states: Iterable[State], target: Partition, queries: QueryFamily
) -> bool:
    """Whether every primitive query is constant on each target block."""
    domain = _domain(states)
    _validate(domain, target)
    family = _queries(domain, queries)
    for query in family.values():
        values: dict[Hashable, Hashable] = {}
        for state in domain:
            key = target[state]
            value = query[state]
            if key in values and values[key] != value:
                return False
            values[key] = value
    return True


def _target_constant(block: frozenset[State], target: Partition) -> bool:
    return len({target[state] for state in block}) <= 1


def _children(
    block: frozenset[State], query: Partition
) -> dict[Hashable, frozenset[State]]:
    result: dict[Hashable, set[State]] = {}
    for state in block:
        result.setdefault(query[state], set()).add(state)
    return {value: frozenset(states) for value, states in result.items()}


def optimal_adaptive_acquisition(
    states: Iterable[State],
    target: Partition,
    queries: QueryFamily,
    base: int = 2,
) -> dict[str, object]:
    """Exact Bellman optimum for unrestricted adaptive query order."""
    domain = _domain(states)
    _validate(domain, target)
    family = _queries(domain, queries)
    all_names = frozenset(family)

    @lru_cache(maxsize=None)
    def solve(
        block: frozenset[State], remaining: frozenset[str]
    ) -> tuple[int | None, str | None]:
        if _target_constant(block, target):
            return 0, None
        best: tuple[int, str] | None = None
        for name in sorted(remaining):
            children = _children(block, family[name])
            if len(children) <= 1:
                continue
            next_remaining = remaining - {name}
            tails: list[int] = []
            for child in children.values():
                tail, _ = solve(child, next_remaining)
                if tail is None:
                    break
                tails.append(tail)
            else:
                candidate = integer_symbol_depth(len(children), base) + max(tails)
                pair = (candidate, name)
                if best is None or pair < best:
                    best = pair
        if best is None:
            return None, None
        return best

    minimum, first = solve(frozenset(domain), all_names)
    target_count = class_count(domain, target)
    target_depth = integer_symbol_depth(target_count, base)
    language = language_safe_partition(domain, target, family)
    language_count = class_count(domain, language)

    if minimum is None:
        return {
            "solvable": False,
            "minimum_symbol_depth": None,
            "first_query": None,
            "target_class_count": target_count,
            "target_storage_depth": target_depth,
            "language_safe_class_count": language_count,
        }

    transcripts: dict[State, tuple[tuple[str, Hashable], ...]] = {}
    leaf_costs: dict[State, int] = {}

    def traverse(
        block: frozenset[State],
        remaining: frozenset[str],
        transcript: tuple[tuple[str, Hashable], ...],
        spent: int,
    ) -> None:
        tail, name = solve(block, remaining)
        if tail == 0 and name is None:
            for state in block:
                transcripts[state] = transcript
                leaf_costs[state] = spent
            return
        if tail is None or name is None:
            raise AssertionError("stored optimal policy became infeasible")
        children = _children(block, family[name])
        step = integer_symbol_depth(len(children), base)
        for answer, child in children.items():
            traverse(
                child,
                remaining - {name},
                (*transcript, (name, answer)),
                spent + step,
            )

    traverse(frozenset(domain), all_names, (), 0)
    if max(leaf_costs.values()) != minimum:
        raise AssertionError("reconstructed strategy disagreed with Bellman optimum")

    transcript_count = len(set(transcripts.values()))
    if not target_count <= transcript_count <= language_count:
        raise AssertionError("answer/transcript/language class hierarchy failed")

    by_target: dict[Hashable, set[tuple[tuple[str, Hashable], ...]]] = {}
    for state in domain:
        by_target.setdefault(target[state], set()).add(transcripts[state])
    proof_sizes = tuple(sorted((len(values) for values in by_target.values()), reverse=True))
    maximum = max(proof_sizes)
    proof_spectrum = tuple(
        sum(comb(size, order) for size in proof_sizes)
        for order in range(1, maximum + 1)
    )

    transcript_depth = integer_symbol_depth(transcript_count, base)
    if not target_depth <= transcript_depth <= minimum:
        raise AssertionError("storage/transcript/acquisition depth hierarchy failed")

    return {
        "solvable": True,
        "minimum_symbol_depth": minimum,
        "first_query": first,
        "target_class_count": target_count,
        "target_storage_depth": target_depth,
        "language_safe_class_count": language_count,
        "transcript_class_count": transcript_count,
        "transcript_depth": transcript_depth,
        "tree_packing_slack": minimum - transcript_depth,
        "transcript_multiplicity_slack": transcript_depth - target_depth,
        "total_acquisition_slack": minimum - target_depth,
        "proof_multiplicities": proof_sizes,
        "proof_repair_spectrum": proof_spectrum,
        "transcripts": transcripts,
        "leaf_costs": leaf_costs,
    }


def fixed_order_interactive_cost(
    states: Iterable[State],
    target: Partition,
    queries: QueryFamily,
    order: Sequence[str],
    base: int = 2,
) -> int | None:
    """Worst branch-local cost under one global query order, with local skips."""
    domain = _domain(states)
    _validate(domain, target)
    family = _queries(domain, queries)
    sequence = tuple(order)
    if len(sequence) != len(family) or set(sequence) != set(family):
        raise ValueError("order must contain every query exactly once")

    @lru_cache(maxsize=None)
    def solve(block: frozenset[State], index: int) -> int | None:
        if _target_constant(block, target):
            return 0
        if index == len(sequence):
            return None
        best = solve(block, index + 1)
        children = _children(block, family[sequence[index]])
        if len(children) > 1:
            tails: list[int] = []
            for child in children.values():
                tail = solve(child, index + 1)
                if tail is None:
                    break
                tails.append(tail)
            else:
                candidate = integer_symbol_depth(len(children), base) + max(tails)
                if best is None or candidate < best:
                    best = candidate
        return best

    return solve(frozenset(domain), 0)


def optimal_fixed_order_interactive(
    states: Iterable[State],
    target: Partition,
    queries: QueryFamily,
    base: int = 2,
) -> dict[str, object]:
    domain = _domain(states)
    _validate(domain, target)
    family = _queries(domain, queries)
    best: tuple[int, tuple[str, ...]] | None = None
    for order in permutations(sorted(family)):
        cost = fixed_order_interactive_cost(domain, target, family, order, base)
        if cost is None:
            continue
        candidate = (cost, order)
        if best is None or candidate < best:
            best = candidate
    if best is None:
        return {"solvable": False, "minimum_symbol_depth": None, "order": None}
    return {"solvable": True, "minimum_symbol_depth": best[0], "order": best[1]}


def stage_synchronous_order_cost(
    states: Iterable[State],
    target: Partition,
    queries: QueryFamily,
    order: Sequence[str],
    base: int = 2,
) -> int | None:
    """Cost when one query stage is applied to every unresolved context."""
    domain = _domain(states)
    _validate(domain, target)
    family = _queries(domain, queries)
    sequence = tuple(order)
    if len(sequence) != len(family) or set(sequence) != set(family):
        raise ValueError("order must contain every query exactly once")

    def canonical(blocks: Iterable[frozenset[State]]) -> tuple[tuple[State, ...], ...]:
        unresolved = [
            tuple(sorted(block, key=repr))
            for block in blocks
            if not _target_constant(block, target)
        ]
        return tuple(sorted(unresolved, key=repr))

    @lru_cache(maxsize=None)
    def solve(
        encoded_blocks: tuple[tuple[State, ...], ...], index: int
    ) -> int | None:
        if not encoded_blocks:
            return 0
        if index == len(sequence):
            return None
        blocks = [frozenset(block) for block in encoded_blocks]
        best = solve(encoded_blocks, index + 1)
        query = family[sequence[index]]
        maximum_answers = 1
        next_blocks: list[frozenset[State]] = []
        for block in blocks:
            children = _children(block, query)
            maximum_answers = max(maximum_answers, len(children))
            next_blocks.extend(children.values())
        if maximum_answers > 1:
            tail = solve(canonical(next_blocks), index + 1)
            if tail is not None:
                candidate = integer_symbol_depth(maximum_answers, base) + tail
                if best is None or candidate < best:
                    best = candidate
        return best

    return solve(canonical([frozenset(domain)]), 0)


def optimal_stage_synchronous(
    states: Iterable[State],
    target: Partition,
    queries: QueryFamily,
    base: int = 2,
) -> dict[str, object]:
    domain = _domain(states)
    _validate(domain, target)
    family = _queries(domain, queries)
    best: tuple[int, tuple[str, ...]] | None = None
    for order in permutations(sorted(family)):
        cost = stage_synchronous_order_cost(domain, target, family, order, base)
        if cost is None:
            continue
        candidate = (cost, order)
        if best is None or candidate < best:
            best = candidate
    if best is None:
        return {"solvable": False, "minimum_symbol_depth": None, "order": None}
    return {"solvable": True, "minimum_symbol_depth": best[0], "order": best[1]}


def power_capacity_tight_tree_exists(
    states: Iterable[State],
    target: Partition,
    queries: QueryFamily,
    base: int = 2,
) -> bool:
    """Balanced-split criterion when the target has exactly B^d classes."""
    domain = _domain(states)
    _validate(domain, target)
    family = _queries(domain, queries)
    if not queries_descend_to_target(domain, target, family):
        raise ValueError("criterion requires target-descending queries")

    def exact_power(value: int) -> int | None:
        depth = integer_symbol_depth(value, base)
        return depth if base**depth == value else None

    @lru_cache(maxsize=None)
    def solve(block: frozenset[State], remaining: frozenset[str]) -> bool:
        depth = exact_power(len({target[state] for state in block}))
        if depth is None:
            return False
        if depth == 0:
            return True
        for name in sorted(remaining):
            children = _children(block, family[name])
            if len(children) <= 1:
                continue
            step = integer_symbol_depth(len(children), base)
            if len(children) != base**step or step > depth:
                continue
            target_capacity = base ** (depth - step)
            if any(
                len({target[state] for state in child}) != target_capacity
                for child in children.values()
            ):
                continue
            if all(solve(child, remaining - {name}) for child in children.values()):
                return True
        return False

    return solve(frozenset(domain), frozenset(family))


def product_acquisition_system(
    left_states: Iterable[State],
    left_target: Partition,
    left_queries: QueryFamily,
    right_states: Iterable[State],
    right_target: Partition,
    right_queries: QueryFamily,
) -> tuple[
    tuple[tuple[State, State], ...],
    dict[tuple[State, State], tuple[Hashable, Hashable]],
    dict[str, dict[tuple[State, State], Hashable]],
]:
    """Cartesian product with component-local query languages."""
    left = _domain(left_states)
    right = _domain(right_states)
    _validate(left, left_target)
    _validate(right, right_target)
    lq = _queries(left, left_queries)
    rq = _queries(right, right_queries)
    states = tuple((x, y) for x in left for y in right)
    target = {(x, y): (left_target[x], right_target[y]) for x, y in states}
    queries: dict[str, dict[tuple[State, State], Hashable]] = {}
    for name, query in lq.items():
        queries[f"L:{name}"] = {(x, y): query[x] for x, y in states}
    for name, query in rq.items():
        queries[f"R:{name}"] = {(x, y): query[y] for x, y in states}
    return states, target, queries


def four_bit_order_separation_witness():
    states = tuple(range(16))
    queries = {
        f"x{index}": {state: (state >> index) & 1 for state in states}
        for index in range(4)
    }
    table = (1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0)
    target = {state: table[state] for state in states}
    return states, target, queries


def four_state_storage_gap_witness():
    states = tuple(range(4))
    queries = {
        "A": {0: 0, 1: 0, 2: 0, 3: 1},
        "B": {0: 0, 1: 0, 2: 1, 3: 0},
        "C": {0: 0, 1: 1, 2: 0, 3: 0},
    }
    target = {
        state: tuple(queries[name][state] for name in ("A", "B", "C"))
        for state in states
    }
    return states, target, queries


def eight_state_stage_gap_witness():
    states = tuple(range(8))
    queries = {
        "A": {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 5, 7: 5},
        "B": {0: 0, 1: 1, 2: 1, 3: 1, 4: 2, 5: 3, 6: 4, 7: 5},
        "C": {0: 0, 1: 0, 2: 0, 3: 0, 4: 1, 5: 1, 6: 1, 7: 1},
    }
    target = {
        state: tuple(queries[name][state] for name in ("A", "B", "C"))
        for state in states
    }
    return states, target, queries


def four_state_process_precision_witness():
    states = tuple(range(4))
    target = {0: 0, 1: 0, 2: 1, 3: 1}
    queries = {
        "Q1": {0: 0, 1: 1, 2: 0, 3: 1},
        "Q2": {0: 0, 1: 1, 2: 1, 3: 0},
    }
    return states, target, queries
