"""Full-product independence normal form for finite A2 task families."""

from __future__ import annotations

from collections.abc import Hashable, Iterable, Mapping, Sequence
from typing import TypeAlias

from .a2_precision_incidence import (
    block_count,
    common_refinement,
    directed_repair_factor,
    formal_joint_candidate_count,
    realized_joint_class_count,
)

State = Hashable
Partition: TypeAlias = Mapping[State, Hashable]


def _domain(states: Iterable[State]) -> tuple[State, ...]:
    domain = tuple(states)
    if not domain:
        raise ValueError("state domain must be nonempty")
    if len(domain) != len(set(domain)):
        raise ValueError("state domain must contain distinct states")
    return domain


def full_incidence_independent(
    states: Iterable[State], partitions: Sequence[Partition]
) -> bool:
    """Whether every formal tuple of task blocks is realized."""
    domain = _domain(states)
    family = tuple(partitions)
    if not family:
        raise ValueError("at least one partition is required")
    return realized_joint_class_count(domain, family) == formal_joint_candidate_count(
        domain, family
    )


def subset_joint_partition(
    states: Iterable[State],
    partitions: Sequence[Partition],
    indices: Iterable[int],
) -> dict[State, Hashable]:
    """Joint partition generated by a coordinate subset."""
    domain = _domain(states)
    family = tuple(partitions)
    chosen = tuple(indices)
    if any(index < 0 or index >= len(family) for index in chosen):
        raise ValueError("subset index outside partition family")
    if not chosen:
        return {state: () for state in domain}
    return common_refinement(domain, [family[index] for index in chosen])


def full_independence_repair_formula(
    states: Iterable[State],
    partitions: Sequence[Partition],
    known_indices: Iterable[int],
    added_indices: Iterable[int],
) -> dict[str, int | bool]:
    """Exact product repair factor under full-incidence independence."""
    domain = _domain(states)
    family = tuple(partitions)
    if not full_incidence_independent(domain, family):
        raise ValueError("family is not full-incidence independent")
    known = frozenset(known_indices)
    added = frozenset(added_indices)
    known_partition = subset_joint_partition(domain, family, known)
    added_partition = subset_joint_partition(domain, family, added)

    expected = 1
    for index in added - known:
        expected *= block_count(domain, family[index])

    actual = directed_repair_factor(domain, known_partition, added_partition)
    if actual != expected:
        raise AssertionError("full-incidence repair product formula failed")
    return {"actual": actual, "expected": expected, "holds": True}
