"""Apéry-semigroup compression of high-dimensional block access in P025.

Let ``b=(b_1,...,b_d)`` be a positive primitive integer coefficient row and

    kappa_b(N) = min { ||x||_infinity : b*x = N, x in Z^d }.

Writing ``P=sum(b_i)`` and fixing a candidate radius ``r``, the change of
variables

    y_i = r - x_i

turns the signed access problem into

    b*y = r*P - N,     0 <= y_i <= 2r.

Thus the eventual access response is controlled by the numerical semigroup
``S=<b_1,...,b_d>``.  For each residue modulo ``P``, its Apéry element and the
minimum non-negative L-infinity factorization radius of that Apéry element give
an exact first target after which

    kappa_b(N+P) = kappa_b(N) + 1.

Numerical semigroups, Apéry sets, and asymptotic/extremal L-infinity
factorization length are established mathematics.  This module is a project
specialization that exposes the exact signed-access -> Apéry-defect bridge; it
does not claim the general semigroup theory as new.
"""

from __future__ import annotations

from dataclasses import dataclass
from heapq import heappop, heappush
from math import gcd


@dataclass(frozen=True)
class AperyAccessResidue:
    """Exact eventual-access data for one target residue modulo ``period``."""

    target_residue: int
    defect_residue: int
    apery_value: int
    apery_min_linf: int
    required_access_radius: int
    first_stable_target: int


@dataclass(frozen=True)
class AperyAccessProfile:
    """Finite residue profile controlling eventual block-access response."""

    coefficients: tuple[int, ...]
    period: int
    residues: tuple[AperyAccessResidue, ...]
    exceptional_targets: tuple[int, ...]


def _require_positive_row(coefficients: tuple[int, ...]) -> None:
    if not coefficients:
        raise ValueError("coefficient row must be nonempty")
    for coefficient in coefficients:
        if (
            isinstance(coefficient, bool)
            or not isinstance(coefficient, int)
            or coefficient <= 0
        ):
            raise ValueError("coefficients must be positive integers")


def primitive_positive_row(coefficients: tuple[int, ...]) -> tuple[tuple[int, ...], int]:
    """Return the primitive row and removed positive gcd scale."""
    _require_positive_row(coefficients)
    scale = 0
    for coefficient in coefficients:
        scale = gcd(scale, coefficient)
    if scale <= 0:
        raise AssertionError("positive row must have positive gcd")
    primitive = tuple(coefficient // scale for coefficient in coefficients)
    return primitive, scale


def _bounded_nonnegative_reachable(
    coefficients: tuple[int, ...], target: int, radius: int
) -> bool:
    """Decide whether ``sum b_i*y_i=target`` with ``0<=y_i<=radius``."""
    if target < 0:
        return False
    reachable = {0}
    for coefficient in coefficients:
        next_reachable: set[int] = set()
        for subtotal in reachable:
            max_count = min(radius, (target - subtotal) // coefficient)
            for count in range(max_count + 1):
                next_reachable.add(subtotal + count * coefficient)
        reachable = next_reachable
        if target in reachable:
            # Later coordinates may all be zero, so early success is exact.
            return True
    return target in reachable


def minimum_nonnegative_linf_factorization(
    coefficients: tuple[int, ...], target: int
) -> int:
    """Return ``min max(y_i)`` over nonnegative factorizations of ``target``.

    Raises ``ValueError`` when ``target`` is not in the numerical semigroup
    generated by the coefficient row.
    """
    primitive, scale = primitive_positive_row(coefficients)
    if isinstance(target, bool) or not isinstance(target, int) or target < 0:
        raise ValueError("target must be a non-negative integer")
    if target % scale:
        raise ValueError("target is outside the coefficient image")
    reduced_target = target // scale
    if reduced_target == 0:
        return 0

    lower = (reduced_target + sum(primitive) - 1) // sum(primitive)
    upper = reduced_target // min(primitive)
    if upper < lower:
        raise ValueError("target is outside the numerical semigroup")

    lo = lower
    hi = upper
    if not _bounded_nonnegative_reachable(primitive, reduced_target, hi):
        raise ValueError("target is outside the numerical semigroup")
    while lo < hi:
        mid = (lo + hi) // 2
        if _bounded_nonnegative_reachable(primitive, reduced_target, mid):
            hi = mid
        else:
            lo = mid + 1
    return lo


def apery_values(coefficients: tuple[int, ...]) -> tuple[int, ...]:
    """Return ``Ap(S;P)`` where ``S=<b_i>`` and ``P=sum(b_i)``.

    Entry ``j`` is the smallest semigroup element congruent to ``j mod P``.
    The primitive row is used, so ``gcd(b_i)=1`` and every residue is reached.
    """
    primitive, _scale = primitive_positive_row(coefficients)
    period = sum(primitive)
    distances: list[int | None] = [None] * period
    distances[0] = 0
    queue: list[tuple[int, int]] = [(0, 0)]

    while queue:
        value, residue = heappop(queue)
        if distances[residue] != value:
            continue
        for coefficient in primitive:
            candidate = value + coefficient
            next_residue = candidate % period
            current = distances[next_residue]
            if current is None or candidate < current:
                distances[next_residue] = candidate
                heappush(queue, (candidate, next_residue))

    if any(value is None for value in distances):
        raise AssertionError("primitive numerical semigroup failed to reach a residue")
    return tuple(int(value) for value in distances)


def _first_target_in_residue_at_least(residue: int, period: int, threshold: int) -> int:
    if threshold <= residue:
        return residue
    steps = (threshold - residue + period - 1) // period
    return residue + steps * period


def apery_access_profile(coefficients: tuple[int, ...]) -> AperyAccessProfile:
    """Build the exact finite eventual-access profile for a positive row.

    If ``a_j`` is the Apéry element in defect residue ``j`` and ``L_j`` is its
    minimum non-negative L-infinity factorization radius, then a target ``N``
    with ``-N == j (mod P)`` reaches the Apéry defect at access radius

        r_0 = (N + a_j) / P.

    This is feasible exactly when ``2*r_0 >= L_j``.  The first target in that
    residue satisfying the inequality is recorded as ``first_stable_target``.
    From that target onward,

        kappa(N) = (N + a_j)/P

    and the period shift adds exactly one to access radius.
    """
    primitive, _scale = primitive_positive_row(coefficients)
    period = sum(primitive)
    apery = apery_values(primitive)
    residue_records: list[AperyAccessResidue] = []
    exceptions: list[int] = []

    for defect_residue, apery_value in enumerate(apery):
        min_linf = minimum_nonnegative_linf_factorization(primitive, apery_value)
        required_radius = (min_linf + 1) // 2
        target_residue = (-defect_residue) % period
        raw_threshold = period * required_radius - apery_value
        first_stable = _first_target_in_residue_at_least(
            target_residue, period, raw_threshold
        )
        residue_records.append(
            AperyAccessResidue(
                target_residue=target_residue,
                defect_residue=defect_residue,
                apery_value=apery_value,
                apery_min_linf=min_linf,
                required_access_radius=required_radius,
                first_stable_target=first_stable,
            )
        )
        exceptions.extend(range(target_residue, first_stable, period))

    residue_records.sort(key=lambda record: record.target_residue)
    return AperyAccessProfile(
        coefficients=primitive,
        period=period,
        residues=tuple(residue_records),
        exceptional_targets=tuple(sorted(set(exceptions))),
    )


def exact_block_access_radius(
    coefficients: tuple[int, ...], target: int, *, max_radius: int = 100_000
) -> int:
    """Return the exact signed L-infinity preimage radius by finite search.

    This is a reference oracle.  The Apéry profile should be used for the
    eventual closed response rather than repeatedly scanning radii.
    """
    primitive, scale = primitive_positive_row(coefficients)
    if isinstance(target, bool) or not isinstance(target, int):
        raise ValueError("target must be an integer")
    if target % scale:
        raise ValueError("target is outside the coefficient image")
    reduced_target = abs(target // scale)
    if reduced_target == 0:
        return 0
    if (
        isinstance(max_radius, bool)
        or not isinstance(max_radius, int)
        or max_radius < 0
    ):
        raise ValueError("max_radius must be a non-negative integer")

    period = sum(primitive)
    lower = (reduced_target + period - 1) // period
    for radius in range(lower, max_radius + 1):
        defect = radius * period - reduced_target
        if defect < 0:
            continue
        if _bounded_nonnegative_reachable(primitive, defect, 2 * radius):
            return radius
    raise ValueError("exact block access exceeds max_radius")


def eventual_block_access_radius(
    coefficients: tuple[int, ...], target: int
) -> int:
    """Return the closed Apéry access formula once the target is in its stable tail."""
    primitive, scale = primitive_positive_row(coefficients)
    if isinstance(target, bool) or not isinstance(target, int):
        raise ValueError("target must be an integer")
    if target % scale:
        raise ValueError("target is outside the coefficient image")
    reduced_target = abs(target // scale)
    profile = apery_access_profile(primitive)
    record = next(
        item
        for item in profile.residues
        if item.target_residue == reduced_target % profile.period
    )
    if reduced_target < record.first_stable_target:
        raise ValueError("target lies in the finite preperiod of its residue class")
    numerator = reduced_target + record.apery_value
    if numerator % profile.period:
        raise AssertionError("Apéry residue failed to close the period")
    radius = numerator // profile.period
    if radius < record.required_access_radius:
        raise AssertionError("stable Apéry target failed factorization-capacity condition")
    return radius


def eventual_period_shift_holds(
    coefficients: tuple[int, ...], target: int
) -> bool:
    """Verify ``kappa(N+P)=kappa(N)+1`` on an Apéry-stable target."""
    primitive, scale = primitive_positive_row(coefficients)
    if target % scale:
        raise ValueError("target is outside the coefficient image")
    reduced_target = abs(target // scale)
    current = eventual_block_access_radius(primitive, reduced_target)
    future = eventual_block_access_radius(primitive, reduced_target + sum(primitive))
    if future != current + 1:
        raise AssertionError("eventual block-access period shift failed")
    return True


def access_defect_transform(
    coefficients: tuple[int, ...], target: int, vector: tuple[int, ...]
) -> dict[str, object]:
    """Expose the exact signed-access -> nonnegative-semigroup change of variables."""
    primitive, scale = primitive_positive_row(coefficients)
    if len(vector) != len(primitive):
        raise ValueError("vector dimension must match coefficient row")
    if target % scale:
        raise ValueError("target is outside the coefficient image")
    reduced_target = target // scale
    if sum(a * x for a, x in zip(primitive, vector, strict=True)) != reduced_target:
        raise ValueError("vector does not realize target")
    radius = max(abs(x) for x in vector)
    nonnegative = tuple(radius - x for x in vector)
    defect = radius * sum(primitive) - reduced_target
    if any(value < 0 or value > 2 * radius for value in nonnegative):
        raise AssertionError("defect transform escaped [0,2r]^d")
    if sum(a * y for a, y in zip(primitive, nonnegative, strict=True)) != defect:
        raise AssertionError("defect transform failed coefficient identity")
    return {
        "radius": radius,
        "period": sum(primitive),
        "defect": defect,
        "nonnegative_coordinates": nonnegative,
    }
