"""Geometric access cost to the arithmetic absorption floor in P025.

P025 distinguishes the first radius containing any non-degenerate witness from
the first radius containing a witness that attains the minimum possible
Wronskian absorption redundancy.  Their difference is an exact finite search
cost.  Rank-one witness lattices admit a closed classification.
"""

from __future__ import annotations

from .abc_witness_absorption import (
    certified_absorption_pareto_frontier,
    minimum_absorption_redundancy,
    witness_absorption_redundancy,
)
from .abc_witness_precision import (
    additive_relation_vector,
    bounded_nondegenerate_witnesses,
    minimal_witness_cost,
    witness_coordinates,
)


def absorption_optimal_radius(
    a: int,
    b: int,
    c: int,
    *,
    max_bound: int = 32,
    state_cap: int = 2_000_000,
) -> int:
    """Return the first L-infinity radius attaining ``eta_min`` exactly."""
    if isinstance(max_bound, bool) or not isinstance(max_bound, int) or max_bound < 1:
        raise ValueError("max_bound must be a positive integer")
    eta_floor = minimum_absorption_redundancy(a, b, c)
    for bound in range(1, max_bound + 1):
        witnesses = bounded_nondegenerate_witnesses(
            a, b, c, bound, state_cap=state_cap
        )
        if any(
            witness_absorption_redundancy(a, b, c, vector) == eta_floor
            for vector in witnesses
        ):
            return bound
    raise ValueError("absorption-optimal witness not found within max_bound")


def absorption_access_delay(
    a: int,
    b: int,
    c: int,
    *,
    max_bound: int = 32,
    state_cap: int = 2_000_000,
) -> int:
    """Return ``nu-mu``: extra radius needed to attain optimal absorption."""
    mu = minimal_witness_cost(a, b, c, max_bound=max_bound, state_cap=state_cap)
    nu = absorption_optimal_radius(
        a, b, c, max_bound=max_bound, state_cap=state_cap
    )
    if nu < mu:
        raise AssertionError("optimal-absorption radius cannot precede first witness radius")
    return nu - mu


def scalar_witness_cost_is_complete_for_two_cost_frontier(
    a: int,
    b: int,
    c: int,
    *,
    max_bound: int = 32,
    state_cap: int = 2_000_000,
) -> bool:
    """Return whether one witness simultaneously minimizes radius and absorption.

    This is equivalent to ``nu=mu`` and to the absorption-aware Pareto frontier
    containing exactly one point.
    """
    mu = minimal_witness_cost(a, b, c, max_bound=max_bound, state_cap=state_cap)
    nu = absorption_optimal_radius(
        a, b, c, max_bound=max_bound, state_cap=state_cap
    )
    frontier = certified_absorption_pareto_frontier(
        a, b, c, max_bound=max_bound, state_cap=state_cap
    )
    equivalent = (mu == nu) == (len(frontier) == 1)
    if not equivalent:
        raise AssertionError("delay-zero and singleton-frontier criteria disagree")
    return mu == nu


def rank_one_witness_ray(a: int, b: int, c: int) -> dict[str, object]:
    """Classify the complete witness-cost geometry when ``omega(abc)=2``.

    If the primitive additive normal is ``alpha=(u,v)``, then
    ``ker_Z(alpha)`` is generated by ``t=(v,-u)``.  Every non-zero witness is
    an integer multiple of ``t`` because the Wronskian degeneracy sublattice is
    proper.  Hence both L-infinity norm and absorption redundancy scale by the
    same positive multiplier, so the Pareto frontier is the singleton
    ``(max(|u|,|v|), eta_min)``.
    """
    coordinates = witness_coordinates(a, b, c)
    if len(coordinates) != 2:
        raise ValueError("rank-one witness ray requires exactly two prime coordinates")
    alpha = additive_relation_vector(a, b, c)
    u, v = alpha
    generator = (v, -u)
    mu_closed = max(abs(u), abs(v))
    eta_floor = minimum_absorption_redundancy(a, b, c)
    generator_eta = witness_absorption_redundancy(a, b, c, generator)
    if generator_eta != eta_floor:
        # Global sign of the generator is irrelevant; failure would contradict
        # the determinantal-divisor image calculation.
        raise AssertionError("primitive kernel generator must attain eta_min")
    frontier = certified_absorption_pareto_frontier(
        a, b, c, max_bound=max(mu_closed, 1)
    )
    expected_frontier = ((mu_closed, eta_floor),)
    if frontier != expected_frontier:
        raise AssertionError("rank-one witness frontier must be a single ray minimum")
    return {
        "coordinates": coordinates,
        "primitive_additive_normal": alpha,
        "primitive_kernel_generator": generator,
        "minimum_witness_radius": mu_closed,
        "minimum_absorption_redundancy": eta_floor,
        "absorption_optimal_radius": mu_closed,
        "absorption_access_delay": 0,
        "pareto_frontier": expected_frontier,
    }


def genuine_tradeoff_requires_three_prime_coordinates(
    a: int,
    b: int,
    c: int,
    *,
    max_bound: int = 32,
    state_cap: int = 2_000_000,
) -> bool:
    """Check the exact necessary condition for a multi-point cost frontier.

    A multi-point frontier implies at least three distinct prime coordinates.
    The converse is false in general.
    """
    frontier = certified_absorption_pareto_frontier(
        a, b, c, max_bound=max_bound, state_cap=state_cap
    )
    if len(frontier) > 1 and len(witness_coordinates(a, b, c)) < 3:
        raise AssertionError("rank-one witness lattice cannot support a genuine tradeoff")
    return len(frontier) <= 1 or len(witness_coordinates(a, b, c)) >= 3
