"""Exact word distances generated by Z/A/D causal primitive event grammars.

No norm is taken as primitive.  Distance is the minimum number of primitive
causal events needed to transform one state into another.

* Z grammar, events +/-e_i: d_Z=sum |delta_i|.
* A grammar, events e_i-e_j on equal-total states: d_A=(1/2)sum |delta_i|.
* D grammar, events +/-e_i +/-e_j on equal-parity states:

      d_D=max(max_i |delta_i|, (1/2)sum_i |delta_i|).

For D, the two terms are obvious lower bounds: one event touches a coordinate at
most once and handles exactly two unit tokens.  They are jointly attainable.  If
no coordinate dominates, pair all target unit tokens across distinct coordinates.
If one coordinate dominates, pair it with every other token; the remaining even
number of dominant tokens are handled in cancelling auxiliary pairs
(+/-e_i+e_j)+(+/-e_i-e_j)=+/-2e_i.

The traditional L1/L-infinity formulas are shadows of these event grammars.
"""

from __future__ import annotations

State = tuple[int, ...]
Event = tuple[int, ...]


def _delta(left: State, right: State) -> tuple[int, ...]:
    if not isinstance(left, tuple) or not isinstance(right, tuple) or len(left) != len(right) or len(left) < 1:
        raise ValueError("states must be equal-length non-empty tuples")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in left + right):
        raise ValueError("state coordinates must be integers")
    return tuple(target - source for source, target in zip(left, right))


def z_word_distance(left: State, right: State) -> int:
    delta = _delta(left, right)
    return sum(abs(value) for value in delta)


def a_word_distance(left: State, right: State) -> int:
    delta = _delta(left, right)
    if sum(delta) != 0:
        raise ValueError("A transfer states must have equal total")
    l1 = sum(abs(value) for value in delta)
    if l1 % 2:
        raise AssertionError("zero-sum integer displacement has even L1")
    return l1 // 2


def d_word_distance(left: State, right: State) -> int:
    delta = _delta(left, right)
    if sum(delta) % 2 != 0:
        raise ValueError("D pair-event states must lie in the same total-parity sector")
    l1 = sum(abs(value) for value in delta)
    if l1 % 2:
        raise AssertionError("even-total-parity displacement has even L1")
    maximum = max((abs(value) for value in delta), default=0)
    return max(maximum, l1 // 2)


def _signed_token_lists(delta: tuple[int, ...]) -> list[list[int]]:
    # Return one signed unit marker per target coordinate unit.  Each marker is
    # represented simply by its coordinate index; target sign is read from delta.
    return [[index] * abs(value) for index, value in enumerate(delta) if value]


def d_canonical_event_program(left: State, right: State) -> tuple[Event, ...]:
    """Construct a minimum-length D primitive event program."""
    delta = _delta(left, right)
    if sum(delta) % 2:
        raise ValueError("states must have equal total parity")
    n = len(delta)
    if n < 2 and any(delta):
        raise ValueError("nontrivial D grammar needs at least two coordinates")
    counts = [abs(value) for value in delta]
    signs = [1 if value > 0 else -1 if value < 0 else 0 for value in delta]
    total = sum(counts)
    if total == 0:
        return ()

    events: list[Event] = []
    dominant = max(range(n), key=lambda index: counts[index])
    other_tokens = [
        index
        for index, count in enumerate(counts)
        if index != dominant
        for _ in range(count)
    ]

    if counts[dominant] > total // 2:
        # Pair every non-dominant token with one dominant token.
        for other in other_tokens:
            event = [0] * n
            event[dominant] = signs[dominant]
            event[other] = signs[other]
            events.append(tuple(event))
        remaining = counts[dominant] - len(other_tokens)
        if remaining % 2:
            raise AssertionError("parity guarantees an even dominant remainder")
        auxiliary = 0 if dominant != 0 else 1
        for _ in range(remaining // 2):
            first = [0] * n
            second = [0] * n
            first[dominant] = signs[dominant]
            second[dominant] = signs[dominant]
            first[auxiliary] = 1
            second[auxiliary] = -1
            events.extend((tuple(first), tuple(second)))
    else:
        # Greedily pair tokens from the two currently largest nonempty coordinate
        # piles.  The non-dominance condition guarantees no pile is stranded.
        remaining = counts[:]
        while sum(remaining):
            available = sorted(
                (index for index, count in enumerate(remaining) if count),
                key=lambda index: remaining[index],
                reverse=True,
            )
            if len(available) < 2:
                raise AssertionError("non-dominance must permit distinct-coordinate pairing")
            left_index, right_index = available[:2]
            event = [0] * n
            event[left_index] = signs[left_index]
            event[right_index] = signs[right_index]
            events.append(tuple(event))
            remaining[left_index] -= 1
            remaining[right_index] -= 1

    if len(events) != d_word_distance(left, right):
        raise AssertionError("constructed D program must attain the closed distance")
    return tuple(events)


def apply_event_program(state: State, events: tuple[Event, ...]) -> State:
    current = list(state)
    for event in events:
        if len(event) != len(current) or sum(value != 0 for value in event) != 2:
            raise ValueError("D primitive event must affect exactly two coordinates")
        if any(value not in (-1, 0, 1) for value in event):
            raise ValueError("D primitive event must be unit amplitude")
        current = [value + delta for value, delta in zip(current, event)]
    return tuple(current)
