"""Scalar Z local residue alphabets and their Lee/Euclidean grade shadow.

For an integer cell reduced modulo q, residue a has a minimum-absolute integer
representative of magnitude lambda_q(a)=min(a,q-a).  With square local grade the
minimum residue grade is lambda_q(a)^2.  The zero residue's minimum nonzero local
event is +/-q with grade q^2.

Thus q-ary code lift grades are generated by local integer representatives; the
traditional Lee/Euclidean symbol weight is a shadow of this minimization.  A
resonant scalar Construction-A primitive shell occurs when the minimum nonzero
code lift grade equals q^2.

For q=2 this reproduces the binary integer alphabet used for E7/E8.  For q=3,
the scalar alphabet has base grade 9 and nonzero residue grade 1, so the ternary
[3,1,3] repetition code is code-dominated at grade three and produces only two
minimum code lifts.  Replacing the scalar cell by a hex/A2 local alphabet lowers
the base grade to three and raises nonzero lift multiplicity to three, creating
the E6 grade resonance.  Hence the code alone does not determine geometry.
"""

from __future__ import annotations

from .causal_local_alphabet_code import (
    LocalResidueAlphabet,
    primitive_grade_and_multiplicity,
    primitive_grade_regime,
    ternary_repetition_3_code,
)


def nearest_residue_magnitude(residue: int, modulus: int) -> int:
    if isinstance(modulus, bool) or not isinstance(modulus, int) or modulus < 2:
        raise ValueError("modulus must be at least two")
    residue %= modulus
    return min(residue, modulus - residue)


def scalar_residue_minimum_multiplicity(residue: int, modulus: int) -> int:
    residue %= modulus
    if residue == 0:
        return 1
    # Only the halfway residue of an even modulus has two equally short signed
    # representatives +q/2 and -q/2 in the same residue class.
    return 2 if modulus % 2 == 0 and residue == modulus // 2 else 1


def scalar_integer_residue_alphabet(modulus: int) -> LocalResidueAlphabet:
    if isinstance(modulus, bool) or not isinstance(modulus, int) or modulus < 2:
        raise ValueError("modulus must be at least two")
    grades = {0: 0}
    multiplicities = {0: 1}
    for residue in range(1, modulus):
        magnitude = nearest_residue_magnitude(residue, modulus)
        grades[residue] = magnitude * magnitude
        multiplicities[residue] = scalar_residue_minimum_multiplicity(residue, modulus)
    return LocalResidueAlphabet(
        zero_symbol=0,
        zero_sector_primitive_grade=modulus * modulus,
        zero_sector_primitive_multiplicity=2,
        residue_grade=grades,
        residue_multiplicity=multiplicities,
    )


def ternary_repetition_scalar_shadow() -> tuple[str, int, int]:
    alphabet = scalar_integer_residue_alphabet(3)
    code = ternary_repetition_3_code()
    grade, multiplicity = primitive_grade_and_multiplicity(code, alphabet)
    return primitive_grade_regime(code, alphabet), grade, multiplicity
