"""Primitive transfer geometry generated by slot future-equivalence classes.

Treat a single unit placed in each slot as the raw slot-state set.  A background
observation and unary future operations generate the coarsest exact continuation
partition P on slots.  Slots in one P-class are causally anonymous: the declared
background language can never distinguish which slot hosts the unit.

The maximal one-unit transfer law that preserves this anonymity partition connects
all pairs inside each class, giving a disjoint union of complete graphs.  Its
relation rank is N-#classes.  Enlarging the background future language refines P,
therefore removes neutral primitive transfers and weakly lowers this relation
rank.

Thus conserved charge/type labels can be viewed as encodings of slot continuation
types in regimes where those signatures are the relevant invariant.
"""

from __future__ import annotations

from collections import defaultdict
from typing import Hashable, Mapping

from .causal_operation_language import Generators, minimum_future_partition, partition_refines

Slot = Hashable
Edge = tuple[Slot, Slot]


def slot_future_partition(
    slots: tuple[Slot, ...],
    observation: Mapping[Slot, Hashable],
    generators: Generators,
) -> dict[Slot, int]:
    return minimum_future_partition(slots, observation, generators)


def partition_blocks(slots: tuple[Slot, ...], partition: Mapping[Slot, int]) -> tuple[tuple[Slot, ...], ...]:
    grouped: dict[int, list[Slot]] = defaultdict(list)
    for slot in slots:
        grouped[partition[slot]].append(slot)
    return tuple(tuple(grouped[key]) for key in sorted(grouped))


def maximal_neutral_transfer_edges(
    slots: tuple[Slot, ...],
    partition: Mapping[Slot, int],
) -> tuple[Edge, ...]:
    edges = []
    for block in partition_blocks(slots, partition):
        for index, left in enumerate(block):
            for right in block[index + 1:]:
                edges.append((left, right))
    return tuple(edges)


def signature_transfer_rank(slots: tuple[Slot, ...], partition: Mapping[Slot, int]) -> int:
    return len(slots) - len(partition_blocks(slots, partition))


def signature_direction_count(slots: tuple[Slot, ...], partition: Mapping[Slot, int]) -> int:
    return sum(len(block) * (len(block) - 1) for block in partition_blocks(slots, partition))


def future_language_refinement_shrinks_neutral_geometry(
    slots: tuple[Slot, ...],
    observation: Mapping[Slot, Hashable],
    coarse_generators: Generators,
    richer_generators: Generators,
) -> bool:
    if not set(coarse_generators) <= set(richer_generators):
        raise ValueError("richer generator family must contain coarse generator labels")
    if any(coarse_generators[label] != richer_generators[label] for label in coarse_generators):
        raise ValueError("shared generator labels must denote the same operations")
    coarse = slot_future_partition(slots, observation, coarse_generators)
    rich = slot_future_partition(slots, observation, richer_generators)
    if not partition_refines(rich, coarse):
        return False
    coarse_edges = set(maximal_neutral_transfer_edges(slots, coarse))
    rich_edges = set(maximal_neutral_transfer_edges(slots, rich))
    return (
        rich_edges <= coarse_edges
        and signature_transfer_rank(slots, rich) <= signature_transfer_rank(slots, coarse)
    )


def slot_signature_geometry_profile(
    slots: tuple[Slot, ...],
    observation: Mapping[Slot, Hashable],
    generators: Generators,
) -> tuple[tuple[int, ...], int, int]:
    partition = slot_future_partition(slots, observation, generators)
    block_sizes = tuple(sorted((len(block) for block in partition_blocks(slots, partition)), reverse=True))
    return (
        block_sizes,
        signature_transfer_rank(slots, partition),
        signature_direction_count(slots, partition),
    )
