"""Exact finite-budget refinement of a fixed block quotient under graded additions.

Current observation is q_d(n)=floor(n/d).  Future primitive operations add
nonnegative integers u_i, each with a positive integer cost c_i.  Inside one
current d-basin, a future sum S with residue a=S mod d introduces exactly one
possible threshold at remainder d-a (when a!=0).  Hence the budget-R minimum
future partition is the interval partition generated by thresholds whose
residues are reachable modulo d at cost <=R.

Minimum threshold revelation costs are shortest-path costs on the finite residue
graph Z/dZ with edges r -> r+u_i mod d.  The eventual reachable residue monoid is
the subgroup generated by the u_i, namely multiples of g=gcd(d,u_i), so the
ultimate interval partition is exactly the uniform g-block refinement q_g.
Finite-budget intermediate partitions need not be uniform divisor scales.
"""

from __future__ import annotations

import heapq
from itertools import count
from math import gcd
from typing import Mapping


def _validate(
    block_capacity: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
) -> None:
    if isinstance(block_capacity, bool) or not isinstance(block_capacity, int) or block_capacity <= 0:
        raise ValueError("block_capacity must be a positive integer")
    if not isinstance(generators, tuple) or not isinstance(costs, tuple):
        raise ValueError("generators and costs must be tuples")
    if len(generators) != len(costs):
        raise ValueError("generators and costs must have the same length")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value < 0
        for value in generators
    ):
        raise ValueError("additive generators must be non-negative integers")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value <= 0
        for value in costs
    ):
        raise ValueError("generator costs must be positive integers")


def ultimate_refinement_scale(
    block_capacity: int,
    generators: tuple[int, ...],
) -> int:
    if isinstance(block_capacity, bool) or not isinstance(block_capacity, int) or block_capacity <= 0:
        raise ValueError("block_capacity must be a positive integer")
    result = block_capacity
    for generator in generators:
        if isinstance(generator, bool) or not isinstance(generator, int) or generator < 0:
            raise ValueError("generators must be non-negative integers")
        result = gcd(result, generator)
    return result


def residue_minimum_costs(
    block_capacity: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
) -> tuple[int | None, ...]:
    """Shortest actual future cost to every residue modulo d; None if unreachable."""
    _validate(block_capacity, generators, costs)
    d = block_capacity
    serial = count()
    queue = [(0, next(serial), 0)]
    best = {0: 0}
    moves = tuple(zip(generators, costs))
    while queue:
        distance, _, residue = heapq.heappop(queue)
        if distance != best[residue]:
            continue
        for generator, edge_cost in moves:
            nxt = (residue + generator) % d
            candidate = distance + edge_cost
            if candidate >= best.get(nxt, candidate + 1):
                continue
            best[nxt] = candidate
            heapq.heappush(queue, (candidate, next(serial), nxt))
    return tuple(best.get(residue) for residue in range(d))


def cut_revelation_costs(
    block_capacity: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
) -> dict[int, int | None]:
    """Minimum cost at which each internal remainder cut 1..d-1 becomes visible."""
    residue_costs = residue_minimum_costs(block_capacity, generators, costs)
    d = block_capacity
    return {
        cut: residue_costs[(-cut) % d]
        for cut in range(1, d)
    }


def budget_cuts(
    block_capacity: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
    budget: int,
) -> tuple[int, ...]:
    if isinstance(budget, bool) or not isinstance(budget, int) or budget < 0:
        raise ValueError("budget must be a non-negative integer")
    cut_costs = cut_revelation_costs(block_capacity, generators, costs)
    return tuple(
        cut
        for cut in range(1, block_capacity)
        if cut_costs[cut] is not None and cut_costs[cut] <= budget
    )


def budget_remainder_intervals(
    block_capacity: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
    budget: int,
) -> tuple[tuple[int, int], ...]:
    """Half-open remainder intervals [start,end) forming the exact budget quotient."""
    cuts = (0,) + budget_cuts(block_capacity, generators, costs, budget) + (block_capacity,)
    return tuple((left, right) for left, right in zip(cuts, cuts[1:]))


def budget_continuation_type(
    remainder: int,
    block_capacity: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
    budget: int,
) -> int:
    if (
        isinstance(remainder, bool)
        or not isinstance(remainder, int)
        or not (0 <= remainder < block_capacity)
    ):
        raise ValueError("remainder must lie in 0..block_capacity-1")
    for class_id, (left, right) in enumerate(
        budget_remainder_intervals(
            block_capacity, generators, costs, budget
        )
    ):
        if left <= remainder < right:
            return class_id
    raise AssertionError("remainder must belong to exactly one budget interval")


def remainder_distinguishing_cost(
    left_remainder: int,
    right_remainder: int,
    block_capacity: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
) -> int | None:
    """Minimum future cost separating two remainders in the same current d-basin."""
    d = block_capacity
    if any(
        isinstance(value, bool)
        or not isinstance(value, int)
        or not (0 <= value < d)
        for value in (left_remainder, right_remainder)
    ):
        raise ValueError("remainders must lie in one d-basin")
    if left_remainder == right_remainder:
        return None
    left, right = sorted((left_remainder, right_remainder))
    cut_costs = cut_revelation_costs(d, generators, costs)
    candidates = [
        cut_costs[cut]
        for cut in range(left + 1, right + 1)
        if cut_costs[cut] is not None
    ]
    return min(candidates) if candidates else None


def future_signature_for_remainder(
    remainder: int,
    block_capacity: int,
    reachable_sums: tuple[int, ...],
) -> tuple[int, ...]:
    """Direct coarse-q increments for an explicit finite future-sum set."""
    if not (0 <= remainder < block_capacity):
        raise ValueError("remainder must lie in current block")
    return tuple(
        (remainder + future_sum) // block_capacity
        for future_sum in reachable_sums
    )


def eventual_intervals_match_gcd_scale(
    block_capacity: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
) -> bool:
    residue_costs = residue_minimum_costs(block_capacity, generators, costs)
    finite = [value for value in residue_costs if value is not None]
    budget = max(finite, default=0)
    intervals = budget_remainder_intervals(
        block_capacity, generators, costs, budget
    )
    g = ultimate_refinement_scale(block_capacity, generators)
    expected = tuple(
        (start, start + g)
        for start in range(0, block_capacity, g)
    )
    return intervals == expected


def budget_partition_is_nested(
    block_capacity: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
    maximum_budget: int,
) -> bool:
    previous_cuts: set[int] = set()
    for budget in range(maximum_budget + 1):
        current = set(budget_cuts(block_capacity, generators, costs, budget))
        if not previous_cuts <= current:
            return False
        previous_cuts = current
    return True
