"""Irreducible modular events generate the full total-modulus displacement group.

For m>=3 the causal irreducible unit-amplitude grammar contains exact-total
transfers e_i-e_j and all-plus/all-minus m-slot events.  Transfers generate every
zero-total integer displacement.  One m-body event changes total by +/-m.
Therefore the group generated by these events is exactly

    {delta in Z^N : sum(delta) is a multiple of m}.

Constructively, for target delta with total k*m, repeat one fixed m-body event
|k| times to make a reference displacement with the same total; the remaining
zero-total difference is decomposed into unit transfers.

Thus the support-two A-type primitive geometry alone connects exact-total fibers,
while the first support-m modular channel glues those components into total-mod-m
sectors.  Higher-grade causal events can therefore change connectivity/topology,
not merely add a scalar interaction on a fixed graph.
"""

from __future__ import annotations

from .causal_unit_transfer_geometry import canonical_transfer_decomposition

Vector = tuple[int, ...]
Event = tuple[int, ...]


def modular_displacement_allowed(displacement: Vector, modulus: int) -> bool:
    if modulus < 1:
        raise ValueError("modulus must be positive")
    return sum(displacement) % modulus == 0


def fixed_m_body_event(slot_count: int, modulus: int, sign: int) -> Event:
    if modulus < 1 or slot_count < modulus:
        raise ValueError("need at least modulus many slots")
    if sign not in (-1, 1):
        raise ValueError("sign must be +/-1")
    return tuple(sign if index < modulus else 0 for index in range(slot_count))


def modular_generation_program(displacement: Vector, modulus: int) -> tuple[Event, ...]:
    if modulus < 1 or len(displacement) < modulus:
        raise ValueError("need enough slots for the modular bridge event")
    total = sum(displacement)
    if total % modulus != 0:
        raise ValueError("displacement is not allowed by the modular conservation law")
    quotient = total // modulus
    bridge_sign = 1 if quotient > 0 else -1
    bridge = fixed_m_body_event(len(displacement), modulus, bridge_sign)
    bridge_events = tuple(bridge for _ in range(abs(quotient)))
    reference = tuple(abs(quotient) * value for value in bridge)
    remainder = tuple(target - current for target, current in zip(displacement, reference))
    if sum(remainder) != 0:
        raise AssertionError("bridge reference must leave zero-total remainder")
    origin = tuple(0 for _ in displacement)
    transfer_events = tuple(
        tuple(
            1 if index == receiver else -1 if index == donor else 0
            for index in range(len(displacement))
        )
        for receiver, donor in canonical_transfer_decomposition(origin, remainder)
    )
    return bridge_events + transfer_events


def apply_event_program(slot_count: int, events: tuple[Event, ...]) -> Vector:
    state = [0] * slot_count
    for event in events:
        if len(event) != slot_count:
            raise ValueError("event length mismatch")
        state = [value + delta for value, delta in zip(state, event)]
    return tuple(state)


def modular_generation_is_exact(displacement: Vector, modulus: int) -> bool:
    if not modular_displacement_allowed(displacement, modulus):
        return False
    program = modular_generation_program(displacement, modulus)
    return apply_event_program(len(displacement), program) == displacement
