"""GCD/LCM shadows of composing modular conservation laws.

Let L_m allow integer events whose total change lies in m Z.  There are two
opposite causal compositions:

1. simultaneous constraints: require both L_m and L_n, so the total change lies
   in mZ intersect nZ = lcm(m,n) Z;
2. generated operation language: allow events from either channel and arbitrary
   finite composition, so achievable signed total changes generate
   mZ+nZ = gcd(m,n) Z.

Thus lcm arises from intersecting conservation restrictions, while gcd arises
from generating a joint operation language.  This is standard arithmetic of
subgroups of Z; the project uses it as a causal origin for divisor-lattice
structures rather than taking the lattice order as primitive.
"""

from __future__ import annotations

from math import gcd, lcm


def simultaneous_constraint_modulus(left: int, right: int) -> int:
    if left <= 0 or right <= 0:
        raise ValueError("moduli must be positive")
    return lcm(left, right)


def generated_operation_modulus(left: int, right: int) -> int:
    if left <= 0 or right <= 0:
        raise ValueError("moduli must be positive")
    return gcd(left, right)


def satisfies_modular_law(total_change: int, modulus: int) -> bool:
    if modulus <= 0:
        raise ValueError("modulus must be positive")
    return total_change % modulus == 0


def intersection_identity(total_change: int, left: int, right: int) -> bool:
    combined = simultaneous_constraint_modulus(left, right)
    return (
        satisfies_modular_law(total_change, left)
        and satisfies_modular_law(total_change, right)
    ) == satisfies_modular_law(total_change, combined)


def bezout_generated_total_changes(left: int, right: int, bound: int) -> set[int]:
    """Finite signed audit of the group generated by m and n total-change channels."""
    if left <= 0 or right <= 0 or bound < 0:
        raise ValueError("moduli must be positive and bound non-negative")
    return {
        a * left + b * right
        for a in range(-bound, bound + 1)
        for b in range(-bound, bound + 1)
    }


def generated_changes_are_gcd_multiples(left: int, right: int, bound: int) -> bool:
    g = generated_operation_modulus(left, right)
    return all(value % g == 0 for value in bezout_generated_total_changes(left, right, bound))
