"""Codimension-one descent by maximizing the surviving primitive unit shell.

Let L be the integer translation module generated by a primitive unit shell R.
A nonzero homomorphism lambda:L->Z defines the slice

    L_lambda = ker(lambda),
    R_lambda = R intersect ker(lambda).

A slice is *unit-shell complete* when R_lambda still spans rank(L)-1.  The causal
descent principle studied here is to maximize |R_lambda|: when one relation
freedom is removed, preserve as many same-scale primitive LEGO moves as possible
rather than silently promoting longer moves to unit status.

Coordinates/selectors are only a computational representation of integer
homomorphisms.  The optimization target is basis-independent.

For A_n and D_n root shells the maximal surviving counts admit direct integer
proofs.  For the exceptional E8->E7->E6->D5 part, this module supplies an exact
small-selector search used as a falsifiable research tool; global optimality over
all dual-lattice homomorphisms remains a separate theorem/prior-art question.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product

from .causal_primitive_group_presentation import dense_coordinate_rank_mod_prime
from .causal_primitive_link_profile import Vector, primitive_direction_graph

Selector = tuple[int, ...]


def selector_value(selector: Selector, vector: Vector) -> int:
    if len(selector) != len(vector):
        raise ValueError("selector and vector dimensions must match")
    return sum(a * b for a, b in zip(selector, vector))


def zero_fiber(primitive_vectors: tuple[Vector, ...], selector: Selector) -> tuple[Vector, ...]:
    if not primitive_vectors:
        raise ValueError("primitive_vectors must be non-empty")
    if not any(selector):
        raise ValueError("selector must be nonzero")
    return tuple(vector for vector in primitive_vectors if selector_value(selector, vector) == 0)


def zero_fiber_rank(primitive_vectors: tuple[Vector, ...], selector: Selector) -> int:
    fiber = zero_fiber(primitive_vectors, selector)
    return dense_coordinate_rank_mod_prime(fiber) if fiber else 0


def unit_shell_complete_slice(
    primitive_vectors: tuple[Vector, ...],
    selector: Selector,
) -> bool:
    ambient_rank = dense_coordinate_rank_mod_prime(primitive_vectors)
    return zero_fiber_rank(primitive_vectors, selector) == ambient_rank - 1


@dataclass(frozen=True)
class UnitShellSlice:
    selector: Selector
    surviving_count: int
    surviving_rank: int
    primitive_degree_histogram: tuple[tuple[int, int], ...]
    link_connected: bool


def _connected(adjacency) -> bool:
    if not adjacency:
        return False
    unseen = set(adjacency)
    stack = [unseen.pop()]
    while stack:
        current = stack.pop()
        for nxt in adjacency[current]:
            if nxt in unseen:
                unseen.remove(nxt)
                stack.append(nxt)
    return not unseen


def slice_summary(primitive_vectors: tuple[Vector, ...], selector: Selector) -> UnitShellSlice:
    fiber = zero_fiber(primitive_vectors, selector)
    adjacency = primitive_direction_graph(fiber) if fiber else {}
    degrees: dict[int, int] = {}
    for vertex in adjacency:
        degree = len(adjacency[vertex])
        degrees[degree] = degrees.get(degree, 0) + 1
    return UnitShellSlice(
        selector=selector,
        surviving_count=len(fiber),
        surviving_rank=dense_coordinate_rank_mod_prime(fiber) if fiber else 0,
        primitive_degree_histogram=tuple(sorted(degrees.items())),
        link_connected=_connected(adjacency),
    )


def best_small_selector_slices(
    primitive_vectors: tuple[Vector, ...],
    alphabet: tuple[int, ...] = (-1, 0, 1),
) -> tuple[UnitShellSlice, ...]:
    """Exhaust all ambient selector coordinates in a small integer alphabet.

    Keeps only codimension-one unit-shell-complete selectors attaining the largest
    surviving primitive count.  This is a finite research audit, not a proof of
    global optimality over all integer/dual-lattice homomorphisms.
    """
    if not primitive_vectors:
        raise ValueError("primitive_vectors must be non-empty")
    if not alphabet or all(value == 0 for value in alphabet):
        raise ValueError("alphabet must contain a nonzero integer")
    coordinate_count = len(primitive_vectors[0])
    ambient_rank = dense_coordinate_rank_mod_prime(primitive_vectors)
    best_count = -1
    winners: list[UnitShellSlice] = []
    for selector in product(alphabet, repeat=coordinate_count):
        if not any(selector):
            continue
        fiber = tuple(
            vector
            for vector in primitive_vectors
            if selector_value(selector, vector) == 0
        )
        if len(fiber) < best_count:
            continue
        rank = dense_coordinate_rank_mod_prime(fiber) if fiber else 0
        if rank != ambient_rank - 1:
            continue
        summary = slice_summary(primitive_vectors, selector)
        if summary.surviving_count > best_count:
            best_count = summary.surviving_count
            winners = [summary]
        elif summary.surviving_count == best_count:
            winners.append(summary)
    return tuple(winners)


def greedy_small_selector_descent(
    primitive_vectors: tuple[Vector, ...],
    target_rank: int = 2,
    alphabet: tuple[int, ...] = (-1, 0, 1),
) -> tuple[UnitShellSlice, ...]:
    """Repeatedly choose a maximum unit-shell-complete small selector slice.

    Tie-breaking is deterministic and computational only; all maximizing slices
    are expected to be symmetry-related in the root examples but the theorem does
    not rely on that expectation.
    """
    current = primitive_vectors
    result = []
    while dense_coordinate_rank_mod_prime(current) > target_rank:
        winners = best_small_selector_slices(current, alphabet)
        if not winners:
            raise ValueError("no codimension-one unit-shell-complete selector found")
        chosen = min(
            winners,
            key=lambda item: (
                sum(value != 0 for value in item.selector),
                sum(abs(value) for value in item.selector),
                item.selector,
            ),
        )
        result.append(chosen)
        current = zero_fiber(current, chosen.selector)
    return tuple(result)


def a_family_maximal_slice_count(rank: int) -> int:
    """Proved A_rank result: maximum codim-one unit-shell count is A_(rank-1)."""
    if isinstance(rank, bool) or not isinstance(rank, int) or rank < 2:
        raise ValueError("A rank must be at least two")
    return rank * (rank - 1)


def d_family_maximal_slice_count(rank: int) -> int:
    """Proved D_rank result for rank>=4.

    A codim-one zero-root subsystem has one nonzero absolute-value selector group.
    If z coordinates have selector value zero and m=rank-z have one common
    nonzero absolute value, its root count is 2*z*(z-1)+m*(m-1).  The maximum is
    attained at z=rank-1 for rank>4, giving D_(rank-1); at rank4 it ties A3.
    """
    if isinstance(rank, bool) or not isinstance(rank, int) or rank < 4:
        raise ValueError("D rank must be at least four")
    return 2 * (rank - 1) * (rank - 2)
