"""Quadratic A_p relation grade as an exact potential of unit-transfer causality.

On a zero-sum integer slot state x define q(x)=1/2 sum_i x_i^2.  A primitive
unit transfer j->i changes q by the purely local integer amount

    gamma(x; i<-j) = x_i - x_j + 1.

Along any finite transfer path the gamma values telescope exactly to q(final)-
q(initial), so every closed transfer loop has total grade zero.  Thus the
quadratic state is an integer potential generated by the same primitive transfer
grammar that generates A_p graph distance.  Graph distance counts unit-transfer
steps; q reads a signed relation grade on those steps.

This is a discrete causal identity.  It does not assert that q is physical energy
or that a continuous gradient field is primitive.
"""

from __future__ import annotations

from .causal_unit_transfer_geometry import State, Transfer, apply_transfer


def require_zero_sum(state: State) -> None:
    if not isinstance(state, tuple) or len(state) < 2:
        raise ValueError("state must contain at least two slots")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in state):
        raise ValueError("state values must be integers")
    if sum(state) != 0:
        raise ValueError("quadratic A_p potential is defined here on zero-sum states")


def quadratic_relation_potential(state: State) -> int:
    require_zero_sum(state)
    square_sum = sum(value * value for value in state)
    if square_sum % 2 != 0:
        raise AssertionError("zero-sum integer state has even square sum")
    return square_sum // 2


def primitive_transfer_quadratic_grade(state: State, transfer: Transfer) -> int:
    require_zero_sum(state)
    receiver, donor = transfer
    if not (0 <= receiver < len(state) and 0 <= donor < len(state)) or receiver == donor:
        raise ValueError("transfer must use distinct valid slots")
    return state[receiver] - state[donor] + 1


def transfer_grade_identity(state: State, transfer: Transfer) -> bool:
    before = quadratic_relation_potential(state)
    grade = primitive_transfer_quadratic_grade(state, transfer)
    after_state = apply_transfer(state, transfer)
    after = quadratic_relation_potential(after_state)
    return after - before == grade


def path_quadratic_grade(
    initial: State,
    transfers: tuple[Transfer, ...],
) -> tuple[State, int]:
    require_zero_sum(initial)
    state = initial
    total_grade = 0
    for transfer in transfers:
        total_grade += primitive_transfer_quadratic_grade(state, transfer)
        state = apply_transfer(state, transfer)
    return state, total_grade


def path_grade_telescopes(initial: State, transfers: tuple[Transfer, ...]) -> bool:
    final, grade = path_quadratic_grade(initial, transfers)
    return grade == (
        quadratic_relation_potential(final)
        - quadratic_relation_potential(initial)
    )


def closed_transfer_loop_has_zero_grade(
    initial: State,
    transfers: tuple[Transfer, ...],
) -> bool:
    final, grade = path_quadratic_grade(initial, transfers)
    if final != initial:
        raise ValueError("declared transfer sequence is not a closed loop")
    return grade == 0
