"""Variable-basin quotient/detail states generated by arbitrary complete growth.

For a strictly increasing complete-growth sequence V(k), P008 gives

    k = max{j : V(j) <= n}.

The exact amount decomposes as

    n = V(k) + detail,
    0 <= detail < V(k+1)-V(k)

whenever a next represented level exists.  Thus the native detail capacity is
the current basin width, not an externally fixed precision scale.

Linear V(k)=d*k recovers ordinary fixed-block quotient/detail.  Square growth,
LEGO allocation growth and A_p ball growth produce state-dependent basin widths.
Adding units simply moves between these exact basin states; the number of
crossed complete levels is the generalized carry.  No division or fixed-base
precision is primitive.
"""

from __future__ import annotations

from dataclasses import dataclass

from .causal_completion_collapse import completion_root_index


@dataclass(frozen=True)
class CausalBasinState:
    level: int
    complete_value: int
    detail: int
    basin_width: int | None

    @property
    def exact_value(self) -> int:
        return self.complete_value + self.detail

    @property
    def remaining_to_next_complete(self) -> int | None:
        if self.basin_width is None:
            return None
        return self.basin_width - self.detail


def _validate_growth(growth: tuple[int, ...]) -> None:
    if not isinstance(growth, tuple) or not growth:
        raise ValueError("growth must be a non-empty tuple")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value < 0
        for value in growth
    ):
        raise ValueError("growth values must be non-negative integers")
    if any(left >= right for left, right in zip(growth, growth[1:])):
        raise ValueError("growth must be strictly increasing")


def basin_state(growth: tuple[int, ...], amount: int) -> CausalBasinState:
    _validate_growth(growth)
    if isinstance(amount, bool) or not isinstance(amount, int) or amount < 0:
        raise ValueError("amount must be a non-negative integer")
    level = completion_root_index(growth, amount)
    if level is None:
        raise ValueError("amount lies below the first represented complete level")
    complete = growth[level]
    detail = amount - complete
    width = None
    if level + 1 < len(growth):
        width = growth[level + 1] - complete
        if not (0 <= detail < width):
            raise AssertionError("P008 detail must lie inside the selected basin")
    return CausalBasinState(level, complete, detail, width)


def advance_amount(
    growth: tuple[int, ...],
    state: CausalBasinState,
    added_units: int,
) -> tuple[CausalBasinState, int]:
    """Advance exact amount and return `(new_state, crossed_complete_levels)`.

    `crossed_complete_levels` is the generalized carry relative to the complete
    growth law.  It may be zero, one, or more and need not be controlled by a
    fixed base.
    """
    _validate_growth(growth)
    if isinstance(added_units, bool) or not isinstance(added_units, int) or added_units < 0:
        raise ValueError("added_units must be a non-negative integer")
    if state.level >= len(growth) or growth[state.level] != state.complete_value:
        raise ValueError("state does not belong to the supplied growth law")
    new_amount = state.exact_value + added_units
    new_state = basin_state(growth, new_amount)
    return new_state, new_state.level - state.level


def basin_widths(growth: tuple[int, ...]) -> tuple[int, ...]:
    _validate_growth(growth)
    return tuple(right - left for left, right in zip(growth, growth[1:]))


def linear_growth(block_capacity: int, levels: int) -> tuple[int, ...]:
    if isinstance(block_capacity, bool) or not isinstance(block_capacity, int) or block_capacity <= 0:
        raise ValueError("block_capacity must be a positive integer")
    if isinstance(levels, bool) or not isinstance(levels, int) or levels <= 0:
        raise ValueError("levels must be a positive integer")
    return tuple(block_capacity * level for level in range(levels))


def square_growth(levels: int) -> tuple[int, ...]:
    if isinstance(levels, bool) or not isinstance(levels, int) or levels <= 0:
        raise ValueError("levels must be a positive integer")
    return tuple(level * level for level in range(levels))
