"""Future precision as causal pullback of P008 completion boundaries.

Let V be a strictly increasing complete-growth sequence and q_V the associated
P008 level quotient.  Under nonnegative additive future sums S, the observation
q_V(n+S) can change only when n crosses a translated-back complete boundary

    V(j) - S.

Therefore, inside any current basin [V(k),V(k+1)), the exact finite-future
partition is the interval subdivision generated by all internal boundary
pullbacks V(j)-S for allowed future sums.  With positive integer generator costs,
budget-R precision is obtained by using exactly the future sums reachable within
cost R.

This is the one-dimensional ordered specialization of the general causal future
quotient E_G = intersection_w ker(O∘w).  Linear block residue cuts and variable
basin refinement are special cases.
"""

from __future__ import annotations

import heapq
from bisect import bisect_right
from itertools import count


def _validate_growth(growth: tuple[int, ...]) -> None:
    if not isinstance(growth, tuple) or len(growth) < 2:
        raise ValueError("growth must contain at least two complete levels")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value < 0
        for value in growth
    ):
        raise ValueError("growth values must be non-negative integers")
    if any(left >= right for left, right in zip(growth, growth[1:])):
        raise ValueError("growth must be strictly increasing")


def reachable_additive_sums(
    generators: tuple[int, ...],
    costs: tuple[int, ...],
    budget: int,
) -> tuple[int, ...]:
    """All actual nonnegative future sums reachable with total operation cost <=R."""
    if not isinstance(generators, tuple) or not isinstance(costs, tuple) or len(generators) != len(costs):
        raise ValueError("generators and costs must be equal-length tuples")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value < 0
        for value in generators
    ):
        raise ValueError("generators must be non-negative integers")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value <= 0
        for value in costs
    ):
        raise ValueError("costs must be positive integers")
    if isinstance(budget, bool) or not isinstance(budget, int) or budget < 0:
        raise ValueError("budget must be a non-negative integer")
    serial = count()
    queue = [(0, next(serial), 0)]
    best = {0: 0}
    while queue:
        current_cost, _, total = heapq.heappop(queue)
        if current_cost != best[total]:
            continue
        for generator, edge_cost in zip(generators, costs):
            candidate_cost = current_cost + edge_cost
            if candidate_cost > budget:
                continue
            candidate_total = total + generator
            if candidate_cost >= best.get(candidate_total, candidate_cost + 1):
                continue
            best[candidate_total] = candidate_cost
            heapq.heappush(queue, (candidate_cost, next(serial), candidate_total))
    return tuple(sorted(best))


def completion_level(growth: tuple[int, ...], amount: int) -> int:
    _validate_growth(growth)
    if isinstance(amount, bool) or not isinstance(amount, int):
        raise ValueError("amount must be an integer")
    if amount < growth[0] or amount >= growth[-1]:
        raise ValueError("amount must lie in the represented half-open growth range")
    return bisect_right(growth, amount) - 1


def basin_pullback_cuts_from_sums(
    growth: tuple[int, ...],
    level: int,
    future_sums: tuple[int, ...],
) -> tuple[int, ...]:
    """Internal cuts V(j)-S lying strictly inside one current basin."""
    _validate_growth(growth)
    if isinstance(level, bool) or not isinstance(level, int) or not (0 <= level < len(growth) - 1):
        raise ValueError("level must have a represented next complete boundary")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value < 0
        for value in future_sums
    ):
        raise ValueError("future sums must be non-negative integers")
    left = growth[level]
    right = growth[level + 1]
    cuts = {
        boundary - future_sum
        for boundary in growth[1:]
        for future_sum in future_sums
        if left < boundary - future_sum < right
    }
    return tuple(sorted(cuts))


def basin_pullback_intervals_from_sums(
    growth: tuple[int, ...],
    level: int,
    future_sums: tuple[int, ...],
) -> tuple[tuple[int, int], ...]:
    left = growth[level]
    right = growth[level + 1]
    cuts = (left,) + basin_pullback_cuts_from_sums(growth, level, future_sums) + (right,)
    return tuple(zip(cuts, cuts[1:]))


def budget_basin_intervals(
    growth: tuple[int, ...],
    level: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
    budget: int,
) -> tuple[tuple[int, int], ...]:
    sums = reachable_additive_sums(generators, costs, budget)
    if growth[level + 1] - 1 + max(sums, default=0) >= growth[-1]:
        raise ValueError("growth sample lacks future headroom for the requested basin and budget")
    return basin_pullback_intervals_from_sums(growth, level, sums)


def direct_future_signature(
    growth: tuple[int, ...],
    amount: int,
    future_sums: tuple[int, ...],
) -> tuple[int, ...]:
    return tuple(completion_level(growth, amount + future_sum) for future_sum in future_sums)


def pullback_partition_matches_direct_signatures(
    growth: tuple[int, ...],
    level: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
    budget: int,
) -> bool:
    sums = reachable_additive_sums(generators, costs, budget)
    if growth[level + 1] - 1 + max(sums, default=0) >= growth[-1]:
        raise ValueError("growth sample lacks future headroom")
    intervals = basin_pullback_intervals_from_sums(growth, level, sums)
    type_of = {}
    for class_id, (left, right) in enumerate(intervals):
        for amount in range(left, right):
            type_of[amount] = class_id
    basin_amounts = tuple(range(growth[level], growth[level + 1]))
    signatures = {
        amount: direct_future_signature(growth, amount, sums)
        for amount in basin_amounts
    }
    return all(
        (type_of[left] == type_of[right]) == (signatures[left] == signatures[right])
        for left in basin_amounts
        for right in basin_amounts
    )


def square_growth(levels: int) -> tuple[int, ...]:
    if isinstance(levels, bool) or not isinstance(levels, int) or levels < 2:
        raise ValueError("levels must be an integer at least two")
    return tuple(level * level for level in range(levels))
