"""Primitive integer geometries generated by different causal conservation laws.

Use unit-amplitude integer events delta_i in {-1,0,+1} and minimize event support.

* No conservation: support one is allowed, giving +/-e_i (Z^N / axis grammar).
* Exact total conservation sum(delta)=0: support one is impossible; minimum
  support two events are e_i-e_j, giving the A_(N-1) transfer grammar.
* Total-parity conservation sum(delta)=0 mod 2: support one is impossible but all
  two-slot sign choices +/-e_i +/-e_j are allowed, giving the D_N root grammar.

Thus A and D can be read as shadows of different conserved observables rather
than competing primitive ontologies.  In rank three A3 and D3 produce isomorphic
FCC geometry, demonstrating that a coarse geometry need not determine a unique
causal conservation law.
"""

from __future__ import annotations

from itertools import product

Vector = tuple[int, ...]


def _validate_slots(slot_count: int) -> None:
    if isinstance(slot_count, bool) or not isinstance(slot_count, int) or slot_count < 1:
        raise ValueError("slot_count must be positive")


def support_size(vector: Vector) -> int:
    return sum(value != 0 for value in vector)


def unit_events(slot_count: int) -> tuple[Vector, ...]:
    _validate_slots(slot_count)
    return tuple(
        tuple(vector)
        for vector in product((-1, 0, 1), repeat=slot_count)
        if any(vector)
    )


def minimum_events_under_constraint(slot_count: int, predicate) -> tuple[Vector, ...]:
    allowed = tuple(event for event in unit_events(slot_count) if predicate(event))
    if not allowed:
        return ()
    minimum = min(support_size(event) for event in allowed)
    return tuple(event for event in allowed if support_size(event) == minimum)


def unconstrained_minimum_events(slot_count: int) -> tuple[Vector, ...]:
    return minimum_events_under_constraint(slot_count, lambda event: True)


def exact_total_conserving_minimum_events(slot_count: int) -> tuple[Vector, ...]:
    if slot_count < 2:
        raise ValueError("exact transfer geometry requires at least two slots")
    return minimum_events_under_constraint(slot_count, lambda event: sum(event) == 0)


def parity_conserving_minimum_events(slot_count: int) -> tuple[Vector, ...]:
    if slot_count < 2:
        raise ValueError("parity geometry requires at least two slots")
    return minimum_events_under_constraint(slot_count, lambda event: sum(event) % 2 == 0)


def expected_z_axis_events(slot_count: int) -> set[Vector]:
    _validate_slots(slot_count)
    result = set()
    for index in range(slot_count):
        for sign in (-1, 1):
            vector = [0] * slot_count
            vector[index] = sign
            result.add(tuple(vector))
    return result


def expected_a_transfer_events(slot_count: int) -> set[Vector]:
    if slot_count < 2:
        raise ValueError("A grammar requires at least two slots")
    return {
        tuple(
            1 if index == receiver else -1 if index == donor else 0
            for index in range(slot_count)
        )
        for receiver in range(slot_count)
        for donor in range(slot_count)
        if receiver != donor
    }


def expected_d_pair_events(slot_count: int) -> set[Vector]:
    if slot_count < 2:
        raise ValueError("D grammar requires at least two slots")
    result = set()
    for i in range(slot_count):
        for j in range(i + 1, slot_count):
            for sign_i in (-1, 1):
                for sign_j in (-1, 1):
                    vector = [0] * slot_count
                    vector[i] = sign_i
                    vector[j] = sign_j
                    result.add(tuple(vector))
    return result


def causal_geometry_shadow_identity(slot_count: int) -> dict[str, bool]:
    return {
        "Z": set(unconstrained_minimum_events(slot_count)) == expected_z_axis_events(slot_count),
        "A": (
            slot_count >= 2
            and set(exact_total_conserving_minimum_events(slot_count))
            == expected_a_transfer_events(slot_count)
        ),
        "D": (
            slot_count >= 2
            and set(parity_conserving_minimum_events(slot_count))
            == expected_d_pair_events(slot_count)
        ),
    }


def primitive_event_counts(slot_count: int) -> dict[str, int]:
    _validate_slots(slot_count)
    counts = {"Z": 2 * slot_count}
    if slot_count >= 2:
        counts["A"] = slot_count * (slot_count - 1)
        counts["D"] = 2 * slot_count * (slot_count - 1)
    return counts
