"""Hidden integer motion inside a fixed-total LEGO fiber.

For m integer slots, the coarse total map is

    total(x)=sum_i x_i.

Differences between any two fine states with the same total lie in

    K_m = {eta in Z^m : sum eta_i = 0}.

The explicit integer generators e_i-e_m, i=1..m-1, form a free basis of K_m, so
its rank is exactly m-1.  For nonnegative allocations, the finite fiber
F_m(c)=N^m intersection {sum=c} is a bounded portion of one affine coset of this
same hidden-motion lattice.

Thus the rank of hidden relation/motion and the finite-difference growth degree
of the fiber multiplicity H_m(c)=C(c+m-1,m-1) are generated by the same coarse-
total collapse.  This bridge is proved directly in integers; Ehrhart theory is a
traditional comparison/shadow, not needed for the result.
"""

from __future__ import annotations


def hidden_motion_basis(slot_count: int) -> tuple[tuple[int, ...], ...]:
    """Basis e_i-e_last of the zero-sum integer motion lattice."""
    if isinstance(slot_count, bool) or not isinstance(slot_count, int) or slot_count <= 0:
        raise ValueError("slot_count must be a positive integer")
    if slot_count == 1:
        return ()
    result = []
    for index in range(slot_count - 1):
        vector = [0] * slot_count
        vector[index] = 1
        vector[-1] = -1
        result.append(tuple(vector))
    return tuple(result)


def hidden_motion_rank(slot_count: int) -> int:
    if isinstance(slot_count, bool) or not isinstance(slot_count, int) or slot_count <= 0:
        raise ValueError("slot_count must be a positive integer")
    return slot_count - 1


def is_zero_sum_motion(vector: tuple[int, ...]) -> bool:
    if not isinstance(vector, tuple) or not vector:
        raise ValueError("vector must be a non-empty tuple")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in vector):
        raise ValueError("motion coordinates must be integers")
    return sum(vector) == 0


def basis_coordinates(vector: tuple[int, ...]) -> tuple[int, ...]:
    """Coordinates of a zero-sum vector in the e_i-e_last basis.

    For eta=(eta_1,...,eta_m) with sum zero, eta is exactly
    sum_(i<m) eta_i (e_i-e_m).
    """
    if not is_zero_sum_motion(vector):
        raise ValueError("vector must have zero total")
    return vector[:-1]


def reconstruct_motion(coordinates: tuple[int, ...]) -> tuple[int, ...]:
    if not isinstance(coordinates, tuple):
        raise ValueError("coordinates must be a tuple")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in coordinates):
        raise ValueError("coordinates must be integers")
    return tuple(coordinates) + (-sum(coordinates),)


def same_total_difference(
    left: tuple[int, ...],
    right: tuple[int, ...],
) -> tuple[int, ...]:
    if (
        not isinstance(left, tuple)
        or not isinstance(right, tuple)
        or not left
        or len(left) != len(right)
    ):
        raise ValueError("states must be non-empty tuples of the same length")
    if any(
        isinstance(value, bool) or not isinstance(value, int)
        for value in left + right
    ):
        raise ValueError("state coordinates must be integers")
    if sum(left) != sum(right):
        raise ValueError("states must have the same coarse total")
    difference = tuple(a - b for a, b in zip(left, right))
    if not is_zero_sum_motion(difference):
        raise AssertionError("same-total difference must lie in hidden motion lattice")
    return difference
