"""Finite-range local grades generated by one-step LEGO growth plus memory.

A q-slot local grade law does not require a q-ary composition primitive.  When
symbols are appended one at a time, it is enough to retain the last q-1 symbols
(or any future-safe quotient of that suffix) and add the grade of the newly
completed q-window.

This separates local interaction-window order from causal composition arity.
The raw suffix state is only an upper bound on continuation complexity; future
signature refinement may collapse many suffixes further.
"""

from __future__ import annotations

from typing import Callable, Hashable

Symbol = Hashable
Word = tuple[Symbol, ...]
LocalGrade = Callable[[Word], int]


def direct_window_grade(word: Word, window: int, local_grade: LocalGrade) -> int:
    if not isinstance(word, tuple):
        raise ValueError("word must be a tuple")
    if isinstance(window, bool) or not isinstance(window, int) or window <= 0:
        raise ValueError("window must be a positive integer")
    total = 0
    if len(word) < window:
        return 0
    for start in range(len(word) - window + 1):
        value = local_grade(word[start : start + window])
        if isinstance(value, bool) or not isinstance(value, int):
            raise ValueError("local_grade must return integers")
        total += value
    return total


def append_symbol(
    memory: Word,
    symbol: Symbol,
    window: int,
    local_grade: LocalGrade,
) -> tuple[Word, int]:
    """Append one symbol, returning `(new_memory, grade_increment)`.

    `memory` stores at most the last q-1 symbols already seen.
    """
    if isinstance(window, bool) or not isinstance(window, int) or window <= 0:
        raise ValueError("window must be a positive integer")
    if not isinstance(memory, tuple) or len(memory) > max(window - 1, 0):
        raise ValueError("memory must contain at most window-1 symbols")
    extended = memory + (symbol,)
    increment = 0
    if len(extended) >= window:
        completed = extended[-window:]
        increment = local_grade(completed)
        if isinstance(increment, bool) or not isinstance(increment, int):
            raise ValueError("local_grade must return integers")
    keep = max(window - 1, 0)
    new_memory = extended[-keep:] if keep else ()
    return new_memory, increment


def sequential_window_grade(word: Word, window: int, local_grade: LocalGrade) -> int:
    """Exact same grade as `direct_window_grade`, using one-symbol growth."""
    memory: Word = ()
    total = 0
    for symbol in word:
        memory, increment = append_symbol(memory, symbol, window, local_grade)
        total += increment
    return total


def raw_memory_state_bound(alphabet_size: int, window: int) -> int:
    """Upper bound on raw suffix states of length at most q-1.

    Includes shorter startup suffixes.  This is not claimed minimal.
    """
    if isinstance(alphabet_size, bool) or not isinstance(alphabet_size, int) or alphabet_size <= 0:
        raise ValueError("alphabet_size must be a positive integer")
    if isinstance(window, bool) or not isinstance(window, int) or window <= 0:
        raise ValueError("window must be a positive integer")
    return sum(alphabet_size**length for length in range(window))
