"""Future precision as causal pullback of P008 completion boundaries.

Let V be a strictly increasing complete-growth sequence and q_V the associated
P008 level quotient.  Under nonnegative additive future sums S, the observation
q_V(n+S) can change only when n crosses a translated-back complete boundary
V(j)-S.  Thus finite-future precision inside a current basin is exactly the
interval subdivision generated by causal pullbacks of future boundaries.

For a primitive +1 operation of positive integer cost c, if the next basin is at
least as wide as the current one, budget R reveals current-basin states one unit
at a time from the upper boundary.  A basin of width w has exactly
min(w,floor(R/c)+1) continuation classes and is fully resolved at cost c(w-1).
"""

from __future__ import annotations

import heapq
from bisect import bisect_right
from itertools import count


def _validate_growth(growth: tuple[int, ...]) -> None:
    if not isinstance(growth, tuple) or len(growth) < 2:
        raise ValueError("growth must contain at least two complete levels")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value < 0
        for value in growth
    ):
        raise ValueError("growth values must be non-negative integers")
    if any(left >= right for left, right in zip(growth, growth[1:])):
        raise ValueError("growth must be strictly increasing")


def basin_widths(growth: tuple[int, ...]) -> tuple[int, ...]:
    _validate_growth(growth)
    return tuple(right - left for left, right in zip(growth, growth[1:]))


def reachable_additive_sums(
    generators: tuple[int, ...],
    costs: tuple[int, ...],
    budget: int,
) -> tuple[int, ...]:
    if not isinstance(generators, tuple) or not isinstance(costs, tuple) or len(generators) != len(costs):
        raise ValueError("generators and costs must be equal-length tuples")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value < 0
        for value in generators
    ):
        raise ValueError("generators must be non-negative integers")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value <= 0
        for value in costs
    ):
        raise ValueError("costs must be positive integers")
    if isinstance(budget, bool) or not isinstance(budget, int) or budget < 0:
        raise ValueError("budget must be a non-negative integer")
    serial = count()
    queue = [(0, next(serial), 0)]
    best = {0: 0}
    while queue:
        current_cost, _, total = heapq.heappop(queue)
        if current_cost != best[total]:
            continue
        for generator, edge_cost in zip(generators, costs):
            candidate_cost = current_cost + edge_cost
            if candidate_cost > budget:
                continue
            candidate_total = total + generator
            if candidate_cost >= best.get(candidate_total, candidate_cost + 1):
                continue
            best[candidate_total] = candidate_cost
            heapq.heappush(queue, (candidate_cost, next(serial), candidate_total))
    return tuple(sorted(best))


def completion_level(growth: tuple[int, ...], amount: int) -> int:
    _validate_growth(growth)
    if isinstance(amount, bool) or not isinstance(amount, int):
        raise ValueError("amount must be an integer")
    if amount < growth[0] or amount >= growth[-1]:
        raise ValueError("amount must lie in the represented half-open growth range")
    return bisect_right(growth, amount) - 1


def basin_pullback_cuts_from_sums(
    growth: tuple[int, ...],
    level: int,
    future_sums: tuple[int, ...],
) -> tuple[int, ...]:
    _validate_growth(growth)
    if isinstance(level, bool) or not isinstance(level, int) or not (0 <= level < len(growth) - 1):
        raise ValueError("level must have a represented next complete boundary")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value < 0
        for value in future_sums
    ):
        raise ValueError("future sums must be non-negative integers")
    left = growth[level]
    right = growth[level + 1]
    cuts = {
        boundary - future_sum
        for boundary in growth[1:]
        for future_sum in future_sums
        if left < boundary - future_sum < right
    }
    return tuple(sorted(cuts))


def basin_pullback_intervals_from_sums(
    growth: tuple[int, ...],
    level: int,
    future_sums: tuple[int, ...],
) -> tuple[tuple[int, int], ...]:
    left = growth[level]
    right = growth[level + 1]
    cuts = (left,) + basin_pullback_cuts_from_sums(growth, level, future_sums) + (right,)
    return tuple(zip(cuts, cuts[1:]))


def budget_basin_intervals(
    growth: tuple[int, ...],
    level: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
    budget: int,
) -> tuple[tuple[int, int], ...]:
    sums = reachable_additive_sums(generators, costs, budget)
    if growth[level + 1] - 1 + max(sums, default=0) >= growth[-1]:
        raise ValueError("growth sample lacks future headroom for the requested basin and budget")
    return basin_pullback_intervals_from_sums(growth, level, sums)


def direct_future_signature(
    growth: tuple[int, ...],
    amount: int,
    future_sums: tuple[int, ...],
) -> tuple[int, ...]:
    return tuple(completion_level(growth, amount + future_sum) for future_sum in future_sums)


def pullback_partition_matches_direct_signatures(
    growth: tuple[int, ...],
    level: int,
    generators: tuple[int, ...],
    costs: tuple[int, ...],
    budget: int,
) -> bool:
    sums = reachable_additive_sums(generators, costs, budget)
    if growth[level + 1] - 1 + max(sums, default=0) >= growth[-1]:
        raise ValueError("growth sample lacks future headroom")
    intervals = basin_pullback_intervals_from_sums(growth, level, sums)
    type_of = {}
    for class_id, (left, right) in enumerate(intervals):
        for amount in range(left, right):
            type_of[amount] = class_id
    basin_amounts = tuple(range(growth[level], growth[level + 1]))
    signatures = {
        amount: direct_future_signature(growth, amount, sums)
        for amount in basin_amounts
    }
    return all(
        (type_of[left] == type_of[right]) == (signatures[left] == signatures[right])
        for left in basin_amounts
        for right in basin_amounts
    )


def unit_increment_continuation_type_count(
    growth: tuple[int, ...],
    level: int,
    unit_cost: int,
    budget: int,
) -> int:
    """Closed local law min(w_k,floor(R/c)+1) under nondecreasing next width."""
    widths = basin_widths(growth)
    if isinstance(level, bool) or not isinstance(level, int) or not (0 <= level < len(widths)):
        raise ValueError("level must index a represented basin")
    if level + 1 >= len(widths):
        raise ValueError("need one following basin to certify the local monotonic-width gate")
    if widths[level + 1] < widths[level]:
        raise ValueError("next basin width must be at least the current width")
    if isinstance(unit_cost, bool) or not isinstance(unit_cost, int) or unit_cost <= 0:
        raise ValueError("unit_cost must be a positive integer")
    if isinstance(budget, bool) or not isinstance(budget, int) or budget < 0:
        raise ValueError("budget must be a non-negative integer")
    steps = budget // unit_cost
    return min(widths[level], steps + 1)


def unit_increment_full_revelation_budget(
    growth: tuple[int, ...],
    level: int,
    unit_cost: int,
) -> int:
    widths = basin_widths(growth)
    if isinstance(level, bool) or not isinstance(level, int) or not (0 <= level < len(widths)):
        raise ValueError("level must index a represented basin")
    if isinstance(unit_cost, bool) or not isinstance(unit_cost, int) or unit_cost <= 0:
        raise ValueError("unit_cost must be a positive integer")
    return unit_cost * (widths[level] - 1)


def unit_increment_formula_matches_pullback(
    growth: tuple[int, ...],
    level: int,
    unit_cost: int,
    budget: int,
) -> bool:
    expected = unit_increment_continuation_type_count(
        growth, level, unit_cost, budget
    )
    intervals = budget_basin_intervals(
        growth,
        level,
        generators=(1,),
        costs=(unit_cost,),
        budget=min(budget, unit_increment_full_revelation_budget(growth, level, unit_cost)),
    )
    return len(intervals) == expected


def square_growth(levels: int) -> tuple[int, ...]:
    if isinstance(levels, bool) or not isinstance(levels, int) or levels < 2:
        raise ValueError("levels must be an integer at least two")
    return tuple(level * level for level in range(levels))
