"""Additive operations that genuinely descend through a P008 level collapse.

For a strictly increasing complete-growth law V, let q(n)=R_V(n) be the level
quotient.  A nonnegative translation t is *safe* when

    q(x)=q(y)  =>  q(x+t)=q(y+t)

for all represented amounts.  Safe translations are generated by the actual
collapse fibers; they are not declared as a precision-compatible operation set.

The exact basin criterion is local and integer: t is safe iff every translated
basin interval

    [V(k)+t, V(k+1)-1+t]

lies inside one q-fiber.  Safe translations contain 0 and are closed under
addition, hence form an additive submonoid of N0.

For linear V(k)=d*k the safe monoid is exactly d*N0.  If basin widths are
unbounded, no positive fixed translation is globally safe.  If widths are
periodic with period p and period capacity T, T and all its multiples are safe;
indeed they preserve basin detail exactly.
"""

from __future__ import annotations

from .causal_completion_collapse import completion_root_index


def _validate_growth(growth: tuple[int, ...]) -> None:
    if not isinstance(growth, tuple) or len(growth) < 2:
        raise ValueError("growth must contain at least two represented complete levels")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value < 0
        for value in growth
    ):
        raise ValueError("growth values must be non-negative integers")
    if any(left >= right for left, right in zip(growth, growth[1:])):
        raise ValueError("growth must be strictly increasing")


def translated_basin_target(
    growth: tuple[int, ...],
    level: int,
    translation: int,
) -> int | None:
    """Target level iff the entire translated represented basin stays in one fiber.

    Returns None if the translated basin crosses a quotient boundary or leaves
    the represented growth range.
    """
    _validate_growth(growth)
    if isinstance(level, bool) or not isinstance(level, int) or not (0 <= level < len(growth) - 1):
        raise ValueError("level must have a represented next level")
    if isinstance(translation, bool) or not isinstance(translation, int) or translation < 0:
        raise ValueError("translation must be non-negative")
    left = growth[level] + translation
    right = growth[level + 1] - 1 + translation
    if right >= growth[-1]:
        return None
    left_target = completion_root_index(growth, left)
    right_target = completion_root_index(growth, right)
    return left_target if left_target == right_target else None


def translation_is_safe_on_levels(
    growth: tuple[int, ...],
    translation: int,
    levels: tuple[int, ...],
) -> bool:
    _validate_growth(growth)
    if isinstance(translation, bool) or not isinstance(translation, int) or translation < 0:
        raise ValueError("translation must be non-negative")
    if any(
        isinstance(level, bool)
        or not isinstance(level, int)
        or not (0 <= level < len(growth) - 1)
        for level in levels
    ):
        raise ValueError("levels must have represented next levels")
    for level in levels:
        left = growth[level] + translation
        right = growth[level + 1] - 1 + translation
        if right >= growth[-1]:
            continue
        if completion_root_index(growth, left) != completion_root_index(growth, right):
            return False
    return True


def safe_translations_on_sample(
    growth: tuple[int, ...],
    maximum_translation: int,
    levels: tuple[int, ...] | None = None,
) -> tuple[int, ...]:
    _validate_growth(growth)
    if (
        isinstance(maximum_translation, bool)
        or not isinstance(maximum_translation, int)
        or maximum_translation < 0
    ):
        raise ValueError("maximum_translation must be non-negative")
    if levels is None:
        # Leave one level of headroom; translated tail basins that leave the
        # represented sample cannot provide a negative witness.
        levels = tuple(range(max(0, len(growth) - 2)))
    return tuple(
        translation
        for translation in range(maximum_translation + 1)
        if translation_is_safe_on_levels(growth, translation, levels)
    )


def safe_set_closed_under_addition(
    growth: tuple[int, ...],
    translations: tuple[int, ...],
    levels: tuple[int, ...],
) -> bool:
    """Finite audit of the exact monoid law whenever sums stay in supplied set."""
    safe = set(translations)
    for left in translations:
        for right in translations:
            total = left + right
            if total not in safe:
                continue
            if not translation_is_safe_on_levels(growth, total, levels):
                return False
    return True


def linear_safe_translation(block_capacity: int, translation: int) -> bool:
    """Closed theorem for V(k)=d*k: safe iff d divides translation."""
    if isinstance(block_capacity, bool) or not isinstance(block_capacity, int) or block_capacity <= 0:
        raise ValueError("block_capacity must be positive")
    if isinstance(translation, bool) or not isinstance(translation, int) or translation < 0:
        raise ValueError("translation must be non-negative")
    return translation % block_capacity == 0


def periodic_detail_preserving_translation(
    growth: tuple[int, ...],
    period: int,
) -> tuple[int, bool]:
    """Return natural period capacity T and exact detail-preserving verdict.

    This is an iff on the represented sequence: one T shifts every basin k to
    k+p with the same detail exactly when `V(k+p)-V(k)` is constant T, which is
    equivalent to p-periodicity of the basin-width sequence.
    """
    _validate_growth(growth)
    if isinstance(period, bool) or not isinstance(period, int) or period <= 0:
        raise ValueError("period must be positive")
    if len(growth) <= period:
        raise ValueError("growth must contain a period-ahead level")
    shifts = tuple(growth[index + period] - growth[index] for index in range(len(growth) - period))
    if len(set(shifts)) != 1:
        return shifts[0], False
    total = shifts[0]
    widths = tuple(right - left for left, right in zip(growth, growth[1:]))
    periodic = all(
        widths[index + period] == widths[index]
        for index in range(len(widths) - period)
    )
    return total, periodic
