"""Finitary causal congruence via elementary one-hole contexts.

For a finite algebra of raw LEGO states, every r-ary operation omega generates
unary elementary contexts by freezing all inputs except one:

    x -> omega(a_1,...,a_(i-1),x,a_(i+1),...,a_r).

All finite one-hole term contexts are compositions of such elementary contexts.
Therefore the coarsest observation-safe congruence for an arbitrary finite
operation signature is exactly the minimum unary future partition generated by
all elementary contexts.  No separate n-ary state-minimization ontology is
needed.

This is standard universal-algebra territory in mathematical form; the project
use is causal: the same future-closure compiler now handles unary dynamics,
binary LEGO joins, and higher-arity declared operations.
"""

from __future__ import annotations

from itertools import product
from typing import Hashable, Mapping

from .causal_operation_language import (
    Generators,
    Partition,
    minimum_future_partition,
    operation_coupling_defect,
    operation_language_is_safe,
)

State = Hashable
Observation = Hashable
OperationTable = tuple[int, Mapping[tuple[State, ...], State]]
Operations = Mapping[str, OperationTable]


def _validate_operations(states: tuple[State, ...], operations: Operations) -> None:
    if not isinstance(states, tuple) or not states or len(set(states)) != len(states):
        raise ValueError("states must be a non-empty tuple of unique states")
    state_set = set(states)
    if not isinstance(operations, Mapping):
        raise ValueError("operations must be a mapping")
    for name, specification in operations.items():
        if not isinstance(name, str) or not name:
            raise ValueError("operation names must be non-empty strings")
        if not isinstance(specification, tuple) or len(specification) != 2:
            raise ValueError("operation specification must be (arity, table)")
        arity, table = specification
        if isinstance(arity, bool) or not isinstance(arity, int) or arity < 0:
            raise ValueError("operation arity must be a non-negative integer")
        required = set(product(states, repeat=arity))
        if set(table) != required:
            raise ValueError("operation table must define every input tuple exactly once")
        if not set(table.values()) <= state_set:
            raise ValueError("operation outputs must stay inside the state set")


def elementary_context_generators(
    states: tuple[State, ...],
    operations: Operations,
    label_prefix: str = "ctx",
) -> dict[str, dict[State, State]]:
    """Compile all elementary one-hole translations of the operation signature."""
    _validate_operations(states, operations)
    result: dict[str, dict[State, State]] = {}
    serial = 0
    for name in sorted(operations):
        arity, table = operations[name]
        if arity == 0:
            continue
        for position in range(arity):
            for partners in product(states, repeat=arity - 1):
                generator: dict[State, State] = {}
                for state in states:
                    args = list(partners)
                    args.insert(position, state)
                    generator[state] = table[tuple(args)]
                label = f"{label_prefix}:{name}:{position}:{serial}"
                result[label] = generator
                serial += 1
    return result


def minimum_term_context_partition(
    states: tuple[State, ...],
    observation: Mapping[State, Observation],
    operations: Operations,
) -> Partition:
    """Coarsest observation-refining congruence for the declared operations."""
    generators = elementary_context_generators(states, operations)
    return minimum_future_partition(states, observation, generators)


def operations_respect_partition(
    states: tuple[State, ...],
    partition: Partition,
    operations: Operations,
) -> bool:
    """Congruence test via elementary contexts."""
    generators = elementary_context_generators(states, operations)
    return operation_language_is_safe(states, partition, generators)


def induced_operation_tables(
    states: tuple[State, ...],
    partition: Partition,
    operations: Operations,
) -> dict[str, tuple[int, dict[tuple[int, ...], int]]]:
    """Descend every raw operation to the quotient classes."""
    _validate_operations(states, operations)
    if not operations_respect_partition(states, partition, operations):
        raise ValueError("partition is not a congruence for the declared operations")
    result: dict[str, tuple[int, dict[tuple[int, ...], int]]] = {}
    for name, (arity, table) in operations.items():
        quotient_table: dict[tuple[int, ...], int] = {}
        for raw_args, raw_output in table.items():
            class_args = tuple(partition[state] for state in raw_args)
            output_class = partition[raw_output]
            previous = quotient_table.get(class_args)
            if previous is not None and previous != output_class:
                raise AssertionError("congruence failed to induce a unique quotient operation")
            quotient_table[class_args] = output_class
        result[name] = (arity, quotient_table)
    return result


def term_operation_coupling_defect(
    states: tuple[State, ...],
    observation: Mapping[State, Observation],
    left_operations: Operations,
    right_operations: Operations,
    maximum_order: int | None = None,
) -> tuple[int, tuple[int, ...]]:
    """Dynamic distinction created by interleaving contexts from two signatures."""
    left = elementary_context_generators(states, left_operations, "left")
    right = elementary_context_generators(states, right_operations, "right")
    return operation_coupling_defect(
        states,
        observation,
        left,
        right,
        maximum_order,
    )
