"""Minimum exact state generated by a finite causal operation language.

A raw state set X carries a declared observation O:X->Y and a finite set of
unary causal generators G.  Two states are future-equivalent when every finite
word in G gives the same declared observation.  On finite X this equivalence is
computed by partition refinement:

    P_0 = current-observation partition
    P_(n+1)(x) = (O(x), P_n(g_1 x), ..., P_n(g_r x)).

The stable partition is the coarsest refinement of the current observation for
which every declared generator descends to a deterministic quotient operation.
It is therefore the minimum exact continuation state for the generated future
operation monoid.

For two generator families G,H, the joint future quotient can be strictly finer
than the static common refinement of their separate quotients because mixed
words such as h∘g become legal.  The resulting extra refinement is an exact
operation-coupling effect, not a numerical approximation.
"""

from __future__ import annotations

from collections import defaultdict
from math import comb
from typing import Hashable, Mapping

State = Hashable
Observation = Hashable
Partition = dict[State, int]
GeneratorMap = Mapping[State, State]
Generators = Mapping[str, GeneratorMap]


def _validate(
    states: tuple[State, ...],
    observation: Mapping[State, Observation],
    generators: Generators,
) -> None:
    if not isinstance(states, tuple) or not states or len(set(states)) != len(states):
        raise ValueError("states must be a non-empty tuple of unique hashable states")
    state_set = set(states)
    if set(observation) != state_set:
        raise ValueError("observation must define every state exactly once")
    if not isinstance(generators, Mapping):
        raise ValueError("generators must be a mapping")
    for label, generator in generators.items():
        if not isinstance(label, str) or not label:
            raise ValueError("generator labels must be non-empty strings")
        if set(generator) != state_set:
            raise ValueError("every generator must define every state")
        if not set(generator.values()) <= state_set:
            raise ValueError("generator outputs must stay inside the state set")


def _canonical_partition(states: tuple[State, ...], signatures: Mapping[State, Hashable]) -> Partition:
    ids: dict[Hashable, int] = {}
    result: Partition = {}
    for state in states:
        signature = signatures[state]
        if signature not in ids:
            ids[signature] = len(ids)
        result[state] = ids[signature]
    return result


def same_partition(left: Partition, right: Partition) -> bool:
    if set(left) != set(right):
        return False
    states = tuple(left)
    return all(
        (left[a] == left[b]) == (right[a] == right[b])
        for a in states
        for b in states
    )


def partition_refines(finer: Partition, coarser: Partition) -> bool:
    if set(finer) != set(coarser):
        raise ValueError("partitions must cover the same state set")
    states = tuple(finer)
    return all(
        finer[a] != finer[b] or coarser[a] == coarser[b]
        for a in states
        for b in states
    )


def observation_partition(
    states: tuple[State, ...],
    observation: Mapping[State, Observation],
) -> Partition:
    if set(observation) != set(states):
        raise ValueError("observation must define every state")
    return _canonical_partition(states, observation)


def generator_respects_partition(
    states: tuple[State, ...],
    partition: Partition,
    generator: GeneratorMap,
) -> bool:
    if set(partition) != set(states) or set(generator) != set(states):
        raise ValueError("partition and generator must cover the state set")
    for left in states:
        for right in states:
            if partition[left] == partition[right] and partition[generator[left]] != partition[generator[right]]:
                return False
    return True


def operation_language_is_safe(
    states: tuple[State, ...],
    partition: Partition,
    generators: Generators,
) -> bool:
    return all(
        generator_respects_partition(states, partition, generator)
        for generator in generators.values()
    )


def refine_once(
    states: tuple[State, ...],
    observation: Mapping[State, Observation],
    generators: Generators,
    partition: Partition,
) -> Partition:
    _validate(states, observation, generators)
    if set(partition) != set(states):
        raise ValueError("partition must define every state")
    labels = tuple(sorted(generators))
    signatures = {
        state: (
            observation[state],
            tuple(partition[generators[label][state]] for label in labels),
        )
        for state in states
    }
    return _canonical_partition(states, signatures)


def minimum_future_partition(
    states: tuple[State, ...],
    observation: Mapping[State, Observation],
    generators: Generators,
) -> Partition:
    """Coarsest observation-refining partition stable under all generators."""
    _validate(states, observation, generators)
    current = observation_partition(states, observation)
    while True:
        refined = refine_once(states, observation, generators, current)
        if same_partition(current, refined):
            if not operation_language_is_safe(states, current, generators):
                raise AssertionError("stable refinement must make all generators descend")
            return current
        current = refined


def refinement_rounds(
    states: tuple[State, ...],
    observation: Mapping[State, Observation],
    generators: Generators,
) -> int:
    _validate(states, observation, generators)
    current = observation_partition(states, observation)
    rounds = 0
    while True:
        refined = refine_once(states, observation, generators, current)
        if same_partition(current, refined):
            return rounds
        rounds += 1
        current = refined


def induced_generator_maps(
    states: tuple[State, ...],
    partition: Partition,
    generators: Generators,
) -> dict[str, dict[int, int]]:
    if not operation_language_is_safe(states, partition, generators):
        raise ValueError("generators do not descend through supplied partition")
    result: dict[str, dict[int, int]] = {}
    for label, generator in generators.items():
        class_map: dict[int, int] = {}
        for state in states:
            source = partition[state]
            target = partition[generator[state]]
            previous = class_map.get(source)
            if previous is not None and previous != target:
                raise AssertionError("safe partition induced inconsistent quotient map")
            class_map[source] = target
        result[label] = class_map
    return result


def common_refinement(
    states: tuple[State, ...],
    left: Partition,
    right: Partition,
) -> Partition:
    if set(left) != set(states) or set(right) != set(states):
        raise ValueError("partitions must cover the state set")
    signatures = {state: (left[state], right[state]) for state in states}
    return _canonical_partition(states, signatures)


def class_count(partition: Partition) -> int:
    return len(set(partition.values()))


def partition_collision_spectrum(
    states: tuple[State, ...],
    partition: Partition,
    maximum_order: int | None = None,
) -> tuple[int, ...]:
    if set(partition) != set(states):
        raise ValueError("partition must cover the state set")
    grouped: dict[int, int] = defaultdict(int)
    for state in states:
        grouped[partition[state]] += 1
    limit = len(states) if maximum_order is None else maximum_order
    if isinstance(limit, bool) or not isinstance(limit, int) or limit < 0:
        raise ValueError("maximum_order must be a non-negative integer")
    return tuple(
        sum(comb(size, order) for size in grouped.values() if size >= order)
        for order in range(limit + 1)
    )


def operation_coupling_defect(
    states: tuple[State, ...],
    observation: Mapping[State, Observation],
    left_generators: Generators,
    right_generators: Generators,
    maximum_order: int | None = None,
) -> tuple[int, tuple[int, ...]]:
    """Extra distinctions caused by allowing mixed words from two languages.

    Returns `(extra_class_count, lost_collision_spectrum)`, where the baseline is
    the static common refinement of the two separately minimized future states.
    Every collision coordinate is nonnegative because the joint future quotient
    refines that baseline.
    """
    overlap = set(left_generators) & set(right_generators)
    if overlap:
        raise ValueError("generator labels must be disjoint across languages")
    left = minimum_future_partition(states, observation, left_generators)
    right = minimum_future_partition(states, observation, right_generators)
    static = common_refinement(states, left, right)
    joint_generators = dict(left_generators)
    joint_generators.update(right_generators)
    joint = minimum_future_partition(states, observation, joint_generators)
    if not partition_refines(joint, static):
        raise AssertionError("joint future quotient must refine separate common refinement")
    static_spectrum = partition_collision_spectrum(states, static, maximum_order)
    joint_spectrum = partition_collision_spectrum(states, joint, maximum_order)
    lost = tuple(before - after for before, after in zip(static_spectrum, joint_spectrum))
    if any(value < 0 for value in lost):
        raise AssertionError("future refinement cannot create new partition collisions")
    return class_count(joint) - class_count(static), lost
