"""Integral certificate-image precision after relation compression.

Let ``Lambda`` be an integer relation lattice with a declared integer basis and
let ``H`` be a family of labelled integer-linear certificate observables.  The
full certificate image is the lattice

    C = H(Lambda) <= Z^q.

For a finite access radius ``R``, let ``Gamma_R`` be the subgroup generated by
relation-compatible states reachable by that radius and set

    C_R = H(Gamma_R) <= C.

There are two distinct finite integral defects once the relevant rational rank
is visible:

* intrinsic certificate congruence defect
      delta_H = [Sat(C) : C],
  which may remain even at unlimited access;
* access-induced certificate defect
      J_H(R) = [C : C_R],
  which eventually falls to one.

If ``C_R`` has full certificate rank, then

    [Sat(C) : C_R] = delta_H * J_H(R).

The scalar index alone can lose congruence structure.  The complete finite
defect is retained by the nonzero Smith invariant factors of the labelled
certificate-image generator matrix.  Smith/determinantal-divisor theory is
standard mathematics; this module is the P025 relation/certificate precision
specialization.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
from math import gcd

from .relation_block_rank import rational_matrix_rank
from .relation_generator_radius import (
    exact_relation_generator_radius,
    relation_generation_layer,
)


Vector = tuple[int, ...]
Matrix = tuple[tuple[int, ...], ...]


@dataclass(frozen=True)
class LatticeImageInvariant:
    rank: int
    saturation_index: int


@dataclass(frozen=True)
class LatticeDefectSignature:
    rank: int
    determinantal_divisors: tuple[int, ...]
    invariant_factors: tuple[int, ...]
    saturation_index: int


@dataclass(frozen=True)
class CertificateImageLayer:
    radius: int
    certificate_rank: int
    saturation_index_in_ambient: int | None
    index_in_full_certificate_image: int | None
    complete_for_certificate_image: bool


@dataclass(frozen=True)
class CertificateImageProfilePoint:
    radius: int
    certificate_rank: int
    index_in_full_certificate_image: int | None
    total_saturation_index: int | None


@dataclass(frozen=True)
class CertificateImageProfile:
    full_certificate_rank: int
    intrinsic_saturation_index: int
    first_nonzero_certificate_radius: int | None
    full_certificate_rank_radius: int
    certificate_complete_radius: int
    relation_generator_radius: int
    points: tuple[CertificateImageProfilePoint, ...]


def _validate_rows(rows: tuple[Vector, ...], ambient: int) -> None:
    for row in rows:
        if len(row) != ambient:
            raise ValueError("certificate rows must match relation-state ambient dimension")
        for value in row:
            if isinstance(value, bool) or not isinstance(value, int):
                raise ValueError("certificate coefficients must be integers")


def _bareiss_determinant(rows: tuple[Vector, ...]) -> int:
    n = len(rows)
    if n == 0:
        return 1
    if any(len(row) != n for row in rows):
        raise ValueError("determinant requires a square integer matrix")
    matrix = [list(row) for row in rows]
    sign = 1
    previous = 1
    for k in range(n - 1):
        if matrix[k][k] == 0:
            pivot = next((r for r in range(k + 1, n) if matrix[r][k] != 0), None)
            if pivot is None:
                return 0
            matrix[k], matrix[pivot] = matrix[pivot], matrix[k]
            sign *= -1
        pivot_value = matrix[k][k]
        for i in range(k + 1, n):
            for j in range(k + 1, n):
                numerator = matrix[i][j] * pivot_value - matrix[i][k] * matrix[k][j]
                if numerator % previous:
                    raise AssertionError("Bareiss exact division failed")
                matrix[i][j] = numerator // previous
        previous = pivot_value
        for i in range(k + 1, n):
            matrix[i][k] = 0
    return sign * matrix[n - 1][n - 1]


def _determinantal_divisor(generators: tuple[Vector, ...], size: int) -> int:
    if size <= 0:
        raise ValueError("minor size must be positive")
    if not generators:
        return 0
    ambient = len(generators[0])
    if size > min(len(generators), ambient):
        return 0
    divisor = 0
    for selected_rows in combinations(range(len(generators)), size):
        for selected_columns in combinations(range(ambient), size):
            square = tuple(
                tuple(generators[i][j] for j in selected_columns)
                for i in selected_rows
            )
            divisor = gcd(divisor, abs(_bareiss_determinant(square)))
    return divisor


def lattice_defect_signature(generators: tuple[Vector, ...]) -> LatticeDefectSignature:
    """Return the complete nonzero Smith defect signature of a labelled image.

    If the image has rank ``d`` and determinantal divisors ``Delta_i`` then

        s_i = Delta_i / Delta_(i-1),   Delta_0 = 1

    are the nonzero Smith invariant factors and

        Sat(C)/C ~= direct_sum_i Z/s_i Z.

    Factors equal to one are retained so rank information remains explicit.
    """
    if not generators:
        return LatticeDefectSignature(0, (), (), 1)
    ambient = len(generators[0])
    if any(len(vector) != ambient for vector in generators):
        raise ValueError("all lattice generators must share labelled dimension")
    if ambient == 0:
        return LatticeDefectSignature(0, (), (), 1)
    rank = rational_matrix_rank(generators)
    if rank == 0:
        return LatticeDefectSignature(0, (), (), 1)

    divisors: list[int] = []
    previous = 1
    factors: list[int] = []
    for size in range(1, rank + 1):
        current = _determinantal_divisor(generators, size)
        if current <= 0:
            raise AssertionError("positive-rank image lost required determinantal divisor")
        if current % previous:
            raise AssertionError("determinantal divisors must form a divisibility chain")
        factor = current // previous
        if factors and factor % factors[-1]:
            raise AssertionError("Smith invariant factors must divide their successors")
        divisors.append(current)
        factors.append(factor)
        previous = current
    return LatticeDefectSignature(
        rank=rank,
        determinantal_divisors=tuple(divisors),
        invariant_factors=tuple(factors),
        saturation_index=divisors[-1],
    )


def lattice_image_invariant(generators: tuple[Vector, ...]) -> LatticeImageInvariant:
    """Return rational rank and index in the saturated labelled lattice."""
    signature = lattice_defect_signature(generators)
    return LatticeImageInvariant(
        rank=signature.rank,
        saturation_index=signature.saturation_index,
    )


def certificate_basis_generators(
    relation_basis: tuple[Vector, ...],
    certificate_rows: tuple[Vector, ...],
) -> tuple[Vector, ...]:
    """Return labelled certificate outputs of the declared relation basis."""
    if not relation_basis:
        raise ValueError("relation basis must be nonempty")
    ambient = len(relation_basis[0])
    if any(len(vector) != ambient for vector in relation_basis):
        raise ValueError("relation basis vectors must share ambient dimension")
    _validate_rows(certificate_rows, ambient)
    return tuple(
        tuple(
            sum(coefficient * coordinate for coefficient, coordinate in zip(row, basis_vector, strict=True))
            for row in certificate_rows
        )
        for basis_vector in relation_basis
    )


def _certificate_generators_from_relation_coordinates(
    relation_coordinates: tuple[Vector, ...],
    certificate_basis: tuple[Vector, ...],
) -> tuple[Vector, ...]:
    if not certificate_basis:
        raise ValueError("certificate basis generator list must be nonempty")
    relation_rank = len(certificate_basis)
    output_dimension = len(certificate_basis[0])
    if any(len(vector) != output_dimension for vector in certificate_basis):
        raise ValueError("certificate basis vectors must share labelled output dimension")
    results: list[Vector] = []
    for coordinates in relation_coordinates:
        if len(coordinates) != relation_rank:
            raise ValueError("relation coordinate vector must match relation basis rank")
        results.append(
            tuple(
                sum(coordinates[i] * certificate_basis[i][j] for i in range(relation_rank))
                for j in range(output_dimension)
            )
        )
    return tuple(results)


def certificate_image_layer(
    matrix: Matrix,
    relation_rows: tuple[Vector, ...],
    relation_basis: tuple[Vector, ...],
    certificate_rows: tuple[Vector, ...],
    radius: int,
) -> CertificateImageLayer:
    """Return integral certificate-image status generated through one radius."""
    full_generators = certificate_basis_generators(relation_basis, certificate_rows)
    full = lattice_image_invariant(full_generators)
    relation_layer = relation_generation_layer(matrix, relation_rows, relation_basis, radius)
    current_generators = _certificate_generators_from_relation_coordinates(
        relation_layer.coordinate_generators,
        full_generators,
    )
    current = lattice_image_invariant(current_generators)

    if current.rank == full.rank:
        if current.saturation_index % full.saturation_index:
            raise AssertionError("nested full-rank certificate image violated lattice index divisibility")
        image_index = current.saturation_index // full.saturation_index
    else:
        image_index = None
    return CertificateImageLayer(
        radius=radius,
        certificate_rank=current.rank,
        saturation_index_in_ambient=(
            current.saturation_index if current.rank == full.rank else None
        ),
        index_in_full_certificate_image=image_index,
        complete_for_certificate_image=image_index == 1,
    )


def exact_certificate_image_profile(
    matrix: Matrix,
    relation_rows: tuple[Vector, ...],
    relation_basis: tuple[Vector, ...],
    certificate_rows: tuple[Vector, ...],
) -> CertificateImageProfile:
    """Return the strict rank/index response through certificate completeness.

    The relation-generator radius is a finite upper bound because once the
    reachable relation states generate ``Lambda``, their certificate outputs
    necessarily generate the full certificate image ``C``.
    """
    full_generators = certificate_basis_generators(relation_basis, certificate_rows)
    full = lattice_image_invariant(full_generators)
    relation_endpoint = exact_relation_generator_radius(matrix, relation_rows, relation_basis)

    if full.rank == 0:
        return CertificateImageProfile(
            full_certificate_rank=0,
            intrinsic_saturation_index=1,
            first_nonzero_certificate_radius=None,
            full_certificate_rank_radius=0,
            certificate_complete_radius=0,
            relation_generator_radius=relation_endpoint.generator_radius,
            points=(),
        )

    first_nonzero: int | None = None
    full_rank_radius: int | None = None
    complete_radius: int | None = None
    previous_state: tuple[int, int | None] | None = None
    previous_finite_index: int | None = None
    points: list[CertificateImageProfilePoint] = []

    for radius in range(1, relation_endpoint.generator_radius + 1):
        layer = certificate_image_layer(
            matrix,
            relation_rows,
            relation_basis,
            certificate_rows,
            radius,
        )
        if first_nonzero is None and layer.certificate_rank > 0:
            first_nonzero = radius
        if full_rank_radius is None and layer.certificate_rank == full.rank:
            full_rank_radius = radius
        image_index = layer.index_in_full_certificate_image
        if image_index is not None:
            if previous_finite_index is not None:
                if previous_finite_index % image_index:
                    raise AssertionError("nested certificate image indices must form a divisibility chain")
                if image_index > previous_finite_index:
                    raise AssertionError("nested certificate image index must not increase")
            previous_finite_index = image_index
            if complete_radius is None and image_index == 1:
                complete_radius = radius

        state = (layer.certificate_rank, image_index)
        if state != previous_state and layer.certificate_rank > 0:
            points.append(
                CertificateImageProfilePoint(
                    radius=radius,
                    certificate_rank=layer.certificate_rank,
                    index_in_full_certificate_image=image_index,
                    total_saturation_index=(
                        None
                        if image_index is None
                        else full.saturation_index * image_index
                    ),
                )
            )
        previous_state = state

    if first_nonzero is None or full_rank_radius is None or complete_radius is None:
        raise AssertionError("relation completeness must force nonzero/full/complete certificate image")
    if complete_radius > relation_endpoint.generator_radius:
        raise AssertionError("certificate completion cannot lag relation generator completeness")
    if not points or points[-1].index_in_full_certificate_image != 1:
        raise AssertionError("certificate profile must terminate at its full image")

    return CertificateImageProfile(
        full_certificate_rank=full.rank,
        intrinsic_saturation_index=full.saturation_index,
        first_nonzero_certificate_radius=first_nonzero,
        full_certificate_rank_radius=full_rank_radius,
        certificate_complete_radius=complete_radius,
        relation_generator_radius=relation_endpoint.generator_radius,
        points=tuple(points),
    )
