"""Transform-free exact membership/kernel calculus for labelled certificate lattices.

Let ``C`` be the integer lattice generated by labelled certificate vectors
``g_1,...,g_m`` in ``Z^q``.  No Smith/Hermite transformation matrices are
needed to decide exact target membership.

For an integer target ``y``:

* ``y`` lies in the saturation ``Sat(C)`` iff adjoining ``y`` does not increase
  rational rank;
* if ``y`` lies in that rational span, then ``C <= <C,y> <= Sat(C)`` and

      y in C  <=>  [Sat(C):<C,y>] = [Sat(C):C].

The two finite indices are the maximal-minor gcds already computed by
``lattice_defect_signature``.  Hence exact membership is a rank +
determinantal-divisor test.

Likewise two saturated targets ``y,z`` represent the same quotient class in
``Sat(C)/C`` iff ``y-z`` passes this membership test.  This defines the exact
P023-style quotient kernel without selecting a normal-form representative.
"""

from __future__ import annotations

from dataclasses import dataclass

from .certificate_image_index import (
    LatticeDefectSignature,
    lattice_defect_signature,
)


Vector = tuple[int, ...]


@dataclass(frozen=True)
class CertificateLatticeKernel:
    generators: tuple[Vector, ...]
    signature: LatticeDefectSignature
    ambient_dimension: int


def certificate_lattice_kernel(generators: tuple[Vector, ...]) -> CertificateLatticeKernel:
    """Package the exact labelled lattice kernel state."""
    if not generators:
        raise ValueError("certificate lattice needs at least one labelled generator")
    ambient = len(generators[0])
    if any(len(vector) != ambient for vector in generators):
        raise ValueError("certificate generators must share labelled dimension")
    return CertificateLatticeKernel(
        generators=generators,
        signature=lattice_defect_signature(generators),
        ambient_dimension=ambient,
    )


def _validate_target(kernel: CertificateLatticeKernel, target: Vector) -> None:
    if len(target) != kernel.ambient_dimension:
        raise ValueError("target dimension must match certificate labels")
    for value in target:
        if isinstance(value, bool) or not isinstance(value, int):
            raise ValueError("certificate targets must be integer vectors")


def target_in_saturation(kernel: CertificateLatticeKernel, target: Vector) -> bool:
    """Return whether target lies in ``span_Q(C) intersect Z^q``."""
    _validate_target(kernel, target)
    augmented = lattice_defect_signature(kernel.generators + (target,))
    return augmented.rank == kernel.signature.rank


def target_in_certificate_lattice(kernel: CertificateLatticeKernel, target: Vector) -> bool:
    """Return exact membership ``target in C`` by rank/index equality."""
    _validate_target(kernel, target)
    augmented = lattice_defect_signature(kernel.generators + (target,))
    if augmented.rank != kernel.signature.rank:
        return False
    return augmented.saturation_index == kernel.signature.saturation_index


def same_certificate_quotient_class(
    kernel: CertificateLatticeKernel,
    left: Vector,
    right: Vector,
) -> bool:
    """Return equality in ``Sat(C)/C`` for two integer saturated targets."""
    _validate_target(kernel, left)
    _validate_target(kernel, right)
    if not target_in_saturation(kernel, left) or not target_in_saturation(kernel, right):
        raise ValueError("quotient classes are defined here only on Sat(C)")
    difference = tuple(a - b for a, b in zip(left, right, strict=True))
    return target_in_certificate_lattice(kernel, difference)


def quotient_order(kernel: CertificateLatticeKernel) -> int:
    """Return ``|Sat(C)/C|``."""
    return kernel.signature.saturation_index


def adjoining_target_index(
    kernel: CertificateLatticeKernel, target: Vector
) -> int | None:
    """Return ``[Sat(C):<C,target>]``; None means target leaves the rational span."""
    _validate_target(kernel, target)
    augmented = lattice_defect_signature(kernel.generators + (target,))
    if augmented.rank != kernel.signature.rank:
        return None
    return augmented.saturation_index
