"""Labelled enabled-helper frontier is an exact coordinate for ideal progress.

For a finite helper dependency poset and progress ideal I,

    En(I) = Min(P \ I).

Since the complement of an ideal is an upset, it is the upward closure of its
minimal elements. Therefore

    I = P \ upward(En(I)).

Thus the full labelled enabled-action set is injective on legal ideals and is a
dual antichain-boundary representation of exact runtime progress.
"""

from __future__ import annotations

from dataclasses import dataclass

from .balanced_binary_synergy import balanced_binary_synergy
from .closure_async_progress_poset import helper_ancestors, helper_ideals
from .closure_async_query_ladder import enabled_helpers


@dataclass(frozen=True)
class EnabledFrontierReport:
    arity: int
    ideal_count: int
    enabled_signature_count: int
    injective: bool
    reconstruction_verified: bool
    maximum_enabled_frontier_size: int
    helper_poset_width: int


def reconstruct_completed_from_enabled(arity: int, enabled: frozenset[str]) -> frozenset[str]:
    """Recover ideal as the complement of the upset generated by enabled roots."""
    compiler = balanced_binary_synergy(arity)
    helpers = frozenset(compiler.helpers)
    if not enabled.issubset(helpers):
        raise ValueError("enabled frontier contains a non-helper label")
    ancestors = helper_ancestors(arity)

    # x lies above a iff a==x or a is an ancestor of x.
    upward = {
        node
        for node in helpers
        if any(root == node or root in ancestors[node] for root in enabled)
    }
    return frozenset(helpers.difference(upward))


def enabled_frontier_report(arity: int) -> EnabledFrontierReport:
    if isinstance(arity, bool) or not isinstance(arity, int) or arity < 4:
        raise ValueError("arity must be an integer >= 4")
    ideals = tuple(helper_ideals(arity))
    signatures = [enabled_helpers(arity, ideal) for ideal in ideals]
    reconstructed = [reconstruct_completed_from_enabled(arity, sig) for sig in signatures]
    from .closure_async_progress_poset import helper_poset_width

    width = helper_poset_width(arity)
    return EnabledFrontierReport(
        arity=arity,
        ideal_count=len(ideals),
        enabled_signature_count=len(set(signatures)),
        injective=len(set(signatures)) == len(ideals),
        reconstruction_verified=tuple(reconstructed) == ideals,
        maximum_enabled_frontier_size=max((len(sig) for sig in signatures), default=0),
        helper_poset_width=width,
    )
