"""Dependency-support footprint of partial helper action languages.

For helper action set Q, the natural autonomous support from Supplement 153 is
the order-ideal/downward closure down(Q) in the helper dependency poset.  The
same support is generated by the maximal actions of Q, so redundant ancestor
actions do not enlarge the support generator boundary.

For perfect k=2^d balanced compilers, a single highest pre-output helper owns a
perfect subtree with k/2 raw leaves and k/2-1 helper gates. Thus one syntactic
action can require semantic dependency support of size k/2-1.
"""

from __future__ import annotations

from dataclasses import dataclass

from .balanced_binary_synergy import balanced_binary_synergy
from .closure_async_progress_poset import helper_ancestors


@dataclass(frozen=True)
class ActionSupportReport:
    arity: int
    raw_action_count: int
    support_generator_count: int
    dependency_support_count: int
    support_generators: frozenset[str]
    dependency_support: frozenset[str]


def action_dependency_support(arity: int, actions: frozenset[str]) -> frozenset[str]:
    compiler = balanced_binary_synergy(arity)
    helpers = frozenset(compiler.helpers)
    if not actions.issubset(helpers):
        raise ValueError("action set contains a non-helper label")
    ancestors = helper_ancestors(arity)
    support = set(actions)
    for action in actions:
        support.update(ancestors[action])
    return frozenset(support)


def maximal_action_generators(arity: int, actions: frozenset[str]) -> frozenset[str]:
    """Maximal actions generate the same downward dependency support."""
    compiler = balanced_binary_synergy(arity)
    helpers = frozenset(compiler.helpers)
    if not actions.issubset(helpers):
        raise ValueError("action set contains a non-helper label")
    ancestors = helper_ancestors(arity)
    return frozenset(
        action
        for action in actions
        if not any(
            action != other and action in ancestors[other]
            for other in actions
        )
    )


def action_support_report(arity: int, actions: frozenset[str]) -> ActionSupportReport:
    support = action_dependency_support(arity, actions)
    generators = maximal_action_generators(arity, actions)
    if action_dependency_support(arity, generators) != support:
        raise AssertionError("maximal actions must generate the same dependency support")
    return ActionSupportReport(
        arity=arity,
        raw_action_count=len(actions),
        support_generator_count=len(generators),
        dependency_support_count=len(support),
        support_generators=generators,
        dependency_support=support,
    )


def largest_single_action_support(arity: int) -> ActionSupportReport:
    compiler = balanced_binary_synergy(arity)
    best = None
    for helper in compiler.helpers:
        report = action_support_report(arity, frozenset({helper}))
        if best is None or report.dependency_support_count > best.dependency_support_count:
            best = report
    if best is None:
        raise AssertionError("compiler must contain helper actions")
    return best
