"""Finite positive-gap interaction layer generated by spatial collapse factor.

Under the active E001 macro-contact law

    Contact_d(g) iff g<d,

where ``g`` is a non-negative primitive clearance and ``d>=1`` is the spatial
collapse factor, primitive contact ``g=0`` is kept separate from coarse-only
positive-gap contact.

The positive-gap macro-contact layer is exactly

    L_d = {1,...,d-1}.

It therefore has thickness ``d-1`` in primitive gap states.  The canonical
inward depth coordinate

    kappa_d(g)=d-g

is a bijection from ``L_d`` to ``{1,...,d-1}``: the outermost coarse-contact gap
``d-1`` has depth 1, and gap 1 has depth ``d-1``.  Refinement reduces or removes
this layer without any hidden continuous penetration coordinate.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CollapseInteractionLayer:
    """Exact finite positive-gap contact layer at one collapse factor."""

    collapse_factor: int
    primitive_gaps: tuple[int, ...]
    depths: tuple[int, ...]
    thickness_states: int


def _require_positive_factor(collapse_factor: int) -> None:
    if (
        isinstance(collapse_factor, bool)
        or not isinstance(collapse_factor, int)
        or collapse_factor <= 0
    ):
        raise ValueError("collapse_factor must be a positive integer")


def collapse_layer_depth(
    primitive_gap: int,
    collapse_factor: int,
) -> int | None:
    """Return coarse-only positive-gap depth, or None outside that layer.

    Primitive contact ``g=0`` intentionally returns ``None`` because its material
    depth must come from the explicit terminal overlap/contact geometry rather
    than be conflated with a coarse positive-gap layer.
    """
    _require_positive_factor(collapse_factor)
    if (
        isinstance(primitive_gap, bool)
        or not isinstance(primitive_gap, int)
        or primitive_gap < 0
    ):
        raise ValueError("primitive_gap must be a non-negative integer")
    if primitive_gap == 0 or primitive_gap >= collapse_factor:
        return None
    return collapse_factor - primitive_gap


def collapse_interaction_layer(collapse_factor: int) -> CollapseInteractionLayer:
    """Enumerate the exact positive-gap layer and its inward depth coordinates."""
    _require_positive_factor(collapse_factor)
    gaps = tuple(range(1, collapse_factor))
    depths = tuple(collapse_factor - gap for gap in gaps)
    if len(gaps) != collapse_factor - 1:
        raise AssertionError("collapse interaction layer has incorrect thickness")
    if set(depths) != set(range(1, collapse_factor)):
        raise AssertionError("collapse layer depth is not a bijection")
    return CollapseInteractionLayer(
        collapse_factor=collapse_factor,
        primitive_gaps=gaps,
        depths=depths,
        thickness_states=len(gaps),
    )


def refinement_layer_depth(
    primitive_gap: int,
    coarse_factor: int,
    fine_factor: int,
) -> tuple[int | None, int | None]:
    """Compare the same positive gap under a coarse-to-fine factor change."""
    _require_positive_factor(coarse_factor)
    _require_positive_factor(fine_factor)
    if fine_factor > coarse_factor:
        raise ValueError("fine_factor must not exceed coarse_factor")
    return (
        collapse_layer_depth(primitive_gap, coarse_factor),
        collapse_layer_depth(primitive_gap, fine_factor),
    )
