"""Exact continuation-language geometry for monotone resource consumption.

Research specialization for Enterprise Math A2/FQ-006.

A generator j carries a nonzero consumption vector c_j in N_0^m and acts by

    x |-> x - c_j

exactly when x >= c_j coordinatewise. Since every generator only consumes
resources, a word with Parikh/count vector z is legal from x iff C z <= x.
Thus the exact operation-only legality quotient is represented by the finite
integer-feasibility profile

    P_C(x) = {z in N_0^r : C z <= x}.

This is a finite-state/executable specialization of the generic partial future
quotient. It does not claim novelty for partial automata, Petri nets/vector
addition systems, integer cones, or parametric integer programming.
"""

from __future__ import annotations

from itertools import product
from math import comb
from typing import Iterable, Sequence

State = tuple[int, ...]
Consumption = tuple[int, ...]
CountVector = tuple[int, ...]


def _state(values: Iterable[int]) -> State:
    x = tuple(values)
    if not x:
        raise ValueError("state must be nonempty")
    if any(not isinstance(v, int) or isinstance(v, bool) or v < 0 for v in x):
        raise ValueError("state coordinates must be nonnegative integers")
    return x


def _consumptions(
    state: State, consumptions: Iterable[Iterable[int]]
) -> tuple[Consumption, ...]:
    cols = tuple(tuple(c) for c in consumptions)
    if not cols:
        raise ValueError("consumption family must be nonempty")
    for c in cols:
        if len(c) != len(state):
            raise ValueError("every consumption vector must match state dimension")
        if any(not isinstance(v, int) or isinstance(v, bool) or v < 0 for v in c):
            raise ValueError("consumption entries must be nonnegative integers")
        if not any(c):
            raise ValueError("zero-consumption generators give unbounded word counts")
    return cols


def feasible_operation_counts(
    state: Iterable[int], consumptions: Iterable[Iterable[int]]
) -> tuple[CountVector, ...]:
    """Return every generator-count vector whose total consumption fits ``state``.

    For monotone consumption, a word is legal iff its total consumption fits:
    every prefix consumes coordinatewise no more than the full word. Hence word
    order is irrelevant to legality once the labeled generator counts are fixed.
    """
    x = _state(state)
    cols = _consumptions(x, consumptions)
    bounds = []
    for c in cols:
        positive = [x_i // c_i for x_i, c_i in zip(x, c) if c_i > 0]
        bounds.append(min(positive))

    feasible: list[CountVector] = []
    for z in product(*(range(bound + 1) for bound in bounds)):
        if all(
            sum(z[j] * cols[j][i] for j in range(len(cols))) <= x[i]
            for i in range(len(x))
        ):
            feasible.append(tuple(z))
    return tuple(feasible)


def same_continuation_profile(
    left: Iterable[int],
    right: Iterable[int],
    consumptions: Iterable[Iterable[int]],
) -> bool:
    """Whether two resource states have exactly the same legal future words."""
    cols = tuple(tuple(c) for c in consumptions)
    return feasible_operation_counts(left, cols) == feasible_operation_counts(right, cols)


def axis_block_quotient(state: Iterable[int], steps: Sequence[int]) -> State:
    """Product quotient generated by independent axis decrements of given steps."""
    x = _state(state)
    if len(x) != len(steps):
        raise ValueError("steps must match state dimension")
    if any(not isinstance(d, int) or isinstance(d, bool) or d <= 0 for d in steps):
        raise ValueError("steps must be positive integers")
    return tuple(x_i // d_i for x_i, d_i in zip(x, steps))


def coupled_wedge_quotient(x: int, y: int) -> tuple[int, int]:
    """Closed form for consumptions (1,0) and (1,1): ``(x, min(x,y))``."""
    state = _state((x, y))
    return state[0], min(state)


def block_totals(state: Iterable[int], block_sizes: Sequence[int]) -> State:
    """Return the visible independent unit-drain clocks for consecutive blocks."""
    x = _state(state)
    if not block_sizes or any(
        not isinstance(m, int) or isinstance(m, bool) or m <= 0 for m in block_sizes
    ):
        raise ValueError("block sizes must be positive integers")
    if sum(block_sizes) != len(x):
        raise ValueError("block sizes must partition the state coordinates")
    totals = []
    start = 0
    for size in block_sizes:
        totals.append(sum(x[start : start + size]))
        start += size
    return tuple(totals)


def block_fiber_size(totals: Sequence[int], block_sizes: Sequence[int]) -> int:
    """Exact number of fine slot states with the declared block-total clocks."""
    if len(totals) != len(block_sizes) or not totals:
        raise ValueError("totals and block sizes must be nonempty and aligned")
    result = 1
    for c, m in zip(totals, block_sizes):
        if not isinstance(c, int) or isinstance(c, bool) or c < 0:
            raise ValueError("block totals must be nonnegative integers")
        if not isinstance(m, int) or isinstance(m, bool) or m <= 0:
            raise ValueError("block sizes must be positive integers")
        result *= comb(c + m - 1, m - 1)
    return result


def block_clock_dimension_balance(block_sizes: Sequence[int]) -> tuple[int, int, int]:
    """Return (visible clock degree, hidden fiber degree, fine slot dimension)."""
    if not block_sizes or any(
        not isinstance(m, int) or isinstance(m, bool) or m <= 0 for m in block_sizes
    ):
        raise ValueError("block sizes must be positive integers")
    total = sum(block_sizes)
    visible = len(block_sizes)
    hidden = total - visible
    return visible, hidden, total
