"""Finite modular precision for hidden contact-cycle witness history.

The exact cycle-witness layer identifies the scalar hidden witness subgroup inside
one coarse body-state fiber as

    g Z = C(ker_Z B),

where ``g>=0`` is the gcd of scalar witness values on a fundamental cycle basis.
If the declared future language observes that witness only modulo ``M>0``, the
hidden subgroup becomes the cyclic subgroup generated by ``g mod M``.  Its exact
size is

    T = M / gcd(M,g).

Thus ``T`` is the minimum number of extra witness phases needed in one coarse
physical fiber for the modular future language.  The coarse body quotient alone
is safe exactly when ``T=1``, equivalently ``M|g`` (with ``g=0`` safe for every
modulus).

The same formula governs a single coarse partial-identity cycle operation with
scalar witness shift ``w``.  Modulo ``M`` its powers have exact period

    M / gcd(M,w).

So one internal cycle may be:

* infinitely distinguishable under exact integer witness state;
* finitely periodic under modular witness precision;
* completely invisible when the modulus kills its witness shift.

This provides an explicit precision ladder between retaining unbounded history
and erasing history entirely.  Cyclic groups and modular subgroup orders are
standard prior mathematics; the project value is the E001/P023 contact-history
specialization.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import gcd
from typing import Sequence

from .contact_cycle_witness_repair import (
    contact_cycle_witness_repair_report,
)


def _require_int(name: str, value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{name} must be an integer")


def _require_positive_int(name: str, value: int) -> None:
    _require_int(name, value)
    if value <= 0:
        raise ValueError(f"{name} must be positive")


def modular_additive_period(modulus: int, shift: int) -> int:
    """Order of additive shift ``shift`` in ``Z/modulus Z``."""
    _require_positive_int("modulus", modulus)
    _require_int("shift", shift)
    return modulus // gcd(modulus, abs(shift))


def modular_additive_phase(
    modulus: int,
    shift: int,
    repetitions: int,
) -> int:
    """Exact modular witness displacement after repeated equal shifts."""
    _require_positive_int("modulus", modulus)
    _require_int("shift", shift)
    _require_int("repetitions", repetitions)
    return (repetitions * shift) % modulus


@dataclass(frozen=True)
class ScalarCycleModularRepairReport:
    modulus: int
    exact_hidden_grain: int
    modular_hidden_phase_count: int
    cycle_rank: int

    @property
    def coarse_body_state_is_modular_future_safe(self) -> bool:
        return self.modular_hidden_phase_count == 1

    @property
    def requires_modular_repair(self) -> bool:
        return self.modular_hidden_phase_count > 1


def scalar_cycle_modular_repair_report(
    incidence: Sequence[Sequence[int]],
    witness_row: Sequence[int],
    modulus: int,
) -> ScalarCycleModularRepairReport:
    """Exact finite repair size for scalar cycle history observed modulo ``M``."""
    _require_positive_int("modulus", modulus)
    repair = contact_cycle_witness_repair_report(
        incidence,
        (tuple(witness_row),),
    )
    hidden_grain = repair.scalar_hidden_grain
    if hidden_grain is None:
        raise AssertionError("scalar witness unexpectedly lost its hidden grain")
    phase_count = modular_additive_period(modulus, hidden_grain)
    return ScalarCycleModularRepairReport(
        modulus=modulus,
        exact_hidden_grain=hidden_grain,
        modular_hidden_phase_count=phase_count,
        cycle_rank=repair.cycle_rank,
    )


def coarse_cycle_operation_modular_period(
    witness_shift: int,
    modulus: int,
) -> int:
    """Exact power period of a coarse partial identity with scalar witness shift."""
    return modular_additive_period(modulus, witness_shift)


def modular_cycle_power_phases(
    witness_shift: int,
    modulus: int,
) -> tuple[int, ...]:
    """One full exact witness-phase orbit beginning at zero."""
    period = coarse_cycle_operation_modular_period(
        witness_shift,
        modulus,
    )
    phases = tuple(
        modular_additive_phase(
            modulus,
            witness_shift,
            repetition,
        )
        for repetition in range(period)
    )
    if len(set(phases)) != period:
        raise AssertionError("modular witness orbit repeated before its predicted period")
    if modular_additive_phase(modulus, witness_shift, period) != 0:
        raise AssertionError("modular witness orbit failed to close at its predicted period")
    return phases
