"""Labelled context-separation depth and split spectra for P018.

This module is downstream of ``contextual_closure``.  It does not introduce a
new quotient state.  Instead it records *when* labelled state pairs are first
forced apart by finite operation contexts, produces shortest distinguishing
context certificates, and projects the refinement filtration to higher-order
collision-polynomial losses.

Nested-equivalence / ultrametric hierarchy language is established prior art.
The project-specific use is the finite operation-context refinement generated by
P018 precision closure and its interface with the P011 collision spectrum.
"""

from __future__ import annotations

from collections import defaultdict, deque
from collections.abc import Callable, Hashable, Iterable, Sequence
from dataclasses import dataclass
from itertools import combinations, product
from typing import Generic, TypeVar

from enterprise_math.collision_increment import collision_polynomial_from_fiber_sizes
from enterprise_math.contextual_closure import (
    FiniteOperation,
    contextual_refine_once,
    first_stable_context_depth,
)
from enterprise_math.predictive_closure import observation_partition, partition_refines

State = TypeVar("State", bound=Hashable)
Output = TypeVar("Output", bound=Hashable)

Partition = frozenset[frozenset[State]]
SeparationDepth = int | None  # None denotes infinity / never separated.


def _states_tuple(states: Iterable[State]) -> tuple[State, ...]:
    materialized = tuple(states)
    if not materialized:
        raise ValueError("states must be nonempty")
    if len(set(materialized)) != len(materialized):
        raise ValueError("states must be distinct labels")
    return materialized


def _block_map(partition: Partition[State]) -> dict[State, frozenset[State]]:
    return {state: block for block in partition for state in block}


@dataclass(frozen=True)
class ElementaryContext(Generic[State]):
    """One basic one-hole translation with all other coordinates fixed."""

    operation_index: int
    coordinate: int
    parameters: tuple[State, ...]


def elementary_contexts(
    states: Iterable[State], operations: Sequence[FiniteOperation[State]]
) -> tuple[ElementaryContext[State], ...]:
    materialized = _states_tuple(states)
    result: list[ElementaryContext[State]] = []
    for operation_index, operation in enumerate(operations):
        if operation.arity == 0:
            continue
        for coordinate in range(operation.arity):
            for parameters in product(materialized, repeat=operation.arity - 1):
                result.append(
                    ElementaryContext(operation_index, coordinate, tuple(parameters))
                )
    return tuple(result)


def apply_elementary_context(
    context: ElementaryContext[State],
    operations: Sequence[FiniteOperation[State]],
    state: State,
) -> State:
    if context.operation_index < 0 or context.operation_index >= len(operations):
        raise ValueError("context operation index is out of range")
    operation = operations[context.operation_index]
    if context.coordinate < 0 or context.coordinate >= operation.arity:
        raise ValueError("context coordinate is out of range")
    if len(context.parameters) != operation.arity - 1:
        raise ValueError("context parameter tuple has wrong arity")
    args: list[State] = []
    parameter_index = 0
    for index in range(operation.arity):
        if index == context.coordinate:
            args.append(state)
        else:
            args.append(context.parameters[parameter_index])
            parameter_index += 1
    return operation.apply(tuple(args))


def apply_context_path(
    path: Sequence[ElementaryContext[State]],
    operations: Sequence[FiniteOperation[State]],
    state: State,
) -> State:
    current = state
    for context in path:
        current = apply_elementary_context(context, operations, current)
    return current


def contextual_refinement_chain(
    states: Iterable[State],
    operations: Sequence[FiniteOperation[State]],
    observation: Callable[[State], Output],
) -> tuple[Partition[State], ...]:
    """Return ``R_0,...,R_h`` where ``R_h`` is the first stable closure."""
    materialized = _states_tuple(states)
    stable_depth, stable = first_stable_context_depth(
        materialized, operations, observation
    )
    chain: list[Partition[State]] = [
        observation_partition(materialized, observation)
    ]
    for _ in range(stable_depth):
        following = contextual_refine_once(materialized, operations, chain[-1])
        if not partition_refines(following, chain[-1]):
            raise AssertionError("contextual refinement chain is not nested")
        chain.append(following)
    if chain[-1] != stable:
        raise AssertionError("refinement chain did not reach the reported closure")
    return tuple(chain)


def pair_separation_depth_from_chain(
    chain: Sequence[Partition[State]], x: State, y: State
) -> SeparationDepth:
    """Least depth where ``x`` and ``y`` cease to lie in one block.

    ``None`` means the pair remains identified in the stable contextual closure.
    """
    if not chain:
        raise ValueError("chain must be nonempty")
    for depth, partition in enumerate(chain):
        mapping = _block_map(partition)
        if x not in mapping or y not in mapping:
            raise ValueError("states must occur in every partition")
        if mapping[x] != mapping[y]:
            return depth
    return None


def pair_separation_matrix(
    states: Iterable[State], chain: Sequence[Partition[State]]
) -> dict[tuple[State, State], SeparationDepth]:
    materialized = _states_tuple(states)
    return {
        (x, y): pair_separation_depth_from_chain(chain, x, y)
        for x in materialized
        for y in materialized
    }


def reconstruct_partition_from_separation(
    states: Iterable[State],
    separation: dict[tuple[State, State], SeparationDepth],
    depth: int,
) -> Partition[State]:
    """Reconstruct ``R_depth`` from the labelled extended separation matrix."""
    if isinstance(depth, bool) or not isinstance(depth, int) or depth < 0:
        raise ValueError("depth must be a non-negative integer")
    materialized = _states_tuple(states)
    remaining = set(materialized)
    blocks: list[frozenset[State]] = []

    def related(x: State, y: State) -> bool:
        value = separation[(x, y)]
        return value is None or value > depth

    while remaining:
        representative = next(iter(remaining))
        block = frozenset(
            state for state in materialized if related(representative, state)
        )
        if not block or representative not in block:
            raise ValueError("separation matrix does not define a reflexive relation")
        for left in block:
            for right in block:
                if not related(left, right):
                    raise ValueError("separation matrix does not define an equivalence")
        blocks.append(block)
        remaining.difference_update(block)
    return frozenset(blocks)


def reverse_context_distance(
    stable_depth: int, separation_depth: SeparationDepth
) -> int:
    """Turn first-separation depth into a nonnegative reversed hierarchy distance."""
    if isinstance(stable_depth, bool) or not isinstance(stable_depth, int) or stable_depth < 0:
        raise ValueError("stable depth must be a non-negative integer")
    if separation_depth is None:
        return 0
    if separation_depth < 0 or separation_depth > stable_depth:
        raise ValueError("finite separation depth must lie in the stable horizon")
    return stable_depth + 1 - separation_depth


def minimum_distinguishing_context(
    states: Iterable[State],
    operations: Sequence[FiniteOperation[State]],
    observation: Callable[[State], Output],
    x: State,
    y: State,
) -> tuple[ElementaryContext[State], ...] | None:
    """Return a shortest finite elementary-context path separating a labelled pair.

    Empty tuple means the pair is already distinguished by the raw observation.
    ``None`` means no finite operation context distinguishes the pair, equivalently
    the pair lies in one final contextual-closure block.
    """
    materialized = _states_tuple(states)
    if x not in materialized or y not in materialized:
        raise ValueError("x and y must belong to the finite state set")
    contexts = elementary_contexts(materialized, operations)
    stable_depth, _ = first_stable_context_depth(
        materialized, operations, observation
    )
    if observation(x) != observation(y):
        return ()

    queue: deque[tuple[State, State, tuple[ElementaryContext[State], ...]]] = deque(
        [(x, y, ())]
    )
    seen = {(x, y)}
    while queue:
        left, right, path = queue.popleft()
        if len(path) >= stable_depth:
            continue
        for context in contexts:
            next_left = apply_elementary_context(context, operations, left)
            next_right = apply_elementary_context(context, operations, right)
            next_path = path + (context,)
            if observation(next_left) != observation(next_right):
                return next_path
            pair = (next_left, next_right)
            if pair not in seen:
                seen.add(pair)
                queue.append((next_left, next_right, next_path))
    return None


def subset_separation_depth(
    subset: Iterable[State],
    separation: dict[tuple[State, State], SeparationDepth],
) -> SeparationDepth:
    """First depth where a finite subset ceases to lie in one equivalence block."""
    values = tuple(dict.fromkeys(subset))
    if len(values) <= 1:
        return None
    finite: list[int] = []
    for left, right in combinations(values, 2):
        depth = separation[(left, right)]
        if depth is not None:
            finite.append(depth)
    return min(finite) if finite else None


def partition_collision_coefficients(partition: Partition[State]) -> tuple[int, ...]:
    return collision_polynomial_from_fiber_sizes(len(block) for block in partition)


def split_increment_coefficients(
    coarse: Partition[State], fine: Partition[State]
) -> tuple[int, ...]:
    """Coefficientwise collision loss under one partition refinement step."""
    if not partition_refines(fine, coarse):
        raise ValueError("fine partition must refine coarse partition")
    coarse_coeff = partition_collision_coefficients(coarse)
    fine_coeff = partition_collision_coefficients(fine)
    length = max(len(coarse_coeff), len(fine_coeff))
    result = tuple(
        (coarse_coeff[index] if index < len(coarse_coeff) else 0)
        - (fine_coeff[index] if index < len(fine_coeff) else 0)
        for index in range(length)
    )
    if any(value < 0 for value in result):
        raise AssertionError("collision loss under refinement must be nonnegative")
    return result


def context_split_spectrum(
    chain: Sequence[Partition[State]],
) -> tuple[tuple[int, ...], ...]:
    if not chain:
        raise ValueError("chain must be nonempty")
    return tuple(
        split_increment_coefficients(chain[index], chain[index + 1])
        for index in range(len(chain) - 1)
    )


def iterate_endomap(operation: Callable[[State], State], state: State, steps: int) -> State:
    if isinstance(steps, bool) or not isinstance(steps, int) or steps < 0:
        raise ValueError("steps must be a non-negative integer")
    current = state
    for _ in range(steps):
        current = operation(current)
    return current


def time_kernel_partition(
    states: Iterable[State],
    operation: Callable[[State], State],
    state_partition: Partition[State],
    steps: int,
) -> Partition[State]:
    """Partition labelled histories by the state-partition block reached at time t."""
    materialized = _states_tuple(states)
    mapping = _block_map(state_partition)
    if set(mapping) != set(materialized):
        raise ValueError("state_partition must cover exactly the finite state set")
    grouped: dict[frozenset[State], set[State]] = defaultdict(set)
    for state in materialized:
        target = iterate_endomap(operation, state, steps)
        if target not in mapping:
            raise ValueError("operation must be an endomap on the finite state set")
        grouped[mapping[target]].add(state)
    return frozenset(frozenset(block) for block in grouped.values())


def unary_partition_compatible(
    states: Iterable[State],
    operation: Callable[[State], State],
    partition: Partition[State],
) -> bool:
    materialized = _states_tuple(states)
    mapping = _block_map(partition)
    if set(mapping) != set(materialized):
        return False
    for block in partition:
        targets = {mapping.get(operation(state)) for state in block}
        if None in targets or len(targets) != 1:
            return False
    return True


def time_kernel_is_monotone(
    states: Iterable[State],
    operation: Callable[[State], State],
    partition: Partition[State],
    horizon: int,
) -> bool:
    """Check K_t refines K_(t+1) over a finite horizon."""
    if isinstance(horizon, bool) or not isinstance(horizon, int) or horizon < 0:
        raise ValueError("horizon must be a non-negative integer")
    materialized = _states_tuple(states)
    previous = time_kernel_partition(materialized, operation, partition, 0)
    for step in range(1, horizon + 1):
        current = time_kernel_partition(materialized, operation, partition, step)
        if not partition_refines(previous, current):
            return False
        previous = current
    return True
