"""Exact future precision for one-dimensional guarded integer translations.

This P024 specialization consumes the generic future-safe quotient viewpoint but
keeps the arithmetic object explicit.  A state is an integer ``x``.  A named
action value ``a`` proposes the translation ``x -> x+a`` and is legal only when
the *current* state, before that action, satisfies the common upper guard

    x < g.

For a literal action word ``w=(a_1,...,a_m)`` let ``s_j`` be the prefix sum after
``j`` actions, with ``s_0=0``.  Two integer coordinates completely determine the
word's guarded threshold behavior:

    T(w) = s_m,
    H(w) = max {s_j : 0 <= j < m}       for m>0.

The empty word has ``T=0`` and no guard peak.  A nonempty word is executable
from ``x`` exactly when

    x < g - H(w),

and, when executable, ends at ``x+T(w)``.  Hence every ordered-threshold
terminal observation depends on the literal word only through the profile
``(T,H)``.

Appending one action does not require retaining the word:

    (T,H) --a--> (T+a, max(H,T)),

with the empty profile mapping to ``(a,0)``.  More generally, for two nonempty
profiles,

    T(uv) = T(u)+T(v),
    H(uv) = max(H(u), T(u)+H(v)).

Thus an exponential word language admits an exact finite profile compiler.
For action magnitude ``M=max |a|`` and horizon ``h>=1`` the number of distinct
profiles is at most

    1 + (2 h M + 1) ((h-1) M + 1),

quadratic in ``h`` for fixed action alphabet.  For strictly positive actions the
profile count is exactly

    1 + |A| |M_{h-1}|,

where ``M_{h-1}`` is the set of cumulative translations reachable in at most
``h-1`` actions: for a positive word, ``H=T-last_action``.

Let ``B`` be the ordered-threshold boundary set.  A nonempty profile has guard
cut ``G=g-H``.  Its legality-sensitive output changes exactly at

* the guard cut ``G``;
* each shifted observation cut ``b-T`` with ``b-T < G``.

Shifted cuts at or above ``G`` are masked because the word is already undefined.
The empty word contributes the ordinary current cuts.  Therefore the exact
horizon-``h`` future partition on ``Z`` is generated by the union of these
profile cuts.  This is the guarded analogue of P024's canonical total-action
boundary orbit ``B-M_h``.

Generic partial-transition/automata and max-prefix mathematics are prior art.
The project contribution here is the exact P024 integer specialization and the
explicit boundary between total-displacement precision and prefix-legality
precision.  No physical scheduler or contact law is asserted.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from .action_language_precision import (
    ordered_threshold_observation,
    reachable_translations,
)


def _require_int(name: str, value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{name} must be an integer")


def _require_nonnegative(name: str, value: int) -> None:
    _require_int(name, value)
    if value < 0:
        raise ValueError(f"{name} must be non-negative")


def _actions(actions: Iterable[int]) -> tuple[int, ...]:
    values = tuple(actions)
    if not values:
        raise ValueError("at least one action is required")
    for action in values:
        _require_int("action", action)
    return tuple(sorted(set(values)))


def _boundaries(boundaries: Iterable[int]) -> tuple[int, ...]:
    values = tuple(boundaries)
    for boundary in values:
        _require_int("boundary", boundary)
    return tuple(sorted(set(values)))


@dataclass(frozen=True)
class GuardedTranslationProfile:
    """Literal-word quotient retaining total translation and preterminal peak."""

    total_translation: int
    preterminal_peak: int | None

    @property
    def is_empty(self) -> bool:
        return self.preterminal_peak is None


def _validate_profile(profile: GuardedTranslationProfile) -> None:
    if not isinstance(profile, GuardedTranslationProfile):
        raise TypeError("profile must be GuardedTranslationProfile")
    _require_int("total_translation", profile.total_translation)
    if profile.preterminal_peak is None:
        if profile.total_translation != 0:
            raise ValueError("empty profile must have zero total translation")
        return
    _require_nonnegative("preterminal_peak", profile.preterminal_peak)


def empty_guarded_translation_profile() -> GuardedTranslationProfile:
    return GuardedTranslationProfile(0, None)


def guarded_word_profile(word: Iterable[int]) -> GuardedTranslationProfile:
    """Compile one literal action word to its exact ``(T,H)`` behavior state."""
    values = tuple(word)
    for action in values:
        _require_int("action", action)
    if not values:
        return empty_guarded_translation_profile()

    total = 0
    peak = 0
    for action in values:
        peak = max(peak, total)
        total += action
    return GuardedTranslationProfile(total, peak)


def append_guarded_action(
    profile: GuardedTranslationProfile,
    action: int,
) -> GuardedTranslationProfile:
    """Append one action without reconstructing the literal word."""
    _validate_profile(profile)
    _require_int("action", action)
    if profile.is_empty:
        return GuardedTranslationProfile(action, 0)
    assert profile.preterminal_peak is not None
    return GuardedTranslationProfile(
        profile.total_translation + action,
        max(profile.preterminal_peak, profile.total_translation),
    )


def compose_guarded_profiles(
    left: GuardedTranslationProfile,
    right: GuardedTranslationProfile,
) -> GuardedTranslationProfile:
    """Exact profile of word concatenation ``left_word + right_word``."""
    _validate_profile(left)
    _validate_profile(right)
    if left.is_empty:
        return right
    if right.is_empty:
        return left
    assert left.preterminal_peak is not None
    assert right.preterminal_peak is not None
    return GuardedTranslationProfile(
        left.total_translation + right.total_translation,
        max(
            left.preterminal_peak,
            left.total_translation + right.preterminal_peak,
        ),
    )


def guarded_translation_profiles(
    actions: Iterable[int],
    horizon: int,
) -> tuple[GuardedTranslationProfile, ...]:
    """Compile all literal words of length at most ``horizon`` to unique profiles."""
    values = _actions(actions)
    _require_nonnegative("horizon", horizon)
    empty = empty_guarded_translation_profile()
    reached = {empty}
    frontier = {empty}
    for _ in range(horizon):
        frontier = {
            append_guarded_action(profile, action)
            for profile in frontier
            for action in values
        }
        reached.update(frontier)
    return tuple(sorted(reached, key=_profile_sort_key))


def _profile_sort_key(profile: GuardedTranslationProfile) -> tuple[int, int, int]:
    return (
        0 if profile.is_empty else 1,
        profile.total_translation,
        -1 if profile.preterminal_peak is None else profile.preterminal_peak,
    )


def guarded_profile_count_upper_bound(actions: Iterable[int], horizon: int) -> int:
    """Quadratic horizon bound for the number of distinct ``(T,H)`` profiles."""
    values = _actions(actions)
    _require_nonnegative("horizon", horizon)
    if horizon == 0:
        return 1
    amplitude = max(abs(action) for action in values)
    return 1 + (2 * horizon * amplitude + 1) * (
        (horizon - 1) * amplitude + 1
    )


def positive_guarded_profile_count(actions: Iterable[int], horizon: int) -> int:
    """Exact profile count for a strictly positive action alphabet."""
    values = _actions(actions)
    _require_nonnegative("horizon", horizon)
    if any(action <= 0 for action in values):
        raise ValueError("positive profile count requires strictly positive actions")
    if horizon == 0:
        return 1
    prefix_totals = reachable_translations(values, horizon - 1)
    return 1 + len(values) * len(prefix_totals)


def guarded_profile_guard_cut(
    profile: GuardedTranslationProfile,
    guard: int,
) -> int | None:
    """Return ``g-H``; empty word has no legality cut."""
    _validate_profile(profile)
    _require_int("guard", guard)
    if profile.is_empty:
        return None
    assert profile.preterminal_peak is not None
    return guard - profile.preterminal_peak


def guarded_profile_defined(
    value: int,
    profile: GuardedTranslationProfile,
    guard: int,
) -> bool:
    """Whether the profile's literal words are legal from ``value``."""
    _require_int("value", value)
    cut = guarded_profile_guard_cut(profile, guard)
    return cut is None or value < cut


@dataclass(frozen=True)
class GuardedTranslationOutcome:
    defined: bool
    final_value: int | None
    observation: int | None


def apply_guarded_translation_word(
    value: int,
    word: Iterable[int],
    guard: int,
    boundaries: Iterable[int] = (),
) -> GuardedTranslationOutcome:
    """Direct literal-word oracle; guard is checked immediately before each action."""
    _require_int("value", value)
    _require_int("guard", guard)
    cuts = _boundaries(boundaries)
    current = value
    for action in tuple(word):
        _require_int("action", action)
        if current >= guard:
            return GuardedTranslationOutcome(False, None, None)
        current += action
    return GuardedTranslationOutcome(
        True,
        current,
        ordered_threshold_observation(current, cuts),
    )


def apply_guarded_translation_profile(
    value: int,
    profile: GuardedTranslationProfile,
    guard: int,
    boundaries: Iterable[int] = (),
) -> GuardedTranslationOutcome:
    """Evaluate a compiled profile with no literal-word reconstruction."""
    _require_int("value", value)
    cuts = _boundaries(boundaries)
    if not guarded_profile_defined(value, profile, guard):
        return GuardedTranslationOutcome(False, None, None)
    final = value + profile.total_translation
    return GuardedTranslationOutcome(
        True,
        final,
        ordered_threshold_observation(final, cuts),
    )


def guarded_profile_effective_cuts(
    profile: GuardedTranslationProfile,
    boundaries: Iterable[int],
    guard: int,
) -> tuple[int, ...]:
    """Exact integer cuts visible through one profile's legality and observation."""
    _validate_profile(profile)
    _require_int("guard", guard)
    cuts = _boundaries(boundaries)
    guard_cut = guarded_profile_guard_cut(profile, guard)
    if guard_cut is None:
        return tuple(sorted({boundary for boundary in cuts}))

    effective = {guard_cut}
    for boundary in cuts:
        shifted = boundary - profile.total_translation
        if shifted < guard_cut:
            effective.add(shifted)
    return tuple(sorted(effective))


def guarded_reachable_boundary_cuts(
    boundaries: Iterable[int],
    actions: Iterable[int],
    guard: int,
    horizon: int,
) -> tuple[int, ...]:
    """Union of all legality/observation cuts for compiled words through a horizon."""
    cuts = _boundaries(boundaries)
    values = _actions(actions)
    _require_int("guard", guard)
    _require_nonnegative("horizon", horizon)
    result: set[int] = set()
    for profile in guarded_translation_profiles(values, horizon):
        result.update(guarded_profile_effective_cuts(profile, cuts, guard))
    return tuple(sorted(result))


def guarded_future_signature(
    value: int,
    boundaries: Iterable[int],
    actions: Iterable[int],
    guard: int,
    horizon: int,
) -> tuple[tuple[GuardedTranslationProfile, bool, int | None], ...]:
    """Exact future signature after quotienting literal words by their ``(T,H)`` profile."""
    _require_int("value", value)
    cuts = _boundaries(boundaries)
    values = _actions(actions)
    _require_int("guard", guard)
    _require_nonnegative("horizon", horizon)
    result = []
    for profile in guarded_translation_profiles(values, horizon):
        outcome = apply_guarded_translation_profile(value, profile, guard, cuts)
        result.append((profile, outcome.defined, outcome.observation))
    return tuple(result)


def guarded_boundary_equivalent(
    left: int,
    right: int,
    boundaries: Iterable[int],
    actions: Iterable[int],
    guard: int,
    horizon: int,
) -> bool:
    """Whether no future-visible guarded cut separates two integer states."""
    _require_int("left", left)
    _require_int("right", right)
    if left == right:
        return True
    low, high = sorted((left, right))
    cuts = guarded_reachable_boundary_cuts(
        boundaries, actions, guard, horizon
    )
    return not any(low < cut <= high for cut in cuts)
