"""Exact future-language difference module for two integer linear models.

Consider two models on the same integer input state space, with the same named
action alphabet but possibly different action matrices and observation rows:

    model 1: C, A_a
    model 2: D, B_a.

For one literal action word w, the output difference on common initial state x is

    (C A_w - D B_w) x.

Rather than enumerate all words, build one block system

    E_a = diag(A_a, B_a),
    H   = (C, -D).

The exact Z-row module generated by all block future rows ``H E_w`` is computed
by the existing HNF action-module closure.  Project each block row
``(u,v)`` back to the original state coordinates by ``u+v``.  Because projection
is Z-linear, the projected HNF basis generates exactly the same module as all
literal dynamic difference rows ``C A_w-D B_w``.

Let ``g`` be the gcd content of the final projected difference module.  Then for
any positive modulus M, the two complete dynamic future languages agree modulo M
for every initial state and every literal action word iff

    M | g,

with ``g=0`` meaning exact integer equality of all linear future outputs.

At finite horizon h, the analogous content ``g_h`` forms a divisibility
filtration: ``g_(h+1) | g_h`` (every positive integer divides zero by the usual
content convention).  Thus future operations can only shrink the modular
indistinguishability down-set.

This construction compares output semantics for corresponding named words.  It
does not say the two models have the same internal states, costs, guards, or
literal actuator semantics.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product
from math import gcd
from typing import Sequence

from .integer_action_module_closure import (
    action_module_closure_report,
    integer_row_hermite_basis,
)
from .integer_action_language_observability import (
    integer_row_action,
)
from .integer_future_modular_model_separation import (
    first_distinguishing_prime_power_exponent,
)


Matrix = tuple[tuple[int, ...], ...]
Vector = tuple[int, ...]


def _rows(values: Sequence[Sequence[int]], *, name: str) -> Matrix:
    rows = tuple(tuple(row) for row in values)
    if not rows:
        raise ValueError(f"{name} must contain at least one row")
    width = len(rows[0])
    if width == 0 or any(len(row) != width for row in rows):
        raise ValueError(f"{name} rows must have one common positive width")
    for row in rows:
        for value in row:
            if isinstance(value, bool) or not isinstance(value, int):
                raise TypeError(f"{name} entries must be integers")
    return rows


def _actions(
    values: Sequence[Sequence[Sequence[int]]],
    dimension: int,
    *,
    name: str,
) -> tuple[Matrix, ...]:
    actions = tuple(tuple(tuple(row) for row in matrix) for matrix in values)
    if not actions:
        raise ValueError(f"{name} must contain at least one action")
    for matrix in actions:
        if len(matrix) != dimension or any(len(row) != dimension for row in matrix):
            raise ValueError(f"{name} actions must be square on the state dimension")
        for row in matrix:
            for value in row:
                if isinstance(value, bool) or not isinstance(value, int):
                    raise TypeError(f"{name} entries must be integers")
    return actions


def _paired_models(
    left_actions: Sequence[Sequence[Sequence[int]]],
    left_observations: Sequence[Sequence[int]],
    right_actions: Sequence[Sequence[Sequence[int]]],
    right_observations: Sequence[Sequence[int]],
) -> tuple[tuple[Matrix, ...], Matrix, tuple[Matrix, ...], Matrix]:
    left_rows = _rows(left_observations, name="left_observations")
    right_rows = _rows(right_observations, name="right_observations")
    if len(left_rows) != len(right_rows):
        raise ValueError("models must expose the same number of observation rows")
    if len(left_rows[0]) != len(right_rows[0]):
        raise ValueError("models must share the same input-state dimension")
    dimension = len(left_rows[0])
    left = _actions(left_actions, dimension, name="left_actions")
    right = _actions(right_actions, dimension, name="right_actions")
    if len(left) != len(right):
        raise ValueError("models must share the same named action alphabet size")
    return left, left_rows, right, right_rows


def block_diagonal_action(left: Matrix, right: Matrix) -> Matrix:
    if len(left) != len(right) or any(len(row) != len(left) for row in left) or any(len(row) != len(right) for row in right):
        raise ValueError("block actions must be square with equal dimension")
    n = len(left)
    return tuple(
        tuple(
            (
                left[row][column]
                if row < n and column < n
                else right[row - n][column - n]
                if row >= n and column >= n
                else 0
            )
            for column in range(2 * n)
        )
        for row in range(2 * n)
    )


def block_difference_observation_rows(
    left_rows: Matrix,
    right_rows: Matrix,
) -> Matrix:
    if len(left_rows) != len(right_rows) or len(left_rows[0]) != len(right_rows[0]):
        raise ValueError("observation blocks must have the same shape")
    return tuple(
        tuple((*left, *(-value for value in right)))
        for left, right in zip(left_rows, right_rows, strict=True)
    )


def project_block_difference_rows(
    block_rows: Sequence[Sequence[int]],
    state_dimension: int,
) -> Matrix:
    rows = tuple(tuple(row) for row in block_rows)
    projected = []
    for row in rows:
        if len(row) != 2 * state_dimension:
            raise ValueError("block row dimension mismatch")
        projected.append(
            tuple(
                row[column] + row[state_dimension + column]
                for column in range(state_dimension)
            )
        )
    return integer_row_hermite_basis(projected)


def row_module_content(rows: Sequence[Sequence[int]]) -> int:
    content = 0
    for row in rows:
        for value in row:
            if isinstance(value, bool) or not isinstance(value, int):
                raise TypeError("row-module entries must be integers")
            content = gcd(content, abs(value))
    return content


def dynamic_difference_module_basis(
    left_actions: Sequence[Sequence[Sequence[int]]],
    left_observations: Sequence[Sequence[int]],
    right_actions: Sequence[Sequence[Sequence[int]]],
    right_observations: Sequence[Sequence[int]],
) -> Matrix:
    left, left_rows, right, right_rows = _paired_models(
        left_actions,
        left_observations,
        right_actions,
        right_observations,
    )
    block_actions = tuple(
        block_diagonal_action(left_action, right_action)
        for left_action, right_action in zip(left, right, strict=True)
    )
    block_rows = block_difference_observation_rows(left_rows, right_rows)
    final_block_basis = action_module_closure_report(
        block_actions,
        block_rows,
    ).final_basis
    return project_block_difference_rows(
        final_block_basis,
        len(left_rows[0]),
    )


def dynamic_difference_content(
    left_actions: Sequence[Sequence[Sequence[int]]],
    left_observations: Sequence[Sequence[int]],
    right_actions: Sequence[Sequence[Sequence[int]]],
    right_observations: Sequence[Sequence[int]],
) -> int:
    return row_module_content(
        dynamic_difference_module_basis(
            left_actions,
            left_observations,
            right_actions,
            right_observations,
        )
    )


def dynamic_models_indistinguishable_modulus(
    left_actions: Sequence[Sequence[Sequence[int]]],
    left_observations: Sequence[Sequence[int]],
    right_actions: Sequence[Sequence[Sequence[int]]],
    right_observations: Sequence[Sequence[int]],
    modulus: int,
) -> bool:
    if isinstance(modulus, bool) or not isinstance(modulus, int):
        raise TypeError("modulus must be an integer")
    if modulus <= 0:
        raise ValueError("modulus must be positive")
    content = dynamic_difference_content(
        left_actions,
        left_observations,
        right_actions,
        right_observations,
    )
    return content == 0 or content % modulus == 0


def first_dynamic_distinguishing_prime_power_exponent(
    left_actions: Sequence[Sequence[Sequence[int]]],
    left_observations: Sequence[Sequence[int]],
    right_actions: Sequence[Sequence[Sequence[int]]],
    right_observations: Sequence[Sequence[int]],
    prime: int,
) -> int | None:
    basis = dynamic_difference_module_basis(
        left_actions,
        left_observations,
        right_actions,
        right_observations,
    )
    if not basis:
        # Validate prime through the existing static helper.
        return first_distinguishing_prime_power_exponent(((0,),), ((0,),), prime)
    zero = tuple((0,) * len(basis[0]) for _ in basis)
    return first_distinguishing_prime_power_exponent(basis, zero, prime)


def _word_rows(
    actions: tuple[Matrix, ...],
    observations: Matrix,
    word: tuple[int, ...],
) -> Matrix:
    current = observations
    for action_index in word:
        current = tuple(
            integer_row_action(row, actions[action_index])
            for row in current
        )
    return current


def literal_dynamic_difference_rows_through_horizon(
    left_actions: Sequence[Sequence[Sequence[int]]],
    left_observations: Sequence[Sequence[int]],
    right_actions: Sequence[Sequence[Sequence[int]]],
    right_observations: Sequence[Sequence[int]],
    horizon: int,
) -> Matrix:
    if isinstance(horizon, bool) or not isinstance(horizon, int):
        raise TypeError("horizon must be an integer")
    if horizon < 0:
        raise ValueError("horizon must be nonnegative")
    left, left_rows, right, right_rows = _paired_models(
        left_actions,
        left_observations,
        right_actions,
        right_observations,
    )
    rows = []
    for length in range(horizon + 1):
        for word in product(range(len(left)), repeat=length):
            left_future = _word_rows(left, left_rows, word)
            right_future = _word_rows(right, right_rows, word)
            rows.extend(
                tuple(a - b for a, b in zip(left_row, right_row, strict=True))
                for left_row, right_row in zip(left_future, right_future, strict=True)
            )
    return tuple(rows)


def finite_horizon_dynamic_difference_content(
    left_actions: Sequence[Sequence[Sequence[int]]],
    left_observations: Sequence[Sequence[int]],
    right_actions: Sequence[Sequence[Sequence[int]]],
    right_observations: Sequence[Sequence[int]],
    horizon: int,
) -> int:
    return row_module_content(
        literal_dynamic_difference_rows_through_horizon(
            left_actions,
            left_observations,
            right_actions,
            right_observations,
            horizon,
        )
    )


@dataclass(frozen=True)
class DynamicModelSeparationReport:
    difference_module_basis: Matrix
    difference_content: int
    exactly_future_equivalent: bool


def dynamic_model_separation_report(
    left_actions: Sequence[Sequence[Sequence[int]]],
    left_observations: Sequence[Sequence[int]],
    right_actions: Sequence[Sequence[Sequence[int]]],
    right_observations: Sequence[Sequence[int]],
) -> DynamicModelSeparationReport:
    basis = dynamic_difference_module_basis(
        left_actions,
        left_observations,
        right_actions,
        right_observations,
    )
    content = row_module_content(basis)
    return DynamicModelSeparationReport(
        difference_module_basis=basis,
        difference_content=content,
        exactly_future_equivalent=(not basis),
    )
