"""p-adic IMAGE precision spectrum for integer affine targets.

For an integer affine equation

    A x=b,

define the p-adic target height

    eta_p(b) = sup { e>=0 : A x == b (mod p^e) is solvable }.

The height may be finite or infinite.

* If b is integrally reachable, eta_p=infinity for every prime p.
* If b is rationally reachable but not integrally reachable, its cokernel class
  has finite order s.  If p does not divide s, multiplication by p is an
  automorphism on the cyclic subgroup generated by [b], so eta_p=infinity.  If
  p divides s, eta_p is finite and is the last prime-power level at which the
  target remains p-divisible in the cokernel.
* If b has a free cokernel component, eta_p is finite for every fixed prime p.

The finite ladder ``solvable mod p, ..., solvable mod p^E`` therefore reports
only the lower bound ``eta_p>=E`` until the first failure.  It cannot certify
infinite p-divisibility from finite precision.

Sharp same-map no-go: for ``A=p^(K+1)``, compare

    b_good = p^(K+1),
    b_bad  = p^(K+1)+p^K.

The first target is exactly reachable, the second is not, and their equation
data are identical modulo p^e for every e<=K.  They separate only at exponent
K+1.

This is the IMAGE-side p-adic dual of the hidden-kernel/deep-torsion precision
spectrum.  The arithmetic is standard cokernel divisibility and congruence.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from .integer_affine_fiber_diagnostic import (
    integrally_reachable,
    modularly_reachable,
    target_class_order_in_saturation,
)
from .integer_future_padic_precision import p_adic_valuation


INFINITE = "INFINITE"


def _prime(value: int) -> int:
    # Reuse exact prime validation.
    p_adic_valuation(1, value)
    return value


def affine_padic_target_height(
    matrix: Sequence[Sequence[int]],
    target: Sequence[int],
    prime: int,
) -> int | str:
    """Exact eta_p target divisibility height, or INFINITE."""
    p = _prime(prime)
    if integrally_reachable(matrix, target):
        return INFINITE

    class_order = target_class_order_in_saturation(matrix, target)
    if class_order is not None and class_order % p != 0:
        # Finite target class of prime-to-p order is p-divisible at every depth.
        return INFINITE

    # Either the target has a free cokernel component (guaranteed finite p-height)
    # or a nonzero p-primary torsion component (also guaranteed finite height).
    exponent = 1
    while modularly_reachable(matrix, target, p ** exponent):
        exponent += 1
    return exponent - 1


@dataclass(frozen=True)
class FinitePadicImageSpectrum:
    prime: int
    observed_max_exponent: int
    solvable_flags: tuple[bool, ...]
    first_unsolvable_exponent: int | None
    observed_height_lower_bound: int
    exact_height: int | str | None

    @property
    def no_failure_observed(self) -> bool:
        return self.first_unsolvable_exponent is None


def finite_padic_image_spectrum(
    matrix: Sequence[Sequence[int]],
    target: Sequence[int],
    prime: int,
    max_exponent: int,
    *,
    resolve_exact_height: bool = False,
) -> FinitePadicImageSpectrum:
    p = _prime(prime)
    if isinstance(max_exponent, bool) or not isinstance(max_exponent, int):
        raise TypeError("max_exponent must be an integer")
    if max_exponent <= 0:
        raise ValueError("max_exponent must be positive")
    flags = tuple(
        modularly_reachable(matrix, target, p ** exponent)
        for exponent in range(1, max_exponent + 1)
    )
    # Downward solvability requires a true-prefix then false-suffix pattern.
    saw_false = False
    for flag in flags:
        if saw_false and flag:
            raise AssertionError("p-adic affine solvability resurrected at finer precision")
        if not flag:
            saw_false = True
    first_failure = next(
        (index + 1 for index, flag in enumerate(flags) if not flag),
        None,
    )
    lower_bound = (
        max_exponent
        if first_failure is None
        else first_failure - 1
    )
    exact = (
        affine_padic_target_height(matrix, target, p)
        if resolve_exact_height
        else None
    )
    if exact != INFINITE and exact is not None:
        if first_failure is None and exact < max_exponent:
            raise AssertionError("finite ladder missed known target-height failure")
        if first_failure is not None and exact != first_failure - 1:
            raise AssertionError("finite ladder disagreed with exact target height")
    return FinitePadicImageSpectrum(
        prime=p,
        observed_max_exponent=max_exponent,
        solvable_flags=flags,
        first_unsolvable_exponent=first_failure,
        observed_height_lower_bound=lower_bound,
        exact_height=exact,
    )


def reachable_vs_deep_image_obstruction_indistinguishable_through(
    prime: int,
    depth: int,
    observed_exponent: int,
) -> bool:
    p = _prime(prime)
    for name, value in (("depth", depth), ("observed_exponent", observed_exponent)):
        if isinstance(value, bool) or not isinstance(value, int):
            raise TypeError(f"{name} must be an integer")
        if value <= 0:
            raise ValueError(f"{name} must be positive")
    coefficient = p ** (depth + 1)
    reachable_target = coefficient
    obstructed_target = coefficient + p ** depth
    equal_through = all(
        reachable_target % (p ** exponent)
        == obstructed_target % (p ** exponent)
        for exponent in range(1, observed_exponent + 1)
    )
    expected = observed_exponent <= depth
    if equal_through != expected:
        raise AssertionError("reachable/deep-image finite-precision boundary failed")
    if integrally_reachable(((coefficient,),), (obstructed_target,)):
        raise AssertionError("deep-image comparison target unexpectedly reachable")
    if not integrally_reachable(((coefficient,),), (reachable_target,)):
        raise AssertionError("reachable comparison target unexpectedly failed")
    return expected
