"""Finite integer observability closure for a family of linear future actions.

Let the integer state be a row-coordinate vector ``x in Z^n``.  A finite family
of total linear future actions is represented by integer matrices ``A_a`` and a
finite current observation family by integer rows ``C``.  A literal action word
``w=a_1...a_k`` contributes future observation rows

    C A_(a_1) ... A_(a_k).

Let ``L_h`` be the Z-row-lattice generated by all such rows for words of length
at most ``h``, and ``W_h=Q span(L_h)``.

The two closures behave differently but both stabilize finitely.

### Rational closure

``W_h`` is ascending.  If one step has

    dim_Q W_(h+1) = dim_Q W_h,

then ``W_h`` is invariant under every declared action matrix: every generator
row in ``W_h`` maps into ``W_(h+1)=W_h``, hence every rational combination does.
Therefore rational rank can never increase later.  Starting at rank ``r_0`` in
state dimension ``n``, the first rational plateau occurs by horizon at most
``n-r_0``.

### Integer closure after rational stabilization

After the rational row space has stabilized, ``L_h`` is an ascending chain of
finite-index sublattices of the fixed saturated lattice ``W cap Z^n``.  Its
index is the maximal nonzero determinantal divisor ``Delta_r(L_h)``.

If ``L_h`` is still strictly enlarged at the next horizon, this index decreases
to a proper positive divisor.  If one step has equal rank and equal index, the
nested lattices are equal; that lattice is action-invariant and no later word can
add a new row-lattice element.

Consequently, if rational stabilization starts at horizon ``h_Q`` with
saturation index ``I``, the final integer row lattice is attained after at most

    Omega(I)

further strict refinement horizons, where ``Omega`` counts prime factors with
multiplicity.  This is a finite arithmetic bound, not an empirical convergence
claim.

### Minimal multi-action witness

In dimension three let

    C = (1,0,0),

and choose actions with

    first row of A = (0,1,0),
    first row of B = (0,0,2),
    second row of B = (0,0,1).

At horizon one the row lattice contains

    e1, e2, 2e3,

so rational rank is already three but saturation index is two.  At horizon two
word ``A B`` contributes ``e3``.  Rank stays three while the index drops from two
to one.  Thus a multi-action future language can continue refining integer
precision after state distinguishability is already complete.

For a single integer action matrix this delayed noncommutative-word mechanism is
absent: Cayley-Hamilton makes all powers beyond ``n-1`` integer combinations of
``I,A,...,A^(n-1)``.  The general multi-action closure studied here is instead a
Z-module generated by a matrix monoid.

Matrix monoids, Noetherian Z-modules, rational invariant subspaces,
determinantal divisors and Cayley-Hamilton are standard prior mathematics.  The
project value is the exact P023 integer future-language closure interpretation.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import gcd
from typing import Iterable, Sequence

from .integer_future_observability import (
    integer_matrix_product,
    integer_matrix_rank,
)
from .integer_future_smith_precision import integer_smith_precision_profile


Vector = tuple[int, ...]
Matrix = tuple[tuple[int, ...], ...]


def _matrix(values: Sequence[Sequence[int]]) -> Matrix:
    matrix = tuple(tuple(row) for row in values)
    if not matrix:
        raise ValueError("matrix must contain at least one row")
    width = len(matrix[0])
    if width == 0 or any(len(row) != width for row in matrix):
        raise ValueError("matrix rows must have one common positive width")
    for row in matrix:
        for value in row:
            if isinstance(value, bool) or not isinstance(value, int):
                raise TypeError("matrix entries must be integers")
    return matrix


def _actions(values: Sequence[Sequence[Sequence[int]]], dimension: int) -> tuple[Matrix, ...]:
    actions = tuple(_matrix(matrix) for matrix in values)
    if not actions:
        raise ValueError("at least one action matrix is required")
    for action in actions:
        if len(action) != dimension or len(action[0]) != dimension:
            raise ValueError("every action must be square on the state dimension")
    return actions


def _row_times_matrix(row: Vector, matrix: Matrix) -> Vector:
    if len(row) != len(matrix):
        raise ValueError("row/action dimension mismatch")
    return tuple(
        sum(row[inner] * matrix[inner][column] for inner in range(len(row)))
        for column in range(len(row))
    )


def action_language_observation_rows(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    horizon: int,
) -> Matrix:
    """Unique literal-word observation rows through a finite horizon."""
    observations = _matrix(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    if isinstance(horizon, bool) or not isinstance(horizon, int):
        raise TypeError("horizon must be an integer")
    if horizon < 0:
        raise ValueError("horizon must be nonnegative")

    reached = set(observations)
    frontier = set(observations)
    for _ in range(horizon):
        frontier = {
            _row_times_matrix(row, action)
            for row in frontier
            for action in actions
        }
        reached.update(frontier)
    return tuple(sorted(reached))


def action_language_smith_profile(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    horizon: int,
):
    """Smith/determinantal precision profile of the future word-row lattice."""
    rows = action_language_observation_rows(
        action_matrices,
        observation_rows,
        horizon,
    )
    return integer_smith_precision_profile(rows)


def prime_factor_multiplicity(value: int) -> int:
    """Omega(value), counting prime factors with multiplicity; Omega(1)=0."""
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError("value must be an integer")
    if value <= 0:
        raise ValueError("value must be positive")
    remaining = value
    divisor = 2
    count = 0
    while divisor * divisor <= remaining:
        while remaining % divisor == 0:
            count += 1
            remaining //= divisor
        divisor = 3 if divisor == 2 else divisor + 2
    if remaining > 1:
        count += 1
    return count


@dataclass(frozen=True)
class ActionLanguageClosureStep:
    horizon: int
    rational_rank: int
    hidden_free_rank: int
    saturation_index: int
    smith_factors: tuple[int, ...]


@dataclass(frozen=True)
class ActionLanguageClosureReport:
    state_dimension: int
    initial_rank: int
    rational_stabilization_horizon: int
    rational_stabilization_index: int
    arithmetic_refinement_bound: int
    final_lattice_attainment_bound: int
    exact_integer_stabilization_horizon: int
    steps: tuple[ActionLanguageClosureStep, ...]

    @property
    def delayed_integer_refinement_after_rational_stability(self) -> bool:
        return self.exact_integer_stabilization_horizon > self.rational_stabilization_horizon


def action_language_closure_report(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
) -> ActionLanguageClosureReport:
    """Find exact rational/integer stabilization with a theorem-backed finite bound."""
    observations = _matrix(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    initial_rank = integer_matrix_rank(observations)

    steps: list[ActionLanguageClosureStep] = []

    def append_step(horizon: int) -> ActionLanguageClosureStep:
        profile = action_language_smith_profile(actions, observations, horizon)
        step = ActionLanguageClosureStep(
            horizon=horizon,
            rational_rank=profile.rational_rank,
            hidden_free_rank=profile.hidden_free_rank,
            saturation_index=profile.maximal_nonzero_determinantal_divisor,
            smith_factors=profile.smith_invariant_factors,
        )
        steps.append(step)
        return step

    append_step(0)
    rational_horizon: int | None = None
    rational_index: int | None = None

    # A rational plateau must occur by dimension-initial_rank.  We evaluate one
    # additional horizon to witness the equality of adjacent ranks.
    rational_search_limit = dimension - initial_rank + 1
    for horizon in range(1, rational_search_limit + 1):
        current = append_step(horizon)
        previous = steps[-2]
        if current.rational_rank == previous.rational_rank:
            rational_horizon = horizon - 1
            rational_index = previous.saturation_index
            break
    if rational_horizon is None or rational_index is None:
        raise AssertionError("rational action-language row space missed its dimension bound")

    omega = prime_factor_multiplicity(rational_index)
    attainment_bound = rational_horizon + omega

    # We need one row-lattice snapshot beyond the attainment bound to identify
    # the first equal adjacent pair, which certifies permanent integer closure.
    required_last_horizon = attainment_bound + 1
    for horizon in range(len(steps), required_last_horizon + 1):
        append_step(horizon)

    exact_integer_horizon: int | None = None
    stable_rank = steps[rational_horizon].rational_rank
    previous_index = steps[rational_horizon].saturation_index
    for horizon in range(rational_horizon + 1, len(steps)):
        current = steps[horizon]
        previous = steps[horizon - 1]
        if current.rational_rank != stable_rank:
            raise AssertionError("rational rank increased after its first plateau")
        if previous.saturation_index % current.saturation_index != 0:
            raise AssertionError("same-span lattice refinement violated index divisibility")
        if current.saturation_index == previous.saturation_index:
            exact_integer_horizon = horizon - 1
            break
        previous_index = current.saturation_index

    if exact_integer_horizon is None:
        # If every observed step through bound+1 strictly refined, the number of
        # strict divisor drops would exceed Omega(rational_index).
        raise AssertionError("integer row lattice exceeded prime-factor refinement bound")
    if exact_integer_horizon > attainment_bound:
        raise AssertionError("integer lattice stabilized after its arithmetic bound")

    return ActionLanguageClosureReport(
        state_dimension=dimension,
        initial_rank=initial_rank,
        rational_stabilization_horizon=rational_horizon,
        rational_stabilization_index=rational_index,
        arithmetic_refinement_bound=omega,
        final_lattice_attainment_bound=attainment_bound,
        exact_integer_stabilization_horizon=exact_integer_horizon,
        steps=tuple(steps),
    )
