"""Exact integer row-module closure for finite linear future-action languages.

Literal future-word enumeration is unnecessary once the observable rows are
viewed as a right module over the integer action monoid.

For observation row lattice ``L_h`` generated by all rows ``C A_w`` with
``|w|<=h`` and action matrices ``A_a``, one has exactly

    L_(h+1) = L_h + sum_a L_h A_a.

Therefore a finite integer basis of ``L_h`` is sufficient to generate the next
horizon.  This module uses row Hermite normal form obtained only by unimodular
row operations, so the returned rows generate exactly the same embedded lattice
in the original named state coordinates.

If the reduced basis is unchanged after one closure step, then ``L_h`` is
right-invariant under every declared action and no longer future word can add
information.  This is an exact online stop certificate, not a cutoff heuristic.

The zero observation lattice is a valid extreme precision state: every future
linear observation is zero, hidden free rank is the full state dimension, and
closure is already complete at horizon zero.

The implementation deliberately keeps the embedded row lattice rather than only
its Smith factors: equal abstract precision type does not imply equal precision
placement in the world coordinates.

Hermite normal form, finitely generated Z-modules and action-module closure are
standard prior mathematics.  The project value is eliminating literal word
explosion from the integer P023 future-language compiler.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence

from .integer_action_language_observability import prime_factor_multiplicity
from .integer_future_smith_precision import integer_smith_precision_profile


Vector = tuple[int, ...]
Matrix = tuple[Vector, ...]


def _matrix(values: Iterable[Sequence[int]], *, allow_empty: bool = False) -> Matrix:
    rows = tuple(tuple(row) for row in values)
    if not rows:
        if allow_empty:
            return ()
        raise ValueError("matrix must contain at least one row")
    width = len(rows[0])
    if width == 0 or any(len(row) != width for row in rows):
        raise ValueError("matrix rows must have one common positive width")
    for row in rows:
        for value in row:
            if isinstance(value, bool) or not isinstance(value, int):
                raise TypeError("matrix entries must be integers")
    return rows


def _square_actions(
    values: Sequence[Sequence[Sequence[int]]],
    dimension: int,
) -> tuple[Matrix, ...]:
    actions = tuple(_matrix(matrix) for matrix in values)
    if not actions:
        raise ValueError("at least one action matrix is required")
    if any(len(action) != dimension or len(action[0]) != dimension for action in actions):
        raise ValueError("every action must be square on the state dimension")
    return actions


def _row_times_matrix(row: Vector, matrix: Matrix) -> Vector:
    if len(row) != len(matrix):
        raise ValueError("row/action dimension mismatch")
    return tuple(
        sum(row[inner] * matrix[inner][column] for inner in range(len(row)))
        for column in range(len(row))
    )


def _extended_gcd(left: int, right: int) -> tuple[int, int, int]:
    """Return ``g,s,t`` with ``g>=0`` and ``s*left+t*right=g``."""
    old_r, r = abs(left), abs(right)
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r:
        quotient = old_r // r
        old_r, r = r, old_r - quotient * r
        old_s, s = s, old_s - quotient * s
        old_t, t = t, old_t - quotient * t
    left_sign = 1 if left >= 0 else -1
    right_sign = 1 if right >= 0 else -1
    return old_r, old_s * left_sign, old_t * right_sign


def integer_row_hermite_basis(rows: Iterable[Sequence[int]]) -> Matrix:
    """Canonical row-Hermite basis using only unimodular row operations.

    Zero rows are removed.  The ambient state coordinates are never changed.
    """
    normalized = _matrix(rows, allow_empty=True)
    if not normalized:
        return ()
    work = [list(row) for row in normalized]
    width = len(work[0])
    pivot_row = 0

    for column in range(width):
        nonzero = next(
            (
                row
                for row in range(pivot_row, len(work))
                if work[row][column] != 0
            ),
            None,
        )
        if nonzero is None:
            continue
        work[pivot_row], work[nonzero] = work[nonzero], work[pivot_row]

        # Pairwise extended-gcd transforms are unimodular and replace the pivot
        # entry by the gcd while killing the selected lower entry.
        for row in range(pivot_row + 1, len(work)):
            if work[row][column] == 0:
                continue
            left = work[pivot_row][column]
            right = work[row][column]
            common, s, t = _extended_gcd(left, right)
            old_pivot = work[pivot_row][:]
            old_row = work[row][:]
            work[pivot_row] = [
                s * a + t * b for a, b in zip(old_pivot, old_row, strict=True)
            ]
            work[row] = [
                (-right // common) * a + (left // common) * b
                for a, b in zip(old_pivot, old_row, strict=True)
            ]
            if work[pivot_row][column] != common or work[row][column] != 0:
                raise AssertionError("unimodular gcd elimination failed")

        if work[pivot_row][column] < 0:
            work[pivot_row] = [-value for value in work[pivot_row]]
        pivot = work[pivot_row][column]

        # Reduce entries above the positive pivot to canonical residues.
        for row in range(pivot_row):
            if work[row][column] == 0:
                continue
            quotient = work[row][column] // pivot
            work[row] = [
                a - quotient * b
                for a, b in zip(work[row], work[pivot_row], strict=True)
            ]
            if not 0 <= work[row][column] < pivot:
                raise AssertionError("row-Hermite residue reduction failed")

        pivot_row += 1
        if pivot_row == len(work):
            break

    return tuple(tuple(row) for row in work if any(row))


def action_module_closure_step(
    basis_rows: Sequence[Sequence[int]],
    action_matrices: Sequence[Sequence[Sequence[int]]],
) -> Matrix:
    """Return a row-Hermite basis of ``L + sum_a L A_a``."""
    raw_basis = tuple(tuple(row) for row in basis_rows)
    if raw_basis:
        normalized = _matrix(raw_basis)
        dimension = len(normalized[0])
    else:
        raw_actions = tuple(_matrix(matrix) for matrix in action_matrices)
        if not raw_actions:
            raise ValueError("at least one action matrix is required")
        dimension = len(raw_actions[0])
        if any(len(action) != dimension or len(action[0]) != dimension for action in raw_actions):
            raise ValueError("every action must be square on one common state dimension")
        return ()

    actions = _square_actions(action_matrices, dimension)
    basis = integer_row_hermite_basis(normalized)
    if not basis:
        return ()
    generated = list(basis)
    generated.extend(
        _row_times_matrix(row, action)
        for row in basis
        for action in actions
    )
    return integer_row_hermite_basis(generated)


@dataclass(frozen=True)
class ActionModuleBasisStep:
    horizon: int
    basis: Matrix
    rational_rank: int
    hidden_free_rank: int
    saturation_index: int
    smith_factors: tuple[int, ...]


@dataclass(frozen=True)
class ActionModuleClosureReport:
    state_dimension: int
    initial_basis: Matrix
    rational_stabilization_horizon: int
    rational_stabilization_index: int
    arithmetic_refinement_budget: int
    theorem_attainment_bound: int
    exact_stabilization_horizon: int
    final_basis: Matrix
    steps: tuple[ActionModuleBasisStep, ...]

    @property
    def delayed_integer_refinement_after_rational_stability(self) -> bool:
        return self.exact_stabilization_horizon > self.rational_stabilization_horizon


def action_module_closure_report(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
) -> ActionModuleClosureReport:
    """Iterate only lattice bases until the exact future row module closes."""
    observations = _matrix(observation_rows)
    dimension = len(observations[0])
    actions = _square_actions(action_matrices, dimension)
    basis = integer_row_hermite_basis(observations)

    def zero_step(horizon: int) -> ActionModuleBasisStep:
        return ActionModuleBasisStep(
            horizon=horizon,
            basis=(),
            rational_rank=0,
            hidden_free_rank=dimension,
            saturation_index=1,
            smith_factors=(),
        )

    if not basis:
        # The zero row lattice is already invariant under every linear action.
        return ActionModuleClosureReport(
            state_dimension=dimension,
            initial_basis=(),
            rational_stabilization_horizon=0,
            rational_stabilization_index=1,
            arithmetic_refinement_budget=0,
            theorem_attainment_bound=0,
            exact_stabilization_horizon=0,
            final_basis=(),
            steps=(zero_step(0), zero_step(1)),
        )

    steps: list[ActionModuleBasisStep] = []

    def record(horizon: int, current_basis: Matrix) -> ActionModuleBasisStep:
        profile = integer_smith_precision_profile(current_basis)
        step = ActionModuleBasisStep(
            horizon=horizon,
            basis=current_basis,
            rational_rank=profile.rational_rank,
            hidden_free_rank=profile.hidden_free_rank,
            saturation_index=profile.maximal_nonzero_determinantal_divisor,
            smith_factors=profile.smith_invariant_factors,
        )
        steps.append(step)
        return step

    current = record(0, basis)
    rational_horizon: int | None = None
    rational_index: int | None = None
    theorem_bound: int | None = None
    horizon = 0

    while True:
        next_basis = action_module_closure_step(current.basis, actions)
        next_step = record(horizon + 1, next_basis)

        if next_step.rational_rank == current.rational_rank and rational_horizon is None:
            rational_horizon = horizon
            rational_index = current.saturation_index
            theorem_bound = rational_horizon + prime_factor_multiplicity(rational_index)

        if next_basis == current.basis:
            exact_horizon = horizon
            if rational_horizon is None or rational_index is None or theorem_bound is None:
                rational_horizon = horizon
                rational_index = current.saturation_index
                theorem_bound = rational_horizon + prime_factor_multiplicity(rational_index)
            if exact_horizon > theorem_bound:
                raise AssertionError("basis closure exceeded the arithmetic refinement bound")
            return ActionModuleClosureReport(
                state_dimension=dimension,
                initial_basis=steps[0].basis,
                rational_stabilization_horizon=rational_horizon,
                rational_stabilization_index=rational_index,
                arithmetic_refinement_budget=prime_factor_multiplicity(rational_index),
                theorem_attainment_bound=theorem_bound,
                exact_stabilization_horizon=exact_horizon,
                final_basis=current.basis,
                steps=tuple(steps),
            )

        if rational_horizon is not None:
            if next_step.rational_rank != current.rational_rank:
                raise AssertionError("rational row space increased after its first plateau")
            if current.saturation_index % next_step.saturation_index != 0:
                raise AssertionError("nested same-span lattice index failed divisibility")
            if theorem_bound is not None and horizon + 1 > theorem_bound:
                raise AssertionError("integer action module exceeded theorem closure bound")
        else:
            if next_step.rational_rank <= current.rational_rank:
                raise AssertionError("unrecorded rational plateau")

        horizon += 1
        current = next_step
