"""Exact action-capability redundancy at two integer future-precision levels.

Given current observation rows ``C`` and a finite family of total integer linear
actions ``E``, let ``M(S)`` be the smallest embedded Z-row-lattice containing
``C`` and invariant under every action in subset ``S``.

Two distinct notions of action-language preservation must be separated.

``STATE_KERNEL``
    ``Q span M(S) = Q span M(E)``.  Removing actions does not change which
    integer states are future-distinguishable, but omitted future integer rows
    may require rational/non-unimodular reconstruction.

``INTEGER_MODULE``
    ``M(S) = M(E)`` as embedded Z-lattices.  Every omitted future integer row is
    already an integer combination of retained rows, so coordinate purification
    as well as state distinguishability is preserved.

The second notion implies the first and can be checked without literal words:
a computed module ``M(S)`` equals ``M(E)`` exactly when every omitted action
preserves ``M(S)``.

Neither level has a generic matroid-like basis theorem.  Inclusion-minimal
preserving action families can have unequal cardinalities and need not have one
least subset.  Local one-at-a-time redundancy is also not globally composable.

Sharp unequal-basis witness, with current row ``e1`` in dimension three:

* action A alone generates ``e1,e2,e3`` through powers;
* action B contributes only ``e2`` from ``e1``;
* action C contributes only ``e3`` from ``e1``.

Then ``{A}`` and ``{B,C}`` are both inclusion-minimal full integer-module action
families.  In the full family every action is individually redundant; greedy
deletion can finish with size one or size two depending on deletion order.

A separate two-action witness shows the two precision levels differ.  If action
A gives ``e2`` while action B gives only ``2e2`` from ``e1``, then ``{B}``
preserves full rational state distinction but not the full integer row module.

Finite module generation, redundancy and upward-closed set families are standard
prior mathematics.  The project value is the exact P023 distinction between a
least *state-separating* capability language and a least *integer-reconstructive*
future language.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
from typing import Sequence

from .integer_action_module_closure import (
    action_module_closure_report,
    action_module_closure_step,
    integer_row_hermite_basis,
)
from .integer_future_observability import integer_matrix_rank


Matrix = tuple[tuple[int, ...], ...]
STATE_KERNEL = "STATE_KERNEL"
INTEGER_MODULE = "INTEGER_MODULE"


def _observations(values: Sequence[Sequence[int]]) -> Matrix:
    rows = tuple(tuple(row) for row in values)
    if not rows:
        raise ValueError("observation_rows must be nonempty")
    width = len(rows[0])
    if width == 0 or any(len(row) != width for row in rows):
        raise ValueError("observation rows must have one common positive width")
    for row in rows:
        for value in row:
            if isinstance(value, bool) or not isinstance(value, int):
                raise TypeError("observation entries must be integers")
    return rows


def _actions(
    values: Sequence[Sequence[Sequence[int]]],
    dimension: int,
) -> tuple[Matrix, ...]:
    actions = tuple(tuple(tuple(row) for row in matrix) for matrix in values)
    if not actions:
        raise ValueError("at least one action is required")
    for matrix in actions:
        if len(matrix) != dimension or any(len(row) != dimension for row in matrix):
            raise ValueError("every action must be square on the state dimension")
        for row in matrix:
            for value in row:
                if isinstance(value, bool) or not isinstance(value, int):
                    raise TypeError("action entries must be integers")
    return actions


def _mode(value: str) -> str:
    if value not in (STATE_KERNEL, INTEGER_MODULE):
        raise ValueError("mode must be STATE_KERNEL or INTEGER_MODULE")
    return value


def action_subset_final_basis(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    action_indices: Sequence[int],
) -> Matrix:
    """Exact final embedded future row module generated by one action subset."""
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    indices = tuple(action_indices)
    if len(set(indices)) != len(indices):
        raise ValueError("action_indices must be distinct")
    for index in indices:
        if isinstance(index, bool) or not isinstance(index, int):
            raise TypeError("action index must be an integer")
        if not 0 <= index < len(actions):
            raise ValueError("action index is outside the action family")

    initial = integer_row_hermite_basis(observations)
    if not indices or not initial:
        return initial
    selected = tuple(actions[index] for index in indices)
    return action_module_closure_report(
        selected,
        observations,
    ).final_basis


def action_preserves_row_module(
    action_matrix: Sequence[Sequence[int]],
    basis_rows: Sequence[Sequence[int]],
) -> bool:
    """Whether one action maps an embedded row lattice back into itself."""
    basis = integer_row_hermite_basis(basis_rows)
    if not basis:
        return True
    return action_module_closure_step(
        basis,
        (action_matrix,),
    ) == basis


def action_subset_preserves_integer_module(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    action_indices: Sequence[int],
) -> bool:
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    selected_basis = action_subset_final_basis(
        actions,
        observations,
        action_indices,
    )
    return all(
        action_preserves_row_module(action, selected_basis)
        for action in actions
    )


def action_subset_preserves_state_kernel(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    action_indices: Sequence[int],
) -> bool:
    """Whether a subset induces the same rational future-equality kernel."""
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    selected = action_subset_final_basis(actions, observations, action_indices)
    full = action_subset_final_basis(
        actions,
        observations,
        tuple(range(len(actions))),
    )
    # The selected row space is automatically contained in the full row space,
    # so equality of rational ranks is exactly equality of rational row spaces.
    return integer_matrix_rank(selected) == integer_matrix_rank(full)


def action_subset_preserves(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    action_indices: Sequence[int],
    *,
    mode: str = INTEGER_MODULE,
) -> bool:
    selected_mode = _mode(mode)
    if selected_mode == STATE_KERNEL:
        return action_subset_preserves_state_kernel(
            action_matrices,
            observation_rows,
            action_indices,
        )
    return action_subset_preserves_integer_module(
        action_matrices,
        observation_rows,
        action_indices,
    )


def action_is_redundant_in_family(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    action_index: int,
    *,
    mode: str = INTEGER_MODULE,
) -> bool:
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    if isinstance(action_index, bool) or not isinstance(action_index, int):
        raise TypeError("action_index must be an integer")
    if not 0 <= action_index < len(actions):
        raise ValueError("action_index is outside the action family")
    retained = tuple(index for index in range(len(actions)) if index != action_index)
    return action_subset_preserves(
        actions,
        observations,
        retained,
        mode=mode,
    )


def preserving_action_subsets(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    *,
    mode: str = INTEGER_MODULE,
) -> tuple[tuple[int, ...], ...]:
    """Enumerate all subsets preserving the selected future-precision level."""
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    selected_mode = _mode(mode)
    preserving = []
    for size in range(len(actions) + 1):
        for subset in combinations(range(len(actions)), size):
            if action_subset_preserves(
                actions,
                observations,
                subset,
                mode=selected_mode,
            ):
                preserving.append(subset)
    return tuple(preserving)


def inclusion_minimal_action_subsets(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    *,
    mode: str = INTEGER_MODULE,
) -> tuple[tuple[int, ...], ...]:
    preserving = preserving_action_subsets(
        action_matrices,
        observation_rows,
        mode=mode,
    )
    preserving_sets = {frozenset(subset) for subset in preserving}
    return tuple(
        subset
        for subset in preserving
        if not any(other < frozenset(subset) for other in preserving_sets)
    )


def least_preserving_action_subset(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    *,
    mode: str = INTEGER_MODULE,
) -> tuple[int, ...] | None:
    """Return the unique least subset for one precision level, else ``None``."""
    preserving = preserving_action_subsets(
        action_matrices,
        observation_rows,
        mode=mode,
    )
    common = set(preserving[0])
    for subset in preserving[1:]:
        common.intersection_update(subset)
    candidate = tuple(sorted(common))
    return (
        candidate
        if action_subset_preserves(
            action_matrices,
            observation_rows,
            candidate,
            mode=mode,
        )
        else None
    )


def greedy_redundant_action_deletion(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    deletion_order: Sequence[int],
    *,
    mode: str = INTEGER_MODULE,
) -> tuple[int, ...]:
    """Delete currently redundant actions in one declared order."""
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    order = tuple(deletion_order)
    if set(order) != set(range(len(actions))) or len(order) != len(actions):
        raise ValueError("deletion_order must be a permutation of action indices")
    retained = list(range(len(actions)))
    for action in order:
        if action not in retained:
            continue
        candidate = tuple(index for index in retained if index != action)
        if action_subset_preserves(
            actions,
            observations,
            candidate,
            mode=mode,
        ):
            retained.remove(action)
    return tuple(retained)


@dataclass(frozen=True)
class ActionCapabilityBasisReport:
    action_count: int
    individually_kernel_redundant_actions: tuple[int, ...]
    individually_integer_module_redundant_actions: tuple[int, ...]
    minimal_kernel_preserving_subsets: tuple[tuple[int, ...], ...]
    minimal_integer_module_subsets: tuple[tuple[int, ...], ...]
    least_kernel_subset: tuple[int, ...] | None
    least_integer_module_subset: tuple[int, ...] | None

    @property
    def kernel_minimal_cardinalities(self) -> tuple[int, ...]:
        return tuple(len(subset) for subset in self.minimal_kernel_preserving_subsets)

    @property
    def integer_module_minimal_cardinalities(self) -> tuple[int, ...]:
        return tuple(len(subset) for subset in self.minimal_integer_module_subsets)

    @property
    def unequal_integer_module_minimal_cardinalities(self) -> bool:
        return len(set(self.integer_module_minimal_cardinalities)) > 1


def action_capability_basis_report(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
) -> ActionCapabilityBasisReport:
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    return ActionCapabilityBasisReport(
        action_count=len(actions),
        individually_kernel_redundant_actions=tuple(
            index
            for index in range(len(actions))
            if action_is_redundant_in_family(
                actions,
                observations,
                index,
                mode=STATE_KERNEL,
            )
        ),
        individually_integer_module_redundant_actions=tuple(
            index
            for index in range(len(actions))
            if action_is_redundant_in_family(
                actions,
                observations,
                index,
                mode=INTEGER_MODULE,
            )
        ),
        minimal_kernel_preserving_subsets=inclusion_minimal_action_subsets(
            actions,
            observations,
            mode=STATE_KERNEL,
        ),
        minimal_integer_module_subsets=inclusion_minimal_action_subsets(
            actions,
            observations,
            mode=INTEGER_MODULE,
        ),
        least_kernel_subset=least_preserving_action_subset(
            actions,
            observations,
            mode=STATE_KERNEL,
        ),
        least_integer_module_subset=least_preserving_action_subset(
            actions,
            observations,
            mode=INTEGER_MODULE,
        ),
    )
