"""Exact action-capability redundancy for integer future-observation modules.

Given current observation rows ``C`` and a finite family of total integer linear
actions ``E``, let ``M(S)`` be the smallest embedded Z-row-lattice containing
``C`` and invariant under every action in subset ``S``.

A subset ``S`` preserves the full declared future precision exactly when

    M(S) = M(E).

Equivalently, after computing ``M(S)``, every omitted action preserves that
lattice.  This turns infinite word-language equivalence into a finite lattice
invariance test.

The family of precision-preserving action subsets is upward closed, but its
inclusion-minimal members need not form matroid-like bases: they can have
unequal cardinalities and there need not be one least subset.

A sharp three-action witness has current row ``e1``:

* action A alone generates ``e1,e2,e3`` through repeated powers;
* action B contributes only ``e2`` from ``e1``;
* action C contributes only ``e3`` from ``e1``.

Then both ``{A}`` and ``{B,C}`` are inclusion-minimal full-precision action
families.  In the full family every individual action is locally redundant,
yet deleting locally redundant actions greedily can terminate at either size
one or size two depending on deletion order.

This is standard finite module-generation/redundancy mathematics.  The project
value is the exact P023 boundary: special routes may have a unique least future
action alphabet, but generic integer action languages do not.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
from typing import Sequence

from .integer_action_module_closure import (
    action_module_closure_report,
    action_module_closure_step,
    integer_row_hermite_basis,
)


Matrix = tuple[tuple[int, ...], ...]


def _observations(values: Sequence[Sequence[int]]) -> Matrix:
    rows = tuple(tuple(row) for row in values)
    if not rows:
        raise ValueError("observation_rows must be nonempty")
    width = len(rows[0])
    if width == 0 or any(len(row) != width for row in rows):
        raise ValueError("observation rows must have one common positive width")
    for row in rows:
        for value in row:
            if isinstance(value, bool) or not isinstance(value, int):
                raise TypeError("observation entries must be integers")
    return rows


def _actions(
    values: Sequence[Sequence[Sequence[int]]],
    dimension: int,
) -> tuple[Matrix, ...]:
    actions = tuple(tuple(tuple(row) for row in matrix) for matrix in values)
    if not actions:
        raise ValueError("at least one action is required")
    for matrix in actions:
        if len(matrix) != dimension or any(len(row) != dimension for row in matrix):
            raise ValueError("every action must be square on the state dimension")
        for row in matrix:
            for value in row:
                if isinstance(value, bool) or not isinstance(value, int):
                    raise TypeError("action entries must be integers")
    return actions


def action_subset_final_basis(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    action_indices: Sequence[int],
) -> Matrix:
    """Exact final future row module generated by one action subset."""
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    indices = tuple(action_indices)
    if len(set(indices)) != len(indices):
        raise ValueError("action_indices must be distinct")
    for index in indices:
        if isinstance(index, bool) or not isinstance(index, int):
            raise TypeError("action index must be an integer")
        if not 0 <= index < len(actions):
            raise ValueError("action index is outside the action family")

    initial = integer_row_hermite_basis(observations)
    if not indices or not initial:
        return initial
    selected = tuple(actions[index] for index in indices)
    return action_module_closure_report(
        selected,
        observations,
    ).final_basis


def action_preserves_row_module(
    action_matrix: Sequence[Sequence[int]],
    basis_rows: Sequence[Sequence[int]],
) -> bool:
    """Whether one action maps the embedded row lattice back into itself."""
    basis = integer_row_hermite_basis(basis_rows)
    if not basis:
        return True
    return action_module_closure_step(
        basis,
        (action_matrix,),
    ) == basis


def action_subset_preserves_full_precision(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    action_indices: Sequence[int],
) -> bool:
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    selected_basis = action_subset_final_basis(
        actions,
        observations,
        action_indices,
    )
    return all(
        action_preserves_row_module(action, selected_basis)
        for action in actions
    )


def action_is_redundant_in_family(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    action_index: int,
) -> bool:
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    if isinstance(action_index, bool) or not isinstance(action_index, int):
        raise TypeError("action_index must be an integer")
    if not 0 <= action_index < len(actions):
        raise ValueError("action_index is outside the action family")
    retained = tuple(index for index in range(len(actions)) if index != action_index)
    return action_subset_preserves_full_precision(
        actions,
        observations,
        retained,
    )


def precision_preserving_action_subsets(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
) -> tuple[tuple[int, ...], ...]:
    """Enumerate all subsets with the same infinite future row module."""
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    preserving = []
    for size in range(len(actions) + 1):
        for subset in combinations(range(len(actions)), size):
            if action_subset_preserves_full_precision(
                actions,
                observations,
                subset,
            ):
                preserving.append(subset)
    return tuple(preserving)


def inclusion_minimal_action_subsets(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
) -> tuple[tuple[int, ...], ...]:
    preserving = precision_preserving_action_subsets(
        action_matrices,
        observation_rows,
    )
    preserving_sets = {frozenset(subset) for subset in preserving}
    minimal = []
    for subset in preserving:
        chosen = frozenset(subset)
        if not any(other < chosen for other in preserving_sets):
            minimal.append(subset)
    return tuple(minimal)


def least_precision_preserving_action_subset(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
) -> tuple[int, ...] | None:
    """Return the unique least subset when one exists, otherwise ``None``."""
    preserving = precision_preserving_action_subsets(
        action_matrices,
        observation_rows,
    )
    common = set(preserving[0])
    for subset in preserving[1:]:
        common.intersection_update(subset)
    candidate = tuple(sorted(common))
    return (
        candidate
        if action_subset_preserves_full_precision(
            action_matrices,
            observation_rows,
            candidate,
        )
        else None
    )


def greedy_redundant_action_deletion(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    deletion_order: Sequence[int],
) -> tuple[int, ...]:
    """Delete actions in one declared order whenever precision remains unchanged."""
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    order = tuple(deletion_order)
    if set(order) != set(range(len(actions))) or len(order) != len(actions):
        raise ValueError("deletion_order must be a permutation of action indices")
    retained = list(range(len(actions)))
    for action in order:
        if action not in retained:
            continue
        candidate = tuple(index for index in retained if index != action)
        if action_subset_preserves_full_precision(
            actions,
            observations,
            candidate,
        ):
            retained.remove(action)
    return tuple(retained)


@dataclass(frozen=True)
class ActionCapabilityBasisReport:
    action_count: int
    individually_redundant_actions: tuple[int, ...]
    minimal_precision_preserving_subsets: tuple[tuple[int, ...], ...]
    minimal_cardinalities: tuple[int, ...]
    least_subset: tuple[int, ...] | None

    @property
    def unequal_minimal_cardinalities(self) -> bool:
        return len(set(self.minimal_cardinalities)) > 1

    @property
    def has_unique_least_subset(self) -> bool:
        return self.least_subset is not None


def action_capability_basis_report(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
) -> ActionCapabilityBasisReport:
    observations = _observations(observation_rows)
    dimension = len(observations[0])
    actions = _actions(action_matrices, dimension)
    minimal = inclusion_minimal_action_subsets(actions, observations)
    return ActionCapabilityBasisReport(
        action_count=len(actions),
        individually_redundant_actions=tuple(
            index
            for index in range(len(actions))
            if action_is_redundant_in_family(actions, observations, index)
        ),
        minimal_precision_preserving_subsets=minimal,
        minimal_cardinalities=tuple(len(subset) for subset in minimal),
        least_subset=least_precision_preserving_action_subset(actions, observations),
    )
