"""Finite integer observability closure for a family of linear future actions.

Let the integer state be a column-coordinate vector ``x in Z^n``.  A finite
family of total linear future actions is represented by integer matrices ``A_a``
and a finite current observation family by integer rows ``C``.  With the project
word convention, a literal action word ``w=a_1...a_k`` contributes future
observation rows

    C A_(a_1) ... A_(a_k).

Let ``L_h`` be the Z-row-lattice generated by all such rows for words of length
at most ``h``, and ``W_h=Q span(L_h)``.

The two closures behave differently but both stabilize finitely.

### Rational closure

``W_h`` is ascending.  If one step has

    dim_Q W_(h+1) = dim_Q W_h,

then ``W_h`` is invariant under every declared action matrix: every generator
row in ``W_h`` maps into ``W_(h+1)=W_h``, hence every rational combination does.
Therefore rational rank can never increase later.  Starting at rank ``r_0`` in
state dimension ``n``, the first rational plateau occurs by horizon at most
``n-r_0``.

### Integer closure after rational stabilization

After the rational row space has stabilized, ``L_h`` is an ascending chain of
finite-index sublattices of the fixed saturated lattice ``W cap Z^n``.  Its
index is the maximal nonzero determinantal divisor ``Delta_r(L_h)``.

If ``L_h`` is still strictly enlarged at the next horizon, this index decreases
to a proper positive divisor.  If one step has equal rank and equal index, the
nested lattices are equal; that lattice is action-invariant and no later word can
add a new row-lattice element.

Consequently, if rational stabilization starts at horizon ``h_Q`` with
saturation index ``I``, the final integer row lattice is attained after at most

    Omega(I)

further strict refinement horizons, where ``Omega`` counts prime factors with
multiplicity.  This is a finite arithmetic bound, not an empirical convergence
claim.

### Minimal multi-action witness

In dimension three let

    C = (1,0,0),

and choose actions with

    first row of A = (0,1,0),
    first row of B = (0,0,2),
    second row of B = (0,0,1).

At horizon one the row lattice contains

    e1, e2, 2e3,

so rational rank is already three but saturation index is two.  At horizon two
word ``A B`` contributes ``e3``.  Rank stays three while the index drops from two
to one.  Thus a multi-action future language can continue refining integer
precision after state distinguishability is already complete.

For a single integer action matrix this delayed noncommutative-word mechanism is
absent: Cayley-Hamilton makes all powers beyond ``n-1`` integer combinations of
``I,A,...,A^(n-1)``.  The general multi-action closure studied here is instead a
Z-module generated by a matrix monoid.

Matrix monoids, Noetherian Z-modules, rational invariant subspaces,
determinantal divisors and Cayley-Hamilton are standard prior mathematics.  The
project value is the exact P023 integer future-language closure interpretation.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from math import prod
from typing import Callable, Sequence

from .material_contact_network_impulse_1d import (
    apply_contact_impulse_vector,
    contact_coupling_gram,
    contact_relative_scores,
)
from .material_contact_network_tick_1d import ContactMaterialNetworkTick1D


Matrix = tuple[tuple[int, ...], ...]
Vector = tuple[int, ...]


def _require_int(name: str, value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{name} must be an integer")


def _integer_vector(
    values: Sequence[int],
    *,
    name: str,
    nonnegative: bool = False,
) -> Vector:
    result = tuple(values)
    if not result:
        raise ValueError(f"{name} must be nonempty")
    for value in result:
        _require_int(name, value)
        if nonnegative and value < 0:
            raise ValueError(f"{name} entries must be nonnegative")
    return result


def _square_integer_matrix(
    values: Sequence[Sequence[int]],
    dimension: int,
) -> Matrix:
    rows = tuple(tuple(row) for row in values)
    if len(rows) != dimension or any(len(row) != dimension for row in rows):
        raise ValueError("coupling matrix must match score dimension")
    for row in rows:
        for value in row:
            _require_int("coupling entry", value)
    return rows


def score_after_counts(
    initial_scores: Sequence[int],
    coupling: Sequence[Sequence[int]],
    counts: Sequence[int],
) -> Vector:
    """Return exact contact scores after an unguarded prefix-count vector."""
    scores = _integer_vector(initial_scores, name="initial_scores")
    matrix = _square_integer_matrix(coupling, len(scores))
    prefix = _integer_vector(counts, name="counts", nonnegative=True)
    if len(prefix) != len(scores):
        raise ValueError("counts must match score dimension")
    return tuple(
        scores[row]
        + sum(
            matrix[row][column] * prefix[column]
            for column in range(len(scores))
        )
        for row in range(len(scores))
    )


def enabled_remaining_contacts(
    initial_scores: Sequence[int],
    coupling: Sequence[Sequence[int]],
    prefix_counts: Sequence[int],
    target_counts: Sequence[int],
) -> tuple[int, ...]:
    """Remaining target actions whose current local closing guard is true."""
    scores = _integer_vector(initial_scores, name="initial_scores")
    matrix = _square_integer_matrix(coupling, len(scores))
    prefix = _integer_vector(
        prefix_counts,
        name="prefix_counts",
        nonnegative=True,
    )
    target = _integer_vector(
        target_counts,
        name="target_counts",
        nonnegative=True,
    )
    if len(prefix) != len(scores) or len(target) != len(scores):
        raise ValueError("count vectors must match score dimension")
    if any(used > required for used, required in zip(prefix, target, strict=True)):
        raise ValueError("prefix counts cannot exceed target counts")
    current = score_after_counts(scores, matrix, prefix)
    return tuple(
        index
        for index, (used, required) in enumerate(
            zip(prefix, target, strict=True)
        )
        if used < required and current[index] < 0
    )


def coupling_is_z_matrix(coupling: Sequence[Sequence[int]]) -> bool:
    rows = tuple(tuple(row) for row in coupling)
    if not rows:
        raise ValueError("coupling matrix must be nonempty")
    matrix = _square_integer_matrix(rows, len(rows))
    return all(
        row == column or matrix[row][column] <= 0
        for row in range(len(matrix))
        for column in range(len(matrix))
    )


def coupling_is_diagonal(coupling: Sequence[Sequence[int]]) -> bool:
    rows = tuple(tuple(row) for row in coupling)
    if not rows:
        raise ValueError("coupling matrix must be nonempty")
    matrix = _square_integer_matrix(rows, len(rows))
    return all(
        row == column or matrix[row][column] == 0
        for row in range(len(matrix))
        for column in range(len(matrix))
    )


@dataclass(frozen=True)
class GuardedImpulseRealization:
    target_counts: Vector
    realizable: bool
    word: tuple[int, ...] | None
    visited_count_states: int
    total_count_states: int

    @property
    def delivered_total(self) -> int:
        return sum(self.target_counts)


def exact_guarded_impulse_realization(
    initial_scores: Sequence[int],
    coupling: Sequence[Sequence[int]],
    target_counts: Sequence[int],
) -> GuardedImpulseRealization:
    """Exact BFS on the finite prefix-count lattice."""
    scores = _integer_vector(initial_scores, name="initial_scores")
    matrix = _square_integer_matrix(coupling, len(scores))
    target = _integer_vector(
        target_counts,
        name="target_counts",
        nonnegative=True,
    )
    if len(target) != len(scores):
        raise ValueError("target_counts must match score dimension")

    zero = (0,) * len(target)
    total_states = prod(value + 1 for value in target)
    queue: deque[Vector] = deque([zero])
    predecessor: dict[Vector, tuple[Vector, int] | None] = {zero: None}

    while queue:
        prefix = queue.popleft()
        if prefix == target:
            word: list[int] = []
            current = prefix
            while predecessor[current] is not None:
                previous, action = predecessor[current]
                word.append(action)
                current = previous
            word.reverse()
            return GuardedImpulseRealization(
                target_counts=target,
                realizable=True,
                word=tuple(word),
                visited_count_states=len(predecessor),
                total_count_states=total_states,
            )

        for action in enabled_remaining_contacts(scores, matrix, prefix, target):
            nxt = tuple(
                value + (1 if index == action else 0)
                for index, value in enumerate(prefix)
            )
            if nxt in predecessor:
                continue
            predecessor[nxt] = (prefix, action)
            queue.append(nxt)

    return GuardedImpulseRealization(
        target_counts=target,
        realizable=False,
        word=None,
        visited_count_states=len(predecessor),
        total_count_states=total_states,
    )


def _lowest_enabled(enabled: tuple[int, ...], _: Vector) -> int:
    return enabled[0]


def _highest_enabled(enabled: tuple[int, ...], _: Vector) -> int:
    return enabled[-1]


def _least_used_enabled(enabled: tuple[int, ...], counts: Vector) -> int:
    return min(enabled, key=lambda index: (counts[index], index))


GREEDY_CHOOSERS: dict[str, Callable[[tuple[int, ...], Vector], int]] = {
    "LOWEST": _lowest_enabled,
    "HIGHEST": _highest_enabled,
    "LEAST_USED": _least_used_enabled,
}


@dataclass(frozen=True)
class ZGreedyGuardedRealization:
    target_counts: Vector
    policy: str
    realizable: bool
    word: tuple[int, ...] | None
    stuck_prefix_counts: Vector | None
    stuck_scores: Vector | None


def z_greedy_guarded_realization(
    initial_scores: Sequence[int],
    coupling: Sequence[Sequence[int]],
    target_counts: Sequence[int],
    *,
    policy: str = "LOWEST",
) -> ZGreedyGuardedRealization:
    """Arbitrary-choice greedy decision procedure for Z-coupled systems."""
    scores = _integer_vector(initial_scores, name="initial_scores")
    matrix = _square_integer_matrix(coupling, len(scores))
    target = _integer_vector(
        target_counts,
        name="target_counts",
        nonnegative=True,
    )
    if len(target) != len(scores):
        raise ValueError("target_counts must match score dimension")
    if not coupling_is_z_matrix(matrix):
        raise ValueError("Z-greedy theorem requires nonpositive off-diagonal coupling")
    if policy not in GREEDY_CHOOSERS:
        raise ValueError("unknown greedy policy")

    chooser = GREEDY_CHOOSERS[policy]
    counts: Vector = (0,) * len(target)
    word: list[int] = []
    while counts != target:
        enabled = enabled_remaining_contacts(scores, matrix, counts, target)
        if not enabled:
            return ZGreedyGuardedRealization(
                target_counts=target,
                policy=policy,
                realizable=False,
                word=None,
                stuck_prefix_counts=counts,
                stuck_scores=score_after_counts(scores, matrix, counts),
            )
        action = chooser(enabled, counts)
        counts = tuple(
            value + (1 if index == action else 0)
            for index, value in enumerate(counts)
        )
        word.append(action)

    return ZGreedyGuardedRealization(
        target_counts=target,
        policy=policy,
        realizable=True,
        word=tuple(word),
        stuck_prefix_counts=None,
        stuck_scores=None,
    )


def diagonal_guarded_realizable_closed_form(
    initial_scores: Sequence[int],
    coupling: Sequence[Sequence[int]],
    target_counts: Sequence[int],
) -> bool:
    """Exact independent-contact criterion for arbitrary integer diagonal coupling."""
    scores = _integer_vector(initial_scores, name="initial_scores")
    matrix = _square_integer_matrix(coupling, len(scores))
    target = _integer_vector(
        target_counts,
        name="target_counts",
        nonnegative=True,
    )
    if len(target) != len(scores):
        raise ValueError("target_counts must match score dimension")
    if not coupling_is_diagonal(matrix):
        raise ValueError("closed form requires diagonal coupling")

    return all(
        count == 0
        or max(
            scores[index],
            scores[index] + matrix[index][index] * (count - 1),
        )
        < 0
        for index, count in enumerate(target)
    )


@dataclass(frozen=True)
class BatchedGuardedTickPolicyReport:
    delivered_impulse_vector: Vector
    initial_scores: Vector
    coupling_gram: Matrix
    guarded_realizable: bool
    guarded_word: tuple[int, ...] | None
    batch_after_matches_guarded_after: bool | None
    z_coupled: bool

    @property
    def batch_is_causally_realizable(self) -> bool:
        return self.guarded_realizable


def compare_batched_tick_to_guarded_sequential(
    tick: ContactMaterialNetworkTick1D,
) -> BatchedGuardedTickPolicyReport:
    """Check whether one already-quantized batch vector has a guarded realization."""
    if not isinstance(tick, ContactMaterialNetworkTick1D):
        raise TypeError("tick must be ContactMaterialNetworkTick1D")
    initial_scores = contact_relative_scores(tick.before)
    gram = contact_coupling_gram(tick.before)
    delivered = tick.delivered_impulse_vector
    exact = exact_guarded_impulse_realization(initial_scores, gram, delivered)

    matches: bool | None = None
    if exact.realizable:
        batch_step = apply_contact_impulse_vector(tick.before, delivered)
        if batch_step.after != tick.after:
            raise AssertionError(
                "material batch after-state disagreed with delivered vector"
            )
        matches = True

    return BatchedGuardedTickPolicyReport(
        delivered_impulse_vector=delivered,
        initial_scores=initial_scores,
        coupling_gram=gram,
        guarded_realizable=exact.realizable,
        guarded_word=exact.word,
        batch_after_matches_guarded_after=matches,
        z_coupled=coupling_is_z_matrix(gram),
    )
