"""Two-axis dynamic model separation by future horizon and modular precision.

For two integer linear models with corresponding named actions, let ``D_h`` be
the Z-row module generated by all output-difference rows

    C A_w - E B_w

for words of length at most h.  Define its content

    g_h = gcd(all entries of D_h),

with content zero when ``D_h={0}``.

As h grows, ``D_h`` enlarges and therefore

    g_(h+1) divides g_h

(using the standard convention that every positive integer divides zero).

For a positive modulus M, the models are indistinguishable for every initial
state and every word through horizon h iff

    g_h=0 or M divides g_h.

Thus model separation has two independent refinement axes:

* deeper future language h;
* finer arithmetic precision ordered by modulus divisibility.

The exact content chain can be computed without literal word enumeration.  Use
the block-diagonal paired-model construction, propagate its HNF row module one
action-closure step per horizon, and project each block module to the original
state-space difference module.  Equality of one block HNF step is a permanent
stop certificate.

This is standard module/congruence arithmetic.  The project value is the exact
future-depth x arithmetic-precision separation frontier.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from .integer_action_module_closure import (
    action_module_closure_step,
    integer_row_hermite_basis,
)
from .integer_dynamic_model_separation import (
    _paired_models,
    block_diagonal_action,
    block_difference_observation_rows,
    project_block_difference_rows,
    row_module_content,
)


Matrix = tuple[tuple[int, ...], ...]


@dataclass(frozen=True)
class DynamicSeparationHorizonStep:
    horizon: int
    block_future_basis: Matrix
    difference_basis: Matrix
    difference_content: int

    def indistinguishable_modulus(self, modulus: int) -> bool:
        if isinstance(modulus, bool) or not isinstance(modulus, int):
            raise TypeError("modulus must be an integer")
        if modulus <= 0:
            raise ValueError("modulus must be positive")
        return self.difference_content == 0 or self.difference_content % modulus == 0


@dataclass(frozen=True)
class DynamicSeparationHorizonReport:
    state_dimension: int
    exact_block_stabilization_horizon: int
    final_difference_content: int
    steps: tuple[DynamicSeparationHorizonStep, ...]

    def first_distinguishing_horizon(self, modulus: int) -> int | None:
        for step in self.steps:
            if not step.indistinguishable_modulus(modulus):
                return step.horizon
        return None

    def indistinguishable_moduli_through_horizon(
        self,
        horizon: int,
        candidate_moduli: Sequence[int],
    ) -> tuple[int, ...]:
        if isinstance(horizon, bool) or not isinstance(horizon, int):
            raise TypeError("horizon must be an integer")
        if horizon < 0:
            raise ValueError("horizon must be nonnegative")
        step = next(
            (
                item
                for item in reversed(self.steps)
                if item.horizon <= horizon
            ),
            None,
        )
        if step is None:
            raise AssertionError("dynamic separation report lost horizon zero")
        return tuple(
            modulus
            for modulus in candidate_moduli
            if step.indistinguishable_modulus(modulus)
        )


def dynamic_model_separation_horizon_report(
    left_actions: Sequence[Sequence[Sequence[int]]],
    left_observations: Sequence[Sequence[int]],
    right_actions: Sequence[Sequence[Sequence[int]]],
    right_observations: Sequence[Sequence[int]],
) -> DynamicSeparationHorizonReport:
    left, left_rows, right, right_rows = _paired_models(
        left_actions,
        left_observations,
        right_actions,
        right_observations,
    )
    dimension = len(left_rows[0])
    block_actions = tuple(
        block_diagonal_action(left_action, right_action)
        for left_action, right_action in zip(left, right, strict=True)
    )
    current = integer_row_hermite_basis(
        block_difference_observation_rows(left_rows, right_rows)
    )
    steps = []
    horizon = 0
    previous_content: int | None = None

    def record(level: int, block_basis: Matrix) -> int:
        difference = project_block_difference_rows(block_basis, dimension)
        content = row_module_content(difference)
        if previous_content is not None:
            if previous_content != 0 and previous_content % content != 0:
                raise AssertionError("dynamic difference content failed divisibility refinement")
        steps.append(
            DynamicSeparationHorizonStep(
                horizon=level,
                block_future_basis=block_basis,
                difference_basis=difference,
                difference_content=content,
            )
        )
        return content

    previous_content = record(0, current)
    while True:
        nxt = action_module_closure_step(current, block_actions)
        next_content = record(horizon + 1, nxt)
        if nxt == current:
            return DynamicSeparationHorizonReport(
                state_dimension=dimension,
                exact_block_stabilization_horizon=horizon,
                final_difference_content=previous_content,
                steps=tuple(steps),
            )
        horizon += 1
        current = nxt
        previous_content = next_content
