"""Compositional synergy in integer future-action capability rank.

For current observation rows ``C`` and action subset ``S``, define

    f(S) = rank_Q M(S),

where ``M(S)`` is the exact closed future row module generated by ``S``.
Because action subsets only enlarge the word language, ``f`` is monotone.
It is not submodular in general: one action can create a state direction that a
second action can only exploit after the first direction exists.

Sharp dimension-three witness with current row ``e1``:

* A maps ``e1`` to ``e2``;
* B maps ``e1`` to zero but maps ``e2`` to ``e3``.

Then

    f(empty)=1,
    f({A})=2,
    f({B})=1,
    f({A,B})=3.

The marginal gain of A is one over the empty context but two over context {B},
violating diminishing returns.  Equivalently B has zero gain alone and positive
gain after A.

Thus generic future-capability selection is not a matroid/submodular rank problem.
Static one-action gain cannot be used as an intrinsic precision value.  This is
standard semigroup/module synergy; the project value is the exact P023 future-
language boundary and its contrast with special routes that admit a unique least
action alphabet.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
from typing import Sequence

from .integer_action_capability_basis import action_subset_final_basis
from .integer_future_observability import integer_matrix_rank


Matrix = tuple[tuple[int, ...], ...]


def action_subset_state_rank(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    action_indices: Sequence[int],
) -> int:
    basis = action_subset_final_basis(
        action_matrices,
        observation_rows,
        action_indices,
    )
    return integer_matrix_rank(basis)


def action_marginal_state_rank_gain(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
    base_indices: Sequence[int],
    added_action: int,
) -> int:
    base = tuple(base_indices)
    if added_action in base:
        return 0
    before = action_subset_state_rank(
        action_matrices,
        observation_rows,
        base,
    )
    after = action_subset_state_rank(
        action_matrices,
        observation_rows,
        tuple((*base, added_action)),
    )
    if after < before:
        raise AssertionError("action addition unexpectedly lowered future state rank")
    return after - before


@dataclass(frozen=True)
class RankSubmodularityViolation:
    smaller_context: tuple[int, ...]
    larger_context: tuple[int, ...]
    added_action: int
    gain_on_smaller: int
    gain_on_larger: int


def first_rank_submodularity_violation(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
) -> RankSubmodularityViolation | None:
    """Return one exact diminishing-returns violation, if the finite family has one."""
    action_count = len(tuple(action_matrices))
    all_indices = tuple(range(action_count))
    subsets = tuple(
        subset
        for size in range(action_count + 1)
        for subset in combinations(all_indices, size)
    )
    for smaller in subsets:
        smaller_set = set(smaller)
        for larger in subsets:
            larger_set = set(larger)
            if not smaller_set.issubset(larger_set):
                continue
            for action in all_indices:
                if action in larger_set:
                    continue
                small_gain = action_marginal_state_rank_gain(
                    action_matrices,
                    observation_rows,
                    smaller,
                    action,
                )
                large_gain = action_marginal_state_rank_gain(
                    action_matrices,
                    observation_rows,
                    larger,
                    action,
                )
                if small_gain < large_gain:
                    return RankSubmodularityViolation(
                        smaller_context=smaller,
                        larger_context=larger,
                        added_action=action,
                        gain_on_smaller=small_gain,
                        gain_on_larger=large_gain,
                    )
    return None


def state_rank_is_monotone_over_action_subsets(
    action_matrices: Sequence[Sequence[Sequence[int]]],
    observation_rows: Sequence[Sequence[int]],
) -> bool:
    action_count = len(tuple(action_matrices))
    all_indices = tuple(range(action_count))
    subsets = tuple(
        subset
        for size in range(action_count + 1)
        for subset in combinations(all_indices, size)
    )
    ranks = {
        subset: action_subset_state_rank(
            action_matrices,
            observation_rows,
            subset,
        )
        for subset in subsets
    }
    for left in subsets:
        for right in subsets:
            if set(left).issubset(right) and ranks[left] > ranks[right]:
                raise AssertionError("future state rank failed action-set monotonicity")
    return True
