"""Dimension families generated by one repeated LEGO occupancy law.

A context-free identical added block is described by an integer occupancy profile
k(c): the number of admissible one-block causal states carrying c units.  If
blocks compose independently at this layer, all dimension rows are generated by
repeated finite LEGO composition

    G_(m+1)(c) = sum_a G_m(a) k(c-a).

No generating function is primitive.  Ordinary repeated convolution/powers are
counting shadows of repeated identical block composition.

Special cases:
* k(c)=1 for all c: unrestricted occupancy, stars-and-bars rows;
* k=(1,1,0,...): at most one unit per block, binomial rows;
* general nonnegative k: occupancy-dependent internal-state multiplicity.
"""

from __future__ import annotations

from math import comb

from .lego_dimension_kernel import apply_dimension_kernel, recover_dimension_kernel


def truncate_profile(profile: tuple[int, ...], length: int) -> tuple[int, ...]:
    if not isinstance(profile, tuple) or not profile:
        raise ValueError("profile must be a non-empty tuple")
    if isinstance(length, bool) or not isinstance(length, int) or length <= 0:
        raise ValueError("length must be a positive integer")
    return tuple(profile[index] if index < len(profile) else 0 for index in range(length))


def generate_dimension_rows(
    occupancy_profile: tuple[int, ...],
    maximum_dimension: int,
    maximum_total: int,
) -> tuple[tuple[int, ...], ...]:
    """Generate rows G_1..G_M from one repeated occupancy profile."""
    if isinstance(maximum_dimension, bool) or not isinstance(maximum_dimension, int) or maximum_dimension <= 0:
        raise ValueError("maximum_dimension must be a positive integer")
    if isinstance(maximum_total, bool) or not isinstance(maximum_total, int) or maximum_total < 0:
        raise ValueError("maximum_total must be a non-negative integer")
    length = maximum_total + 1
    kernel = truncate_profile(occupancy_profile, length)
    if kernel[0] != 1:
        raise ValueError("occupancy profile must have one empty-block state: k(0)=1")
    rows = [kernel]
    while len(rows) < maximum_dimension:
        rows.append(apply_dimension_kernel(rows[-1], kernel))
    return tuple(rows)


def unrestricted_occupancy_profile(maximum_total: int) -> tuple[int, ...]:
    if isinstance(maximum_total, bool) or not isinstance(maximum_total, int) or maximum_total < 0:
        raise ValueError("maximum_total must be a non-negative integer")
    return tuple(1 for _ in range(maximum_total + 1))


def hard_single_occupancy_profile(maximum_total: int) -> tuple[int, ...]:
    if isinstance(maximum_total, bool) or not isinstance(maximum_total, int) or maximum_total < 0:
        raise ValueError("maximum_total must be a non-negative integer")
    return tuple(1 if total <= 1 else 0 for total in range(maximum_total + 1))


def expected_unrestricted_row(dimension: int, maximum_total: int) -> tuple[int, ...]:
    if isinstance(dimension, bool) or not isinstance(dimension, int) or dimension <= 0:
        raise ValueError("dimension must be a positive integer")
    return tuple(comb(total + dimension - 1, dimension - 1) for total in range(maximum_total + 1))


def expected_hard_single_row(dimension: int, maximum_total: int) -> tuple[int, ...]:
    if isinstance(dimension, bool) or not isinstance(dimension, int) or dimension <= 0:
        raise ValueError("dimension must be a positive integer")
    return tuple(comb(dimension, total) if total <= dimension else 0 for total in range(maximum_total + 1))


def recover_shared_kernel_from_rows(
    rows: tuple[tuple[int, ...], ...],
) -> tuple[int, ...]:
    """Recover and require one common dimension-raising kernel across all adjacent rows."""
    if not isinstance(rows, tuple) or len(rows) < 2:
        raise ValueError("at least two dimension rows are required")
    length = len(rows[0])
    if any(len(row) != length for row in rows):
        raise ValueError("all rows must have equal truncation length")
    recovered = tuple(
        recover_dimension_kernel(rows[index], rows[index + 1])
        for index in range(len(rows) - 1)
    )
    first = recovered[0]
    if any(kernel != first for kernel in recovered[1:]):
        raise ValueError("dimension rows do not share one context-free occupancy kernel")
    return first


def nonnegative_multiplicity_profile(profile: tuple[int, ...]) -> bool:
    """Necessary condition for interpreting a recovered kernel as state multiplicity."""
    return all(
        not isinstance(value, bool) and isinstance(value, int) and value >= 0
        for value in profile
    )
