"""Multiquadratic state-language complexity of exact material momentum radicals.

Exact material work prefixes can require momentum values of the form

    (a/b) * sqrt(s)

with squarefree positive integer radicand s.  A single quadratic radicand only
requires one quadratic extension, but a profile can expose several radicands at
different material depths.

For squarefree integers, independence of the corresponding quadratic extensions
is measured by prime-exponent parity vectors over F_2.  Let r be the F_2 rank of
the vectors for all required radicands.  The multiquadratic field generated by
the radicals has exact degree

    2^r

over Q.  Radicands related by multiplication modulo squares do not add another
independent dimension; for example {2,3,6} has rank 2 and field degree 4.

This module treats that degree as an E001 exact-state-language complexity metric.
It does not claim that multiquadratic values are the preferred final physical
representation.  The field-degree theorem is standard algebra; the project use
is to quantify the cost of refusing momentum projection for one material profile.
"""

from __future__ import annotations

from dataclasses import dataclass

from .material_force_work import FiniteForceLaw
from .material_work_momentum_closure import material_return_radical_spectrum


def _positive(name: str, value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ValueError(f"{name} must be a positive integer")


def squarefree_prime_support(radicand: int) -> tuple[int, ...]:
    """Return the prime support of one positive squarefree radicand."""
    _positive("radicand", radicand)
    value = radicand
    primes: list[int] = []
    p = 2
    while p * p <= value:
        if value % p == 0:
            exponent = 0
            while value % p == 0:
                value //= p
                exponent += 1
            if exponent != 1:
                raise ValueError("radicand must be squarefree")
            primes.append(p)
        p += 1
    if value > 1:
        primes.append(value)
    product = 1
    for prime in primes:
        product *= prime
    if product != radicand:
        raise ValueError("radicand must be squarefree")
    return tuple(primes)


def _gf2_rank(bit_rows: tuple[int, ...]) -> int:
    basis: dict[int, int] = {}
    rank = 0
    for row in bit_rows:
        value = row
        while value:
            pivot = value.bit_length() - 1
            if pivot in basis:
                value ^= basis[pivot]
            else:
                basis[pivot] = value
                rank += 1
                break
    return rank


@dataclass(frozen=True)
class RadicalFieldComplexity:
    radicands: tuple[int, ...]
    prime_basis: tuple[int, ...]
    parity_vectors: tuple[int, ...]
    radical_rank: int
    exact_field_degree: int
    independent_radicand_witnesses: tuple[int, ...]


def radical_field_complexity(
    radicands: tuple[int, ...] | list[int],
) -> RadicalFieldComplexity:
    """Return the F2 radical rank and exact multiquadratic field degree."""
    values = tuple(sorted(set(radicands)))
    if not values:
        raise ValueError("at least one radicand is required")
    supports = {value: squarefree_prime_support(value) for value in values}
    primes = tuple(sorted({prime for support in supports.values() for prime in support}))
    index = {prime: bit for bit, prime in enumerate(primes)}
    rows: list[int] = []
    independent: list[int] = []
    basis: dict[int, int] = {}
    for value in values:
        mask = 0
        for prime in supports[value]:
            mask ^= 1 << index[prime]
        rows.append(mask)
        reduced = mask
        while reduced:
            pivot = reduced.bit_length() - 1
            if pivot in basis:
                reduced ^= basis[pivot]
            else:
                basis[pivot] = reduced
                independent.append(value)
                break
    rank = _gf2_rank(tuple(rows))
    if rank != len(independent):
        raise AssertionError("independent radical witnesses disagree with GF2 rank")
    return RadicalFieldComplexity(
        radicands=values,
        prime_basis=primes,
        parity_vectors=tuple(rows),
        radical_rank=rank,
        exact_field_degree=1 << rank,
        independent_radicand_witnesses=tuple(independent),
    )


@dataclass(frozen=True)
class MaterialRadicalFieldComplexity:
    radicands_by_depth: tuple[int, ...]
    radical_field: RadicalFieldComplexity
    represented_depth_count: int
    algebraic_depth_count: int


def material_radical_field_complexity(
    law: FiniteForceLaw,
    momentum_scale_factor: int = 1,
    mass_scale_factor: int = 1,
    mass_count: int = 1,
) -> MaterialRadicalFieldComplexity:
    spectrum = material_return_radical_spectrum(
        law,
        momentum_scale_factor=momentum_scale_factor,
        mass_scale_factor=mass_scale_factor,
        mass_count=mass_count,
    )
    field = radical_field_complexity(spectrum.radicands_by_depth)
    return MaterialRadicalFieldComplexity(
        radicands_by_depth=spectrum.radicands_by_depth,
        radical_field=field,
        represented_depth_count=len(spectrum.radicands_by_depth),
        algebraic_depth_count=len(spectrum.algebraic_depths),
    )
