"""Exact additive future-policy precision from joint component-sum observations.

A family of future material transfer graphs does not, in general, reduce to the
common refinement of pairwise connectivity partitions when the ledger state is
additive.  The correct object is the joint integer observation matrix.

For each possible future transfer graph ``G_i``, let its connected components be
``C``.  Each component contributes one integer row ``1_C`` measuring the total
ledger content in that component.  Stack all such rows into

    S : Z^V -> Z^m.

Two current ledgers ``ell,ell'`` are indistinguishable by **all** declared future
component-total observations exactly when

    S(ell-ell') = 0.

Equivalently the hidden difference lattice is

    ker_Z S
      = intersection_i im_Z D_i,

where ``D_i`` is any oriented incidence matrix for future transfer graph ``G_i``:
integer graph-incidence image is exactly the set of vectors whose total on each
connected component is zero.

Thus the exact additive future quotient is controlled by the joint observation
kernel, not merely by pairwise compartment equivalence.  The minimal number of
independent scalar linear coordinates is ``rank_Q(S)``; hidden free rank is
``|V|-rank_Q(S)``.

### Why connectivity-meet blocks can overrefine

With four compartments and future partitions

    {0,1}|{2,3},
    {0,2}|{1,3},

the connectivity-equivalence meet is four singletons.  Nevertheless

    d=(1,-1,-1,1)

has zero total on every component of both future partitions, so ``S d=0``.
Keeping all four singleton totals is safe but not minimal; the joint observation
rank is only three.

### A second, separate integer-coordinate issue

Even when ``ker S=0`` (future totals uniquely determine the current ledger), the
integer row lattice generated by future component indicators need not be a
unimodular coordinate lattice.  The gcd of all nonzero maximal minors is the
index of the row lattice inside its rational saturation.  For full column rank,
index greater than one means reconstruction from a chosen independent family of
future totals necessarily encounters a non-unimodular integer coordinate
change / rational denominator somewhere.

Example: the three pair partitions of four compartments

    01|23, 02|13, 03|12

jointly determine the full four-entry ledger, but their component-indicator row
lattice has saturation index 2.  This is a coordinate/representation obstruction,
not hidden-state ambiguity.

The module therefore reports separately:

* joint observation rank / hidden kernel rank;
* a safe but possibly overfine connectivity-meet block count;
* row-lattice saturation index.

This is standard integer linear algebra and graph-incidence theory.  The project
value is correcting the future-policy precision boundary and preserving the
same kernel-vs-torsion distinction already seen in contact-network research.
"""

from __future__ import annotations

from fractions import Fraction
from itertools import combinations
from math import gcd
from typing import Hashable, Iterable, Mapping, Sequence

from .material_ledger_transfer_graph import TransferEdge, transfer_graph_components


Compartment = Hashable
Vector = tuple[int, ...]
Matrix = tuple[tuple[int, ...], ...]


def _vertices(values: Iterable[Compartment]) -> tuple[Compartment, ...]:
    result = tuple(values)
    if not result:
        raise ValueError("at least one compartment is required")
    if len(set(result)) != len(result):
        raise ValueError("compartment names must be unique")
    return result


def _future_graphs(
    values: Sequence[Iterable[TransferEdge]],
) -> tuple[tuple[TransferEdge, ...], ...]:
    result = tuple(tuple(edges) for edges in values)
    if not result:
        raise ValueError("at least one future transfer graph is required")
    return result


def joint_future_component_sum_matrix(
    compartments: Iterable[Compartment],
    future_transfer_graphs: Sequence[Iterable[TransferEdge]],
) -> Matrix:
    """Stack every future connected-component indicator row."""
    vertices = _vertices(compartments)
    graphs = _future_graphs(future_transfer_graphs)
    index = {vertex: position for position, vertex in enumerate(vertices)}
    rows: list[Vector] = []
    for edges in graphs:
        for component in transfer_graph_components(vertices, edges):
            row = [0] * len(vertices)
            for vertex in component:
                row[index[vertex]] = 1
            rows.append(tuple(row))
    return tuple(rows)


def apply_integer_matrix(matrix: Matrix, vector: Sequence[int]) -> Vector:
    values = tuple(vector)
    if not matrix:
        raise ValueError("matrix must contain at least one row")
    width = len(matrix[0])
    if len(values) != width:
        raise ValueError("vector width does not match matrix")
    if any(len(row) != width for row in matrix):
        raise ValueError("matrix rows must have equal width")
    for value in values:
        if isinstance(value, bool) or not isinstance(value, int):
            raise TypeError("vector entries must be integers")
    return tuple(
        sum(coefficient * value for coefficient, value in zip(row, values, strict=True))
        for row in matrix
    )


def joint_future_component_sum_signature(
    compartments: Iterable[Compartment],
    future_transfer_graphs: Sequence[Iterable[TransferEdge]],
    ledger: Mapping[Compartment, int],
) -> Vector:
    """All future graph component totals, including linearly redundant rows."""
    vertices = _vertices(compartments)
    if set(ledger) != set(vertices):
        raise ValueError("ledger must define exactly one value per compartment")
    vector = []
    for vertex in vertices:
        value = ledger[vertex]
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            raise ValueError("ledger entries must be nonnegative integers")
        vector.append(value)
    matrix = joint_future_component_sum_matrix(vertices, future_transfer_graphs)
    return apply_integer_matrix(matrix, vector)


def _matrix_rank_fraction(matrix: Matrix) -> int:
    if not matrix:
        return 0
    width = len(matrix[0])
    work = [[Fraction(value) for value in row] for row in matrix]
    rank = 0
    for column in range(width):
        pivot = next(
            (row for row in range(rank, len(work)) if work[row][column] != 0),
            None,
        )
        if pivot is None:
            continue
        work[rank], work[pivot] = work[pivot], work[rank]
        pivot_value = work[rank][column]
        work[rank] = [value / pivot_value for value in work[rank]]
        for row in range(len(work)):
            if row == rank:
                continue
            factor = work[row][column]
            if factor == 0:
                continue
            work[row] = [
                left - factor * right
                for left, right in zip(work[row], work[rank], strict=True)
            ]
        rank += 1
        if rank == len(work):
            break
    return rank


def joint_future_component_sum_rank(
    compartments: Iterable[Compartment],
    future_transfer_graphs: Sequence[Iterable[TransferEdge]],
) -> int:
    return _matrix_rank_fraction(
        joint_future_component_sum_matrix(compartments, future_transfer_graphs)
    )


def independent_joint_future_rows(
    compartments: Iterable[Compartment],
    future_transfer_graphs: Sequence[Iterable[TransferEdge]],
) -> Matrix:
    """Greedily select original component rows spanning the same Q-row-space."""
    matrix = joint_future_component_sum_matrix(compartments, future_transfer_graphs)
    selected: list[Vector] = []
    current_rank = 0
    for row in matrix:
        candidate = tuple((*selected, row))
        candidate_rank = _matrix_rank_fraction(candidate)
        if candidate_rank > current_rank:
            selected.append(row)
            current_rank = candidate_rank
    return tuple(selected)


def minimal_linear_future_signature(
    compartments: Iterable[Compartment],
    future_transfer_graphs: Sequence[Iterable[TransferEdge]],
    ledger: Mapping[Compartment, int],
) -> Vector:
    """A rank-sized integer signature with exactly the same equality kernel as all future totals."""
    vertices = _vertices(compartments)
    if set(ledger) != set(vertices):
        raise ValueError("ledger must define exactly one value per compartment")
    vector = tuple(ledger[vertex] for vertex in vertices)
    if any(isinstance(value, bool) or not isinstance(value, int) for value in vector):
        raise TypeError("ledger entries must be integers")
    rows = independent_joint_future_rows(vertices, future_transfer_graphs)
    return apply_integer_matrix(rows, vector)


def difference_hidden_from_all_future_component_totals(
    compartments: Iterable[Compartment],
    future_transfer_graphs: Sequence[Iterable[TransferEdge]],
    difference: Sequence[int],
) -> bool:
    """Exact joint-kernel test for an integer ledger difference."""
    vertices = _vertices(compartments)
    values = tuple(difference)
    if len(values) != len(vertices):
        raise ValueError("difference must match compartment count")
    matrix = joint_future_component_sum_matrix(vertices, future_transfer_graphs)
    return not any(apply_integer_matrix(matrix, values))


def difference_is_redistribution_in_every_future_graph(
    compartments: Iterable[Compartment],
    future_transfer_graphs: Sequence[Iterable[TransferEdge]],
    difference: Sequence[int],
) -> bool:
    """Graph form of the same hidden-kernel condition using component zero-sums."""
    vertices = _vertices(compartments)
    graphs = _future_graphs(future_transfer_graphs)
    values = tuple(difference)
    if len(values) != len(vertices):
        raise ValueError("difference must match compartment count")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in values):
        raise TypeError("difference entries must be integers")
    index = {vertex: position for position, vertex in enumerate(vertices)}
    return all(
        all(
            sum(values[index[vertex]] for vertex in component) == 0
            for component in transfer_graph_components(vertices, edges)
        )
        for edges in graphs
    )


def _bareiss_determinant(square: Matrix) -> int:
    size = len(square)
    if size == 0:
        return 1
    if any(len(row) != size for row in square):
        raise ValueError("determinant requires a square matrix")
    work = [list(row) for row in square]
    sign = 1
    previous = 1
    for pivot_index in range(size - 1):
        if work[pivot_index][pivot_index] == 0:
            replacement = next(
                (
                    row
                    for row in range(pivot_index + 1, size)
                    if work[row][pivot_index] != 0
                ),
                None,
            )
            if replacement is None:
                return 0
            work[pivot_index], work[replacement] = (
                work[replacement],
                work[pivot_index],
            )
            sign *= -1
        pivot = work[pivot_index][pivot_index]
        for row in range(pivot_index + 1, size):
            for column in range(pivot_index + 1, size):
                numerator = (
                    work[row][column] * pivot
                    - work[row][pivot_index] * work[pivot_index][column]
                )
                if numerator % previous != 0:
                    raise AssertionError("Bareiss division lost exactness")
                work[row][column] = numerator // previous
            work[row][pivot_index] = 0
        previous = pivot
    return sign * work[-1][-1]


def maximal_minor_gcd(matrix: Matrix) -> int:
    """Gcd of all nonzero maximal-rank minors; saturation index of the row lattice."""
    if not matrix:
        return 1
    rank = _matrix_rank_fraction(matrix)
    if rank == 0:
        return 1
    row_count = len(matrix)
    column_count = len(matrix[0])
    common = 0
    for row_indices in combinations(range(row_count), rank):
        for column_indices in combinations(range(column_count), rank):
            square = tuple(
                tuple(matrix[row][column] for column in column_indices)
                for row in row_indices
            )
            determinant = abs(_bareiss_determinant(square))
            if determinant:
                common = gcd(common, determinant)
                if common == 1:
                    return 1
    if common == 0:
        raise AssertionError("rank-positive matrix had no nonzero maximal minor")
    return common


def future_component_observation_saturation_index(
    compartments: Iterable[Compartment],
    future_transfer_graphs: Sequence[Iterable[TransferEdge]],
) -> int:
    return maximal_minor_gcd(
        joint_future_component_sum_matrix(compartments, future_transfer_graphs)
    )


def pairwise_connectivity_meet_blocks(
    compartments: Iterable[Compartment],
    future_transfer_graphs: Sequence[Iterable[TransferEdge]],
) -> tuple[frozenset[Compartment], ...]:
    """Safe combinatorial upper bound: compartments connected in every future graph.

    These blocks exactly classify single-unit placements by pairwise connectivity,
    but one total per block may overrefine a general additive ledger because
    balanced multi-compartment differences can remain in the joint kernel.
    """
    vertices = _vertices(compartments)
    graphs = _future_graphs(future_transfer_graphs)
    component_maps = []
    for edges in graphs:
        components = transfer_graph_components(vertices, edges)
        component_maps.append(
            {vertex: component for component in components for vertex in component}
        )
    groups: dict[tuple[frozenset[Compartment], ...], set[Compartment]] = {}
    for vertex in vertices:
        signature = tuple(mapping[vertex] for mapping in component_maps)
        groups.setdefault(signature, set()).add(vertex)
    return tuple(
        sorted(
            (frozenset(group) for group in groups.values()),
            key=lambda block: tuple(sorted(map(repr, block))),
        )
    )


class FutureTransferLatticeReport(tuple):
    """Small immutable report tuple with named accessors kept dependency-free."""

    __slots__ = ()

    @property
    def compartment_count(self) -> int:
        return self[0]

    @property
    def joint_observation_rank(self) -> int:
        return self[1]

    @property
    def hidden_difference_rank(self) -> int:
        return self[2]

    @property
    def connectivity_meet_block_count(self) -> int:
        return self[3]

    @property
    def row_lattice_saturation_index(self) -> int:
        return self[4]

    @property
    def joint_observation_injective(self) -> bool:
        return self.joint_observation_rank == self.compartment_count

    @property
    def injective_but_nonunimodular(self) -> bool:
        return (
            self.joint_observation_injective
            and self.row_lattice_saturation_index > 1
        )


def future_transfer_lattice_report(
    compartments: Iterable[Compartment],
    future_transfer_graphs: Sequence[Iterable[TransferEdge]],
) -> FutureTransferLatticeReport:
    vertices = _vertices(compartments)
    matrix = joint_future_component_sum_matrix(vertices, future_transfer_graphs)
    rank = _matrix_rank_fraction(matrix)
    meet = pairwise_connectivity_meet_blocks(vertices, future_transfer_graphs)
    saturation_index = maximal_minor_gcd(matrix)
    return FutureTransferLatticeReport(
        (
            len(vertices),
            rank,
            len(vertices) - rank,
            len(meet),
            saturation_index,
        )
    )
