"""Exact compatibility window between spatial collapse depth and material depth.

A finite E001 material profile represents deformation depths

    0,...,K,

where ``K=len(profile.loading)-1``.  A positive primitive spatial gap ``g`` at
collapse factor ``d`` generates coarse-only interaction depth

    k=d-g

whenever ``d>g``.

Therefore a coarse contact is materially represented exactly when

    1 <= d-g <= K,

or equivalently

    g+1 <= d <= g+K.

If ``d<=g`` the coarse layer is absent/resolved.  If ``d>g+K`` the spatial world
asks for a material depth that does not exist at the current material precision.
The correct result is an explicit incompatibility, not saturation/clamping to K.

When the material base comes from the intrinsic projected-peak construction, K
is itself finite and derived from the oscillator turning point, yielding a
fully integer spatial/material precision contract.
"""

from __future__ import annotations

from dataclasses import dataclass

from .material_peak_profile import IntrinsicPeakMaterialProfile
from .material_response import MaterialCurveProfile

RESOLVED = "RESOLVED"
REPRESENTED_CONTACT = "REPRESENTED_CONTACT"
MATERIAL_UNDERRESOLVED = "MATERIAL_UNDERRESOLVED"


@dataclass(frozen=True)
class MaterialPrecisionCompatibility:
    """One spatial-factor/material-depth compatibility classification."""

    primitive_gap: int
    collapse_factor: int
    max_material_depth: int
    generated_depth: int | None
    status: str
    finest_contact_factor: int
    coarsest_represented_contact_factor: int


def _validate_gap_factor(primitive_gap: int, collapse_factor: int) -> None:
    if (
        isinstance(primitive_gap, bool)
        or not isinstance(primitive_gap, int)
        or primitive_gap <= 0
    ):
        raise ValueError("primitive_gap must be a positive integer")
    if (
        isinstance(collapse_factor, bool)
        or not isinstance(collapse_factor, int)
        or collapse_factor <= 0
    ):
        raise ValueError("collapse_factor must be a positive integer")


def spatial_material_compatibility(
    primitive_gap: int,
    collapse_factor: int,
    profile: MaterialCurveProfile,
) -> MaterialPrecisionCompatibility:
    """Classify one positive-gap spatial factor against finite material depth."""
    _validate_gap_factor(primitive_gap, collapse_factor)
    if not profile.loading or len(profile.loading) != len(profile.returning):
        raise ValueError("material profile must contain equal nonempty branches")
    max_depth = len(profile.loading) - 1
    if collapse_factor <= primitive_gap:
        depth = None
        status = RESOLVED
    else:
        depth = collapse_factor - primitive_gap
        status = (
            REPRESENTED_CONTACT
            if depth <= max_depth
            else MATERIAL_UNDERRESOLVED
        )
    return MaterialPrecisionCompatibility(
        primitive_gap=primitive_gap,
        collapse_factor=collapse_factor,
        max_material_depth=max_depth,
        generated_depth=depth,
        status=status,
        finest_contact_factor=primitive_gap + 1,
        coarsest_represented_contact_factor=primitive_gap + max_depth,
    )


def intrinsic_spatial_material_compatibility(
    primitive_gap: int,
    collapse_factor: int,
    intrinsic_profile: IntrinsicPeakMaterialProfile,
) -> MaterialPrecisionCompatibility:
    """Apply the same contract when material depth is generated by intrinsic peak."""
    return spatial_material_compatibility(
        primitive_gap,
        collapse_factor,
        intrinsic_profile.material_profile,
    )
