"""Composable finite material-curve programs for the stacked E001 line.

Loading and returning are represented by explicit ordered words over a small
integer operator alphabet.  Word order is retained because finite projection and
root operations need not commute and cannot generally be collapsed to a single
aggregate exponent.

All operators remain on one declared amplitude scale.  The program still does
not assign force, energy, velocity, or physical units.
"""

from __future__ import annotations

from dataclasses import dataclass

from .material_response import (
    branch_gap_sum,
    hardening_sample,
    offset_sample,
    retained_sample,
    signed_branch_area,
    softening_sample,
)

HARDEN = "HARDEN"
SOFTEN = "SOFTEN"
RETAIN = "RETAIN"
OFFSET = "OFFSET"
MaterialOperatorKind = str


@dataclass(frozen=True)
class MaterialOperator:
    """One finite scale-preserving material-curve operation."""

    kind: MaterialOperatorKind
    parameter: int


@dataclass(frozen=True)
class MaterialWordStep:
    """One evaluated operator step for a single sample."""

    operator: MaterialOperator
    before: int
    after: int


@dataclass(frozen=True)
class MaterialWordTrace:
    """Exact evaluation trace of one ordered material operator word."""

    amplitude: int
    initial_sample: int
    word: tuple[MaterialOperator, ...]
    steps: tuple[MaterialWordStep, ...]
    result: int


@dataclass(frozen=True)
class MaterialProgramProfile:
    """Loading/return curve tables generated by two explicit operator words."""

    amplitude: int
    base_samples: tuple[int, ...]
    loading_word: tuple[MaterialOperator, ...]
    return_word: tuple[MaterialOperator, ...]
    loading: tuple[int, ...]
    returning: tuple[int, ...]
    branch_gap: int
    signed_area: int


def _validate_amplitude_sample(sample: int, amplitude: int) -> None:
    if isinstance(amplitude, bool) or not isinstance(amplitude, int) or amplitude <= 0:
        raise ValueError("amplitude must be a positive integer")
    if isinstance(sample, bool) or not isinstance(sample, int) or not 0 <= sample <= amplitude:
        raise ValueError("sample must be an integer in 0..amplitude")


def apply_material_operator(
    sample: int,
    amplitude: int,
    operator: MaterialOperator,
) -> int:
    """Apply one declared finite material operator."""
    _validate_amplitude_sample(sample, amplitude)
    if isinstance(operator.parameter, bool) or not isinstance(operator.parameter, int):
        raise ValueError("material operator parameter must be an integer")

    if operator.kind == HARDEN:
        if operator.parameter <= 0:
            raise ValueError("HARDEN power must be positive")
        return hardening_sample(sample, amplitude, operator.parameter)
    if operator.kind == SOFTEN:
        if operator.parameter <= 0:
            raise ValueError("SOFTEN power must be positive")
        return softening_sample(sample, amplitude, operator.parameter)
    if operator.kind == RETAIN:
        return retained_sample(sample, amplitude, operator.parameter)
    if operator.kind == OFFSET:
        return offset_sample(sample, amplitude, operator.parameter)
    raise ValueError("unknown material operator kind")


def apply_material_word(
    sample: int,
    amplitude: int,
    word: tuple[MaterialOperator, ...] | list[MaterialOperator],
) -> MaterialWordTrace:
    """Evaluate one ordered operator word and retain every intermediate sample."""
    _validate_amplitude_sample(sample, amplitude)
    operators = tuple(word)
    current = sample
    steps: list[MaterialWordStep] = []
    for operator in operators:
        following = apply_material_operator(current, amplitude, operator)
        steps.append(MaterialWordStep(operator=operator, before=current, after=following))
        current = following
    return MaterialWordTrace(
        amplitude=amplitude,
        initial_sample=sample,
        word=operators,
        steps=tuple(steps),
        result=current,
    )


def material_word_branch(
    base_samples: tuple[int, ...] | list[int],
    amplitude: int,
    word: tuple[MaterialOperator, ...] | list[MaterialOperator],
) -> tuple[int, ...]:
    """Evaluate one operator word pointwise over a finite curve basis."""
    return tuple(
        apply_material_word(sample, amplitude, word).result
        for sample in base_samples
    )


def material_program_profile(
    base_samples: tuple[int, ...] | list[int],
    amplitude: int,
    loading_word: tuple[MaterialOperator, ...] | list[MaterialOperator],
    return_word: tuple[MaterialOperator, ...] | list[MaterialOperator],
) -> MaterialProgramProfile:
    """Build two explicit branch programs on one common finite basis."""
    base = tuple(base_samples)
    if not base:
        raise ValueError("base material curve must be nonempty")
    for sample in base:
        _validate_amplitude_sample(sample, amplitude)
    loading_ops = tuple(loading_word)
    return_ops = tuple(return_word)
    loading = material_word_branch(base, amplitude, loading_ops)
    returning = material_word_branch(base, amplitude, return_ops)
    return MaterialProgramProfile(
        amplitude=amplitude,
        base_samples=base,
        loading_word=loading_ops,
        return_word=return_ops,
        loading=loading,
        returning=returning,
        branch_gap=branch_gap_sum(loading, returning),
        signed_area=signed_branch_area(loading, returning),
    )
