"""Exact two-body 1D material-impulse response on one declared contact channel.

This module is the next E001 owner generation after the one-body wall impulse
probe.  Geometry/contact discovery is deliberately out of scope: the caller has
already declared one contact channel and its normal ``n in {-1,+1}`` from the
left body toward the right body.

For integer momenta ``p_L,p_R`` and positive integer masses ``m_L,m_R``, define
the division-free relative-motion numerator

    v# = n * (m_L*p_R - m_R*p_L).

Its sign is exactly the sign of the relative velocity along the declared normal
without introducing rational state:

    v# < 0  -> pair is closing,
    v# = 0  -> pair is comoving along the normal,
    v# > 0  -> pair is separating.

One non-negative delivered repulsive impulse quantum ``j`` acts equally and
oppositely:

    p_L' = p_L - n*j,
    p_R' = p_R + n*j.

Hence total integer momentum is preserved exactly and

    v#' = v# + (m_L + m_R)*j.

The impulse quantum is generated by the same finite material-response quotient
used by the one-body E001 probe.  Its bounded pending detail belongs to this
*contact channel*.  This module intentionally requires a non-negative detail in
``0..A-1`` because the channel orientation is fixed and repulsive.  Details from
unrelated contacts or opposite directions must not be silently pooled into this
reservoir.

No claim of kinetic-energy conservation, coefficient of restitution, SI-unit
calibration, continuum force, or hidden trajectory subdivision is made here.
"""

from __future__ import annotations

from dataclasses import dataclass, replace

from .material_impulse_world_1d import material_impulse_quantization

PAIR_CLOSING = "PAIR_CLOSING"
PAIR_COMOVING = "PAIR_COMOVING"
PAIR_SEPARATING = "PAIR_SEPARATING"


def _require_integer(name: str, value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{name} must be an integer")


def _require_positive(name: str, value: int) -> None:
    _require_integer(name, value)
    if value <= 0:
        raise ValueError(f"{name} must be positive")


def _ceil_div_positive(numerator: int, denominator: int) -> int:
    if numerator <= 0 or denominator <= 0:
        raise ValueError("ceil-div arguments must be positive")
    return (numerator + denominator - 1) // denominator


@dataclass(frozen=True)
class PairMomentumState1D:
    left_momentum: int
    right_momentum: int
    left_mass: int
    right_mass: int
    contact_normal: int = 1
    contact_impulse_detail: int = 0

    def __post_init__(self) -> None:
        _require_integer("left_momentum", self.left_momentum)
        _require_integer("right_momentum", self.right_momentum)
        _require_positive("left_mass", self.left_mass)
        _require_positive("right_mass", self.right_mass)
        _require_integer("contact_normal", self.contact_normal)
        if self.contact_normal not in (-1, 1):
            raise ValueError("contact_normal must be -1 or +1")
        _require_integer("contact_impulse_detail", self.contact_impulse_detail)
        if self.contact_impulse_detail < 0:
            raise ValueError("contact_impulse_detail must be non-negative on this fixed repulsive channel")

    @property
    def total_momentum(self) -> int:
        return self.left_momentum + self.right_momentum

    @property
    def mass_sum(self) -> int:
        return self.left_mass + self.right_mass


def pair_relative_motion_numerator(state: PairMomentumState1D) -> int:
    """Return ``n*(m_L*p_R-m_R*p_L)`` with no division."""
    return state.contact_normal * (
        state.left_mass * state.right_momentum
        - state.right_mass * state.left_momentum
    )


def pair_motion_status(state: PairMomentumState1D) -> str:
    """Classify relative motion on the declared contact normal."""
    value = pair_relative_motion_numerator(state)
    if value < 0:
        return PAIR_CLOSING
    if value == 0:
        return PAIR_COMOVING
    return PAIR_SEPARATING


@dataclass(frozen=True)
class PairMaterialImpulseStep1D:
    before: PairMomentumState1D
    response_sample: int
    amplitude: int
    impulse_scale_magnitude: int
    delivered_impulse_quanta: int
    contact_detail_after: int
    after: PairMomentumState1D
    relative_numerator_before: int
    relative_numerator_after: int
    status_before: str
    status_after: str


def apply_pair_material_impulse(
    state: PairMomentumState1D,
    response_sample: int,
    amplitude: int,
    impulse_scale_magnitude: int,
) -> PairMaterialImpulseStep1D:
    """Apply one equal-and-opposite repulsive impulse on one contact channel."""
    _require_positive("amplitude", amplitude)
    _require_integer("response_sample", response_sample)
    if not 0 <= response_sample <= amplitude:
        raise ValueError("response_sample must lie in 0..amplitude")
    _require_positive("impulse_scale_magnitude", impulse_scale_magnitude)
    if state.contact_impulse_detail >= amplitude:
        raise ValueError("contact_impulse_detail must lie in 0..amplitude-1")

    impulse = material_impulse_quantization(
        response_sample=response_sample,
        amplitude=amplitude,
        signed_impulse_scale=impulse_scale_magnitude,
        detail=state.contact_impulse_detail,
    )
    delivered = impulse.impulse_quanta
    if delivered < 0 or impulse.detail_after < 0:
        raise AssertionError("fixed repulsive channel produced a negative impulse/detail")

    normal = state.contact_normal
    before_relative = pair_relative_motion_numerator(state)
    after = PairMomentumState1D(
        left_momentum=state.left_momentum - normal * delivered,
        right_momentum=state.right_momentum + normal * delivered,
        left_mass=state.left_mass,
        right_mass=state.right_mass,
        contact_normal=normal,
        contact_impulse_detail=impulse.detail_after,
    )
    after_relative = pair_relative_motion_numerator(after)

    if after.total_momentum != state.total_momentum:
        raise AssertionError("equal-and-opposite impulse changed total momentum")
    expected_relative = before_relative + state.mass_sum * delivered
    if after_relative != expected_relative:
        raise AssertionError("relative-motion numerator violated the exact impulse update")

    return PairMaterialImpulseStep1D(
        before=state,
        response_sample=response_sample,
        amplitude=amplitude,
        impulse_scale_magnitude=impulse_scale_magnitude,
        delivered_impulse_quanta=delivered,
        contact_detail_after=impulse.detail_after,
        after=after,
        relative_numerator_before=before_relative,
        relative_numerator_after=after_relative,
        status_before=pair_motion_status(state),
        status_after=pair_motion_status(after),
    )


@dataclass(frozen=True)
class PairImpulseTrace1D:
    initial: PairMomentumState1D
    response_samples: tuple[int, ...]
    retain_contact_detail: bool
    steps: tuple[PairMaterialImpulseStep1D, ...]
    final: PairMomentumState1D
    total_delivered_impulse_quanta: int


def trace_pair_material_impulses(
    initial: PairMomentumState1D,
    response_samples: tuple[int, ...] | list[int],
    amplitude: int,
    impulse_scale_magnitude: int,
    retain_contact_detail: bool = True,
) -> PairImpulseTrace1D:
    """Trace one fixed contact channel with retained or deliberately dropped detail."""
    _require_positive("amplitude", amplitude)
    _require_positive("impulse_scale_magnitude", impulse_scale_magnitude)
    if initial.contact_impulse_detail >= amplitude:
        raise ValueError("initial contact detail must lie in 0..amplitude-1")

    current = initial
    steps: list[PairMaterialImpulseStep1D] = []
    for response in tuple(response_samples):
        if not retain_contact_detail and current.contact_impulse_detail:
            current = replace(current, contact_impulse_detail=0)
        step = apply_pair_material_impulse(
            current,
            response,
            amplitude,
            impulse_scale_magnitude,
        )
        steps.append(step)
        current = step.after
        if not retain_contact_detail and current.contact_impulse_detail:
            current = replace(current, contact_impulse_detail=0)

    return PairImpulseTrace1D(
        initial=initial,
        response_samples=tuple(response_samples),
        retain_contact_detail=retain_contact_detail,
        steps=tuple(steps),
        final=current,
        total_delivered_impulse_quanta=sum(
            step.delivered_impulse_quanta for step in steps
        ),
    )


@dataclass(frozen=True)
class ConstantPairResponseThresholds1D:
    initial_closing_numerator_magnitude: int
    mass_sum: int
    required_quanta_for_nonclosing: int
    required_quanta_for_separating: int
    retained_first_nonclosing_event: int | None
    retained_first_separating_event: int | None
    dropped_impulse_per_event: int
    dropped_first_nonclosing_event: int | None
    dropped_first_separating_event: int | None


def constant_pair_response_thresholds(
    initial: PairMomentumState1D,
    amplitude: int,
    response_sample: int,
    impulse_scale_magnitude: int,
) -> ConstantPairResponseThresholds1D:
    """Exact event thresholds for a fixed response while the contact channel persists."""
    _require_positive("amplitude", amplitude)
    _require_integer("response_sample", response_sample)
    if not 0 <= response_sample <= amplitude:
        raise ValueError("response_sample must lie in 0..amplitude")
    _require_positive("impulse_scale_magnitude", impulse_scale_magnitude)
    if initial.contact_impulse_detail != 0:
        raise ValueError("closed-form thresholds require zero initial contact detail")

    relative = pair_relative_motion_numerator(initial)
    if relative >= 0:
        raise ValueError("closed-form thresholds require an initially closing pair")
    closing = -relative
    mass_sum = initial.mass_sum
    required_nonclosing = _ceil_div_positive(closing, mass_sum)
    required_separating = closing // mass_sum + 1
    per_event_numerator = impulse_scale_magnitude * response_sample

    if per_event_numerator == 0:
        retained_nonclosing = None
        retained_separating = None
    else:
        retained_nonclosing = _ceil_div_positive(
            amplitude * required_nonclosing,
            per_event_numerator,
        )
        retained_separating = _ceil_div_positive(
            amplitude * required_separating,
            per_event_numerator,
        )

    dropped_per_event = per_event_numerator // amplitude
    if dropped_per_event == 0:
        dropped_nonclosing = None
        dropped_separating = None
    else:
        dropped_nonclosing = _ceil_div_positive(
            required_nonclosing,
            dropped_per_event,
        )
        dropped_separating = _ceil_div_positive(
            required_separating,
            dropped_per_event,
        )

    return ConstantPairResponseThresholds1D(
        initial_closing_numerator_magnitude=closing,
        mass_sum=mass_sum,
        required_quanta_for_nonclosing=required_nonclosing,
        required_quanta_for_separating=required_separating,
        retained_first_nonclosing_event=retained_nonclosing,
        retained_first_separating_event=retained_separating,
        dropped_impulse_per_event=dropped_per_event,
        dropped_first_nonclosing_event=dropped_nonclosing,
        dropped_first_separating_event=dropped_separating,
    )
