"""Matrix-preimage L-infinity access as an exact word norm on the image lattice.

For an integer matrix ``B`` with columns indexed by fine coordinates, define

    Z_r = {B*x : x in Z^s, ||x||_infinity <= r}.

Coordinatewise splitting of an integer cube gives the exact Minkowski law

    Z_(r+s) = Z_r + Z_s,

hence ``Z_r`` is the r-fold Minkowski sum of ``Z_1``.  Since the signed columns
of ``B`` lie in ``Z_1``, this one-step image generates ``im_Z(B)``.  Therefore

    kappa_B(t)=min{r:t in Z_r}

is exactly the word norm of the image-lattice element ``t`` with respect to the
finite symmetric generating set ``Z_1``.

When a relation subgroup ``Lambda=im(B) intersect ker(L)`` is imposed, its
access cost is the restriction of the ambient word norm.  It need not equal the
intrinsic word norm generated by ``Z_1 intersect Lambda``; relation-compatible
large-radius states can require cancellations through one-step image elements
that individually leave the relation subgroup.
"""

from __future__ import annotations

from dataclasses import dataclass

from .relation_shared_prime_rank import shared_prime_relation_system


Vector = tuple[int, ...]
Matrix = tuple[tuple[int, ...], ...]


@dataclass(frozen=True)
class MatrixAccessState:
    matrix: Matrix
    radius: int
    reachable_values: frozenset[Vector]


def _validate_matrix(matrix: Matrix) -> tuple[int, int]:
    if not matrix:
        raise ValueError("matrix must have at least one row")
    width = len(matrix[0])
    if width == 0:
        raise ValueError("matrix must have at least one fine-coordinate column")
    for row in matrix:
        if len(row) != width:
            raise ValueError("matrix rows must have equal width")
        for value in row:
            if isinstance(value, bool) or not isinstance(value, int):
                raise ValueError("matrix coefficients must be integers")
    return len(matrix), width


def _columns(matrix: Matrix) -> tuple[Vector, ...]:
    height, width = _validate_matrix(matrix)
    return tuple(
        tuple(matrix[i][j] for i in range(height))
        for j in range(width)
    )


def _add(left: Vector, right: Vector) -> Vector:
    if len(left) != len(right):
        raise ValueError("vectors must have equal dimension")
    return tuple(a + b for a, b in zip(left, right, strict=True))


def minkowski_sum(left: frozenset[Vector], right: frozenset[Vector]) -> frozenset[Vector]:
    """Return exact finite Minkowski sum of two integer-vector sets."""
    if not left or not right:
        return frozenset()
    return frozenset(_add(a, b) for a in left for b in right)


def matrix_image_at_radius(matrix: Matrix, radius: int) -> frozenset[Vector]:
    """Return ``B([-r,r]^s intersect Z^s)`` without enumerating the full cube.

    Dynamic Minkowski addition by each column segment merges equal image values
    immediately.  The result is exact.
    """
    height, _width = _validate_matrix(matrix)
    if isinstance(radius, bool) or not isinstance(radius, int) or radius < 0:
        raise ValueError("radius must be a non-negative integer")
    reachable: frozenset[Vector] = frozenset({tuple(0 for _ in range(height))})
    for column in _columns(matrix):
        segment = frozenset(
            tuple(k * value for value in column)
            for k in range(-radius, radius + 1)
        )
        reachable = minkowski_sum(reachable, segment)
    return reachable


def one_step_image(matrix: Matrix) -> frozenset[Vector]:
    """Return the finite symmetric word generator ``Z_1``."""
    return matrix_image_at_radius(matrix, 1)


def repeated_one_step_image(matrix: Matrix, radius: int) -> frozenset[Vector]:
    """Return the r-fold Minkowski sum of ``Z_1`` (with ``Z_0={0}``)."""
    height, _width = _validate_matrix(matrix)
    if isinstance(radius, bool) or not isinstance(radius, int) or radius < 0:
        raise ValueError("radius must be a non-negative integer")
    result = frozenset({tuple(0 for _ in range(height))})
    step = one_step_image(matrix)
    for _ in range(radius):
        result = minkowski_sum(result, step)
    return result


def matrix_access_radius(matrix: Matrix, target: Vector, *, max_radius: int) -> int:
    """Return exact word/preimage radius up to a declared finite search bound."""
    height, _width = _validate_matrix(matrix)
    if len(target) != height:
        raise ValueError("target must match matrix row dimension")
    if isinstance(max_radius, bool) or not isinstance(max_radius, int) or max_radius < 0:
        raise ValueError("max_radius must be a non-negative integer")
    for radius in range(max_radius + 1):
        if target in matrix_image_at_radius(matrix, radius):
            return radius
    raise ValueError("target not reached within max_radius")


def minkowski_radius_law_holds(matrix: Matrix, r: int, s: int) -> bool:
    """Executable check of ``Z_(r+s)=Z_r+Z_s``."""
    if r < 0 or s < 0:
        raise ValueError("radii must be non-negative")
    left = matrix_image_at_radius(matrix, r + s)
    right = minkowski_sum(
        matrix_image_at_radius(matrix, r),
        matrix_image_at_radius(matrix, s),
    )
    if left != right:
        raise AssertionError("integer cube image violated exact Minkowski radius law")
    return True


def word_norm_triangle_holds(
    matrix: Matrix,
    left: Vector,
    right: Vector,
    *,
    max_radius: int,
) -> bool:
    """Check ``kappa(left+right)<=kappa(left)+kappa(right)`` on reachable targets."""
    left_radius = matrix_access_radius(matrix, left, max_radius=max_radius)
    right_radius = matrix_access_radius(matrix, right, max_radius=max_radius)
    total = _add(left, right)
    total_radius = matrix_access_radius(
        matrix,
        total,
        max_radius=left_radius + right_radius,
    )
    if total_radius > left_radius + right_radius:
        raise AssertionError("matrix access lost word-norm triangle inequality")
    return True


def relation_subgroup_one_step_failure_counterexample() -> dict[str, object]:
    """Show ambient word norm need not be intrinsic to ``Z_1 intersect ker L``.

    Use blocks ``(2,4,6)`` and the valid relation

        4*2 + 1*4 - 2*6 = 0.

    The derivative matrix is ``[[1,0],[4,0],[3,2]]`` and ``L*B=(2,-4)``, so
    relation-adapted fine coordinates satisfy ``x_2=2*x_3``.  At radius one the
    only relation-compatible image is zero.  At radius two, ``x=(2,1)`` gives
    the nonzero relation state ``(2,8,8)``.  Thus restricting the ambient access
    norm to the relation subgroup is not the word norm of its radius-one
    intersection.
    """
    blocks = (2, 4, 6)
    relation = ((4, 1, -2),)
    system = shared_prime_relation_system(blocks, relation)
    matrix = system.derivative_matrix
    step = one_step_image(matrix)

    def relation_ok(value: Vector) -> bool:
        return sum(c * t for c, t in zip(relation[0], value, strict=True)) == 0

    relation_step = frozenset(value for value in step if relation_ok(value))
    target = (2, 8, 8)
    if relation_step != frozenset({(0, 0, 0)}):
        raise AssertionError("counterexample lost trivial radius-one relation intersection")
    if target not in matrix_image_at_radius(matrix, 2) or not relation_ok(target):
        raise AssertionError("counterexample target lost radius-two relation reachability")
    if matrix_access_radius(matrix, target, max_radius=2) != 2:
        raise AssertionError("counterexample target lost ambient access radius two")

    return {
        "blocks": blocks,
        "relation": relation[0],
        "derivative_matrix": matrix,
        "relation_derivative_row": system.relation_derivative_matrix[0],
        "radius_one_relation_image": tuple(sorted(relation_step)),
        "radius_two_target": target,
        "ambient_access_radius": 2,
    }
