"""Quadratic channel covering and the surviving low-height CRT barrier.

The E=1 square-basin channel has

    y0 + c = (k+1)^2,

with c=2 for even k and c=3 for odd k.  Hence every odd prime p<k forbids the
index residue

    tau_p = y0 * 2^{-1} (mod p),

which necessarily satisfies

    2 tau_p + c = square (mod p).

It is tempting to regard this local quadratic-image restriction as the extra
structure beyond a generic Jacobsthal covering.  That is false.

There exists an explicit relaxed covering already at k=73: choose, independently
for every odd prime p<73, a residue tau_p satisfying the local square condition;
the resulting residue classes cover all 72 channel indices.  Thus local
quadratic admissibility alone does not prevent a complete sieve cover.

What distinguishes the actual square basin is **global root height**.  The local
square values must all be generated by the same integer root R=k+1.  For any
relaxed residue system define its compatible CRT roots by

    R^2 = 2 tau_p + c (mod p)    for every p.

The explicit k=73 relaxed cover below has primorial

    278970415063349480483707695

and minimum centered compatible root height

    17447277685465296722137,

whereas the true basin would require height k+1=74.  The surviving research
frontier is therefore a low-height quadratic-covering theorem, not a local
quadratic-residue theorem.

This finite counterexample does not prove or disprove Legendre's conjecture.  It
rules out one over-weak abstraction and gives an exact global-consistency
coordinate for the remaining special diagonal.
"""

from __future__ import annotations

from math import prod


RELAXED_K73_COVER: tuple[tuple[int, int], ...] = (
    (3, 2),
    (5, 3),
    (7, 2),
    (11, 1),
    (13, 10),
    (17, 6),
    (19, 4),
    (23, 0),
    (29, 25),
    (31, 24),
    (37, 15),
    (41, 19),
    (43, 27),
    (47, 22),
    (53, 11),
    (59, 7),
    (61, 31),
    (67, 39),
    (71, 21),
)

RELAXED_K73_PRIMORIAL = 278970415063349480483707695
RELAXED_K73_MIN_CENTERED_ROOT = 17447277685465296722137


def _primes_below(limit: int) -> tuple[int, ...]:
    primes: list[int] = []
    for candidate in range(2, limit):
        prime = True
        for p in primes:
            if p * p > candidate:
                break
            if candidate % p == 0:
                prime = False
                break
        if prime:
            primes.append(candidate)
    return tuple(primes)


def _quadratic_roots_mod_prime(value: int, prime: int) -> tuple[int, ...]:
    roots = tuple(r for r in range(prime) if (r * r - value) % prime == 0)
    return roots


def quadratic_allowed_residues(prime: int, offset: int) -> tuple[int, ...]:
    """Return tau with 2*tau+offset a square modulo the odd prime."""
    if isinstance(prime, bool) or not isinstance(prime, int) or prime < 3 or prime % 2 == 0:
        raise ValueError("prime must be an odd prime")
    if any(prime % d == 0 for d in range(3, int(prime**0.5) + 1, 2)):
        raise ValueError("prime must be prime")
    inverse_two = pow(2, -1, prime)
    return tuple(
        sorted({((root * root - offset) * inverse_two) % prime for root in range(prime)})
    )


def _crt_root_set(
    choices: tuple[tuple[int, int], ...],
    offset: int,
) -> tuple[int, tuple[int, ...]]:
    """Return the primorial and all simultaneous square roots of the local values."""
    residues = [0]
    modulus = 1
    for prime, tau in choices:
        roots = _quadratic_roots_mod_prime((2 * tau + offset) % prime, prime)
        if not roots:
            raise ValueError("a chosen residue is not locally quadratic-admissible")
        inverse = pow(modulus, -1, prime)
        next_residues: list[int] = []
        for current in residues:
            for root in roots:
                multiplier = ((root - current) % prime) * inverse % prime
                next_residues.append(current + modulus * multiplier)
        modulus *= prime
        residues = next_residues
    return modulus, tuple(residues)


def verify_relaxed_quadratic_cover(
    k: int,
    choices: tuple[tuple[int, int], ...],
) -> dict[str, object]:
    """Verify a complete locally-quadratic channel cover and compute CRT root height."""
    if isinstance(k, bool) or not isinstance(k, int) or k < 3:
        raise ValueError("k must be an integer >=3")
    offset = 2 if k % 2 == 0 else 3
    length = k if k % 2 == 0 else k - 1
    normalized = tuple(sorted((int(p), int(tau)) for p, tau in choices))
    expected_primes = tuple(p for p in _primes_below(k) if p % 2 == 1)
    if tuple(p for p, _tau in normalized) != expected_primes:
        raise ValueError("choices must contain exactly one residue for every odd prime <k")

    covered_by: list[list[int]] = [[] for _ in range(length)]
    local_roots: list[dict[str, object]] = []
    for prime, tau in normalized:
        if not (0 <= tau < prime):
            raise ValueError("chosen residues must use 0<=tau<p")
        roots = _quadratic_roots_mod_prime((2 * tau + offset) % prime, prime)
        if not roots:
            raise ValueError("chosen residue violates the local quadratic condition")
        local_roots.append({"prime": prime, "tau": tau, "roots": roots})
        for index in range(tau, length, prime):
            covered_by[index].append(prime)

    uncovered = tuple(index for index, owners in enumerate(covered_by) if not owners)
    primorial, roots = _crt_root_set(normalized, offset)
    centered_heights = tuple(min(root, primorial - root) for root in roots)
    minimum_height = min(centered_heights)

    return {
        "k": k,
        "offset": offset,
        "channel_length": length,
        "choices": normalized,
        "complete_cover": not uncovered,
        "uncovered_indices": uncovered,
        "covered_by": tuple(tuple(owners) for owners in covered_by),
        "local_roots": tuple(local_roots),
        "primorial": primorial,
        "compatible_root_count": len(roots),
        "minimum_centered_root_height": minimum_height,
        "actual_square_basin_root_height": k + 1,
        "local_quadratic_condition_is_insufficient": not uncovered and minimum_height > k + 1,
    }


def actual_square_basin_residues(k: int) -> dict[str, object]:
    """Return the genuine low-height quadratic residue system generated by R=k+1."""
    if isinstance(k, bool) or not isinstance(k, int) or k < 3:
        raise ValueError("k must be an integer >=3")
    offset = 2 if k % 2 == 0 else 3
    root = k + 1
    choices: list[tuple[int, int]] = []
    for prime in _primes_below(k):
        if prime == 2:
            continue
        tau = ((root * root - offset) * pow(2, -1, prime)) % prime
        choices.append((prime, tau))
    length = k if k % 2 == 0 else k - 1
    covered = [False] * length
    for prime, tau in choices:
        for index in range(tau, length, prime):
            covered[index] = True
    return {
        "k": k,
        "offset": offset,
        "common_root": root,
        "choices": tuple(choices),
        "channel_length": length,
        "complete_cover": all(covered),
        "uncovered_indices": tuple(index for index, hit in enumerate(covered) if not hit),
        "common_root_is_low_height": root == k + 1,
    }


def verify_k73_relaxed_counterexample() -> dict[str, object]:
    """Verify the explicit first discovered relaxed quadratic covering witness."""
    data = verify_relaxed_quadratic_cover(73, RELAXED_K73_COVER)
    if not bool(data["complete_cover"]):
        raise AssertionError("stored k=73 relaxed witness no longer covers the channel")
    if int(data["primorial"]) != RELAXED_K73_PRIMORIAL:
        raise AssertionError("stored k=73 primorial changed")
    if int(data["minimum_centered_root_height"]) != RELAXED_K73_MIN_CENTERED_ROOT:
        raise AssertionError("stored k=73 minimum CRT root height changed")
    if not bool(data["local_quadratic_condition_is_insufficient"]):
        raise AssertionError("k=73 witness failed its local-vs-global negative boundary")
    return data
