"""Unified P017 carry field as an exact roughness-displacement discrepancy.

Let K=k-1, M=(K+1)(K+2), and let P be a finite odd squarefree product.  For
every divisor E|P, write

    F_E(K)=floor(K/E)+eta_E(K).

Then complete Mobius inversion on the two pieces gives the exact identity

    sum_(E|P) mu(E) eta_E(K)
      = S_square(P,K) - S_origin(P,K),

where

    S_square(P,K)
      = #{x odd, -K<=x<=K : gcd(M-x,P)=1},

and

    S_origin(P,K)
      = #{1<=q<=K : gcd(q,P)=1}.

Thus the full centered carry field is a displacement discrepancy between two
ordinary rough-number counts.  It is not an extra sieve observable hidden on
top of them.

The E=1 quotient channel converts S_square to a consecutive-index roughness
count because its quotient progression is y_t=y0-2t and 2 is invertible modulo
P.  Therefore the refinement-monoid representation, the unified carry field,
and the Ramanujan/Fourier conductor representation all factor through the same
classical reduced-residue projector.

This is a strong negative boundary, but it deliberately does *not* discard the
square-basin diagonal.  In the actual P017 specialization the shifted interval
origin, its length and the prime cutoff are all generated by the same small
integer k.  Any continuation of this route must exploit that low-height
quadratic coupling; generic Jacobsthal/sieve bounds for arbitrary shifts cannot
be expected to close the problem.
"""

from __future__ import annotations

from math import gcd, prod

from .legendre import squarefree_divisors_with_mu
from .p017_p018_carry_phase_mean import unified_centered_carry_bit
from .p017_p018_carry_refinement_channel import signed_fiber_channel_state


def _require_primes(primes: tuple[int, ...]) -> tuple[int, ...]:
    normalized = tuple(sorted(int(p) for p in primes))
    if not normalized or len(set(normalized)) != len(normalized):
        raise ValueError("primes must be a nonempty tuple of distinct odd primes")
    for prime in normalized:
        if prime < 3 or prime % 2 == 0:
            raise ValueError("primes must be odd")
        divisor = 3
        while divisor * divisor <= prime:
            if prime % divisor == 0:
                raise ValueError("entries must be prime")
            divisor += 2
    return normalized


def carry_roughness_discrepancy(K: int, primes: tuple[int, ...]) -> dict[str, object]:
    """Verify carry = shifted roughness count - origin roughness count exactly."""
    if isinstance(K, bool) or not isinstance(K, int) or K < 0:
        raise ValueError("K must be a nonnegative integer")
    normalized = _require_primes(primes)
    P = prod(normalized)
    M = (K + 1) * (K + 2)

    carry_sum = 0
    floor_mobius_sum = 0
    exact_fiber_mobius_sum = 0
    rows: list[dict[str, int]] = []
    for divisor, mu in squarefree_divisors_with_mu(list(normalized)):
        eta = unified_centered_carry_bit(K, divisor)
        floor_part = K // divisor
        exact = floor_part + eta
        carry_sum += mu * eta
        floor_mobius_sum += mu * floor_part
        exact_fiber_mobius_sum += mu * exact
        rows.append(
            {
                "divisor": divisor,
                "mu": mu,
                "floor_part": floor_part,
                "centered_carry": eta,
                "exact_fiber_size": exact,
            }
        )

    square_rough = sum(
        gcd(M - x, P) == 1
        for x in range(-K, K + 1)
        if x % 2 != 0
    )
    origin_rough = sum(gcd(q, P) == 1 for q in range(1, K + 1))

    parent = signed_fiber_channel_state(K, 1)
    N = int(parent["fiber_size"])
    y0 = None if parent["first_quotient"] is None else int(parent["first_quotient"])
    if N == 0:
        channel_rough = 0
    else:
        if y0 is None:
            raise AssertionError("nonempty E=1 channel lost its quotient origin")
        channel_rough = sum(gcd(y0 - 2 * t, P) == 1 for t in range(N))

    if exact_fiber_mobius_sum != square_rough or square_rough != channel_rough:
        raise AssertionError("exact divisor Mobius sum failed shifted roughness projection")
    if floor_mobius_sum != origin_rough:
        raise AssertionError("floor Mobius sum failed origin roughness projection")
    if carry_sum != square_rough - origin_rough:
        raise AssertionError("centered carry field failed roughness-discrepancy identity")

    return {
        "K": K,
        "k": K + 1,
        "center": M,
        "primes": normalized,
        "primorial": P,
        "mobius_carry_field": carry_sum,
        "mobius_exact_fiber_sum": exact_fiber_mobius_sum,
        "mobius_floor_sum": floor_mobius_sum,
        "square_basin_roughness_count": square_rough,
        "origin_roughness_count": origin_rough,
        "channelized_square_roughness_count": channel_rough,
        "E1_channel_fiber_size": N,
        "E1_channel_first_quotient": y0,
        "rows": tuple(rows),
        "carry_is_roughness_displacement_discrepancy": True,
    }


def full_small_prime_origin_is_dyadic(k: int, primes_below_k: tuple[int, ...]) -> dict[str, object]:
    """Verify that the full odd-prime origin roughness set below k is the dyadic axis.

    The caller supplies the complete tuple of odd primes <k; the function checks
    completeness by trial division so the statement cannot silently use a
    truncated prime list.
    """
    if isinstance(k, bool) or not isinstance(k, int) or k < 3:
        raise ValueError("k must be an integer >=3")
    normalized = _require_primes(primes_below_k)
    expected: list[int] = []
    for candidate in range(3, k, 2):
        prime = True
        divisor = 3
        while divisor * divisor <= candidate:
            if candidate % divisor == 0:
                prime = False
                break
            divisor += 2
        if prime:
            expected.append(candidate)
    if tuple(expected) != normalized:
        raise ValueError("primes_below_k must be the complete tuple of odd primes <k")

    K = k - 1
    P = prod(normalized)
    rough = tuple(q for q in range(1, K + 1) if gcd(q, P) == 1)
    dyadic: list[int] = []
    power = 1
    while power <= K:
        dyadic.append(power)
        power *= 2
    if rough != tuple(dyadic):
        raise AssertionError("full small-prime origin roughness did not collapse to powers of two")
    return {
        "k": k,
        "K": K,
        "odd_primes_below_k": normalized,
        "origin_rough_values": rough,
        "dyadic_axis": tuple(dyadic),
        "origin_roughness_is_exactly_dyadic": True,
    }
