"""P017 residual core mass: uniform Rankin bound after anchor normalization.

This module records an elementary analytic upper-bound route that avoids the
uniformity problem of applying a fixed-parameter Selberg--Delange asymptotic to
``M=k(k+1)`` while k varies.

Let

    F_M(sigma)
      = sum_{S odd, gcd(S,M)=1} 2^omega(S) / (phi(S) S^sigma),

and let

    delta_M = prod_{odd p|M} (1-1/p).

For an allowed odd prime p the local factor is

    L_p(sigma)
      = 1 + sum_{a>=1} 2/[phi(p^a) p^(a sigma)].

Write y=p^sigma>=1.  Exact summation gives

    L_p = 1 + 2p / ((p-1)(py-1)).

If p is excluded by the anchor, the local ratio generated by dividing by
``delta_M^2`` is

    R_p(y) = (1-1/p)^(-2) / L_p.

Pure polynomial algebra shows

    R_p(y) <= y = p^sigma      (p>=3, y>=1).

Indeed, after clearing positive denominators the required margin is

    D_p(y)
      = y(p-1)(p(p-1)y+p+1) - p^2(py-1).

One has ``D_p(1)=p-1>0`` and

    D'_p(y)=2p(p-1)^2 y - p^3 + p^2 - 1,

whose value at y=1 is ``p(p-1)(p-2)-1>0`` for p>=3; the derivative then
increases with y.  Thus every anchor-prime ratio is at most p^sigma, and

    delta_M^(-2) F_M(sigma) <= M^sigma F_1(sigma).

For the unrestricted odd series, put z=p^(-1-sigma).  Factoring the local
``zeta(1+sigma)^2`` contribution leaves

    G_p(z)
      = 1 + 2z/(p-1) - (p+1)z^2/(p-1).

For ``0<=z<=1/p`` this concave quadratic is maximized at z=1/(p+1), where

    G_p <= p^2/(p^2-1).

Consequently

    F_1(sigma)
      <= zeta(1+sigma)^2 * prod_{p odd} p^2/(p^2-1)
      = (pi^2/8) zeta(1+sigma)^2.

Rankin's inequality therefore gives, for x>1 and sigma>0,

    delta_M^(-2)
    sum_{S<x, odd, (S,M)=1} 2^omega(S)/phi(S)
      <= (xM)^sigma (pi^2/8) zeta(1+sigma)^2.

For log(xM)>=1 choose sigma=1/log(xM).  The integral-test bound
``zeta(1+sigma)<=1+1/sigma`` yields the completely uniform estimate

    delta_M^(-2) core_mass(x;M)
      <= (e*pi^2/8) [1+log(xM)]^2.

Since ``2^omega(S)-2 <= 2^omega(S)``, the same upper bound applies to the
ordered nontrivial split mass used by the hard-core bridge.

This is a rigorous upper bound, not an asymptotic formula and not a prime-pair
sieve estimate.  It controls the global *core-weight* layer uniformly in M;
the simultaneous-prime lift probability/capacity remains a separate sieve
problem.

The executable helpers below audit the exact local polynomial inequalities over
rational y.  They deliberately do not approximate e, pi, logarithms, or zeta.
"""

from __future__ import annotations

from math import gcd

from .legendre import is_prime


def _require_prime(prime: int) -> None:
    if isinstance(prime, bool) or not isinstance(prime, int) or prime < 3 or not is_prime(prime):
        raise ValueError("prime must be an odd prime")


def _require_positive_rational(numerator: int, denominator: int) -> None:
    for value in (numerator, denominator):
        if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
            raise ValueError("rational components must be positive integers")
    if numerator < denominator:
        raise ValueError("require y>=1")


def reduced_pair(numerator: int, denominator: int) -> tuple[int, int]:
    if denominator <= 0:
        raise ValueError("denominator must be positive")
    common = gcd(numerator, denominator)
    return numerator // common, denominator // common


def anchor_local_rankin_margin(
    prime: int, y_numerator: int, y_denominator: int
) -> dict[str, object]:
    """Certify R_p(y)<=y for one rational y>=1 by cleared polynomial margin."""
    _require_prime(prime)
    _require_positive_rational(y_numerator, y_denominator)
    p = prime
    yn = y_numerator
    yd = y_denominator

    # yd^2 * D_p(yn/yd), expanded with integers only.
    margin = (
        yn * (p - 1) * (p * (p - 1) * yn + (p + 1) * yd)
        - p * p * (p * yn - yd) * yd
    )
    if margin <= 0:
        raise AssertionError("anchor local Rankin margin is not positive")

    derivative_at_one = p * (p - 1) * (p - 2) - 1
    if derivative_at_one <= 0:
        raise AssertionError("local margin derivative is not positive at y=1")

    # Exact R_p(y) after substituting y=yn/yd:
    # p^2(p*y-1) / [(p-1)(p(p-1)y+p+1)].
    ratio = reduced_pair(
        p * p * (p * yn - yd),
        (p - 1) * (p * (p - 1) * yn + (p + 1) * yd),
    )
    if ratio[0] * yd > ratio[1] * yn:
        raise AssertionError("exact local ratio exceeded y")

    return {
        "prime": p,
        "y": reduced_pair(yn, yd),
        "rankin_ratio": ratio,
        "cleared_margin": margin,
        "derivative_at_one": derivative_at_one,
    }


def unrestricted_local_correction(
    prime: int, z_numerator: int, z_denominator: int
) -> dict[str, object]:
    """Certify G_p(z)<=p^2/(p^2-1) for rational 0<=z<=1/p."""
    _require_prime(prime)
    if any(
        isinstance(value, bool) or not isinstance(value, int)
        for value in (z_numerator, z_denominator)
    ):
        raise ValueError("z components must be integers")
    if z_denominator <= 0 or z_numerator < 0:
        raise ValueError("require nonnegative rational z")
    if prime * z_numerator > z_denominator:
        raise ValueError("require z<=1/p")

    p = prime
    zn = z_numerator
    zd = z_denominator
    # G = [ (p-1) zd^2 + 2 zn zd - (p+1) zn^2 ] / [(p-1) zd^2].
    correction = reduced_pair(
        (p - 1) * zd * zd + 2 * zn * zd - (p + 1) * zn * zn,
        (p - 1) * zd * zd,
    )
    maximum = reduced_pair(p * p, p * p - 1)
    if correction[0] * maximum[1] > maximum[0] * correction[1]:
        raise AssertionError("local zeta correction exceeded its exact quadratic maximum")

    return {
        "prime": p,
        "z": reduced_pair(zn, zd),
        "correction": correction,
        "maximum": maximum,
        "maximizer": reduced_pair(1, p + 1),
    }


def odd_zeta_correction_partial(primes: tuple[int, ...]) -> tuple[int, int]:
    """Return product p^2/(p^2-1) over a finite list of odd primes."""
    if len(set(primes)) != len(primes):
        raise ValueError("primes must be distinct")
    numerator = 1
    denominator = 1
    for prime in primes:
        _require_prime(prime)
        numerator *= prime * prime
        denominator *= prime * prime - 1
    return reduced_pair(numerator, denominator)
