"""Task-relative future-safe quotient for the quadratic carry reflection.

For a fixed nontrivial odd squarefree P, let

    C(K)=C_P(K)

be the Mobius carry field and let

    D(K)=1_{gcd(P,H(K))=1}-1_{gcd(P,A(K))=1} in {-1,0,1}

be the exact reflection defect from p017_p018_carry_quadratic_reflection.
The reflection r(K)=-K-3 satisfies

    C(rK)=D(K)-C(K),
    D(rK)=D(K).

Therefore the compressed state

    Sigma(K)=(C(K),D(K))

is closed under the future language generated by reflection, with exact induced
action

    (c,d) -> (d-c,d).

This is an explicit P017/P018 instance of the P023 future-safe-collapse rule:
current carry alone is not generally sufficient, while one ternary repair
coordinate makes the operation exact.  The repair is genuinely needed.  For
P=15 the phases K=3 and K=5 both have C=1, but their reflected carries are 0
and -1 respectively.

No claim is made that this reflection-safe quotient resolves the Legendre
problem; it is a reusable finite future-signature theorem.
"""

from __future__ import annotations

from .p017_p018_carry_quadratic_reflection import (
    mobius_carry_quadratic_reflection,
    mobius_carry_field,
)


def induced_reflection_state(carry_value: int, reflection_defect: int) -> tuple[int, int]:
    if isinstance(carry_value, bool) or not isinstance(carry_value, int):
        raise ValueError("carry_value must be an integer")
    if reflection_defect not in (-1, 0, 1):
        raise ValueError("reflection_defect must lie in {-1,0,1}")
    return reflection_defect - carry_value, reflection_defect


def reflection_safe_signature(K: int, primes: tuple[int, ...]) -> dict[str, object]:
    """Return Sigma=(C,D) and verify that reflection factors through it."""
    data = mobius_carry_quadratic_reflection(K, primes)
    carry = int(data["physical_carry_field"])
    defect = int(data["reflection_defect"])
    predicted_reflected, invariant_defect = induced_reflection_state(carry, defect)
    actual_reflected = int(data["reflected_carry_field"])
    reflected_data = mobius_carry_quadratic_reflection(-K - 3, primes)
    if predicted_reflected != actual_reflected:
        raise AssertionError("compressed reflection state lost the future carry")
    if invariant_defect != int(reflected_data["reflection_defect"]):
        raise AssertionError("reflection defect is not invariant under the involution")
    twice = induced_reflection_state(predicted_reflected, invariant_defect)
    if twice != (carry, defect):
        raise AssertionError("induced reflection on compressed state is not an involution")
    return {
        "K": K,
        "primes": tuple(primes),
        "carry_coordinate": carry,
        "reflection_defect_coordinate": defect,
        "signature": (carry, defect),
        "induced_reflected_signature": (predicted_reflected, invariant_defect),
        "actual_reflected_carry": actual_reflected,
        "reflection_defect_invariant": True,
        "induced_reflection_is_involution": True,
        "reflection_future_safe": True,
    }


def carry_only_insufficiency_witness() -> dict[str, object]:
    """Return an exact P=15 witness that C alone does not determine C after reflection."""
    primes = (3, 5)
    first_K = 3
    second_K = 5
    first = reflection_safe_signature(first_K, primes)
    second = reflection_safe_signature(second_K, primes)
    first_carry = mobius_carry_field(first_K, primes)
    second_carry = mobius_carry_field(second_K, primes)
    first_future = int(first["actual_reflected_carry"])
    second_future = int(second["actual_reflected_carry"])
    if first_carry != second_carry:
        raise AssertionError("insufficiency witness lost equal current carry")
    if first_future == second_future:
        raise AssertionError("equal current carries unexpectedly have equal reflected futures")
    return {
        "primes": primes,
        "first_K": first_K,
        "second_K": second_K,
        "shared_current_carry": first_carry,
        "first_reflected_carry": first_future,
        "second_reflected_carry": second_future,
        "first_defect": int(first["reflection_defect_coordinate"]),
        "second_defect": int(second["reflection_defect_coordinate"]),
        "carry_alone_future_safe": False,
        "carry_plus_ternary_defect_future_safe": True,
    }
