"""Exact algebraic language for an invisible Franel-defect valuation row.

Fix a finite prefix A_n=C(2n,n), 1<=n<=N.  The group generated by these
central-binomial coordinates is the free abelian group generated by the primes
p<=2N-1.  A depth profile z_n lies in the kernel of every composite A-relation

    z_n = sum_j alpha_(n,j) z_j

exactly when there is an additive prime-weight functional L on that group with

    z_n = L(A_n)

for every n<=N.

The forward direction is constructive.  Define the weight of a prime p from
its canonical expression in the A-basis.  Prime-boundary indices introduce one
new free prime weight; composite-boundary indices have no new prime and their
kernel equation is exactly the consistency condition.  The converse is just
additivity applied to the canonical A-relation.

Thus a q-adic Franel row that is invisible to every composite defect is not an
arbitrary cancellation pattern: its full depth sequence must factor through an
additive functional on central-binomial prime-exponent coordinates.  The global
P022 problem may therefore be stated as incompatibility between that A-group
functional and the base-q self-similarity of Franel depths.
"""

from __future__ import annotations

from .p022_barlow_low_order_defect_reduction import (
    _factor_integer,
    composite_A_relation_exponents,
    composite_indices,
    integer_in_central_binomial_basis,
    primes_through,
)
from .p022_barlow_low_order_identifiability import pair_moment_factor


def _require_depths(max_segment: int, depths: tuple[int, ...]) -> None:
    if isinstance(max_segment, bool) or not isinstance(max_segment, int) or max_segment < 1:
        raise ValueError("max_segment must be positive")
    if len(depths) != max_segment + 1:
        raise ValueError("depths must be indexed by 0..max_segment")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in depths):
        raise ValueError("depths must contain integers")


def prime_weight_from_depths(prime: int, depths: tuple[int, ...]) -> int:
    """L(p) from the canonical expression of the integer prime in A-coordinates."""
    if prime not in primes_through(prime):
        raise ValueError("prime must be prime")
    exponents = integer_in_central_binomial_basis(prime)
    if exponents and max(index for index, _ in exponents) >= len(depths):
        raise ValueError("depth prefix is too short for this prime")
    return sum(exponent * depths[index] for index, exponent in exponents)


def prime_weights_from_depths(max_segment: int, depths: tuple[int, ...]) -> tuple[tuple[int, int], ...]:
    """All prime weights needed for A_1,...,A_N."""
    _require_depths(max_segment, depths)
    return tuple(
        (prime, prime_weight_from_depths(prime, depths))
        for prime in primes_through(2 * max_segment - 1)
    )


def additive_A_depth(segment: int, weights: tuple[tuple[int, int], ...]) -> int:
    """Evaluate L(A_n) from prime weights."""
    if isinstance(segment, bool) or not isinstance(segment, int) or segment < 1:
        raise ValueError("segment must be positive")
    weight_map = dict(weights)
    total = 0
    for prime, exponent in _factor_integer(pair_moment_factor(segment)):
        if prime not in weight_map:
            raise ValueError("weights do not cover every prime factor of A_n")
        total += exponent * weight_map[prime]
    return total


def defect_kernel_residuals(max_segment: int, depths: tuple[int, ...]) -> tuple[tuple[int, int], ...]:
    """Return (n, z_n-sum alpha*z_j) at every composite-boundary column."""
    _require_depths(max_segment, depths)
    return tuple(
        (
            segment,
            depths[segment]
            - sum(
                exponent * depths[index]
                for index, exponent in composite_A_relation_exponents(segment)
            ),
        )
        for segment in composite_indices(max_segment)
    )


def defect_kernel_factorization_theorem(max_segment: int, depths: tuple[int, ...]) -> bool:
    """Certify zero composite residuals iff z_n factors as L(A_n)."""
    _require_depths(max_segment, depths)
    invisible = all(value == 0 for _, value in defect_kernel_residuals(max_segment, depths))
    weights = prime_weights_from_depths(max_segment, depths)
    factors = all(
        additive_A_depth(segment, weights) == depths[segment]
        for segment in range(1, max_segment + 1)
    )
    if invisible != factors:
        raise AssertionError("defect kernel must equal the additive A-functional image")
    return invisible


def twin_source_signed_prime_weights(rank: int, depth: int) -> tuple[int, int]:
    """Primitive twin source forces neighboring new-prime weights +z and -z.

    This is the local signature of any defect-invisible extension with z_j=0
    for j<r, z_r=depth and z_(r+1)=0.
    """
    if isinstance(rank, bool) or not isinstance(rank, int) or rank < 3:
        raise ValueError("rank must be at least three")
    if isinstance(depth, bool) or not isinstance(depth, int) or depth <= 0:
        raise ValueError("depth must be positive")
    left_prime = 2 * rank - 1
    right_prime = 2 * rank + 1
    if left_prime not in primes_through(left_prime) or right_prime not in primes_through(right_prime):
        raise ValueError("rank must be a twin-prime center")
    depths = tuple([0] * rank + [depth, 0])
    left = prime_weight_from_depths(left_prime, depths)
    right = prime_weight_from_depths(right_prime, depths)
    if left != depth or right != -depth:
        raise AssertionError("primitive twin source must create signed neighboring prime weights")
    return left, right
