"""Prime-halving DAG envelope for canonical central-binomial support.

For the canonical central-binomial basis expansion E(x), an odd prime q enters
through h=(q+1)/2 as

    E(q)=E(h)-E(2)+e_h-e_(h-1).

Thus every nontrivial support index is an endpoint of an edge generated by an
odd prime encountered while recursively factoring x, then (q+1)/2, and so on.

Define Q(x) to be that recursive odd-prime ancestor set.  Then

    supp(E(x)) \ {1}
      subseteq { (q-1)/2, (q+1)/2 : q in Q(x) }.

For the P022 composite-boundary half-index relation at m=(p-1)/2, the support
is contained in the union of the endpoint envelopes for m and p-2, together
with the explicit point m-1.

Combining this with the integer midpoint companion H_d, a left Franel zero
j=m-d can threaten support only if p|H_d and one of

    2j-1 = p-2d-2,
    2j+1 = p-2d

belongs to Q(m) union Q(p-2).

Absence of such endpoint collisions is a proved sufficient support-avoidance
certificate.  Presence is only a candidate because endpoint coefficients may
still cancel in the exact exponent vector.
"""

from __future__ import annotations

from functools import lru_cache

from .p022_barlow_franel_half_index import composite_boundary_half_witness
from .p022_barlow_franel_integer_companion import (
    forced_zero_offsets_from_integer_companion,
)
from .p022_barlow_half_defect_obstructions import half_defect_support_zero_hits
from .p022_barlow_low_order_defect_reduction import (
    _factor_integer,
    composite_A_relation_exponents,
    integer_in_central_binomial_basis,
)


def _require_positive(name: str, value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ValueError(f"{name} must be a positive integer")


@lru_cache(maxsize=None)
def prime_halving_ancestor_primes(value: int) -> tuple[int, ...]:
    """Recursive odd-prime set generated by q | x and x <- (q+1)/2."""
    _require_positive("value", value)
    primes: set[int] = set()
    for prime, _ in _factor_integer(value):
        if prime == 2:
            continue
        primes.add(prime)
        child = (prime + 1) // 2
        if child < value:
            primes.update(prime_halving_ancestor_primes(child))
    return tuple(sorted(primes))


def prime_halving_endpoint_envelope(value: int) -> tuple[int, ...]:
    """All possible j>=2 endpoints touched by the recursive A-basis DAG."""
    _require_positive("value", value)
    endpoints: set[int] = set()
    for prime in prime_halving_ancestor_primes(value):
        lower = (prime - 1) // 2
        upper = (prime + 1) // 2
        if lower >= 2:
            endpoints.add(lower)
        if upper >= 2:
            endpoints.add(upper)
    return tuple(sorted(endpoints))


def basis_support_lies_in_endpoint_envelope(value: int) -> bool:
    """Exact expansion support is contained in {1} plus the DAG endpoints."""
    _require_positive("value", value)
    envelope = set(prime_halving_endpoint_envelope(value))
    expansion = integer_in_central_binomial_basis(value)
    escaped = [index for index, _ in expansion if index != 1 and index not in envelope]
    if escaped:
        raise AssertionError("canonical A-basis support escaped its prime-halving DAG")
    return True


def half_defect_endpoint_envelope(prime: int) -> tuple[int, ...]:
    """Support envelope for the target composite-boundary midpoint relation."""
    midpoint, _ = composite_boundary_half_witness(prime)
    endpoints = set(prime_halving_endpoint_envelope(midpoint))
    endpoints.update(prime_halving_endpoint_envelope(prime - 2))
    endpoints.add(midpoint - 1)
    endpoints.add(1)
    return tuple(sorted(endpoints))


def half_defect_support_lies_in_endpoint_envelope(prime: int) -> bool:
    midpoint, _ = composite_boundary_half_witness(prime)
    envelope = set(half_defect_endpoint_envelope(prime))
    support = {index for index, _ in composite_A_relation_exponents(midpoint)}
    if not support.issubset(envelope):
        raise AssertionError("half-defect support escaped the combined prime-halving DAG")
    return True


def left_zero_endpoint_collision_candidates(prime: int) -> tuple[int, ...]:
    """Left zero digits that are even eligible to lie on the A-support DAG."""
    midpoint, _ = composite_boundary_half_witness(prime)
    ancestor_primes = set(prime_halving_ancestor_primes(midpoint))
    ancestor_primes.update(prime_halving_ancestor_primes(prime - 2))
    candidates = []
    for offset in forced_zero_offsets_from_integer_companion(prime):
        index = midpoint - offset
        if (2 * index - 1) in ancestor_primes or (2 * index + 1) in ancestor_primes:
            candidates.append(index)
    return tuple(sorted(candidates))


def endpoint_dag_certifies_support_avoidance(prime: int) -> bool:
    """Sufficient certificate: no zero digit is even an eligible DAG endpoint."""
    candidates = left_zero_endpoint_collision_candidates(prime)
    if candidates:
        return False
    if half_defect_support_zero_hits(prime):
        raise AssertionError("empty DAG candidate set must force exact support avoidance")
    return True


def companion_offset_collision_signature(prime: int) -> tuple[tuple[int, int, int], ...]:
    """Return (d, p-2d-2, p-2d) for zero offsets touching ancestor primes.

    This is the offset-coordinate form of the exact necessary collision test.
    """
    midpoint, _ = composite_boundary_half_witness(prime)
    ancestor_primes = set(prime_halving_ancestor_primes(midpoint))
    ancestor_primes.update(prime_halving_ancestor_primes(prime - 2))
    output = []
    for offset in forced_zero_offsets_from_integer_companion(prime):
        lower_prime = prime - 2 * offset - 2
        upper_prime = prime - 2 * offset
        if lower_prime in ancestor_primes or upper_prime in ancestor_primes:
            output.append((offset, lower_prime, upper_prime))
    return tuple(output)
