"""Structural reduction of Barlow low-order identifiability certificates.

Let

    A_n = C(2n,n),
    F_n = sum_k C(n,k)^3.

The joint M2/M3 generator of one observed segment is g_n=(A_n,F_n), and
the hidden-tail generator is h=(4,8).

The A-coordinate is completely understood multiplicatively:

    A_n/A_(n-1) = 2(2n-1)/n.

The group generated by A_1,...,A_N is exactly the free abelian subgroup of
Q_+^x generated by the primes <=2N-1.  Hence a new A-coordinate appears at
index n exactly when 2n-1 is prime.  If 2n-1 is composite, A_n has a canonical
triangular expression in earlier A_j.  Applying the same exponent vector to
F_j produces a pure Franel defect D_n.

Together with the tail defect h/g_1^2=(1,2), these D_n form a triangular basis
of all relations killed by A-projection.  Therefore joint multiplicative
identifiability is equivalent to multiplicative independence of

    2, {D_n : 2n-1 composite}.

This module makes that reduction executable and compresses the current N=150
151x151 certificate to an 89x89 pure Franel-defect valuation certificate.
"""

from __future__ import annotations

from functools import lru_cache
from fractions import Fraction
from math import prod

from .p022_barlow_low_order_identifiability import (
    CERTIFICATE_MODULUS,
    determinant_mod_prime,
    p_adic_valuation,
    pair_moment_factor,
    triple_moment_factor,
)
from .p022_barlow_low_order_identifiability_66 import CERTIFICATE_66_ROWS
from .p022_barlow_low_order_identifiability_150 import CERTIFICATE_150_ROWS

ExponentVector = tuple[tuple[int, int], ...]  # sorted (A_index, exponent)

DEFECT_66_DETERMINANT_RESIDUE = 4
DEFECT_67_DETERMINANT_RESIDUE = 999_999
DEFECT_150_DETERMINANT_RESIDUE = 26_622


def _require_positive(name: str, value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ValueError(f"{name} must be a positive integer")


def _is_prime(value: int) -> bool:
    if value < 2:
        return False
    if value == 2:
        return True
    if value % 2 == 0:
        return False
    divisor = 3
    while divisor * divisor <= value:
        if value % divisor == 0:
            return False
        divisor += 2
    return True


def primes_through(limit: int) -> tuple[int, ...]:
    if isinstance(limit, bool) or not isinstance(limit, int) or limit < 0:
        raise ValueError("limit must be a non-negative integer")
    return tuple(value for value in range(2, limit + 1) if _is_prime(value))


def _factor_integer(value: int) -> tuple[tuple[int, int], ...]:
    _require_positive("value", value)
    remaining = value
    factors = []
    prime = 2
    while prime * prime <= remaining:
        exponent = 0
        while remaining % prime == 0:
            remaining //= prime
            exponent += 1
        if exponent:
            factors.append((prime, exponent))
        prime = 3 if prime == 2 else prime + 2
    if remaining > 1:
        factors.append((remaining, 1))
    return tuple(factors)


def _add_scaled(target: dict[int, int], source: ExponentVector, scale: int) -> None:
    for index, exponent in source:
        target[index] = target.get(index, 0) + scale * exponent
        if target[index] == 0:
            del target[index]


def _freeze(exponents: dict[int, int]) -> ExponentVector:
    return tuple(sorted((index, exponent) for index, exponent in exponents.items() if exponent))


@lru_cache(maxsize=None)
def integer_in_central_binomial_basis(value: int) -> ExponentVector:
    """Express a positive integer using the central-binomial generators A_j.

    A_1=2.  For an odd prime p, set j=(p+1)/2.  The exact recurrence gives

        p = (j/2) * A_j/A_(j-1).

    Since j<p, recursively expanding j terminates.  General integers are
    obtained by prime factorization.
    """
    _require_positive("value", value)
    if value == 1:
        return ()
    if value == 2:
        return ((1, 1),)

    output: dict[int, int] = {}
    for prime, multiplicity in _factor_integer(value):
        if prime == 2:
            output[1] = output.get(1, 0) + multiplicity
            continue
        j = (prime + 1) // 2
        prime_rep: dict[int, int] = {}
        _add_scaled(prime_rep, integer_in_central_binomial_basis(j), 1)
        prime_rep[1] = prime_rep.get(1, 0) - 1
        if prime_rep.get(1) == 0:
            prime_rep.pop(1, None)
        prime_rep[j] = prime_rep.get(j, 0) + 1
        prime_rep[j - 1] = prime_rep.get(j - 1, 0) - 1
        if prime_rep.get(j - 1) == 0:
            prime_rep.pop(j - 1, None)
        _add_scaled(output, _freeze(prime_rep), multiplicity)
    return _freeze(output)


def evaluate_A_exponents(exponents: ExponentVector) -> Fraction:
    result = Fraction(1, 1)
    for index, exponent in exponents:
        result *= Fraction(pair_moment_factor(index), 1) ** exponent
    return result


def evaluate_F_exponents(exponents: ExponentVector) -> Fraction:
    result = Fraction(1, 1)
    for index, exponent in exponents:
        result *= Fraction(triple_moment_factor(index), 1) ** exponent
    return result


def composite_A_relation_exponents(segment: int) -> ExponentVector:
    """Return alpha with ``A_n=prod_(j<n) A_j^alpha_j``.

    This is defined exactly when ``2n-1`` is composite.  The recurrence

        A_n=A_(n-1)*2*(2n-1)/n

    and the recursive integer basis above make every right-hand index strictly
    smaller than n.
    """
    _require_positive("segment", segment)
    if segment < 2:
        raise ValueError("composite defect requires segment at least two")
    odd_boundary = 2 * segment - 1
    if _is_prime(odd_boundary):
        raise ValueError("prime odd boundary creates a new A pivot, not a defect")

    output: dict[int, int] = {segment - 1: 1, 1: 1}
    _add_scaled(output, integer_in_central_binomial_basis(odd_boundary), 1)
    _add_scaled(output, integer_in_central_binomial_basis(segment), -1)
    frozen = _freeze(output)
    if any(index >= segment for index, _ in frozen):
        raise AssertionError("composite A relation must be triangular")
    if evaluate_A_exponents(frozen) != pair_moment_factor(segment):
        raise AssertionError("central-binomial relation failed exact evaluation")
    return frozen


def composite_indices(max_segment: int) -> tuple[int, ...]:
    _require_positive("max_segment", max_segment)
    return tuple(
        segment
        for segment in range(2, max_segment + 1)
        if not _is_prime(2 * segment - 1)
    )


def franel_defect(segment: int) -> Fraction:
    """Pure F-coordinate after cancelling the canonical composite A relation."""
    exponents = composite_A_relation_exponents(segment)
    return Fraction(triple_moment_factor(segment), 1) / evaluate_F_exponents(exponents)


def franel_defect_valuation(segment: int, prime: int) -> int:
    """Exact p-adic valuation of D_n without constructing the rational D_n."""
    _require_positive("prime", prime)
    exponents = composite_A_relation_exponents(segment)
    return p_adic_valuation(triple_moment_factor(segment), prime) - sum(
        exponent * p_adic_valuation(triple_moment_factor(index), prime)
        for index, exponent in exponents
    )


def tail_defect_valuation(prime: int) -> int:
    """Tail defect h/g_1^2=(1,2)."""
    _require_positive("prime", prime)
    return 1 if prime == 2 else 0


def franel_rows_from_joint_rows(
    rows: tuple[tuple[str, int], ...]
) -> tuple[int, ...]:
    return tuple(prime for kind, prime in rows if kind == "F3")


def A_rows_from_joint_rows(
    rows: tuple[tuple[str, int], ...]
) -> tuple[int, ...]:
    return tuple(prime for kind, prime in rows if kind == "A")


def defect_valuation_matrix(
    max_segment: int, primes: tuple[int, ...]
) -> tuple[tuple[int, ...], ...]:
    """Rows are p-valuations; columns are tail defect then composite D_n."""
    columns = composite_indices(max_segment)
    return tuple(
        tuple(
            [tail_defect_valuation(prime)]
            + [franel_defect_valuation(segment, prime) for segment in columns]
        )
        for prime in primes
    )


def defect_certificate_66_residue() -> int:
    primes = franel_rows_from_joint_rows(CERTIFICATE_66_ROWS)
    matrix = defect_valuation_matrix(66, primes)
    if len(matrix) != 35 or any(len(row) != 35 for row in matrix):
        raise AssertionError("length-66 defect certificate must be 35x35")
    return determinant_mod_prime(matrix, CERTIFICATE_MODULUS)


def defect_certificate_67_residue() -> int:
    primes = franel_rows_from_joint_rows(CERTIFICATE_66_ROWS) + (337,)
    matrix = defect_valuation_matrix(67, primes)
    if len(matrix) != 36 or any(len(row) != 36 for row in matrix):
        raise AssertionError("length-67 defect certificate must be 36x36")
    return determinant_mod_prime(matrix, CERTIFICATE_MODULUS)


def defect_certificate_150_residue() -> int:
    primes = franel_rows_from_joint_rows(CERTIFICATE_150_ROWS)
    matrix = defect_valuation_matrix(150, primes)
    if len(matrix) != 89 or any(len(row) != 89 for row in matrix):
        raise AssertionError("length-150 defect certificate must be 89x89")
    return determinant_mod_prime(matrix, CERTIFICATE_MODULUS)


def A_certificate_rows_are_complete_prime_basis_150() -> bool:
    """The selected A rows are exactly all primes <=299."""
    return A_rows_from_joint_rows(CERTIFICATE_150_ROWS) == primes_through(299)


def segment_67_A_relation() -> ExponentVector:
    expected: ExponentVector = (
        (1, 3),
        (2, -2),
        (4, 1),
        (8, 1),
        (9, -2),
        (10, 1),
        (33, 1),
        (34, -1),
        (66, 1),
    )
    actual = composite_A_relation_exponents(67)
    if actual != expected:
        raise AssertionError("segment-67 canonical A relation changed")
    return actual


def segment_67_row_337_defect_support() -> tuple[tuple[int, int], ...]:
    """Composite defects <=67 on which the valuation v_337 is nonzero."""
    support = tuple(
        (segment, franel_defect_valuation(segment, 337))
        for segment in composite_indices(67)
        if franel_defect_valuation(segment, 337)
    )
    expected = ((11, 1), (23, -1), (35, 1), (46, -1), (58, 1))
    if support != expected:
        raise AssertionError("337 defect support changed")
    return support
