"""Positive-depth affine-semigroup certificate for half-defect markers.

The exact marker is

    kappa = z_m + sum_i z_i c_i,

where every Franel zero depth z_i is a positive integer and c_i is a nonzero
signed zero-boundary crossing coefficient.

The crossing-lattice certificate uses only gcd(c_i).  Positivity of the depths
gives a stronger statement when all c_i have one sign.

* If every c_i>0, then kappa>0 automatically.
* If every c_i<0, write a_i=-c_i>0 and A0=sum_i a_i.  Since z_i=1+n_i,
  n_i>=0,

      kappa = z_m - A0 - sum_i n_i a_i.

  Hence cancellation is possible from positivity data alone iff

      z_m-A0

  belongs to the additive numerical semigroup generated by the a_i.  If it
does not, kappa is certified nonzero without knowing the exact earlier depths.

Mixed-sign coefficients require the full signed affine-semigroup problem and
are intentionally not collapsed by this helper.
"""

from __future__ import annotations

from math import gcd

from .p022_barlow_marker_crossing_lattice import boundary_zero_coefficients


def _require_positive(name: str, value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ValueError(f"{name} must be a positive integer")


def coefficient_sign_class(coefficients: tuple[int, ...]) -> str:
    """Return NONE, POSITIVE, NEGATIVE, or MIXED for nonzero coefficients."""
    if any(isinstance(value, bool) or not isinstance(value, int) for value in coefficients):
        raise ValueError("coefficients must be integers")
    nonzero = tuple(value for value in coefficients if value)
    if not nonzero:
        return "NONE"
    if all(value > 0 for value in nonzero):
        return "POSITIVE"
    if all(value < 0 for value in nonzero):
        return "NEGATIVE"
    return "MIXED"


def numerical_semigroup_contains(target: int, generators: tuple[int, ...]) -> bool:
    """Exact membership in <generators> for one nonnegative target.

    This finite dynamic program is an executable oracle, not a new numerical-
    semigroup theorem.  All generators must be positive integers.
    """
    if isinstance(target, bool) or not isinstance(target, int) or target < 0:
        raise ValueError("target must be a non-negative integer")
    if not generators:
        return target == 0
    if any(isinstance(value, bool) or not isinstance(value, int) or value <= 0 for value in generators):
        raise ValueError("generators must be positive integers")
    reduced = tuple(sorted(set(generators)))
    common = 0
    for value in reduced:
        common = gcd(common, value)
    if target % common:
        return False
    # Divide by the gcd before the finite reachability calculation.
    target //= common
    reduced = tuple(value // common for value in reduced)
    reachable = bytearray(target + 1)
    reachable[0] = 1
    for value in range(target + 1):
        if not reachable[value]:
            continue
        for generator in reduced:
            nxt = value + generator
            if nxt <= target:
                reachable[nxt] = 1
    return bool(reachable[target])


def same_sign_cancellation_possible(
    midpoint_depth: int,
    coefficients: tuple[int, ...],
) -> bool | None:
    """Can kappa=0 occur for some positive earlier depths?

    Returns an exact Boolean for NONE/POSITIVE/NEGATIVE sign classes.  Returns
    None for MIXED because positivity alone does not reduce that case to an
    ordinary one-sided numerical semigroup.
    """
    _require_positive("midpoint_depth", midpoint_depth)
    sign_class = coefficient_sign_class(coefficients)
    nonzero = tuple(value for value in coefficients if value)
    if sign_class == "NONE":
        return False
    if sign_class == "POSITIVE":
        return False
    if sign_class == "MIXED":
        return None

    magnitudes = tuple(-value for value in nonzero)
    base_load = sum(magnitudes)
    residual = midpoint_depth - base_load
    if residual < 0:
        return False
    return numerical_semigroup_contains(residual, magnitudes)


def same_sign_semigroup_certifies_nonzero(
    midpoint_depth: int,
    coefficients: tuple[int, ...],
) -> bool:
    """Sufficient nonvanishing certificate using only positivity of zero depths."""
    possible = same_sign_cancellation_possible(midpoint_depth, coefficients)
    return possible is False


def half_defect_crossing_coefficients(prime: int) -> tuple[int, ...]:
    return tuple(coefficient for _, coefficient in boundary_zero_coefficients(prime))


def half_defect_semigroup_certificate(prime: int, midpoint_depth: int) -> bool:
    """Apply the same-sign certificate to one forced composite midpoint.

    False is only 'not certified by this quotient'; it is never an assertion
    that the exact marker vanishes.
    """
    coefficients = half_defect_crossing_coefficients(prime)
    return same_sign_semigroup_certifies_nonzero(midpoint_depth, coefficients)


def negative_crossing_load_profile(
    midpoint_depth: int,
    coefficients: tuple[int, ...],
) -> tuple[int, int, bool] | None:
    """For all-negative c_i, return (A0, residual, semigroup_reachable).

    The marker can vanish for some positive earlier depths iff the final Boolean
    is true.  Other sign classes return None.
    """
    _require_positive("midpoint_depth", midpoint_depth)
    if coefficient_sign_class(coefficients) != "NEGATIVE":
        return None
    magnitudes = tuple(-value for value in coefficients if value)
    base_load = sum(magnitudes)
    residual = midpoint_depth - base_load
    if residual < 0:
        return base_load, residual, False
    return base_load, residual, numerical_semigroup_contains(residual, magnitudes)
