"""Exact positive-depth cancellation classification for half-defect markers.

The marker has the form

    kappa = z_m + sum_i z_i c_i,

where z_m and every earlier Franel zero depth z_i are positive integers, and
c_i are the nonzero signed zero-boundary crossing coefficients.

Positivity gives an exact coefficient-only classification of whether *some*
positive earlier depths can make kappa vanish:

* no c_i: impossible;
* all c_i>0: impossible;
* all c_i<0: write a_i=-c_i>0 and A0=sum a_i; cancellation is possible iff
  z_m-A0 belongs to the numerical semigroup <a_i>;
* mixed signs: cancellation is possible iff gcd(|c_i|) divides z_m.

The mixed-sign statement follows because a finitely generated additive monoid
containing both positive and negative integers is exactly the subgroup g Z,
where g is the gcd of its generators.  Positivity of the depth shifts does not
shrink that subgroup: zero-sum relations between opposite-sign generators let
any integer Bezout representation be shifted to nonnegative multiplicities.

This theorem classifies *possibility from coefficient geometry and positivity*.
It does not assert that the actual Franel depths realize a possible cancellation.
"""

from __future__ import annotations

from math import gcd

from .p022_barlow_marker_crossing_lattice import boundary_zero_coefficients


def _require_positive(name: str, value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ValueError(f"{name} must be a positive integer")


def coefficient_sign_class(coefficients: tuple[int, ...]) -> str:
    """Return NONE, POSITIVE, NEGATIVE, or MIXED for nonzero coefficients."""
    if any(isinstance(value, bool) or not isinstance(value, int) for value in coefficients):
        raise ValueError("coefficients must be integers")
    nonzero = tuple(value for value in coefficients if value)
    if not nonzero:
        return "NONE"
    if all(value > 0 for value in nonzero):
        return "POSITIVE"
    if all(value < 0 for value in nonzero):
        return "NEGATIVE"
    return "MIXED"


def coefficient_gcd(coefficients: tuple[int, ...]) -> int:
    common = 0
    for value in coefficients:
        if isinstance(value, bool) or not isinstance(value, int):
            raise ValueError("coefficients must be integers")
        if value:
            common = gcd(common, abs(value))
    return common


def numerical_semigroup_contains(target: int, generators: tuple[int, ...]) -> bool:
    """Exact membership in <generators> for one nonnegative target."""
    if isinstance(target, bool) or not isinstance(target, int) or target < 0:
        raise ValueError("target must be a non-negative integer")
    if not generators:
        return target == 0
    if any(isinstance(value, bool) or not isinstance(value, int) or value <= 0 for value in generators):
        raise ValueError("generators must be positive integers")
    reduced = tuple(sorted(set(generators)))
    common = 0
    for value in reduced:
        common = gcd(common, value)
    if target % common:
        return False
    target //= common
    reduced = tuple(value // common for value in reduced)
    reachable = bytearray(target + 1)
    reachable[0] = 1
    for value in range(target + 1):
        if not reachable[value]:
            continue
        for generator in reduced:
            nxt = value + generator
            if nxt <= target:
                reachable[nxt] = 1
    return bool(reachable[target])


def positive_depth_cancellation_possible(
    midpoint_depth: int,
    coefficients: tuple[int, ...],
) -> bool:
    """Exact existence of positive integer depths z_i with kappa=0.

    This quantifies over arbitrary positive depths compatible with the supplied
    crossing coefficients.  It is therefore a quotient-state possibility test,
    not a claim about the actual Franel depths for one prime.
    """
    _require_positive("midpoint_depth", midpoint_depth)
    sign_class = coefficient_sign_class(coefficients)
    nonzero = tuple(value for value in coefficients if value)

    if sign_class in ("NONE", "POSITIVE"):
        return False

    if sign_class == "NEGATIVE":
        magnitudes = tuple(-value for value in nonzero)
        base_load = sum(magnitudes)
        residual = midpoint_depth - base_load
        if residual < 0:
            return False
        return numerical_semigroup_contains(residual, magnitudes)

    # Mixed signs.  After z_i=1+n_i, the variable correction belongs to the
    # monoid generated by the same signed coefficients.  Because that monoid
    # contains both signs, it equals gZ.  The fixed base sum is itself in gZ,
    # so zero marker is possible exactly when g divides midpoint_depth.
    common = coefficient_gcd(nonzero)
    if common <= 0:
        raise AssertionError("mixed nonzero coefficients must have positive gcd")
    return midpoint_depth % common == 0


def coefficient_geometry_certifies_nonzero(
    midpoint_depth: int,
    coefficients: tuple[int, ...],
) -> bool:
    """Whether coefficient geometry + positivity alone rule out cancellation."""
    return not positive_depth_cancellation_possible(midpoint_depth, coefficients)


# Backward-compatible same-sign names retained for existing P022 tests/users.
def same_sign_cancellation_possible(
    midpoint_depth: int,
    coefficients: tuple[int, ...],
) -> bool | None:
    sign_class = coefficient_sign_class(coefficients)
    if sign_class == "MIXED":
        return None
    return positive_depth_cancellation_possible(midpoint_depth, coefficients)


def same_sign_semigroup_certifies_nonzero(
    midpoint_depth: int,
    coefficients: tuple[int, ...],
) -> bool:
    possible = same_sign_cancellation_possible(midpoint_depth, coefficients)
    return possible is False


def half_defect_crossing_coefficients(prime: int) -> tuple[int, ...]:
    return tuple(coefficient for _, coefficient in boundary_zero_coefficients(prime))


def half_defect_semigroup_certificate(prime: int, midpoint_depth: int) -> bool:
    """Apply the full coefficient-geometry classification to one prime.

    False means only that positivity/coefficient geometry allow cancellation;
    it never asserts that the actual Franel depths cancel.
    """
    coefficients = half_defect_crossing_coefficients(prime)
    return coefficient_geometry_certifies_nonzero(midpoint_depth, coefficients)


def negative_crossing_load_profile(
    midpoint_depth: int,
    coefficients: tuple[int, ...],
) -> tuple[int, int, bool] | None:
    """For all-negative c_i, return (A0, residual, semigroup_reachable)."""
    _require_positive("midpoint_depth", midpoint_depth)
    if coefficient_sign_class(coefficients) != "NEGATIVE":
        return None
    magnitudes = tuple(-value for value in coefficients if value)
    base_load = sum(magnitudes)
    residual = midpoint_depth - base_load
    if residual < 0:
        return base_load, residual, False
    return base_load, residual, numerical_semigroup_contains(residual, magnitudes)
