"""Prime-halving flow whose discrete boundary is the central-binomial A-basis.

For a positive integer v, start one positive flow packet for every prime factor
occurrence.  An odd prime q sends its full packet through

    h=(q+1)/2

and the packet branches according to the prime multiplicities of h.  This
produces a finite positive flow c_v(q) on the prime-halving ancestry graph.

Each odd prime node q with h=(q+1)/2 contributes the signed A-boundary

    +c_v(q) at A_h,
    -c_v(q) at A_(h-1),
    -c_v(q) at A_1,

while q=2 contributes +c_v(2) at A_1.

The resulting boundary vector is exactly the canonical integer-in-A-basis
exponent vector beta(v).

Pairing against an odd-prime Franel valuation field w_j (so w_1=0) gives

    tau_w(v)=sum_(q odd) c_v(q) [w_((q+1)/2)-w_((q-1)/2)].

Thus the transfer valuation is a positive ancestry flow paired with the
discrete gradient of the Franel valuation field.
"""

from __future__ import annotations

from collections import defaultdict
from functools import lru_cache

from .p022_barlow_low_order_defect_reduction import (
    _factor_integer,
    integer_in_central_binomial_basis,
)

PrimeFlow = tuple[tuple[int, int], ...]
ExponentVector = tuple[tuple[int, int], ...]


@lru_cache(maxsize=None)
def unit_prime_halving_flow(prime: int) -> PrimeFlow:
    """Prime-flow generated by one occurrence of one prime root."""
    if (
        isinstance(prime, bool)
        or not isinstance(prime, int)
        or prime < 2
        or _factor_integer(prime) != ((prime, 1),)
    ):
        raise ValueError("prime must be prime")
    output: dict[int, int] = {prime: 1}
    if prime == 2:
        return ((2, 1),)
    half = (prime + 1) // 2
    for child, multiplicity in _factor_integer(half):
        for descendant, count in unit_prime_halving_flow(child):
            output[descendant] = output.get(descendant, 0) + multiplicity * count
    return tuple(sorted(output.items()))


def prime_halving_flow(value: int) -> PrimeFlow:
    """Positive ancestry flow c_v(q) for a positive integer v."""
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ValueError("value must be positive")
    output: dict[int, int] = defaultdict(int)
    for prime, multiplicity in _factor_integer(value):
        for descendant, count in unit_prime_halving_flow(prime):
            output[descendant] += multiplicity * count
    return tuple(sorted((prime, count) for prime, count in output.items() if count))


def flow_boundary_exponents(value: int) -> ExponentVector:
    """Take the signed A-boundary of the positive prime-halving flow."""
    boundary: dict[int, int] = defaultdict(int)
    for prime, count in prime_halving_flow(value):
        if prime == 2:
            boundary[1] += count
            continue
        half = (prime + 1) // 2
        boundary[half] += count
        boundary[half - 1] -= count
        boundary[1] -= count
    return tuple(sorted((index, exponent) for index, exponent in boundary.items() if exponent))


def flow_boundary_equals_canonical_basis(value: int) -> bool:
    """Exact theorem: boundary(c_v)=beta(v)."""
    boundary = flow_boundary_exponents(value)
    canonical = integer_in_central_binomial_basis(value)
    if boundary != canonical:
        raise AssertionError("prime-halving flow boundary must equal canonical A-basis")
    return True


def flow_weight(prime: int, value: int) -> int:
    """c_v(prime), zero if the prime is absent from the ancestry flow."""
    return dict(prime_halving_flow(value)).get(prime, 0)


def valuation_gradient_pairing(value: int, weights: dict[int, int]) -> int:
    """sum c_v(q)*(w_h-w_(h-1)) for odd q, requiring w_1=0.

    This is the transfer pairing for odd-prime Franel valuation fields.
    """
    if weights.get(1, 0) != 0:
        raise ValueError("gradient form requires base weight w_1=0")
    total = 0
    for prime, count in prime_halving_flow(value):
        if prime == 2:
            continue
        half = (prime + 1) // 2
        total += count * (weights.get(half, 0) - weights.get(half - 1, 0))
    return total


def canonical_pairing_from_boundary(value: int, weights: dict[int, int]) -> int:
    """Direct beta(v)-weight pairing used to verify the gradient formula."""
    return sum(
        exponent * weights.get(index, 0)
        for index, exponent in integer_in_central_binomial_basis(value)
    )


def gradient_pairing_equals_canonical(value: int, weights: dict[int, int]) -> bool:
    gradient = valuation_gradient_pairing(value, weights)
    canonical = canonical_pairing_from_boundary(value, weights)
    if gradient != canonical:
        raise AssertionError("flow-gradient pairing must equal canonical transfer pairing")
    return True


def flow_paths_amplify_terminal_prime(value: int, terminal_prime: int) -> int:
    """Return the positive path multiplicity c_v(q) at one terminal prime."""
    return flow_weight(terminal_prime, value)


def p369581_flow_certificate() -> tuple[int, int, int, int]:
    """Explain alpha_8=+2 by two units of m-flow through prime 17.

    Returns (c_m(17), c_(p-2)(17), beta_m(8), alpha_m8).
    """
    p = 369_581
    m = 184_790
    c_m = flow_weight(17, m)
    c_boundary = flow_weight(17, p - 2)
    beta_m_8 = dict(flow_boundary_exponents(m)).get(8, 0)
    beta_boundary_8 = dict(flow_boundary_exponents(p - 2)).get(8, 0)
    alpha_8 = beta_boundary_8 - beta_m_8
    if (c_m, c_boundary, beta_m_8, alpha_8) != (2, 0, -2, 2):
        raise AssertionError("p=369581 flow multiplicity certificate changed")
    return c_m, c_boundary, beta_m_8, alpha_8


def p157_flow_certificate() -> tuple[int, int, int, int]:
    """Explain alpha_16=+1 by one p-2 flow packet through prime 31."""
    p = 157
    m = 78
    c_m = flow_weight(31, m)
    c_boundary = flow_weight(31, p - 2)
    beta_m_16 = dict(flow_boundary_exponents(m)).get(16, 0)
    beta_boundary_16 = dict(flow_boundary_exponents(p - 2)).get(16, 0)
    alpha_16 = beta_boundary_16 - beta_m_16
    if (c_m, c_boundary, beta_m_16, alpha_16) != (0, 1, 0, 1):
        raise AssertionError("p=157 flow multiplicity certificate changed")
    return c_m, c_boundary, beta_m_16, alpha_16
