"""Antichain-normalized witness spectra and width saturation.

Joint membership queries on ideal states are first quotiented by the poset law:
S is equivalent to its maximal antichain alpha(S).  For an admissible family F,
retain the antichains of size <=k that fit inside at least one admissible ideal.
This is the exact bounded-arity joint-MAY signature after operation
normalization.  It is downward closed under antichain dominance and generated by
its dominance-maximal members.

Because every antichain has size at most width(P), witness-arity precision
saturates once k reaches width(P).  In particular width-one (chain) observation
families have no joint-correlation refinement beyond pointwise support.
"""

from __future__ import annotations

from dataclasses import dataclass

from .poset_boundary_width import poset_width
from .poset_joint_may_complex import maximal_admissible_ideals
from .poset_observation_boundary import (
    Antichain,
    Element,
    Ideal,
    Relation,
    antichain_dominates,
    enumerate_antichains,
    maximal_boundary,
)


@dataclass(frozen=True)
class AntichainWitnessSpectrum:
    raw_arity_cap: int
    effective_arity_cap: int
    poset_width: int
    may_antichains: frozenset[Antichain]
    maximal_generators: frozenset[Antichain]
    saturated: bool


def antichain_witness_spectrum(
    elements: tuple[Element, ...],
    leq: Relation,
    admissible_ideals: frozenset[Ideal],
    raw_arity_cap: int,
) -> AntichainWitnessSpectrum:
    if isinstance(raw_arity_cap, bool) or not isinstance(raw_arity_cap, int) or raw_arity_cap < 1:
        raise ValueError("raw_arity_cap must be a positive integer")
    width = poset_width(elements, leq)
    effective = min(raw_arity_cap, width)
    maximals = maximal_admissible_ideals(elements, leq, admissible_ideals)

    antichains = enumerate_antichains(elements, leq)
    may = frozenset(
        antichain
        for antichain in antichains
        if len(antichain) <= effective
        and any(antichain.issubset(ideal) for ideal in maximals)
    )

    generators = frozenset(
        candidate
        for candidate in may
        if not any(
            candidate != other
            and antichain_dominates(elements, leq, candidate, other)
            for other in may
        )
    )

    # Regenerate the full bounded spectrum from dominance-maximal generators.
    regenerated = frozenset(
        candidate
        for candidate in antichains
        if len(candidate) <= effective
        and any(
            antichain_dominates(elements, leq, candidate, generator)
            for generator in generators
        )
    )
    if regenerated != may:
        raise AssertionError("dominance-maximal antichains failed to regenerate the witness spectrum")

    return AntichainWitnessSpectrum(
        raw_arity_cap=raw_arity_cap,
        effective_arity_cap=effective,
        poset_width=width,
        may_antichains=may,
        maximal_generators=generators,
        saturated=raw_arity_cap >= width,
    )


def full_maximal_ideal_boundaries(
    elements: tuple[Element, ...], leq: Relation, admissible_ideals: frozenset[Ideal]
) -> frozenset[Antichain]:
    maximals = maximal_admissible_ideals(elements, leq, admissible_ideals)
    return frozenset(maximal_boundary(elements, leq, ideal) for ideal in maximals)
