"""Higher-order incidence hypergraph for finite precision task families.

Pairwise block-incidence graphs do not determine a joint precision state for
three or more observations.  The exact object is the set of realized block
label tuples.  When one more task is added, the number of possible extensions
of each realized prefix tuple is the local minimum repair alphabet for that
conditional task upgrade.
"""

from __future__ import annotations

from collections import Counter
from collections.abc import Hashable, Iterable, Mapping, Sequence
from math import comb

State = Hashable
Partition = Mapping[State, Hashable]


def _domain(states: Iterable[State]) -> tuple[State, ...]:
    domain = tuple(states)
    if not domain:
        raise ValueError("state domain must be nonempty")
    if len(domain) != len(set(domain)):
        raise ValueError("state domain must contain distinct states")
    return domain


def _partitions(
    states: tuple[State, ...], partitions: Sequence[Partition]
) -> tuple[Partition, ...]:
    result = tuple(partitions)
    if not result:
        raise ValueError("at least one precision partition is required")
    state_set = set(states)
    for partition in result:
        if set(partition) != state_set:
            raise ValueError("every partition must cover the state domain exactly")
    return result


def realized_joint_tuples(
    states: Iterable[State], partitions: Sequence[Partition]
) -> frozenset[tuple[Hashable, ...]]:
    """Hyperedges of the precision incidence hypergraph."""

    domain = _domain(states)
    family = _partitions(domain, partitions)
    return frozenset(
        tuple(partition[state] for partition in family)
        for state in domain
    )


def joint_tuple_multiplicities(
    states: Iterable[State], partitions: Sequence[Partition]
) -> dict[tuple[Hashable, ...], int]:
    """Number of raw states realizing each joint precision tuple."""

    domain = _domain(states)
    family = _partitions(domain, partitions)
    counts = Counter(
        tuple(partition[state] for partition in family)
        for state in domain
    )
    return dict(counts)


def joint_partition(
    states: Iterable[State], partitions: Sequence[Partition]
) -> dict[State, tuple[Hashable, ...]]:
    """Common refinement generated by all supplied precision partitions."""

    domain = _domain(states)
    family = _partitions(domain, partitions)
    return {
        state: tuple(partition[state] for partition in family)
        for state in domain
    }


def realized_joint_class_count(
    states: Iterable[State], partitions: Sequence[Partition]
) -> int:
    return len(realized_joint_tuples(states, partitions))


def formal_joint_candidate_count(
    states: Iterable[State], partitions: Sequence[Partition]
) -> int:
    domain = _domain(states)
    family = _partitions(domain, partitions)
    product = 1
    for partition in family:
        product *= len({partition[state] for state in domain})
    return product


def unrealized_joint_tuple_defect(
    states: Iterable[State], partitions: Sequence[Partition]
) -> int:
    return formal_joint_candidate_count(states, partitions) - realized_joint_class_count(
        states, partitions
    )


def extension_sets(
    states: Iterable[State],
    known_partitions: Sequence[Partition],
    added_partition: Partition,
) -> dict[tuple[Hashable, ...], frozenset[Hashable]]:
    """Possible added-task labels extending each realized known-task tuple."""

    domain = _domain(states)
    known = _partitions(domain, known_partitions)
    if set(added_partition) != set(domain):
        raise ValueError("added partition must cover the state domain exactly")
    extensions: dict[tuple[Hashable, ...], set[Hashable]] = {}
    for state in domain:
        prefix = tuple(partition[state] for partition in known)
        extensions.setdefault(prefix, set()).add(added_partition[state])
    return {
        prefix: frozenset(labels)
        for prefix, labels in extensions.items()
    }


def conditional_repair_factor(
    states: Iterable[State],
    known_partitions: Sequence[Partition],
    added_partition: Partition,
) -> int:
    """Minimum alphabet for adding one task after all known tasks are retained."""

    return max(
        len(labels)
        for labels in extension_sets(states, known_partitions, added_partition).values()
    )


def conditional_repair_spectrum(
    states: Iterable[State],
    known_partitions: Sequence[Partition],
    added_partition: Partition,
) -> tuple[int, ...]:
    """Binomial spectrum of extension degrees for the added task."""

    extensions = extension_sets(states, known_partitions, added_partition)
    added_joint_classes = sum(len(labels) for labels in extensions.values())
    return tuple(
        sum(comb(len(labels), order) for labels in extensions.values())
        for order in range(1, added_joint_classes + 1)
    )


def context_refinement_monotone(
    states: Iterable[State],
    less_context: Sequence[Partition],
    more_context: Sequence[Partition],
    added_partition: Partition,
) -> bool:
    """Verify that adding known context cannot increase conditional repair.

    ``more_context`` must start with exactly the partitions in ``less_context``;
    the additional suffix provides extra retained information.
    """

    less = tuple(less_context)
    more = tuple(more_context)
    if more[: len(less)] != less:
        raise ValueError("more_context must extend less_context as a prefix")
    return conditional_repair_factor(
        states, more, added_partition
    ) <= conditional_repair_factor(states, less, added_partition)


def pairwise_intersection_counts(
    states: Iterable[State], partitions: Sequence[Partition]
) -> dict[tuple[int, int], dict[tuple[Hashable, Hashable], int]]:
    """Weighted pairwise incidence shadows of a higher-order task family."""

    domain = _domain(states)
    family = _partitions(domain, partitions)
    result: dict[tuple[int, int], dict[tuple[Hashable, Hashable], int]] = {}
    for i in range(len(family)):
        for j in range(i + 1, len(family)):
            counts = Counter(
                (family[i][state], family[j][state])
                for state in domain
            )
            result[(i, j)] = dict(counts)
    return result
