"""One-sided versus bidirectional contact action languages for E001/E002.

This module records the strict boundary exposed after the symmetric action-family
result.  Gcd is the exact minimal arbitrary-future Boolean-contact coordinate
whenever the signed action monoid contains both positive and negative moves:
its additive monoid equals the full subgroup ``g Z`` generated by the actions.

For a one-sided separating language, however, future words form a numerical
semigroup rather than its group completion.  Only cumulative sums that are
actually reachable can cut the current contact fiber.  The exact predictive
partition is therefore indexed by reachable semigroup thresholds, and a gcd
coordinate can retain unnecessary detail when small multiples of the gcd are
semigroup holes.

The same threshold statement has a closing-only analogue on a finite separated
shell.  These results are Boolean-contact specializations, not complete
collision-response semantics.
"""

from __future__ import annotations

from functools import reduce
from math import gcd
from typing import Iterable


def _require_int(name: str, value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{name} must be an integer")


def _require_positive(name: str, value: int) -> None:
    _require_int(name, value)
    if value <= 0:
        raise ValueError(f"{name} must be positive")


def _require_nonnegative(name: str, value: int) -> None:
    _require_int(name, value)
    if value < 0:
        raise ValueError(f"{name} must be nonnegative")


def normalize_positive_actions(actions: Iterable[int]) -> tuple[int, ...]:
    values = tuple(actions)
    if not values:
        raise ValueError("at least one positive action is required")
    for value in values:
        _require_positive("action", value)
    return values


def normalize_signed_actions(actions: Iterable[int]) -> tuple[int, ...]:
    values = tuple(actions)
    if not values:
        raise ValueError("at least one signed action is required")
    for value in values:
        _require_int("action", value)
        if value == 0:
            raise ValueError("actions must be nonzero")
    return values


def action_gcd(actions: Iterable[int]) -> int:
    values = normalize_signed_actions(actions)
    return reduce(gcd, (abs(value) for value in values))


def action_language_is_bidirectional(actions: Iterable[int]) -> bool:
    values = normalize_signed_actions(actions)
    return any(value > 0 for value in values) and any(value < 0 for value in values)


def reachable_positive_sums(
    actions: Iterable[int],
    cutoff: int,
    horizon: int | None = None,
) -> tuple[int, ...]:
    """All distinct cumulative sums below ``cutoff`` in a positive action monoid.

    If ``horizon`` is supplied, only words of length at most that horizon are
    used.  The empty sum zero is always present.
    """
    values = normalize_positive_actions(actions)
    _require_positive("cutoff", cutoff)
    if horizon is not None:
        _require_nonnegative("horizon", horizon)

    reachable = {0}
    frontier = {0}
    depth = 0
    while frontier and (horizon is None or depth < horizon):
        next_frontier = {
            total + action
            for total in frontier
            for action in values
            if total + action < cutoff
        } - reachable
        reachable.update(next_frontier)
        frontier = next_frontier
        depth += 1
    return tuple(sorted(reachable))


def separating_semigroup_rank(
    gap: int,
    precision: int,
    actions: Iterable[int],
    horizon: int | None = None,
) -> int:
    """Minimal nested-threshold rank inside the current contact fiber.

    A future cumulative separating displacement ``s`` remains contact exactly
    when ``s < precision-gap``.  Distinct reachable sums are therefore the only
    thresholds that can separate current-contact gaps.
    """
    _require_nonnegative("gap", gap)
    _require_positive("precision", precision)
    if gap >= precision:
        raise ValueError("gap must currently be contact")
    remaining = precision - gap
    reachable = reachable_positive_sums(actions, precision, horizon)
    return sum(1 for total in reachable if 0 < total < remaining)


def separating_semigroup_class_count(
    precision: int,
    actions: Iterable[int],
    horizon: int | None = None,
) -> int:
    """Exact predictive classes in ``0..precision-1`` for separating-only words."""
    _require_positive("precision", precision)
    reachable = reachable_positive_sums(actions, precision, horizon)
    # Each positive reachable cumulative displacement s<d contributes exactly
    # one boundary r=s+1 on the remaining-distance coordinate r=d-gap.
    return 1 + sum(1 for total in reachable if total > 0)


def separating_gcd_class_count(precision: int, actions: Iterable[int]) -> int:
    """Classes retained by the sufficient gcd coordinate, whether or not minimal."""
    _require_positive("precision", precision)
    values = normalize_positive_actions(actions)
    grain = reduce(gcd, values)
    return (precision + grain - 1) // grain


def separating_gcd_is_minimal(precision: int, actions: Iterable[int]) -> bool:
    """Whether every positive gcd multiple below d is actually semigroup-reachable."""
    _require_positive("precision", precision)
    values = normalize_positive_actions(actions)
    grain = reduce(gcd, values)
    reachable = set(reachable_positive_sums(values, precision, None))
    return all(value in reachable for value in range(grain, precision, grain))


def separating_semigroup_holes(
    precision: int,
    actions: Iterable[int],
) -> tuple[int, ...]:
    """Positive gcd multiples below d that the one-sided action monoid cannot reach."""
    _require_positive("precision", precision)
    values = normalize_positive_actions(actions)
    grain = reduce(gcd, values)
    reachable = set(reachable_positive_sums(values, precision, None))
    return tuple(
        value
        for value in range(grain, precision, grain)
        if value not in reachable
    )


def closing_shell_semigroup_rank(
    offset: int,
    shell_width: int,
    actions: Iterable[int],
    horizon: int | None = None,
) -> int:
    """Minimal threshold rank for closing-only motion in a separated shell.

    ``offset`` means current gap ``d+offset``.  A cumulative closing displacement
    ``s`` reaches contact exactly when ``s > offset``.  Only reachable sums below
    the shell width create distinctions among offsets ``0..R-1``.
    """
    _require_nonnegative("offset", offset)
    _require_positive("shell_width", shell_width)
    if offset >= shell_width:
        raise ValueError("offset must lie inside the declared shell")
    reachable = reachable_positive_sums(actions, shell_width, horizon)
    return sum(1 for total in reachable if total > offset)


def closing_shell_semigroup_class_count(
    shell_width: int,
    actions: Iterable[int],
    horizon: int | None = None,
) -> int:
    """Exact predictive classes in a width-R separated shell for closing-only words."""
    _require_positive("shell_width", shell_width)
    reachable = reachable_positive_sums(actions, shell_width, horizon)
    return 1 + sum(1 for total in reachable if total > 0)


def bidirectional_contact_coordinate(
    gap: int,
    precision: int,
    signed_actions: Iterable[int],
) -> int:
    """Exact gcd coordinate for any action language containing both signs."""
    _require_nonnegative("gap", gap)
    _require_positive("precision", precision)
    values = normalize_signed_actions(signed_actions)
    if not action_language_is_bidirectional(values):
        raise ValueError("signed action language must contain both positive and negative moves")
    grain = action_gcd(values)
    return -((gap - precision) // grain)


def bidirectional_coordinate_cap(precision: int, signed_actions: Iterable[int]) -> int:
    _require_positive("precision", precision)
    values = normalize_signed_actions(signed_actions)
    if not action_language_is_bidirectional(values):
        raise ValueError("signed action language must contain both signs")
    grain = action_gcd(values)
    return (precision + grain - 1) // grain


def apply_bidirectional_coordinate_action(
    coordinate: int,
    precision: int,
    signed_action: int,
    signed_actions: Iterable[int],
) -> int:
    """Exact K transport for one declared signed physical gap action."""
    _require_int("coordinate", coordinate)
    _require_positive("precision", precision)
    _require_int("signed_action", signed_action)
    values = normalize_signed_actions(signed_actions)
    if signed_action not in values:
        raise ValueError("signed_action must belong to the declared action language")
    if not action_language_is_bidirectional(values):
        raise ValueError("signed action language must contain both signs")
    grain = action_gcd(values)
    shift = signed_action // grain
    if signed_action > 0:
        return coordinate - shift
    return min(
        coordinate - shift,
        bidirectional_coordinate_cap(precision, values),
    )


def bidirectional_contact_from_coordinate(coordinate: int) -> bool:
    _require_int("coordinate", coordinate)
    return coordinate >= 1
