"""Canonical hidden-sublattice refinements for rank-two A3 guard images.

Fix a parent partition with rank-two hidden guard image L and an exact basis
H: Z^2 -> L. Every fine coordinate inside one parent block receives an integer
label lambda_i in Z^2 from its guard-coefficient difference to a block anchor.

For any target subgroup M <= Z^2, grouping coordinates by cosets modulo M is
the coarsest partition refinement whose child hidden image lies inside H(M).
If M is realizable as the exact image of some refinement, the canonical coset
refinement has exact image H(M) as well.
"""

from __future__ import annotations

from dataclasses import dataclass

from .guard_image_lattice import (
    GuardFamily,
    IntMatrix,
    guard_kernel_image_generators,
    integer_matrix_rank,
    rank_one_lattice_step,
)
from .linear_relation_quotient import Partition
from .rank_two_guard_reachability import (
    rank_two_basis_coordinates,
    rank_two_lattice_basis,
)


Coordinate = tuple[int, int]
SubgroupBasis = tuple[Coordinate, ...]


@dataclass(frozen=True)
class RankTwoHiddenLabels:
    parent_basis: tuple[tuple[int, ...], tuple[int, ...]]
    labeled_blocks: tuple[tuple[tuple[int, Coordinate], ...], ...]


def canonical_z2_subgroup(generators: tuple[Coordinate, ...]) -> SubgroupBasis:
    """Canonical basis of the subgroup of Z^2 generated by the inputs."""
    nonzero = tuple(generator for generator in generators if generator != (0, 0))
    if not nonzero:
        return ()
    rank = integer_matrix_rank(nonzero, column_count=2)
    if rank == 1:
        return (rank_one_lattice_step(nonzero, coordinate_count=2),)
    if rank == 2:
        return rank_two_lattice_basis(nonzero)
    raise AssertionError("a subgroup of Z^2 cannot have rank above two")


def z2_subgroup_contains(basis: SubgroupBasis, vector: Coordinate) -> bool:
    """Exact membership test for a canonical rank 0/1/2 subgroup of Z^2."""
    if not isinstance(vector, tuple) or len(vector) != 2:
        raise ValueError("vector must be a 2D integer tuple")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in vector):
        raise ValueError("vector entries must be integers")
    if not basis:
        return vector == (0, 0)
    if len(basis) == 1:
        step = basis[0]
        pivot = next(index for index, value in enumerate(step) if value != 0)
        if vector[pivot] % step[pivot] != 0:
            return False
        coefficient = vector[pivot] // step[pivot]
        return tuple(coefficient * value for value in step) == vector
    if len(basis) == 2:
        return rank_two_basis_coordinates(vector, (basis[0], basis[1])) is not None
    raise ValueError("basis must have rank at most two")


def rank_two_guard_labels(
    guards: GuardFamily, parent_partition: Partition
) -> RankTwoHiddenLabels:
    """Assign exact Z^2 hidden labels to fine coordinates inside parent blocks."""
    generators = guard_kernel_image_generators(guards, parent_partition)
    if integer_matrix_rank(generators, column_count=len(guards)) != 2:
        raise ValueError("parent guard-image lattice must have rank two")
    parent_basis = rank_two_lattice_basis(generators)
    labeled_blocks = []
    for group in parent_partition:
        anchor = group[0]
        labels = [(anchor, (0, 0))]
        for coordinate in group[1:]:
            difference = tuple(
                guard[coordinate] - guard[anchor]
                for guard in guards
            )
            coordinates = rank_two_basis_coordinates(difference, parent_basis)
            if coordinates is None:
                raise AssertionError("parent hidden basis must contain every within-block difference")
            labels.append((coordinate, coordinates))
        labeled_blocks.append(tuple(labels))
    return RankTwoHiddenLabels(
        parent_basis=parent_basis,
        labeled_blocks=tuple(labeled_blocks),
    )


def rank_two_canonical_sublattice_refinement(
    guards: GuardFamily,
    parent_partition: Partition,
    target_subgroup: SubgroupBasis,
) -> Partition:
    """Coarsest refinement whose hidden label differences lie in target_subgroup."""
    hidden = rank_two_guard_labels(guards, parent_partition)
    canonical_target = canonical_z2_subgroup(target_subgroup)
    refined = []
    for group in hidden.labeled_blocks:
        buckets: list[list[tuple[int, Coordinate]]] = []
        for coordinate, label in group:
            placed = False
            for bucket in buckets:
                representative_label = bucket[0][1]
                difference = (
                    label[0] - representative_label[0],
                    label[1] - representative_label[1],
                )
                if z2_subgroup_contains(canonical_target, difference):
                    bucket.append((coordinate, label))
                    placed = True
                    break
            if not placed:
                buckets.append([(coordinate, label)])
        refined.extend(tuple(coordinate for coordinate, _ in bucket) for bucket in buckets)
    return tuple(refined)


def rank_two_label_differences(
    guards: GuardFamily, parent_partition: Partition
) -> tuple[Coordinate, ...]:
    """Finite set of canonical nonzero hidden-label differences inside parent blocks."""
    hidden = rank_two_guard_labels(guards, parent_partition)
    differences = set()
    for group in hidden.labeled_blocks:
        labels = [label for _, label in group]
        for left in range(len(labels)):
            for right in range(left + 1, len(labels)):
                difference = (
                    labels[right][0] - labels[left][0],
                    labels[right][1] - labels[left][1],
                )
                if difference == (0, 0):
                    continue
                # Canonical sign for deduplication only; subgroup generation is sign-insensitive.
                if difference[0] < 0 or (difference[0] == 0 and difference[1] < 0):
                    difference = (-difference[0], -difference[1])
                differences.add(difference)
    return tuple(sorted(differences))


def rank_two_realizable_image_subgroups(
    guards: GuardFamily, parent_partition: Partition
) -> tuple[SubgroupBasis, ...]:
    """All distinct hidden-image subgroups realizable by partition refinements.

    Every child image is generated by a subset of the finite within-parent label
    differences. We enumerate subgroup closures incrementally and canonicalize
    after each added difference. This can still be exponential in the worst
    case, but it replaces Bell-number partition enumeration with the actual
    finite subgroup structure relevant to hidden guard behavior.
    """
    differences = rank_two_label_differences(guards, parent_partition)
    subgroups: set[SubgroupBasis] = {()}
    for difference in differences:
        current = tuple(subgroups)
        for subgroup in current:
            subgroups.add(canonical_z2_subgroup(subgroup + (difference,)))
    return tuple(sorted(subgroups, key=lambda basis: (len(basis), basis)))
