"""A3 relation-state quotient under zero-grand-total internal updates.

For positive capacities ``m`` let ``R`` be the canonical weighted relation map

    R(p)_ij = m_j*p_i - m_i*p_j.

Write

    g = gcd_i(m_i),
    a = m/g,
    tau = sum_i a_i.

Canonical ``relation_lattice`` already proves that the integer kernel of ``R``
is generated by the primitive capacity vector ``a``: equal relation fields
differ by integer multiples of ``a``, and one primitive shift changes grand
total by exactly ``tau``.

Let

    H = { h in Z^N : sum_i h_i = 0 }

be the lattice of all zero-grand-total internal state updates.  Acting by ``H``
on states induces the subgroup ``R(H)`` inside the legal relation-state lattice
``Lambda=im_Z(R)``.  The exact orbit quotient is

    Lambda / R(H)  ~=  Z / tau Z.

Indeed ``R(p)`` determines ``sum(p) mod tau`` because replacing a state by
another representative of the same relation field adds ``t*a`` and changes its
total by ``t*tau``.  Conversely, if states ``p,q`` have total difference
``t*tau``, then

    h = q - p - t*a

has zero grand total and

    R(p+h) = R(q-t*a) = R(q).

Thus two legal A3 relation states lie in the same zero-total-update orbit exactly
when their representative grand totals have the same residue modulo ``tau``.
The canonical translation period is therefore also the exact internal-update
orbit period of relation state.

This is pure A3 lattice algebra.  It does not assume contact, momentum, physics,
or a particular graph, and no novelty claim is made relative to standard lattice
quotient/isomorphism theory.
"""

from __future__ import annotations

from dataclasses import dataclass

from .relation_lattice import (
    primitive_capacity_vector,
    relation_translation_period,
    same_field_shift_multiple,
)
from .weighted_relation_field import WeightedField, weighted_relation_field


def _require_state(
    capacities: tuple[int, ...],
    totals: tuple[int, ...],
    name: str,
) -> None:
    if not isinstance(capacities, tuple) or not capacities:
        raise ValueError("capacities must be a nonempty tuple")
    if any(
        isinstance(value, bool) or not isinstance(value, int) or value <= 0
        for value in capacities
    ):
        raise ValueError("capacities must be positive integers")
    if not isinstance(totals, tuple) or len(totals) != len(capacities):
        raise ValueError(f"{name} must match capacities")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in totals):
        raise ValueError(f"{name} entries must be integers")


def relation_zero_total_orbit_residue(
    capacities: tuple[int, ...],
    totals: tuple[int, ...],
) -> int:
    """Canonical representative residue ``sum(totals) mod tau`` in ``0..tau-1``."""
    _require_state(capacities, totals, "totals")
    period = relation_translation_period(capacities)
    return sum(totals) % period


def relation_fields_share_zero_total_orbit(
    capacities: tuple[int, ...],
    left: tuple[int, ...],
    right: tuple[int, ...],
) -> bool:
    """Whether ``R(left)`` and ``R(right)`` differ by some zero-total state update."""
    _require_state(capacities, left, "left")
    _require_state(capacities, right, "right")
    period = relation_translation_period(capacities)
    return (sum(right) - sum(left)) % period == 0


@dataclass(frozen=True)
class ZeroTotalRelationOrbitWitness:
    capacities: tuple[int, ...]
    primitive_capacity_vector: tuple[int, ...]
    translation_period: int
    left: tuple[int, ...]
    right: tuple[int, ...]
    left_field: WeightedField
    right_field: WeightedField
    grand_total_difference: int
    kernel_shift_steps: int | None
    zero_total_update: tuple[int, ...] | None
    shifted_left: tuple[int, ...] | None
    same_orbit: bool


def zero_total_relation_orbit_witness(
    capacities: tuple[int, ...],
    left: tuple[int, ...],
    right: tuple[int, ...],
) -> ZeroTotalRelationOrbitWitness:
    """Construct the exact zero-total update witness whenever the residues agree."""
    _require_state(capacities, left, "left")
    _require_state(capacities, right, "right")
    primitive = primitive_capacity_vector(capacities)
    period = relation_translation_period(capacities)
    left_field = weighted_relation_field(capacities, left)
    right_field = weighted_relation_field(capacities, right)
    difference = sum(right) - sum(left)

    if difference % period:
        return ZeroTotalRelationOrbitWitness(
            capacities=capacities,
            primitive_capacity_vector=primitive,
            translation_period=period,
            left=left,
            right=right,
            left_field=left_field,
            right_field=right_field,
            grand_total_difference=difference,
            kernel_shift_steps=None,
            zero_total_update=None,
            shifted_left=None,
            same_orbit=False,
        )

    steps = difference // period
    update = tuple(
        right_value - left_value - steps * primitive_value
        for left_value, right_value, primitive_value in zip(left, right, primitive)
    )
    if sum(update) != 0:
        raise AssertionError("constructed relation-orbit update lost zero-total property")
    shifted_left = tuple(value + change for value, change in zip(left, update))
    if weighted_relation_field(capacities, shifted_left) != right_field:
        raise AssertionError("constructed zero-total update did not reach the target relation field")
    if same_field_shift_multiple(capacities, shifted_left, right) != steps:
        raise AssertionError("target relation representatives lost the primitive kernel shift")
    if relation_zero_total_orbit_residue(capacities, left) != relation_zero_total_orbit_residue(
        capacities, right
    ):
        raise AssertionError("constructed same-orbit states disagree on canonical residue")

    return ZeroTotalRelationOrbitWitness(
        capacities=capacities,
        primitive_capacity_vector=primitive,
        translation_period=period,
        left=left,
        right=right,
        left_field=left_field,
        right_field=right_field,
        grand_total_difference=difference,
        kernel_shift_steps=steps,
        zero_total_update=update,
        shifted_left=shifted_left,
        same_orbit=True,
    )


def relation_field_total_residue_is_well_defined(
    capacities: tuple[int, ...],
    left: tuple[int, ...],
    right: tuple[int, ...],
) -> bool:
    """Check that equal relation fields force equal grand-total residue mod ``tau``."""
    _require_state(capacities, left, "left")
    _require_state(capacities, right, "right")
    if weighted_relation_field(capacities, left) != weighted_relation_field(capacities, right):
        raise ValueError("states must represent the same weighted relation field")
    steps = same_field_shift_multiple(capacities, left, right)
    if steps is None:
        raise AssertionError("equal relation fields lost the canonical kernel characterization")
    period = relation_translation_period(capacities)
    if sum(right) - sum(left) != steps * period:
        raise AssertionError("equal-field total difference disagrees with translation period")
    return relation_zero_total_orbit_residue(capacities, left) == relation_zero_total_orbit_residue(
        capacities, right
    )
