"""Reachable coefficient subsemirings for unweighted relation semantics.

An unweighted raw relation contributes only the semiring unit ``1_K`` per edge.
Every local block coefficient is therefore ``n * 1_K`` for some natural n, and
all later trace calculations use only semiring addition/multiplication of such
values.

Hence the only coefficient elements reachable from the world law are

    K_nat = { n * 1_K : n in N }.

This is the unique smallest subsemiring of K containing the unit.  Replacing K
by this natural image leaves all unweighted branching signatures and terminal
traces unchanged.

Categorical products can therefore contain a first kind of overprecision:
unreachable coefficient carrier elements.  This is distinct from the structural
successor-correlation issue studied in the compositional-interface generation.

Concrete examples:

* Z/M x Z/N has full carrier M*N but natural image size lcm(M,N), the compatible
  CRT subring isomorphic to Z/lcm(M,N);
* Boolean x Z/M has full carrier 2M but natural image size M+1.  The image is the
  ``zero-aware modular`` semiring with one true zero plus M positive residue
  classes.

The natural image is the minimal coefficient algebra for unweighted relation
execution inside the chosen ambient semiring.  If raw edges carry additional
weights, this theorem must be replaced by the subsemiring generated by those
actual primitive weights.

Prime subsemirings, images of semiring homomorphisms and CRT are standard prior
algebra.  The project value is the explicit reachable-carrier minimization layer
inside semantic precision joins.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import lcm, prod
from typing import Callable, Hashable, Mapping, Sequence

from .admissible_support import Relation
from .relation_branching_semiring import (
    Coefficient,
    SemiringSpec,
    boolean_semiring,
    modular_semiring,
    product_semiring,
    raw_semiring_word_trace,
    semiring_branching_partition,
)


State = Hashable
Action = Hashable
Observation = Hashable


def zero_aware_modular_semiring(modulus: int) -> SemiringSpec:
    """Natural-image semiring of Boolean x Z/M on unweighted counts.

    Elements reachable from N have canonical form

    `(0,0)` for exact zero,
    `(1,r)` for a positive count congruent to r modulo M.
    """
    if isinstance(modulus, bool) or not isinstance(modulus, int):
        raise TypeError("modulus must be an integer")
    if modulus <= 1:
        raise ValueError("modulus must exceed one")

    def add(left, right):
        positive = int(bool(left[0]) or bool(right[0]))
        residue = (int(left[1]) + int(right[1])) % modulus
        return (positive, residue) if positive else (0, 0)

    def mul(left, right):
        positive = int(bool(left[0]) and bool(right[0]))
        residue = (int(left[1]) * int(right[1])) % modulus
        return (positive, residue) if positive else (0, 0)

    return SemiringSpec(
        name=f"ZA/{modulus}",
        zero=(0, 0),
        one=(1, 1 % modulus),
        add=add,
        mul=mul,
    )


def zero_aware_modular_elements(modulus: int) -> tuple[tuple[int, int], ...]:
    semiring = zero_aware_modular_semiring(modulus)
    # One true zero plus one positive element for every modular residue.
    return (semiring.zero,) + tuple((1, residue) for residue in range(modulus))


def boolean_modular_product_elements(modulus: int) -> tuple[tuple[int, int], ...]:
    if isinstance(modulus, bool) or not isinstance(modulus, int):
        raise TypeError("modulus must be an integer")
    if modulus <= 1:
        raise ValueError("modulus must exceed one")
    return tuple(
        (support, residue)
        for support in (0, 1)
        for residue in range(modulus)
    )


def boolean_modular_natural_image(modulus: int) -> tuple[tuple[int, int], ...]:
    semiring = product_semiring(boolean_semiring(), modular_semiring(modulus))
    # Period starts after zero: counts 1..M cover all positive residue classes.
    values = {semiring.natural(count) for count in range(modulus + 1)}
    return tuple(sorted(values, key=repr))


def boolean_modular_reachable_carrier_size(modulus: int) -> int:
    return len(boolean_modular_natural_image(modulus))


def modular_product_full_carrier_size(moduli: Sequence[int]) -> int:
    values = tuple(moduli)
    if not values:
        raise ValueError("moduli must be nonempty")
    for modulus in values:
        if isinstance(modulus, bool) or not isinstance(modulus, int):
            raise TypeError("every modulus must be an integer")
        if modulus <= 1:
            raise ValueError("every modulus must exceed one")
    return prod(values)


def modular_product_natural_image_size(moduli: Sequence[int]) -> int:
    values = tuple(moduli)
    if not values:
        raise ValueError("moduli must be nonempty")
    result = 1
    for modulus in values:
        if isinstance(modulus, bool) or not isinstance(modulus, int):
            raise TypeError("every modulus must be an integer")
        if modulus <= 1:
            raise ValueError("every modulus must exceed one")
        result = lcm(result, modulus)
    return result


def natural_image_is_closed_on_samples(
    semiring: SemiringSpec,
    sample_limit: int,
) -> bool:
    """Finite regression check for closure of the natural image sample.

    For periodic finite examples choose a limit large enough to contain the full
    image.  The algebraic theorem itself follows from
    `eta(n)+eta(m)=eta(n+m)` and `eta(n)eta(m)=eta(nm)`.
    """
    if isinstance(sample_limit, bool) or not isinstance(sample_limit, int):
        raise TypeError("sample_limit must be an integer")
    if sample_limit < 0:
        raise ValueError("sample_limit must be nonnegative")
    values = {semiring.natural(count) for count in range(sample_limit + 1)}
    if semiring.zero not in values or semiring.one not in values:
        return False
    for left_count in range(sample_limit + 1):
        for right_count in range(sample_limit + 1):
            left = semiring.natural(left_count)
            right = semiring.natural(right_count)
            if semiring.add(left, right) != semiring.natural(left_count + right_count):
                return False
            if semiring.mul(left, right) != semiring.natural(left_count * right_count):
                return False
    return True


def zero_aware_and_full_boolean_modular_branching_agree(
    states: Sequence[State],
    relations: Mapping[Action, Relation],
    observation: Callable[[State], Observation],
    horizon: int,
    modulus: int,
) -> bool:
    zero_aware = zero_aware_modular_semiring(modulus)
    full_product = product_semiring(boolean_semiring(), modular_semiring(modulus))
    left = semiring_branching_partition(
        states,
        relations,
        observation,
        horizon,
        zero_aware,
    )
    right = semiring_branching_partition(
        states,
        relations,
        observation,
        horizon,
        full_product,
    )
    if left != right:
        raise AssertionError("reachable zero-aware subsemiring changed branching kernel")
    return True


def zero_aware_and_full_boolean_modular_traces_agree(
    states: Sequence[State],
    relations: Mapping[Action, Relation],
    observation: Callable[[State], Observation],
    source: State,
    word: Sequence[Action],
    modulus: int,
) -> bool:
    zero_aware = zero_aware_modular_semiring(modulus)
    full_product = product_semiring(boolean_semiring(), modular_semiring(modulus))
    left = raw_semiring_word_trace(
        states,
        relations,
        observation,
        source,
        word,
        zero_aware,
    )
    right = raw_semiring_word_trace(
        states,
        relations,
        observation,
        source,
        word,
        full_product,
    )
    if left != right:
        raise AssertionError("reachable zero-aware subsemiring changed terminal trace")
    return True


@dataclass(frozen=True)
class ReachableCoefficientCarrierReport:
    ambient_name: str
    ambient_carrier_size: int
    reachable_carrier_size: int
    unreachable_carrier_states: int

    @property
    def has_carrier_overprecision(self) -> bool:
        return self.unreachable_carrier_states > 0


def boolean_modular_carrier_report(modulus: int) -> ReachableCoefficientCarrierReport:
    ambient = boolean_modular_product_elements(modulus)
    reachable = boolean_modular_natural_image(modulus)
    return ReachableCoefficientCarrierReport(
        ambient_name=f"B x Z/{modulus}Z",
        ambient_carrier_size=len(ambient),
        reachable_carrier_size=len(reachable),
        unreachable_carrier_states=len(ambient) - len(reachable),
    )


def modular_product_carrier_report(moduli: Sequence[int]) -> ReachableCoefficientCarrierReport:
    values = tuple(moduli)
    full = modular_product_full_carrier_size(values)
    reachable = modular_product_natural_image_size(values)
    return ReachableCoefficientCarrierReport(
        ambient_name=" x ".join(f"Z/{modulus}Z" for modulus in values),
        ambient_carrier_size=full,
        reachable_carrier_size=reachable,
        unreachable_carrier_states=full - reachable,
    )
