"""Finite relation whose natural-count future semimodule never stabilizes.

The shared future-closure recurrence does not imply a shared finite-horizon
closure theorem for every coefficient semiring.

Take two raw states and one relation with Boolean adjacency

    A = [[1,1],
         [0,1]]

under target-row/source-column convention.  With constant all-state observation
row

    C = (1,1),

ordinary natural-number path counting gives exactly

    C A^h = (1,h+1).

Let ``N_h`` be the N-semimodule generated by rows through horizon h.  The chain
is strictly increasing forever.  Every generator has first coordinate one.  If
new row ``(1,h+2)`` were a nonnegative integer combination of old rows, the
first coordinate would force the coefficient sum to equal one, so the
combination would have to be exactly one old generator, impossible.

Three coefficient semantics therefore behave differently on the same finite
relation:

* Boolean support maps every positive count row to ``(1,1)`` and never separates
  the two sources under the constant observation;
* exact natural counts distinguish them from horizon one, but the N-semimodule
  reconstruction state continues to grow forever;
* the Z-module envelope has the same equality kernel as all exact count rows and
  closes at horizon one because ``(1,2)-(1,1)=(0,1)``.

Thus finite state/action cardinality does not make the N-semimodule Noetherian.
Group completion to Z is an exact equality-kernel analysis relaxation but a
strictly stronger reconstruction language because it permits subtraction.

This is standard semimodule/monoid mathematics.  The project value is the sharp
coefficient-dependent termination boundary for future-language compilers.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from .integer_action_module_closure import integer_row_hermite_basis
from .relation_path_count_precision import relation_word_path_counts


Vector = tuple[int, ...]


def triangular_count_relation() -> frozenset[tuple[int, int]]:
    # A[target,source]=[[1,1],[0,1]] means edges 0->0, 1->0, 1->1.
    return frozenset({(0, 0), (1, 0), (1, 1)})


def triangular_count_future_row(horizon: int) -> Vector:
    if isinstance(horizon, bool) or not isinstance(horizon, int):
        raise TypeError("horizon must be an integer")
    if horizon < 0:
        raise ValueError("horizon must be nonnegative")
    relation = triangular_count_relation()
    family = {"R": relation}
    # Constant observation sums counts at both targets.  Evaluate the same word
    # separately from each source to obtain the row on initial states.
    word = ("R",) * horizon
    return tuple(
        sum(relation_word_path_counts((0, 1), family, source, word))
        for source in (0, 1)
    )


def natural_count_generators_through_horizon(horizon: int) -> tuple[Vector, ...]:
    if isinstance(horizon, bool) or not isinstance(horizon, int):
        raise TypeError("horizon must be an integer")
    if horizon < 0:
        raise ValueError("horizon must be nonnegative")
    return tuple(triangular_count_future_row(level) for level in range(horizon + 1))


def new_row_not_in_previous_natural_span(horizon: int) -> bool:
    """Exact first-coordinate proof for the strict N-semimodule chain."""
    if isinstance(horizon, bool) or not isinstance(horizon, int):
        raise TypeError("horizon must be an integer")
    if horizon < 1:
        raise ValueError("horizon must be at least one")
    previous = natural_count_generators_through_horizon(horizon - 1)
    new = triangular_count_future_row(horizon)
    if new[0] != 1 or any(row[0] != 1 for row in previous):
        raise AssertionError("triangular witness lost unit first coordinate")
    if new in previous:
        raise AssertionError("new count row unexpectedly repeated")
    # Any N-linear combination with first coordinate one has coefficient sum
    # one and therefore selects exactly one generator.
    return True


def booleanized_count_row(row: Sequence[int]) -> Vector:
    result = tuple(row)
    for value in result:
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            raise ValueError("count row must contain nonnegative integers")
    return tuple(int(value > 0) for value in result)


@dataclass(frozen=True)
class CountCoefficientComparison:
    horizon: int
    natural_generators: tuple[Vector, ...]
    natural_chain_strict: bool
    boolean_rows: tuple[Vector, ...]
    boolean_distinguishes_states: bool
    integer_envelope_basis: tuple[Vector, ...]
    integer_envelope_closed_from_horizon_one: bool


def triangular_count_coefficient_comparison(horizon: int) -> CountCoefficientComparison:
    if isinstance(horizon, bool) or not isinstance(horizon, int):
        raise TypeError("horizon must be an integer")
    if horizon < 1:
        raise ValueError("horizon must be at least one")
    natural = natural_count_generators_through_horizon(horizon)
    strict = all(new_row_not_in_previous_natural_span(level) for level in range(1, horizon + 1))
    boolean = tuple(booleanized_count_row(row) for row in natural)
    boolean_distinguishes = any(row[0] != row[1] for row in boolean)
    integer_basis = integer_row_hermite_basis(natural)
    horizon_one_basis = integer_row_hermite_basis(
        natural_count_generators_through_horizon(1)
    )
    return CountCoefficientComparison(
        horizon=horizon,
        natural_generators=natural,
        natural_chain_strict=strict,
        boolean_rows=boolean,
        boolean_distinguishes_states=boolean_distinguishes,
        integer_envelope_basis=integer_basis,
        integer_envelope_closed_from_horizon_one=(integer_basis == horizon_one_basis),
    )
