#!/usr/bin/env python3
"""Deterministic validator for CBRC F3R balanced-mixing survivor-family completion.

Exact integer / finite-field / Fraction arithmetic only.
Finite enumeration validates theorem reductions; no GL_2(Z) completeness claim is inferred from a box scan.
"""
from fractions import Fraction
import hashlib
import itertools
import json
from math import gcd

P = ((0,1),(1,0))
A0 = ((2,3),(3,4))
I3 = ((1,0),(0,1))
B0 = ((0,0),(0,0))

def det2(A):
    return A[0][0]*A[1][1]-A[0][1]*A[1][0]

def mmul(A,B):
    return (
        (A[0][0]*B[0][0]+A[0][1]*B[1][0], A[0][0]*B[0][1]+A[0][1]*B[1][1]),
        (A[1][0]*B[0][0]+A[1][1]*B[1][0], A[1][0]*B[0][1]+A[1][1]*B[1][1]),
    )

def mvec(A,v):
    return (A[0][0]*v[0]+A[0][1]*v[1], A[1][0]*v[0]+A[1][1]*v[1])

def inv2(A):
    d=det2(A)
    assert d in (1,-1)
    return ((A[1][1]//d,-A[0][1]//d),(-A[1][0]//d,A[0][0]//d))

def diag(s,t):
    return ((s,0),(0,t))

SIGNS=[diag(s,t) for s in (1,-1) for t in (1,-1)]

def free_orbit(A):
    """Physical free-quotient orbit generated by left/right unary sign gauge, marker conjugation, inverse."""
    seen=set()
    stack=[A]
    while stack:
        X=stack.pop()
        if X in seen:
            continue
        seen.add(X)
        for L in SIGNS:
            for R in SIGNS:
                stack.append(mmul(mmul(L,X),R))
        stack.append(mmul(mmul(P,X),P))
        stack.append(inv2(X))
    return seen

def free_canonical(A):
    return min(tuple(x for row in X for x in row) for X in free_orbit(A))

def support(n,p):
    return 0 if n%p==0 else 1

def f_pr(n,p,r):
    return Fraction(support(n,p)+support(n,r),2)

def q_pr(z,p,r):
    n,t=z
    return f_pr(n,p,r)

def perm_type_mod(A,p):
    a,b=A[0][0]%p,A[0][1]%p
    c,d=A[1][0]%p,A[1][1]%p
    if a and d and not b and not c:
        return 0  # diagonal support
    if b and c and not a and not d:
        return 1  # anti-diagonal support
    return None

def theorem_support_split(A,p,r):
    return perm_type_mod(A,p) is not None and perm_type_mod(A,r) is not None and perm_type_mod(A,p)!=perm_type_mod(A,r)

def preserves_finite_pr(A,p,r):
    N=p*r
    for x,y in itertools.product(range(N),repeat=2):
        u,v=mvec(A,(x,y))
        if f_pr(u,p,r)+f_pr(v,p,r) != f_pr(x,p,r)+f_pr(y,p,r):
            return False
    return True

def egcd(a,b):
    if b==0:
        return (abs(a), 1 if a>0 else -1, 0)
    g,x1,y1=egcd(b,a%b)
    return g,y1,x1-(a//b)*y1

def invmod(a,m):
    g,x,_=egcd(a,m)
    assert g==1
    return x%m

def crt2(a,m,b,n):
    assert gcd(m,n)==1
    # x=a mod m; x=b mod n
    return (a + ((b-a)*invmod(m,n)%n)*m)%(m*n)

def prime_pair_completion(p,r,eps=1,ell=0):
    assert p!=r and p>1 and r>1
    g,x,y=egcd(p,r)
    assert g==1
    # p*x+r*y=1 -> p*(eps*x)-r*(-eps*y)=eps
    b0=-eps*y
    d0=eps*x
    kp=(-d0*invmod(r,p))%p       # d0+k*r = 0 mod p
    kr=(-b0*invmod(p,r))%r       # b0+k*p = 0 mod r
    k0=crt2(kp,p,kr,r)
    k=k0+ell*p*r
    b=b0+k*p
    d=d0+k*r
    A=((p,b),(r,d))
    assert det2(A)==eps
    assert theorem_support_split(A,p,r)
    return A

def all_gl2_f3():
    out=[]
    for vals in itertools.product(range(3),repeat=4):
        A=((vals[0],vals[1]),(vals[2],vals[3]))
        if det2(A)%3:
            out.append(A)
    return out

def all_b_f3():
    return [((a,b),(c,d)) for a,b,c,d in itertools.product(range(3),repeat=4)]

GL3=all_gl2_f3()
BS=all_b_f3()

def apply_general(state,A,B,D):
    (n1,t1),(n2,t2)=state
    u,v=mvec(A,(n1,n2))
    r1,r2=n1%3,n2%3
    ot1=(B[0][0]*r1+B[0][1]*r2+D[0][0]*t1+D[0][1]*t2)%3
    ot2=(B[1][0]*r1+B[1][1]*r2+D[1][0]*t1+D[1][1]*t2)%3
    return ((u,ot1),(v,ot2))

def torsion_bonus(z):
    n,t=z
    return 1 if n%3==0 and t%3!=0 else 0

def T_total(state):
    return torsion_bonus(state[0])+torsion_bonus(state[1])

def preserves_T_mod3(A,B,D):
    A3=((A[0][0]%3,A[0][1]%3),(A[1][0]%3,A[1][1]%3))
    for n1,n2,t1,t2 in itertools.product(range(3),repeat=4):
        st=((n1,t1),(n2,t2))
        if T_total(apply_general(st,A3,B,D))!=T_total(st):
            return False
    return True

def same_perm_support(M,ptype,require_nonzero=False):
    if ptype==0:
        if M[0][1]%3 or M[1][0]%3:
            return False
        return (M[0][0]%3!=0 and M[1][1]%3!=0) if require_nonzero else True
    if M[0][0]%3 or M[1][1]%3:
        return False
    return (M[0][1]%3!=0 and M[1][0]%3!=0) if require_nonzero else True

def theorem_delta_lift(A,B,D):
    ptype=perm_type_mod(A,3)
    assert ptype is not None
    return same_perm_support(B,ptype,False) and same_perm_support(D,ptype,True)

def coeff_add(x,y):
    return (x[0]+y[0],(x[1]+y[1])%3)

def coeff_neg(x):
    return (-x[0],(-x[1])%3)

def R(z):
    n,t=z
    return (n,(t+n)%3)

def J(z):
    n,t=z
    return (-n,(-t)%3)

def apply_pair3(st,i,j,A,B,D):
    st=list(st)
    out=apply_general((st[i],st[j]),A,B,D)
    st[i],st[j]=out
    return tuple(st)

def check_canonical_and_composition():
    assert det2(A0)==-1
    Ainv=inv2(A0)
    assert mmul(A0,Ainv)==I3
    e=(1,0); zero=(0,0)
    split=apply_general((e,zero),A0,B0,I3)
    assert split==((2,0),(3,0))
    assert f_pr(2,2,3)==f_pr(3,2,3)==Fraction(1,2)
    # depth 4 exact recovery
    seeds=[((x,t1),(y,t2)) for x,y in itertools.product(range(-2,3),repeat=2) for t1,t2 in itertools.product(range(3),repeat=2)]
    for st in seeds:
        cur=st
        for _ in range(4):
            cur=apply_general(cur,A0,B0,I3)
        for _ in range(4):
            cur=apply_general(cur,Ainv,B0,I3)
        assert cur==st
    # 3-marker direct sum + inverse serialization
    Ainv=inv2(A0)
    for st in [((1,0),(0,0),(-1,1)),((2,1),(3,2),(1,0))]:
        cur=apply_pair3(st,0,1,A0,B0,I3)
        cur=apply_pair3(cur,1,2,A0,B0,I3)
        cur=apply_pair3(cur,1,2,Ainv,B0,I3)
        cur=apply_pair3(cur,0,1,Ainv,B0,I3)
        assert cur==st
    return True

def check_support_theorem(p,r):
    N=p*r
    mismatches=0
    admissible=0
    # residue matrices only; require determinant a unit modulo N
    for vals in itertools.product(range(N),repeat=4):
        A=((vals[0],vals[1]),(vals[2],vals[3]))
        if gcd(det2(A),N)!=1:
            continue
        pred=theorem_support_split(A,p,r)
        direct=preserves_finite_pr(A,p,r)
        # conservation alone includes same-permutation monomial cases; balance distinguishes opposite.
        first_bal=(f_pr(A[0][0],p,r)==Fraction(1,2) and f_pr(A[1][0],p,r)==Fraction(1,2))
        direct_bal=direct and first_bal
        if pred!=direct_bal:
            mismatches+=1
        if pred:
            admissible+=1
    assert mismatches==0
    return admissible

def r6_residue_classes():
    out=[]
    for vals in itertools.product(range(6),repeat=4):
        A=((vals[0],vals[1]),(vals[2],vals[3]))
        if gcd(det2(A),6)==1 and theorem_support_split(A,2,3):
            out.append(vals)
    # Invertible residue matrices include scalar choices; over F2 only 1, over F3 1/2.
    assert len(out)==8
    return sorted(out)

def bounded_regression():
    mismatches=0
    tested=0
    predicted=0
    for a,b,c,d in itertools.product(range(-8,9),repeat=4):
        if a*d-b*c not in (1,-1):
            continue
        A=((a,b),(c,d))
        tested+=1
        pred=theorem_support_split(A,2,3)
        direct=preserves_finite_pr(A,2,3) and f_pr(a,2,3)==Fraction(1,2) and f_pr(c,2,3)==Fraction(1,2)
        if pred:
            predicted+=1
        if pred!=direct:
            mismatches+=1
    assert mismatches==0
    return {"tested_unimodular":tested,"predicted_q23_survivors":predicted,"mismatches":mismatches}

def check_infinite_inequivalence():
    keys=[]
    maxes=[]
    for k in range(21):
        C=((1,6*k),(0,1))
        A=mmul(A0,C)
        assert det2(A)==-1
        assert theorem_support_split(A,2,3)
        assert preserves_finite_pr(A,2,3)
        keys.append(free_canonical(A))
        maxes.append(max(abs(x) for row in A for x in row))
    assert len(set(keys))==len(keys)
    assert maxes==sorted(maxes) and len(set(maxes))==len(maxes)
    return {"checked_k":[0,20],"distinct_physical_classes":len(keys)}

def check_minimal_q23_classes():
    mats=[]
    for vals in itertools.product(range(-4,5),repeat=4):
        A=((vals[0],vals[1]),(vals[2],vals[3]))
        if det2(A) in (1,-1) and theorem_support_split(A,2,3):
            mats.append(A)
    assert mats
    minmax=min(max(abs(x) for row in A for x in row) for A in mats)
    mins=[A for A in mats if max(abs(x) for row in A for x in row)==minmax]
    minsum=min(sum(abs(x) for row in A for x in row) for A in mins)
    mins=[A for A in mins if sum(abs(x) for row in A for x in row)==minsum]
    classes={free_canonical(A) for A in mins}
    assert minmax==4 and minsum==12
    assert len(classes)==2
    assert free_canonical(A0) in classes
    return {"min_max_entry":minmax,"min_l1":minsum,"minimal_physical_classes":len(classes),"canonical_is_cominimal":True}

def check_lifts():
    R6=r6_residue_classes()
    total_q0=len(BS)*len(GL3)
    assert total_q0==3888
    per_class=[]
    for vals in R6:
        A=((vals[0],vals[1]),(vals[2],vals[3]))
        count_exact=0
        count_formula=0
        mismatch=0
        for B in BS:
            for D in GL3:
                exact=preserves_T_mod3(A,B,D)
                formula=theorem_delta_lift(A,B,D)
                count_exact+=int(exact)
                count_formula+=int(formula)
                mismatch+=int(exact!=formula)
        assert mismatch==0 and count_exact==36 and count_formula==36
        per_class.append(36)
    return {"torsion_blind_lifts_per_free_A":3888,"delta_positive_lifts_per_r6_class":per_class,"lift_formula_mismatches":0}

def check_prime_pair_models():
    samples=[]
    for p,r in [(2,3),(2,5),(3,5),(2,7)]:
        for eps in (1,-1):
            for ell in (-2,0,2):
                A=prime_pair_completion(p,r,eps,ell)
                assert preserves_finite_pr(A,p,r)
                assert f_pr(A[0][0],p,r)==f_pr(A[1][0],p,r)==Fraction(1,2)
                # relabeled elementary input: second column is also balanced for this support-split family
                assert f_pr(A[0][1],p,r)==f_pr(A[1][1],p,r)==Fraction(1,2)
                samples.append((p,r,eps,ell,A))
    return {"sample_models_checked":len(samples),"prime_pairs":[[2,3],[2,5],[3,5],[2,7]]}

def check_first_column_general_sufficiency():
    # theorem regression: any primitive (a,c), |a|,|c|>=2, choose a prime divisor from each
    def prime_divisor(n):
        n=abs(n)
        for p in range(2,n+1):
            if n%p==0 and all(p%q for q in range(2,int(p**0.5)+1)):
                return p
        raise AssertionError
    checked=0
    for a,c in itertools.product(range(-12,13),repeat=2):
        if a==0 or c==0 or abs(a)<2 or abs(c)<2 or gcd(abs(a),abs(c))!=1:
            continue
        p=prime_divisor(a); r=prime_divisor(c)
        assert p!=r and c%p and a%r
        # build any Bezout completion for this actual first column, then impose support complement via k CRT
        g,x,y=egcd(a,c)
        assert g==1
        # a*x + c*y = 1 -> a*d0-c*b0=1
        d0=x; b0=-y
        # mod p: a=0, c!=0 -> require d=0
        kp=(-d0*invmod(c%p,p))%p
        # mod r: c=0, a!=0 -> require b=0
        kr=(-b0*invmod(a%r,r))%r
        k=crt2(kp,p,kr,r)
        A=((a,b0+k*a),(c,d0+k*c))
        assert det2(A)==1
        assert theorem_support_split(A,p,r)
        assert preserves_finite_pr(A,p,r)
        checked+=1
    assert checked>0
    return checked

def check_recoalescence():
    # Input pair difference v1-v0 is pure torsion in slot 2.
    # Aggregate after M differs by sum of D's second column.
    fixed_fail=0
    for D in GL3:
        s1=(D[0][0]+D[1][0])%3
        s2=(D[0][1]+D[1][1])%3
        assert s1 or s2  # both zero would make both columns lie in 1D kernel of [1,1]
        if not s2:
            fixed_fail+=1
    # For delta-positive lift D is monomial, so every column sum is nonzero.
    monomial_D=[D for D in GL3 if perm_type_mod(D,3) is not None]
    assert len(monomial_D)==8
    assert all((D[0][0]+D[1][0])%3 and (D[0][1]+D[1][1])%3 for D in monomial_D)
    # accepted sign-dark / relative nonsign relation
    e=(1,0)
    assert coeff_add(e,J(e))==(0,0)
    assert coeff_add(e,J(R(e)))==(0,2)
    return {"all_D_have_some_orientation_discriminator":True,"fixed_slot2_failures":fixed_fail,"delta_patterned_D_fixed_orientation_survives":True}

def check_regularity():
    rows=[]
    for p,r in [(2,3),(2,5),(3,5)]:
        assert f_pr(p*r,p,r)==0
        assert f_pr(p,p,r)==Fraction(1,2) < f_pr(1,p,r)
        A=prime_pair_completion(p,r,1,0)
        # exact nonamplification = conservation on every residue state
        assert preserves_finite_pr(A,p,r)
        rows.append({"p":p,"r":r,"zero_at_copy":p*r,"copy_value":str(f_pr(p,p,r))})
    return {
        "support_split_global_zero_separation":"FAIL",
        "support_split_integer_copy_monotonicity":"FAIL",
        "support_split_finite_copy_nondegeneracy":"FAIL",
        "tagged_refinement_nonamplification":"PASS_BY_M6_EQUALITY",
        "examples":rows,
    }

def main():
    assert len(GL3)==48 and len(BS)==81
    check_canonical_and_composition()
    # exact residue theorem checks
    n23=check_support_theorem(2,3)
    n25=check_support_theorem(2,5)
    r6=r6_residue_classes()
    bounded=bounded_regression()
    infinite=check_infinite_inequivalence()
    minimal=check_minimal_q23_classes()
    lifts=check_lifts()
    primes=check_prime_pair_models()
    firstcols=check_first_column_general_sufficiency()
    reco=check_recoalescence()
    reg=check_regularity()

    payload={
        "schema":"CBRC_F3R_CHECK_V1",
        "accepted_canonical_replay":True,
        "physical_equivalence":{
            "free_generators":["left_diagonal_sign","right_diagonal_sign","marker_P_conjugation","inverse_orientation"],
            "A0_orbit_size":len(free_orbit(A0)),
        },
        "q_pr_theorem":{
            "formula":"q_{p,r}(n,a)=1/2*(1_{p∤n}+1_{r∤n})",
            "necessary_sufficient_for_fixed_q":"A mod p and mod r monomial with opposite permutation type",
            "r6_residue_classes":[list(x) for x in r6],
            "invertible_residue_survivors_p2_r3":n23,
            "invertible_residue_survivors_p2_r5":n25,
        },
        "bounded_regression":bounded,
        "infinite_inequivalent_q23_subfamily":infinite,
        "q23_secondary_complexity":minimal,
        "torsion_lifts":lifts,
        "prime_pair_parameterized_models":primes,
        "primitive_first_columns_constructively_realized_in_window":firstcols,
        "composition_depth_checked":4,
        "direct_sum_markers_checked":3,
        "recoalescence":reco,
        "regularity_counterfactuals":reg,
        "theorem_enumeration_mismatches":0,
        "primary_verdict":"F3R_CURRENT_AXIOMS_STRICTLY_UNDERDETERMINE_MIXING",
    }
    canonical=json.dumps(payload,sort_keys=True,separators=(",",":"))
    digest=hashlib.sha256(canonical.encode()).hexdigest()
    print(json.dumps({"deterministic_digest":digest,"payload":payload},indent=2,sort_keys=True))

if __name__=="__main__":
    main()
