#!/usr/bin/env python3
"""Exact finite checks for the pi-to-prime spectral/rotation frontiers.

No floating target for pi/tau is used.  All mathematical comparisons are over
integers or fractions.  This is a finite regression/checker, not a proof of the
infinite #1159 sine-product or Dirichlet-L completion dependencies.
"""

from __future__ import annotations

from fractions import Fraction
from math import comb


def is_prime(n: int) -> bool:
    if n < 2:
        return False
    d = 2
    while d * d <= n:
        if n % d == 0:
            return False
        d += 1
    return True


def primes_upto(limit: int) -> list[int]:
    return [n for n in range(2, limit + 1) if is_prime(n)]


def multiplicative_birth(k: int) -> bool:
    """Birth(k): k is not a product of two earlier nontrivial modes.

    For k>=2 this is equivalent to not belonging to the monoid generated by
    2,...,k-1: any nontrivial monoid expression can be grouped into a*b with
    2<=a,b<k.
    """
    assert k >= 2
    for a in range(2, k):
        if k % a == 0:
            b = k // a
            if 2 <= b < k:
                return False
    return True


def vp_int(n: int, p: int) -> int:
    assert n > 0 and is_prime(p)
    e = 0
    while n % p == 0:
        n //= p
        e += 1
    return e


def carry_count_double(n: int, p: int) -> int:
    """Number of base-p carries in n+n."""
    assert n >= 0 and p >= 2
    carry = 0
    count = 0
    m = n
    while m > 0 or carry:
        digit = m % p
        m //= p
        total = 2 * digit + carry
        next_carry = 1 if total >= p else 0
        if next_carry:
            count += 1
        carry = next_carry
    return count


def chi3(n: int) -> int:
    """Nonprincipal Dirichlet character modulo 3."""
    r = n % 3
    if r == 0:
        return 0
    return 1 if r == 1 else -1


def z_birth(M: int, r: int = 2) -> Fraction:
    assert M >= 1 and r >= 1
    z = Fraction(1, 1)
    for p in primes_upto(M):
        z *= Fraction(p**r, p**r - 1)
    return z


def z_birth_det_ratio(M: int, r: int = 2) -> Fraction:
    """det(B)^r/det(B^r-I) for diagonal birth block B=diag(p)."""
    det_b = 1
    det_gap = 1
    for p in primes_upto(M):
        det_b *= p
        det_gap *= p**r - 1
    return Fraction(det_b**r, det_gap)


def z_birth_sixfold_degenerate(M: int) -> Fraction:
    """Naive sixfold spatial degeneracy repeats every Euler eigenfactor six times."""
    z = Fraction(1, 1)
    for p in primes_upto(M):
        z *= Fraction(p * p, p * p - 1) ** 6
    return z


def prime_tau2_bounds(M: int) -> tuple[Fraction, Fraction]:
    """PBH-T05 rational interval for tau^2."""
    z = z_birth(M, 2)
    lower = 6 * z
    upper = lower * Fraction(M + 1, M)
    return lower, upper


def wallis_state(n: int) -> Fraction:
    assert n >= 1
    P_2n = 4**n
    C_n = comb(2 * n, n)
    return Fraction(P_2n * P_2n, (2 * n + 1) * C_n * C_n)


def diamond_tau_bounds(n: int) -> tuple[Fraction, Fraction]:
    """#1161 pure-integer interval for tau."""
    assert n >= 1
    P_2n = 4**n
    C_n = comb(2 * n, n)
    lower = Fraction(2 * P_2n * P_2n, (2 * n + 1) * C_n * C_n)
    upper = Fraction(4 * P_2n * P_2n, (4 * n + 1) * C_n * C_n)
    return lower, upper


def c3_orientation_partial(K: int) -> Fraction:
    """S_K = sum_{k=0}^{K-1} (1/(3k+1)-1/(3k+2))."""
    assert K >= 1
    return sum(
        (Fraction(1, 3 * k + 1) - Fraction(1, 3 * k + 2) for k in range(K)),
        Fraction(0, 1),
    )


def check_birth_equivalence(limit: int = 250) -> None:
    for k in range(2, limit + 1):
        assert multiplicative_birth(k) == is_prime(k), k


def check_birth_determinant(limit: int = 250) -> None:
    for M in range(1, limit + 1):
        assert z_birth(M, 2) == z_birth_det_ratio(M, 2), M
        assert z_birth(M, 3) == z_birth_det_ratio(M, 3), M
        assert z_birth_sixfold_degenerate(M) == z_birth(M, 2) ** 6, M


def check_telescoping_tail(limit: int = 100) -> None:
    for M in range(1, limit + 1):
        for N in (M + 1, M + 2, M + 7, M + 31):
            product = Fraction(1, 1)
            for n in range(M + 1, N + 1):
                product *= Fraction(n * n - 1, n * n)
            expected = Fraction(M * (N + 1), (M + 1) * N)
            assert product == expected, (M, N)
        lo, hi = prime_tau2_bounds(M)
        assert Fraction(hi - lo, lo) == Fraction(1, M)


def check_factorial_provenance(limit: int = 250) -> None:
    """Exact j=1 normalized Dirichlet coefficient and S3 orbit count."""
    for M in range(2, limit + 1):
        lhs = Fraction(comb(M + 1, 3), M**3)
        rhs = Fraction(1, 6) * (1 - Fraction(1, M * M))
        assert lhs == rhs, M
        assert 6 * comb(M + 1, 3) == (M + 1) * M * (M - 1), M


def check_c3_prime_phase(limit: int = 250) -> None:
    """Finite split/nonsplit/ramified classification of Phi_3(x)."""
    for p in primes_upto(limit):
        roots = [x for x in range(p) if (x * x + x + 1) % p == 0]
        if p == 3:
            assert roots == [1]
            # Repeated root: derivative 2x+1 also vanishes at x=1 mod 3.
            assert (2 * roots[0] + 1) % p == 0
            assert chi3(p) == 0
        elif p % 3 == 1:
            assert len(roots) == 2, (p, roots)
            assert chi3(p) == 1
            assert all(pow(x, 3, p) == 1 and x != 1 for x in roots)
        else:
            assert p % 3 == 2
            assert roots == [], (p, roots)
            assert chi3(p) == -1


def check_c3_orientation_tail(limit: int = 100) -> None:
    """Finite proof kernel for S_K < O_3 < S_K + 1/(9K)."""
    for K in range(1, limit + 1):
        _SK = c3_orientation_partial(K)
        for k in range(max(1, K), K + 50):
            term = Fraction(1, (3 * k + 1) * (3 * k + 2))
            majorant = Fraction(1, 9 * k * (k + 1))
            assert 0 < term < majorant

        # The majorant telescopes exactly on every finite tail segment.
        for N in (K, K + 1, K + 9, K + 37):
            majorant_sum = sum(
                (Fraction(1, 9 * k * (k + 1)) for k in range(K, N + 1)),
                Fraction(0, 1),
            )
            expected = Fraction(1, 9) * (Fraction(1, K) - Fraction(1, N + 1))
            assert majorant_sum == expected, (K, N)
            assert majorant_sum < Fraction(1, 9 * K)


def check_wallis_flux(limit: int = 120) -> None:
    for n in range(1, limit + 1):
        Wn = wallis_state(n)
        W1 = wallis_state(n + 1)
        assert Fraction(W1, Wn) == Fraction(
            4 * (n + 1) ** 2, (2 * n + 1) * (2 * n + 3)
        )

        Cn = comb(2 * n, n)
        for p in primes_upto(2 * n + 3):
            c = vp_int(Cn, p)
            assert c == carry_count_double(n, p), (n, p, c)

            lhs = vp_int(Wn.numerator, p) - vp_int(Wn.denominator, p)
            rhs = (4 * n if p == 2 else 0) - 2 * c - vp_int(2 * n + 1, p)
            assert lhs == rhs, (n, p, lhs, rhs)

            flux = (
                (2 if p == 2 else 0)
                + 2 * vp_int(n + 1, p)
                - vp_int(2 * n + 1, p)
                - vp_int(2 * n + 3, p)
            )
            lhs_flux = (
                vp_int(W1.numerator, p)
                - vp_int(W1.denominator, p)
                - lhs
            )
            assert lhs_flux == flux, (n, p, lhs_flux, flux)

        # v2(C(2n,n)) = popcount(n), hence v2(W_n)=4n-2*popcount(n).
        v2_w = vp_int(Wn.numerator, 2) - vp_int(Wn.denominator, 2)
        assert vp_int(Cn, 2) == n.bit_count()
        assert v2_w == 4 * n - 2 * n.bit_count()


def check_two_carrier_finite_consistency(limit: int = 80) -> None:
    """Finite sample of PBH-T09 using M=2n; no tau target is evaluated."""
    for n in range(1, limit + 1):
        M = 2 * n
        L, U = diamond_tau_bounds(n)
        PL, PU = prime_tau2_bounds(M)
        left = max(L * L, PL)
        right = min(U * U, PU)
        assert left < right, (n, M, left, right)
        assert Fraction(U - L, L) == Fraction(1, 4 * n + 1)


def main() -> None:
    check_birth_equivalence()
    check_birth_determinant()
    check_telescoping_tail()
    check_factorial_provenance()
    check_c3_prime_phase()
    check_c3_orientation_tail()
    check_wallis_flux()
    check_two_carrier_finite_consistency()
    print("pi-prime spectral/rotation finite checks: PASS")


if __name__ == "__main__":
    main()
