"""Certified final-bit character shortcut for the actual checkpoint walker.

Only the canonical initial-state trajectory is accepted. Unavailable character
certificates fall back to the full row-query sampler; no arbitrary state input.
"""
from __future__ import annotations
from fractions import Fraction as F
from pathlib import Path
import hashlib
import sys

ROOT = Path(__file__).resolve().parent
for path in (ROOT.parent / 'gram_research', ROOT.parent / 'point_queries',
             ROOT.parent / 'character_certificates'):
    sys.path.insert(0, str(path))
from single_walker import SingleWalker
from checkpoint_row_oracle import CheckpointRowOracle
from typed_jacobi import certify_program_final_bit, verify_program_final_bit
from lazy_modular import digest
from stage45.brc_loop_recheck import CALLS


def certificate_digit_cost(certificate):
    witness = certificate.get('schedule_witness', {})
    return (witness.get('jacobi', {}).get('cost', {}).get('adder_digit_replays', 0)
            + witness.get('schedule_arithmetic_cost', {}).get('adder_digit_replays', 0)
            + witness.get('permutation_verification_adder_digits', 0))


class CharacterWalker(SingleWalker):
    def __init__(self, program, *, query_budget=100000, checkpoint_depth_cap=None):
        oracle = CheckpointRowOracle(program, query_budget=query_budget,
                                     checkpoint_depth_cap=checkpoint_depth_cap)
        super().__init__(program, oracle=oracle)
        self._owned_oracle = oracle
        start = len(CALLS)
        try:
            self.character_certificate = certify_program_final_bit(program)
        except ValueError as error:
            # Failure to certify never implies a biased bit, and the original
            # admitted instrument still has its unchanged row-query route.
            self.character_certificate = {'status': 'UNAVAILABLE',
                'reason': str(error), 'fallback': 'unchanged exact row-query sampler'}
        self.certification_core_calls = len(CALLS)-start
        self.certification_digit_replays = certificate_digit_cost(self.character_certificate)
        self.verification_receipts = []
        self.shortcut_rounds = 0

    def _check_owned_trajectory(self):
        if self.oracle is not self._owned_oracle or self.oracle.program is not self.program:
            raise ValueError('externally replaced oracle/program is not character certified')
        if self.history != tuple(event['selected_bit'] for event in self.events):
            raise ValueError('history was not generated by this walker')
        expected_latent = 1
        prefix = ()
        for event in self.events:
            if event['latent_before'] != expected_latent or tuple(event['history']) != prefix:
                raise ValueError('retained trajectory lost its canonical initial origin')
            expected_latent = event['candidate']
            prefix += (event['selected_bit'],)
        if self.latent != expected_latent:
            raise ValueError('latent label was externally replaced')

    def _verified_final_certificate(self):
        if self.character_certificate.get('status') != 'CERTIFIED_FINAL_BIT_FAIR':
            return False
        if len(self.history) != self.program.t-1:
            return False
        start = len(CALLS)
        try:
            verified = verify_program_final_bit(self.character_certificate, self.program)
        except ValueError as error:
            self.verification_receipts.append({'verified': False, 'reason': str(error),
                'native_core_calls': len(CALLS)-start, 'fallback': 'full row queries'})
            return False
        self.verification_receipts.append({**verified, 'native_core_calls': len(CALLS)-start,
            'replayed_adder_digits': certificate_digit_cost(self.character_certificate)})
        return verified.get('verified') is True and verified.get('status') == 'CERTIFIED_FINAL_BIT_FAIR'

    def step(self, rng):
        self._check_owned_trajectory()
        if not self._verified_final_certificate():
            # A certificate failure with a retained character proposal must
            # recompute its ordinary local score, preserving the same coin.
            if self.pending_plan is not None and self.pending_plan.get('mode') == 'CERTIFIED_FINAL_CHARACTER':
                self.pending_plan = None
            return super().step(rng)
        if self.pending_auxiliary_bit is None:
            self.pending_auxiliary_bit = self._draw(F(1, 2), rng)
        if self.pending_plan is None:
            auxiliary = self.pending_auxiliary_bit
            candidate = (self.latent if auxiliary == 0
                         else self.program.tables[-1][self.latent])
            self.pending_plan = {'mode': 'CERTIFIED_FINAL_CHARACTER',
                'history': self.history, 'latent_before': self.latent,
                'auxiliary_bit': auxiliary, 'candidate': candidate,
                'bit_probability_given_proposed_label': F(1, 2),
                'character_certificate_sha256': digest(self.character_certificate),
                'row_query_performed': False,
                'justification': 'reachable square-character support and its final translate are disjoint'}
        plan = self.pending_plan
        if tuple(plan['history']) != self.history or plan['latent_before'] != self.latent:
            raise AssertionError('character proposal lost its raw parent')
        bit = self._draw(F(1, 2), rng)
        self.oracle.append(bit)
        self.latent = plan['candidate']
        self.events.append({**plan, 'selected_bit': bit, 'selected_local_probability': F(1, 2)})
        self.shortcut_rounds += 1
        self.pending_auxiliary_bit = self.pending_plan = None
        return self.events[-1]

    def run(self, rng, *, postprocess=None):
        result = super().run(rng, postprocess=postprocess)
        result['character_optimization'] = self.character_report()
        return result

    def character_report(self):
        return {'certificate_status': self.character_certificate['status'],
            'certificate_sha256': digest(self.character_certificate),
            'certification_native_core_calls': self.certification_core_calls,
            'certification_adder_digit_replays': self.certification_digit_replays,
            'verification_receipts': list(self.verification_receipts),
            'shortcut_rounds': self.shortcut_rounds,
            'only_final_round_authorized': True,
            'arbitrary_midrun_state_input': False,
            'fallback_when_unavailable': True,
            'certification_cost_separate_from_point_query_budget': True,
            'source_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}

    def evidence(self):
        return {'character_report': self.character_report(),
            'character_certificate': self.character_certificate, 'oracle': self.oracle.evidence(),
            'events': list(self.events), 'history': self.history, 'latent_work_label': self.latent,
            'pending_auxiliary_bit': self.pending_auxiliary_bit, 'pending_plan': self.pending_plan}
