#!/usr/bin/env python3
"""Render a source-index view; this program grants no research authority."""

import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
DATA = "research_progress_map.json"
LANGUAGES = ("en", "zh-CN")
DIMENSIONS = ("mathematics", "lean", "program", "publication", "formal_review")


def require(condition, message):
    if not condition:
        raise ValueError(message)


def bilingual(value, label):
    require(isinstance(value, dict) and set(value) == set(LANGUAGES), label)
    require(all(isinstance(value[lang], str) and value[lang].strip() for lang in LANGUAGES), label)


def unique(rows, label):
    ids = [row["id"] for row in rows]
    require(len(ids) == len(set(ids)), f"duplicate {label} ID")
    require(all(re.fullmatch(r"[A-Za-z][A-Za-z0-9_-]*", item) for item in ids), f"invalid {label} ID")
    return set(ids)


def validate(data):
    require(data["schema"] == "ENTERPRISE_MATH_RESEARCH_PROGRESS_MAP_V1", "schema")
    require(data["authority"] == "SOURCE_INDEX_ONLY_NO_TASK_OR_THEOREM_AUTHORITY", "authority")
    for field in ("title", "scope_note", "evidence_note", "maintenance_note", "freshness_note"):
        bilingual(data[field], field)
    for key in ("main_source_commit", "composition_base_commit"):
        require(re.fullmatch(r"[0-9a-f]{40}", data[key]), key)
    source_ids = unique(data["sources"], "source")
    node_ids = unique(data["nodes"], "node")
    edge_ids = unique(data["edges"], "edge")
    require(source_ids.isdisjoint(node_ids | edge_ids) and node_ids.isdisjoint(edge_ids), "IDs overlap")
    for source in data["sources"]:
        path = PurePosixPath(source["path"])
        require(not path.is_absolute() and ".." not in path.parts and "\\" not in source["path"], "source path")
        require(re.fullmatch(r"[0-9a-f]{64}", source["sha256"]), "source SHA256")
        bilingual(source["label"], "source label")
        require(source["verification"] in data["verification_levels"], "source verification")
        if source["kind"] == "git_file":
            require(re.fullmatch(r"[0-9a-f]{40}", source["commit"]), "immutable source commit")
            require(re.fullmatch(r"[0-9a-f]{40}", source["blob_sha1"]), "source Git blob")
            require(source["repository"] in data["repositories"], "source repository")
        else:
            require(source["kind"] == "local_frozen" and source["publication"] == "NOT_PUBLISHED", "local source boundary")
            require("commit" not in source and "url" not in source, "unpublished source cannot claim a commit or URL")
    for mapping in (data["edge_types"], data["verification_levels"], data["priority_labels"]):
        for value in mapping.values():
            bilingual(value, "legend")
    for node in data["nodes"]:
        require(node["kind"] in ("home", "tool", "branch", "frontier"), "node kind")
        require(node["priority"] in data["priority_labels"], "node priority")
        for field in ("label", "scope", "frontier", "next"):
            bilingual(node[field], f"{node['id']} {field}")
        require(set(node["evidence"]) == set(DIMENSIONS), f"{node['id']} evidence dimensions")
        for value in node["evidence"].values():
            bilingual(value, "evidence")
        require(node["source_ids"] and set(node["source_ids"]) <= source_ids, "dangling node source")
        require(len(node["source_ids"]) == len(set(node["source_ids"])), "duplicate node source")
    require({node["id"] for node in data["nodes"] if node["kind"] == "home"} == {f"A{i}" for i in range(6)}, "A0-A5 homes")
    used_sources = set()
    for node in data["nodes"]:
        used_sources.update(node["source_ids"])
    for edge in data["edges"]:
        require(edge["from"] in node_ids and edge["to"] in node_ids, "dangling edge")
        require(edge["from"] != edge["to"], "self edge")
        require(edge["type"] in data["edge_types"], "edge type")
        bilingual(edge["scope"], "edge scope")
        require(edge["source_ids"] and set(edge["source_ids"]) <= source_ids, "dangling edge source")
        used_sources.update(edge["source_ids"])
    require(used_sources == source_ids, "unreferenced source")
    return data


def cell(text):
    return text.replace("|", "&#124;").replace("\n", "<br>")


def source_link(source):
    return f"https://github.com/{source['repository']}/blob/{source['commit']}/{source['path']}"


def refs(ids):
    return ", ".join(f"[{item}](#source-{item.lower()})" for item in ids)


def render(data, lang):
    zh = lang == "zh-CN"
    heading = lambda en, cn: cn if zh else en
    lines = [f"# {data['title'][lang]}", "", "<!-- Generated by tools/render_research_progress_map.py; edit research_progress_map.json. -->", "",
             data["scope_note"][lang], "", data["freshness_note"][lang], "",
             f"{heading('Frozen main source', '冻结主线来源')}: [`{data['main_source_commit'][:12]}`](https://github.com/awdawmip/enterprise-math/commit/{data['main_source_commit']}). "
             f"{heading('Composition base', '组合基线')}: `{data['composition_base_commit']}`.", "",
             f"## {heading('Direction map', '方向图')}", "", data["evidence_note"][lang], "", "```mermaid", "flowchart TB", "  subgraph homes[\"A0 - A5\"]"]
    for node in data["nodes"]:
        if node["kind"] == "home":
            lines.append(f'    {node["id"]}["{node["id"]}: {node["label"][lang]}"]')
    lines.append("  end")
    for node in data["nodes"]:
        if node["kind"] != "home":
            lines.append(f'  {node["id"]}["{node["label"][lang]}"]')
    for edge in data["edges"]:
        arrow = "-.->" if edge["type"] == "REUSE_IDENTIFIED" else "-->"
        lines.append(f'  {edge["from"]} {arrow}|"{edge["type"]}"| {edge["to"]}')
    lines.extend(["```", "", f"## {heading('Comparable evidence at the stated scope', '同一范围内的证据对照')}", "",
                  heading("These are source statements and recorded receipts, not new checks performed by this map.", "以下区分来源声明与已记录回执；建图本身没有重新证明或执行数学。"), "",
                  heading("| Node / exact scope | Mathematics | Lean | Program evidence | Publication | Formal review |", "| 节点 / 精确范围 | 数学证据 | Lean | 程序证据 | 发布层 | 正式审查 |"),
                  "| --- | --- | --- | --- | --- | --- |"])
    for node in data["nodes"]:
        values = [f"**{node['id']} — {node['label'][lang]}**<br>{cell(node['scope'][lang])}<br>{refs(node['source_ids'])}"]
        values.extend(cell(node["evidence"][key][lang]) for key in DIMENSIONS)
        lines.append("| " + " | ".join(values) + " |")
    lines.extend(["", f"## {heading('Unfinished frontier and existing next action', '未完前沿与已有下一步')}", "",
                  heading("Reading order only; this is not the live task-selection queue.", "仅为阅读顺序，不是 live 任务选择队列。"), "",
                  heading("| Reading priority | Node | What remains / limiting boundary | Existing next action |", "| 阅读优先级 | 节点 | 未完项 / 限定边界 | 已有下一步 |"), "| --- | --- | --- | --- |"])
    priorities = list(data["priority_labels"])
    for node in sorted(data["nodes"], key=lambda item: priorities.index(item["priority"])):
        lines.append(f"| {data['priority_labels'][node['priority']][lang]} | {node['id']} | {cell(node['frontier'][lang])} | {cell(node['next'][lang])} |")
    lines.extend(["", f"## {heading('Typed connections', '有型别的关系')}", ""])
    for kind, meaning in data["edge_types"].items():
        lines.append(f"- `{kind}`: {meaning[lang]}")
    lines.extend(["", heading("| From → to | Type | Exact meaning / boundary | Sources |", "| 从 → 到 | 型别 | 精确含义 / 边界 | 来源 |"), "| --- | --- | --- | --- |"])
    for edge in data["edges"]:
        lines.append(f"| {edge['from']} → {edge['to']} | `{edge['type']}` | {cell(edge['scope'][lang])} | {refs(edge['source_ids'])} |")
    lines.extend(["", f"## {heading('Immutable source pins and evidence depth', '不可变来源与证据深度')}", "",
                  heading("Source IDs resolve below; SHA256 values pin file contents. An immutable file link does not prove current runtime authority.", "source ID 在此解析，SHA256 固定文件字节；不可变文件链接不证明当前运行时权威。"), ""])
    for key, description in data["verification_levels"].items():
        lines.append(f"- `{key}`: {description[lang]}")
    lines.append("")
    for source in data["sources"]:
        label = source["label"][lang]
        link = f"[{label}]({source_link(source)})" if source["kind"] == "git_file" else f"{label} — `{source['path']}` ({heading('not published', '未发布')})"
        lines.extend([f'<a id="source-{source["id"].lower()}"></a>', f"- **{source['id']}** {link}; `{source['verification']}`; SHA256 `{source['sha256']}`.", ""])
    lines.extend([f"## {heading('Maintenance', '维护方法')}", "", data["maintenance_note"][lang], "", "```sh", "python tools/render_research_progress_map.py", "python tools/render_research_progress_map.py --check", "```", "",
                  heading("`--check` checks the JSON structure, local source-ID references, immutable-pin syntax and generated bytes. It performs no network fetch, theorem check, CI run, live claim lookup or status promotion. Reverify source contents before updating a pin or a factual frontier.", "`--check` 检查 JSON 结构、本地 source-ID 引用、不可变 pin 格式及生成文件字节。它不访问网络，不证明数学，不运行 CI，不读取 live claim，也不提升状态。修改 pin 或事实前沿前仍需核对原来源字节。"), ""])
    return "\n".join(lines).encode("utf-8")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        raw = args.root.joinpath(DATA).read_bytes()
        data = validate(json.loads(raw))
        for lang in LANGUAGES:
            path = args.root.joinpath(f"docs/RESEARCH_PROGRESS_MAP.{lang}.md")
            expected = render(data, lang)
            if args.check:
                require(path.is_file() and path.read_bytes() == expected, f"generated output drift: {path.name}")
            else:
                path.write_bytes(expected)
        print(f"PASS: {len(data['nodes'])} nodes, {len(data['edges'])} typed edges, {len(data['sources'])} source pins; data SHA256={hashlib.sha256(raw).hexdigest()}")
        return 0
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
