"""Schedule-robust readouts via a minimum complementary reservation event.

TEST_ONLY: member IDs are occurrences, not six spatial axes. Pinned old
reserve/release and positive CWM BRC are executed unchanged. No old suite runs.
New event K is an explicit change to the test library, NOT a native closure law.
"""
from __future__ import annotations
import hashlib, importlib.util, json, sys
from fractions import Fraction as Q
from itertools import combinations, permutations
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PRIOR = ROOT/'prior/check_membership.py'
if not PRIOR.exists():
    PRIOR = ROOT.parent/'20261008_residual_membership_7c2e8a/check_membership.py'
raw = PRIOR.read_bytes()
if hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest() != 'be1b60446e31c2c8489d1ce0db16cc1e952d11c8':
    raise RuntimeError('membership source pin mismatch')
spec = importlib.util.spec_from_file_location('robust_pinned_membership', PRIOR)
m = importlib.util.module_from_spec(spec);sys.modules[spec.name]=m;spec.loader.exec_module(m)
s,r=m.s,m.r
CHECKS=0;STEPS=0
SOURCE=(1,2,3)
TARGETS=(7,13,19,25,31)
OLD={'G1':(1,7,13),'G2':(2,19,25),'G3':(3,31,32),'H':(1,7,19)}
REPAIR=(2,13,25)

def ck(ok: bool, label: str) -> None:
    global CHECKS
    CHECKS+=1
    if not ok:raise AssertionError(label)

def cw(v):return dict(C=v.count,W=str(v.total),M=str(v.dominant))
def put(out,key,v):out[key]=r.merge(out.get(key,r.brc.CWM_ZERO),v)
def occ(J,targets=TARGETS):return tuple(int(x in m.used(J)) for x in targets)
def step(J,op):
    global STEPS
    STEPS+=1
    return m.full_step(J,op)

def polynomial(library,initial=()):
    """All compatible additions generated by the ORIGINAL positive BRC algebra."""
    busy=m.used(initial)
    available={key:tuple(h) for key,h in library.items() if not busy&set(h)}
    E=tuple(s.TestEvent(key,frozenset(h),r.brc.CWM_ONE) for key,h in available.items())
    I=frozenset().union(*(frozenset(h) for h in library.values()),busy)
    return available,s.assemble(E,I)

def maximal(poly):
    # Only tests compatibility support; CWM coefficients remain in poly.
    return tuple(key for key in poly if not any(key[0]<other[0] for other in poly))

def blocker_certificate(available,poly,t):
    incident=tuple(frozenset(h) for h in available.values() if t in h)
    # An empty incident family has the empty matching as its certificate.
    for J,U in sorted(poly,key=lambda q:(len(q[0]),tuple(sorted(q[0])))):
        if t not in U and all(U&h for h in incident):
            return dict(events=sorted(J),used=sorted(U),incident=[sorted(h) for h in incident])
    return None

def check_criterion():
    H=tuple(combinations(range(1,7),3));cases=0;queries=0;hashes=hashlib.sha256()
    examples=[]
    # NEW tests: all FOUR-event libraries, not the old three-event suite.
    for hs in combinations(H,4):
        lib={str(i):h for i,h in enumerate(hs)}
        available,poly=polynomial(lib);ends=maximal(poly)
        for t in range(1,7):
            cert=blocker_certificate(available,poly,t)
            all_cover=all(t in U for J,U in ends)
            ck(all_cover==(cert is None),'blocker certificate iff a maximal outcome avoids target')
            if cert is not None:
                keys=set(cert['events'])
                ck(all(t not in available[k] for k in keys),'certificate never covers its target')
                ck(any(keys<=J and t not in U for J,U in ends),'certificate extends to a failure maximal matching')
            queries+=1
            hashes.update(repr((hs,t,all_cover,cert)).encode())
        cases+=1
    # Declared initial occupation, no candidate touching it can become available.
    lib={'a':(1,4,5),'b':(4,5,6),'c':(6,7,8),'d':(7,8,9)}
    initial=m.canon((SOURCE,));available,poly=polynomial(lib,initial)
    ends=maximal(poly)
    for t in range(1,10):
        robust=t in m.used(initial) or blocker_certificate(available,poly,t) is None
        ck(robust==all(t in (U|m.used(initial)) for J,U in ends),'initially occupied targets and unavailable candidates')
    return dict(four_event_libraries=cases,target_queries=queries,
                input_universe=list(range(1,7)),certificate_digest=hashes.hexdigest(),
                theorem_scope='all distinct candidates attempted once; reserve only; all orders')

def synthesize():
    # Search all source-gated triples on the declared 36-occurrence inventory.
    lib=dict(OLD);candidates=[];winners=[];total=r.brc.CWM_ZERO
    A,p=polynomial(OLD)
    before={str(t):blocker_certificate(A,p,t) for t in TARGETS}
    ck(before['13'] is not None and before['25'] is not None,'old bad targets have explicit blocker witnesses')
    for h in combinations(range(1,37),3):
        if not set(h)&set(SOURCE) or h in OLD.values():continue
        total=r.merge(total,r.brc.CWM_ONE)
        trial=dict(OLD,K=h);a,poly=polynomial(trial);ends=maximal(poly)
        failure=next(((J,U) for J,U in ends if not set(TARGETS)<=U),None)
        ok=failure is None
        if ok:winners.append(h)
        else:
            chosen=sorted(failure[0]);word=chosen+[k for k in trial if k not in failure[0]]
            state=()
            for key in word:state,_,_=step(state,('reserve',trial[key]))
            ck(not all(occ(state)),'every rejected repair has an executable adversarial order')
        candidates.append(dict(candidate=h,robust=ok,
            failure_events=None if failure is None else sorted(failure[0])))
    ck(total.count==1680 and total.total==1680,'exhaustive declared single-addition search size')
    ck(winners==[REPAIR],'unique source-gated one-event repair in the fixed inventory')
    _,poly=polynomial(dict(OLD,K=REPAIR));ends=maximal(poly)
    expected={frozenset(('G1','G2','G3')),frozenset(('H','K','G3'))}
    ck({J for J,U in ends}==expected,'repaired terminal structures exactly two complementary matchings')
    ck(len({U for J,U in ends})==1,'different memberships, identical complete occupancy')
    return dict(old_target_blockers=before,search_CWM=cw(total),unique_repair=REPAIR,
        assumptions=['old four candidates retained','one added distinct triple',
                     'fixed inventory 1..36','new triple intersects initial source event'],
        candidates=candidates,terminal_event_sets=[sorted(x) for x in sorted(expected,key=lambda z:sorted(z))])

def paired_orders(library,keep_trace=True):
    names=tuple(library);orders=tuple(permutations(names));law={};endpoints={};records=[]
    weight=r.edge(Q(1,len(orders)))
    for order in orders:
        ctl=m.canon((SOURCE,));trt,_,ok=step(ctl,('release',1))
        ck(ok and not trt,'one actual source release prepares treatment')
        w=r.serial(weight,r.brc.CWM_ONE);trace=[]
        for key in order:
            ctl,_,cok=step(ctl,('reserve',library[key]))
            trt,_,tok=step(trt,('reserve',library[key]))
            w=r.serial(w,r.brc.CWM_ONE) # Same paired preparation counted ONCE.
            trace.append(dict(event=key,control=ctl,treatment=trt,control_success=cok,treatment_success=tok))
        d=tuple(b-a for a,b in zip(occ(ctl),occ(trt)));mask=tuple(int(x!=0) for x in d)
        put(law,mask,w);put(endpoints,(ctl,trt),w)
        ck(occ(ctl)==(0,)*5,'source-gated control has no target occupation')
        if keep_trace:records.append(dict(order=order,trace=trace,difference=d,mask=mask,coefficient=cw(w)))
    ck(r.total(law.values()).total==1,'all schedule weights including blocked proposals conserved')
    return law,endpoints,records

def repair_execution():
    library=dict(OLD,K=REPAIR)
    law,ends,records=paired_orders(library)
    ck(set(law)=={(1,)*5},'all 120 paired schedules yield five-target response')
    ck(law[(1,)*5].count==120,'C preserves every schedule, not only two outcomes')
    ck(len(ends)==2,'repaired complete state still not confluent')
    ck(all(v.count==60 and v.total==Q(1,2) and v.dominant==Q(1,120) for v in ends.values()),'uniform diagnostic keeps tied order multiplicities')
    distinguished=[]
    for (ctl,J),v in ends.items():
        after,_,ok=step(J,('release',7))
        ck(ok,'future release really has a reserved member')
        distinguished.append(dict(before=J,after_release7=after,targets_after=occ(after),CWM=cw(v)))
    ck(len({tuple(x['targets_after']) for x in distinguished})==2,'one future release distinguishes equal terminal occupancy')
    # Equal occupation hides only one binary relation choice in this reachable family.
    occupation=next(iter(ends))[1]
    return dict(gamma=[dict(mask=k,CWM=cw(v)) for k,v in law.items()],
                uniform_diagnostic_only=True,source_weight_counted_once=True,
                order_count=len(records),endpoints=distinguished,all_paired_traces=records)

def more_options_can_hurt():
    lib=dict(OLD,K=REPAIR,L=(1,2,7))
    law,ends,records=paired_orders(lib,False)
    ck((1,)*5 in law and len(law)>1,'extra competing route destroys robust coverage')
    bad=()
    for name in ('L','G3','G1','G2','H','K'):
        bad,_,_=step(bad,('reserve',lib[name]))
    ck(occ(bad)==(1,0,0,0,1),'specific new blocker schedule misses three targets')
    return dict(extra_event=lib['L'],adversarial_order=['L','G3','G1','G2','H','K'],
                adversarial_targets=occ(bad),gamma=[dict(mask=k,CWM=cw(v)) for k,v in sorted(law.items())],
                original_primitives_unchanged=True)

def reliability():
    lib=dict(OLD,K=REPAIR);names=tuple(lib);orders=tuple(permutations(names));rows=[]
    for q in (Q(0),Q(1,4),Q(1,2),Q(3,4),Q(1)):
        law={}
        for active,p in ((False,1-q),(True,q)):
            if p==0:continue # Zero weight is not a positive prepared branch.
            for order in orders:
                J=();w=r.serial(r.edge(Q(1,len(orders))),r.edge(p))
                for name in order:
                    if name!='K' or active:J,_,_=step(J,('reserve',lib[name]))
                    w=r.serial(w,r.brc.CWM_ONE)
                put(law,occ(J),w)
        theta=law.get((1,)*5,r.brc.CWM_ZERO).total
        extra=r.brc.CWM_ZERO if q==0 else r.serial(r.edge(q),r.edge(Q(1,3)))
        expected=r.merge(r.edge(Q(2,3)),extra).total
        ck(theta==expected,'uniform-order independent repair-availability formula')
        ck(r.total(law.values()).total==1,'missing repair branch explicitly retained')
        # For fixed H-first order, coverage iff K available; other orders always succeed.
        rows.append(dict(q=str(q),uniform_order_theta=str(theta),worst_fixed_order_theta=str(q),
                         scope='independent declared availability flag, not physical reliability'))
    return rows

def main():
    criterion=check_criterion();repair=synthesize();execution=repair_execution()
    instability=more_options_can_hurt();availability=reliability()
    result=dict(schema='EM_RESIDUAL_ROBUST_READOUT_V1',
        status='CONDITIONAL_EXECUTED_BRC_UNREVIEWED_NOT_NATIVE_DYNAMICS',
        event_id='EM-20261009-RESIDUAL-ROBUST-READOUT-7C2E8A',
        global_read='7b9eb1223c4139523fa4abb0b663fdcbf02e9273',
        source_read='a80c1772a95ed4705bb83e84b6c383aa6b88b71a',
        activity_status='REGISTER_PENDING_PLATFORM_BLOCKED_NO_RETRY',activity_id=None,
        criterion=criterion,repair_search=repair,repair_execution=execution,
        added_competition=instability,availability=availability,
        assertions=CHECKS,full_step_calls=STEPS,BRC_calls=dict(r.CALLS),
        old_main_suites_executed=False,independent_review=False,native_mapping_supplied=False)
    raw=(json.dumps(result,ensure_ascii=False,sort_keys=True,indent=2)+'\n').encode()
    (ROOT/'results.json').write_bytes(raw)
    summary={k:result[k] for k in ('event_id','status','assertions','full_step_calls','BRC_calls','activity_status')}
    summary.update(libraries=criterion['four_event_libraries'],target_queries=criterion['target_queries'],
        single_addition_candidates=repair['search_CWM']['C'],unique_repair=REPAIR,
        robust_orders=execution['order_count'],output_bytes=len(raw),output_sha256=hashlib.sha256(raw).hexdigest())
    (ROOT/'summary.json').write_text(json.dumps(summary,indent=2,ensure_ascii=False)+'\n')
    print(json.dumps(summary,indent=2,ensure_ascii=False))
if __name__=='__main__':main()
