"""Consecutive certified uniform-suffix steps of the actual single walker."""
from __future__ import annotations
from fractions import Fraction as F
from pathlib import Path
import hashlib
import sys

ROOT = Path(__file__).resolve().parent
sys.path.insert(0,str(ROOT.parents[1]/'sep27-qft-research/gram_research'))
from single_walker import SingleWalker
from power_sum_certificate import certify_program_suffix, verify_program_suffix
from lazy_modular import digest
from stage45.brc_loop_recheck import CALLS


def certificate_digits(certificate):
    if certificate.get('schema') != 'ACTUAL_NATIVE_POWER_SUM_UNIFORM_SUFFIX_V1':
        return 0
    structure = certificate['structure_witness']
    schedule = certificate['program_witness']['schedule_witness']
    return (structure['arithmetic_cost']['adder_digit_replays']
        + structure['primitive_witness_gcd']['cost']['adder_digit_replays']
        + structure['jacobi']['cost']['adder_digit_replays']
        + schedule['jacobi']['cost']['adder_digit_replays']
        + schedule['schedule_arithmetic_cost']['adder_digit_replays']
        + schedule['permutation_verification_adder_digits'])


class PowerSumWalker(SingleWalker):
    def __init__(self,program,ell,u,v,*,query_budget=1000):
        super().__init__(program,query_budget=query_budget)
        self._owned_oracle = self.oracle
        start = len(CALLS)
        try:
            self.suffix_certificate = certify_program_suffix(program,ell,u,v)
        except ValueError as error:
            self.suffix_certificate = {'status':'UNAVAILABLE','reason':str(error)}
        self.certification_native_calls = len(CALLS)-start
        self.certification_digit_replays = certificate_digits(self.suffix_certificate)
        self.verifications = []
        self.shortcut_rounds = 0

    def _check_owned_trajectory(self):
        if self.oracle is not self._owned_oracle or self.oracle.program is not self.program:
            raise ValueError('externally replaced oracle is not certified')
        if self.history != tuple(event['selected_bit'] for event in self.events):
            raise ValueError('history must be generated by this walker')
        expected,history = 1,()
        for event in self.events:
            if event['latent_before'] != expected or tuple(event['history']) != history:
                raise ValueError('trajectory does not retain the initial work label 1')
            expected = event['candidate']
            history += (event['selected_bit'],)
        if self.latent != expected:
            raise ValueError('latent label was externally replaced')

    def _verified_suffix(self):
        if self.suffix_certificate.get('status') != 'CERTIFIED_UNIFORM_TERMINAL_SUFFIX':
            return False
        if not self.suffix_certificate['suffix_start_depth'] <= len(self.history) < self.program.t:
            return False
        start = len(CALLS)
        try:
            verified = verify_program_suffix(self.suffix_certificate,self.program)
        except ValueError as error:
            self.verifications.append({'verified':False,'reason':str(error),
                                       'native_core_calls':len(CALLS)-start})
            return False
        self.verifications.append({**verified,'native_core_calls':len(CALLS)-start,
                                   'replayed_adder_digits':certificate_digits(self.suffix_certificate)})
        return verified['verified'] and verified['status'] == 'CERTIFIED_UNIFORM_TERMINAL_SUFFIX'

    def step(self,rng):
        self._check_owned_trajectory()
        if len(self.history) >= self.program.t:
            raise ValueError('terminal walker')
        if not self._verified_suffix():
            if self.pending_plan is not None and self.pending_plan.get('mode') == 'CERTIFIED_POWER_SUM_SUFFIX':
                self.pending_plan = None
            return super().step(rng)
        if self.pending_auxiliary_bit is None:
            self.pending_auxiliary_bit = self._draw(F(1,2),rng)
        if self.pending_plan is None:
            auxiliary = self.pending_auxiliary_bit
            candidate = self.latent if auxiliary == 0 else self.program.tables[len(self.history)][self.latent]
            self.pending_plan = {'mode':'CERTIFIED_POWER_SUM_SUFFIX','history':self.history,
                'latent_before':self.latent,'auxiliary_bit':auxiliary,'candidate':candidate,
                'bit_probability_given_proposed_label':F(1,2),
                'certificate_sha256':digest(self.suffix_certificate),
                'row_query_performed':False}
        plan = self.pending_plan
        if tuple(plan['history']) != self.history or plan['latent_before'] != self.latent:
            raise ValueError('unfinished proposal no longer has its original parent')
        bit = self._draw(F(1,2),rng)
        self.oracle.append(bit)
        self.latent = plan['candidate']
        self.events.append({**plan,'selected_bit':bit,'selected_local_probability':F(1,2)})
        self.shortcut_rounds += 1
        self.pending_auxiliary_bit = self.pending_plan = None
        return self.events[-1]

    def report(self):
        return {'certificate_status':self.suffix_certificate['status'],
            'certificate_sha256':digest(self.suffix_certificate),
            'certification_native_core_calls':self.certification_native_calls,
            'certification_adder_digit_replays':self.certification_digit_replays,
            'verifications':list(self.verifications),'shortcut_rounds':self.shortcut_rounds,
            'source_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
            'scope':'same live object, canonical initial trajectory, unchanged admitted program',
            'complete_history_and_point_oracle_retained':True,
            'certificate_work_not_charged_as_zero_point_queries':True}

    def run(self,rng,*,postprocess=None):
        result = super().run(rng,postprocess=postprocess)
        result['power_sum_optimization'] = self.report()
        return result
